### ISSUE TITLE
az-group-deploy.sh: 'group deployment' is deprecated

### ISSUE THREAD

**Issue by lanceshelton** [Azure/azure-quickstart-templates#10112]
### Issue Details
When running az-group-deploy.sh:
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

It is just a warning, not a failure.

### Repro steps (*if necessary, delete otherwise*)
1. Run az-group-deploy.sh

**Comment by bmoore-msft** [comment]
I think you got this one...
