### ISSUE TITLE
Deploying a blob storage container using resource templates

### ISSUE THREAD

**Issue by activatedgeek** [Azure/azure-quickstart-templates#1014]
It is possible to deploy a storage account using the resource templates, but I haven't been able to find any way to deploy a blob container inside the storage account. Is that possible via the resource templates?

**Comment by singhkay** [comment]
@activatedgeek That's not possible. Templates can only spin up resources on the management plane. Blobs lie on the storage data plane.

**Comment by kattakishore12** [comment]
whats is the alternative to create Blob, File and queue storage's in Azure via automation?

**Comment by kattakishore12** [comment]
@singhkays whats is the alternative to create Blob, File and queue storage's in Azure via automation?

**Comment by kattakishore12** [comment]
@singhkays whats is the alternative to create Blob, File and queue storage's in Azure via automation?

**Comment by singhkays** [comment]
@kattakishore12 Use PowerShell, CLI, REST APIs or a SDK client library in the language of your choice (.NET, Python, Go, Java etc.)
