### ISSUE TITLE
sideload-createuidef.sh: Microsoft.Common.Slider is broken

### ISSUE THREAD

**Issue by lanceshelton** [Azure/azure-quickstart-templates#10253]
### Issue Details

Attempting to use the Microsoft.Common.Slider UI component:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-common-slider

Testing createUIDefinition.json via the sideload-createuidef.sh script, the slider does not appear at all, nor does it generate any errors in the web browser console.  Testing an identical createUIDefinition.json via the portal's Create UI Definition Sandbox, the slider works.

Using the example from the docs:

```
{
    "name": "memorySize",
    "type": "Microsoft.Common.Slider",
    "min": 1,
    "max": 64,
    "label": "Memory",
    "subLabel": "MB",
    "defaultValue": 24,
    "showStepMarkers": false,
    "toolTip": "Pick the size in MB",
    "constraints": {
        "required": false
    },
    "visible": true
}
```

When testing via sideload-createuidef.sh, it is completely ignored. Even the Azure JSON plugin for Visual Studio Code does not recognize the element.

Notably, Microsoft.Common.Slider is not used in any of the createUIDefinition files contained in this repo.

### Repro steps
1. Create a createUIDefinition.json including the Microsoft.Common.Slider example snippet
2. Deploy using sideload-createuidef.sh
3. See that the UI shows nothing for the slider element.

**Comment by lanceshelton** [comment]
@bmoore-msft what is the difference between sideload-createuidef.sh and the Create UI Definition Sandbox?  They both appear to be used to test the UI, but display the createUIDefinition.json output differently. Any idea why the slider would work in sandbox but not in sideload?

The documentation I was following suggested sideload-createuidef.sh, but now I may switch to the sandbox if that's better supported...

**Comment by bmoore-msft** [comment]
You should use the new sandbox - it has different/newer capabilities, which is why you see the slider working in one but not the other.

AFAIKI, there's no side-load capability for the new sandbox you have to copy/paste.

**Comment by lanceshelton** [comment]
Ok, thanks.

**Comment by bmoore-msft** [comment]
I'll go ahead and close - feel free to ping as needed...
