### ISSUE TITLE
cloud pak for data - OpenShift Deployment Failed

### ISSUE THREAD

**Issue by domi20** [Azure/azure-quickstart-templates#10503]
[IBM Cloud Pak for Data](https://github.com/Azure/azure-quickstart-templates/tree/master/ibm-cloud-pak-for-data)

### Issue Details
Hi all,
i'm trying to deploy Cloud Pak for Data on Azure with this template and instructions. When deploying the OpenShift (sometimes the BastionVmDeployment) deployment fails with the error "SSL peer rejected your certificate as expired." See the complete Error Log below...

I think, it might have something to do with the SSH public Key. I have tried a key (RSA, Length 4096) generated by Azure and another generated by using puTTYgen. But makes no difference.

Does anyone have an idea what I did wrong?
Thx

`{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenshift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nThu May 27 08:19:20 UTC 2021  - ############## Starting Script ####################\\nLoaded plugins: langpacks, product-id, search-disabled-repos\\n\\n[stderr]\\nhttps://rhui-1.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\nTrying other mirror.\\nhttps://rhui-2.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\nTrying other mirror.\\nhttps://rhui-3.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\nTrying other mirror.\\n\\n\\n One of the configured repositories failed (dotNET on RHEL Debug RPMs for Red Hat Enterprise Linux 7 Server from RHUI),\\n and yum doesn't have enough cached data to continue. At this point the only\\n safe thing yum can do is fail. There are a few ways to work \\\"fix\\\" this:\\n\\n     1. Contact the upstream for the repository and get them to fix the problem.\\n\\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\\n        upstream. This is most often useful if you are using a newer\\n        distribution release than is supported by the repository (and the\\n        packages for the previous distribution release still work).\\n\\n     3. Run the command with the repository temporarily disabled\\n            yum --disablerepo=rhui-rhel-7-server-dotnet-rhui-debug-rpms ...\\n\\n     4. Disable the repository permanently, so yum won't use it by default. Yum\\n        will then just ignore the repository until you permanently enable it\\n        again or use --enablerepo for temporary usage:\\n\\n            yum-config-manager --disable rhui-rhel-7-server-dotnet-rhui-debug-rpms\\n        or\\n            subscription-manager repos --disable=rhui-rhel-7-server-dotnet-rhui-debug-rpms\\n\\n     5. Configure the failing repository to be skipped, if it is unavailable.\\n        Note that yum will try to contact the repo. when it runs most commands,\\n        so will have to try and fail each time (and thus. yum will be be much\\n        slower). If it is a very temporary problem though, this is often a nice\\n        compromise:\\n\\n            yum-config-manager --save --setopt=rhui-rhel-7-server-dotnet-rhui-debug-rpms.skip_if_unavailable=true\\n\\nfailure: repodata/repomd.xml from rhui-rhel-7-server-dotnet-rhui-debug-rpms: [Errno 256] No more mirrors to try.\\nhttps://rhui-1.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\nhttps://rhui-2.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\nhttps://rhui-3.microsoft.com/pulp/repos//content/dist/rhel/rhui/server/7/7Server/x86_64/dotnet/1/debug/repodata/repomd.xml: [Errno 14] curl#58 - \\\"SSL peer rejected your certificate as expired.\\\"\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}`

**Comment by DennisStav** [comment]
Same problem here. I googled a bit and found this https://access.redhat.com/solutions/3167021
Could it be connected?

**Comment by domi20** [comment]
Yes i found the same solution. Running `yum update` works for me.

This Problem was fixed for the master branch in the meantime. See PR #10757
