### ISSUE TITLE
DSC Configuration completed with error

### ISSUE THREAD

**Issue by erelh** [Azure/azure-quickstart-templates#1054]
Hi,

I am trying to create a VM with DSC extension
taken from the example templates in azure-quickstart-templates: 'dsc-extension-iis-server-windows-vm'

I am getting the following error:
"DSC Configuration completed with error(s)"

Why can this happen?

This is relevant part of my json file:

		{
			"type": "Microsoft.Compute/virtualMachines/extensions",
			"name": "[concat(variables('vmName'), copyindex(), '/dscExtension')]",
			"apiVersion": "2015-05-01-preview",
			"location": "[resourceGroup().location]",
			"copy": {
                "name": "extensionLoop",
                "count": "[variables('numberOfInstances')]"
            },
			"dependsOn": [
				"[concat('Microsoft.Compute/virtualMachines/', variables('vmName'), copyindex())]"
			],
			"properties": {
				"publisher": "Microsoft.Powershell",
				"type": "DSC",
				"typeHandlerVersion": "2.8",
				"settings": {
					"ModulesUrl": "[variables('modulesUrl')]",
					"ConfigurationFunction": "[variables('configurationFunction')]",
					"Properties": {
						"MachineName": "[concat(variables('vmName'), copyindex())]"
					}
				},
				"protectedSettings": null
			}
		}

variables:

"vmName": "[concat(parameters('envPrefix'), 'VM')]",
"modulesUrl": "https://drive.google.com/uc?export=download&id=0B2MZ567J__vEWEJaVWRCVjNUOHM",
"configurationFunction": "ContosoWebsite.ps1\\ContosoWebsite"
modulesUrl is a direct downloadable link to zip file which contains ContosoWebsite.ps1

Thanks

**Comment by glennmate** [comment]
You'll need to log into the VM that failed and read the DSC logs to find out why the cluster isn't building. It's likely a parameter isn't set properly or there's an issue with the underlying Azure infrastructure you're deploying the cluster into. 

Look at the deployment failure message in the portal:
```
STATUSMESSAGE
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CreateCluster'. Error message: \"DSC Configuration completed with error(s).\"."}]}}
RESOURCE
azu-prod-sqlA02/CreateCluster
```

Resource shows you which VM to log into. From there, check the file ```C:\Packages\Plugins\Microsoft.Powershell.DSC\%version%\Status\0.status file```. 

This file is in JSON format. Pull it somewhere you can read it with a text editor. The status->subStatus->formattedMessage->message field will provide verbose output to every single component of the DSC configuration and any errors thrown. Be warned this is a very verbose and make take a few minutes to parse and find the errors. This should point you in the right direction to troubleshoot.

Unfortunately the Azure portal isn't pulling this information from the VMs and giving us digestible errors, so we're stuck to muddle through vague Azure deployment errors to find the real DSC issues.

**Comment by singhkay** [comment]
@glennmate Thanks for the detailed help! 

@erelh You can also take a look at the instance view of the VM in resource.azure.com to see what failed. I'll close this but if you still need more help, feel free to reopen.
