### ISSUE TITLE
Searchable index seems to have lost some templates

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-quickstart-templates#1061]
This link used to work:

https://azure.microsoft.com/en-us/documentation/templates/201-dynamic-web-tests/

Now it's returning a 404.

**Comment by singhkay** [comment]
The searchable index is owned by the Azure.com team. The latest I have from them is that this is a transient issue currently due to exceeding Github's API rate limits but they are working on a better architecture to alleviate this pain.
