### ISSUE TITLE
bicep-with-prereqs shouldn't show up in azure.com search

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-quickstart-templates#10921]
https://azure.microsoft.com/de-de/resources/templates/?term=bicep

![image](https://user-images.githubusercontent.com/6913354/121260142-ceb2ab80-c865-11eb-9d30-8d4514f91330.png)

**Comment by bmoore-msft** [comment]
@StephenWeatherford - I think the only short-term option is to remove the metadata.json file from the folder...  Not sure if that going to interfere with the purpose of the sample, but that's how a few of the experiences (ACOM, Portal, EDU) will find it...

**Comment by StephenWeatherford** [comment]
The other possibility is to move it under "test", right?  That has issues of its own, though.

**Comment by bmoore-msft** [comment]
I don't think so - I think anywhere a metadata.json file is found, it's assumed to be a sample (for most "clients" crawling the repo)...  they are supposed to filter by the type property in the file, but ACOM does not (and I doubt the others do).
