### ISSUE TITLE
[Question]How to add a new subnet into an existing vnet?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#1110]
For example, I deployed a vnet which has two subnets in a resource group.
I'd like to deploy another template add a new subnet into the existing vnet.
Is it possible to add a new subnet without re-creating the existing vnet and subnets?
Thanks

**Comment by singhkay** [comment]
Haven't tested this but I believe so. Try keeping the deployment name same and same VNET definition but with another subnet added and see if it works?

**Comment by bingosummer** [comment]
@singhkay Thanks for your reply.
If I want to deploy another template with a different deployment name (since I don't know the original deployment name) and I don't know how many subnets are there in the VNET, is it possible to add a new subnet?
And I suggest to provide a 101/201 sample template to show how to do it.

**Comment by stinck** [comment]
i don't think it's possible, because you can only deploy a resource object. A subnet is not a resource object (for the moment), but a property of a resource object

**Comment by singhkay** [comment]
@bingosummer @stinck I just tested it and it works. You do need to know the number of subnets in a vnet and replicate the existing template definition of the VNET. Then add a code block for the new subnet and it should work

```
{
	"name": "subnet2",
	"properties": {
		"addressPrefix": "10.0.1.0/24"
	}
}
```

I think for the scenario you're asking where you don't know the existing number of subnets in the VNET, you might want to go with the imperative APIs i.e. PS or CLI
