### ISSUE TITLE
Cannot use ExpressRoute circuit from ASM Virt.Network in my new ARM Virt.Network

### ISSUE THREAD

**Issue by stinck** [Azure/azure-quickstart-templates#1121]
azure-quickstart-templates / 301-expressroute-circuit-vnet-connection / 
 This template seems not to work with a circuit i requested with the ASM powershell commands.
 it fails when provisioning a resource from the "Microsoft.Network/connections" class
 Do i need to request a new circuit with the ARM powershell cmdlets?

**Comment by singhkay** [comment]
@amitsriva Can you take a look at this?

**Comment by stinck** [comment]
@singhkay We are going to request a new service id in the ARM model, but when running the Get-AzureRmExpressRouteServiceProvider cmdlet we are getting the value 'null' for PeeringLocations and BandwidthsOffered. Any idea why?

**Comment by amitsriva** [comment]
ASM circuits do not work with ARM resources. You would need to create a new ARM circuit.
