### ISSUE TITLE
Incorrect check-in of Quick Start templates

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-quickstart-templates#11335]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.databricks/data-factory-ftp-hive-blob

### Issue Details
Someone has checkedin data factory related quick start templates into Databricks Folder.  Please move to correct folder.

**Comment by bmoore-msft** [comment]
fixed in #11338
