### ISSUE TITLE
Question about 101-internal-loadbalancer-create Template

### ISSUE THREAD

**Issue by Larcen** [Azure/azure-quickstart-templates#1134]
Hello all,

I'm checking this template ( https://github.com/Azure/azure-quickstart-templates/tree/master/101-internal-loadbalancer-create ) to create an internal load balancer inside an existing infraestructure with one Virtual Network and two subnets. I need to create this load balancer inside one of the existing subnets, and associate the backend to an existing NIC that is assigned to a working VM.

The template is creating new resources (Virtual Network, subnet, NIC, ...), but I need to associate the load balancer to preexisting resources. Is it possible?

Thanks in advance.

**Comment by singhkay** [comment]
@Larcen See the subnet ref at https://github.com/Azure/azure-quickstart-templates/blob/master/101-internal-loadbalancer-create/azuredeploy.json#L102 ? It's composed at https://github.com/Azure/azure-quickstart-templates/blob/master/101-internal-loadbalancer-create/azuredeploy.json#L32

In this case this subnet is being spun up as part of the VNET that's created. You can pass in the resource Id of the existing subnet and the LB would be hooked up to it.
