### ISSUE TITLE
Question: API Documentation for templates?

### ISSUE THREAD

**Issue by ArneCoder** [Azure/azure-quickstart-templates#1135]
Is there somewhere on the Planet an documentation about all ARM ServiceProviders? I mean... what kind of options are possible, etc.

**Comment by singhkay** [comment]
@ArneCoder Is this what you're looking for? https://msdn.microsoft.com/en-us/library/azure/dn790568.aspx and https://msdn.microsoft.com/en-us/library/azure/mt420159.aspx (ARM resource providers (non-classic) should have REST APIs on the left nav)

**Comment by ArneCoder** [comment]
Thanks for your answer, maybe iam just to stupid .. but i am searching for something where all "options" are documentated. For example: 

If i call:  "type": "Microsoft.Web/sites", what options are possible in the json template. Or is this not available and i have to use : 	
https://management.azure.com/subscriptions/{subscription-id}/providers/{resource-provider-namespace}?api-version={api-version} to find out?

**Comment by singhkay** [comment]
@ArneCoder If you look closely at the REST API and templates, you'll notice that the properties element is an exact match. So the thinks you can put inside the resource property is derived directly from the resource API.

**Comment by ArneCoder** [comment]
Ah ok, so how to find the propertiers for an Azure Webapp/Website? sorry
for the stupid question, but it is a bit hard to find the information for
me.

Kay Singh <notifications@github.com> schrieb am Mo., 25. Jan. 2016 um
19:52 Uhr:

> @ArneCoder <https://github.com/ArneCoder> If you look closely at the REST
> API and templates, you'll notice that the properties element is an exact
> match. So the thinks you can put inside the resource property is derived
> directly from the resource API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-quickstart-templates/issues/1135#issuecomment-174619577>
> .
>
-- 

Viele Grüße,
Arne Riemann

Blog: www.geekpub.de
Twitter: @ArneCoder

**Comment by singhkay** [comment]
@ArneCoder The web apps documentation is here https://azure.microsoft.com/en-us/documentation/articles/app-service-web-overview/ but it looks like you're not the only one having trouble finding the Web Apps REST API. @davidebbo Do you know where to find the REST reference for web apps?

**Comment by davidebbo** [comment]
The best place to get API details now is Resource Explorer (https://resources.azure.com/). We're working toward better separate documentation, but we're not quite there.
