### ISSUE TITLE
The sql-server-2014-alwayson-dsc arm template missing nodes

### ISSUE THREAD

**Issue by thehyperadvisor** [Azure/azure-quickstart-templates#1151]
The sql-server-2014-alwayson-dsc arm template is missing nodes after it shows complete. There should be 3 nodes in a cluster as described but I only end up with one sql and one witness. I also noticed that there's a nic for the other sql node that's not attached to anything. This happens every time i deploy the arm template with no errors.

**Comment by thehyperadvisor** [comment]
Looks like this is due to the quota limit even though the deployment completes with a successful status.

**Comment by singhkay** [comment]
@thehyperadvisor We have a work stream going that can catch quota errors before deploying. Should come online in the next month!
