### ISSUE TITLE
Possible error in vm-disk-utils.sh

### ISSUE THREAD

**Issue by DhruvKumar** [Azure/azure-quickstart-templates#1154]
The vm-disk-utils.sh provided by Ubuntu is excellent. But I think there's an error in this function since the way `echo` is being used looks circumspect:

```
do_partition() {
# This function creates one (1) primary partition on the
# disk, using all available space
    _disk=${1}
    _type=${2}
    if [ -z "${_type}" ]; then
        # default to Linux partition type (ie, ext3/ext4/xfs)
        _type=83
    fi
    echo "n
p
1
t
${_type}
w"| fdisk "${_disk}"
```
https://github.com/Azure/azure-quickstart-templates/blob/master/shared_scripts/ubuntu/vm-disk-utils-0.1.sh#L189-L196

**Comment by singhkay** [comment]
@trentmswanson Can you take a look at this?

**Comment by trentmswanson** [comment]
Thanks @DhruvKumar 

I guess I don't see the problem. I see a few different ways this could be implemented, but how it's currently implemented should and does work.  I hesitate to change it now, unless there's a problems.

-Trent
