### ISSUE TITLE
creating VM in an existing subnet and vnet

### ISSUE THREAD

**Issue by MannyGarcia** [Azure/azure-quickstart-templates#1173]
the deploy vm template for windows and linux creates a new vnet and subnet for each VM. is no a way to create the VMs and add them to an existing vnet and subnet?

**Comment by singhkay** [comment]
Sure, just remove the Vnet and subnet resources from the template and pass in the names of existing VNET and Subnet.

**Comment by MannyGarcia** [comment]
thank you singhkay.

Here is my json file:

https://raw.githubusercontent.com/MannyGarcia/GitRepo/master/azuredeploy.json

I dont really follow you with the removing the subnet and vnnet of our the resources and pass in the names of existing vnet and subnet.

if you look at the template, I already defining the existing vnet and subnet, but my VM fails while creating with an error saying that the subnet already exist.

**Comment by singhkay** [comment]
@MannyGarcia When you put a resource definition inside a template file like below, what you're doing is telling ARM - "Hey! Go create this thing!" 

```json
    {
      "apiVersion": "2015-05-01-preview",
      "type": "Microsoft.Network/virtualNetworks",
      "name": "[variables('virtualNetworkName')]",
      "location": "[variables('location')]",
      "properties": {
        "addressSpace": {
          "addressPrefixes": [
            "[variables('addressPrefix')]"
          ]
        },
        "subnets": [
          {
            "name": "[variables('subnet1Name')]",
            "properties": {
              "addressPrefix": "[variables('subnet1Prefix')]"
            }
          }
        ]
      }
    },
```

What you need do is tell ARM, "Hey! I already have this. Just use it!" 

See another template here that creates a VM in an existing VNET - https://github.com/Azure/azure-quickstart-templates/tree/master/201-specialized-vm-in-existing-vnet

**Comment by ShruthiHarsha** [comment]
I have gone through the template to create vm in existing vnet and subnet, here where is the vm login credentials given.
