### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by brandubh** [Azure/azure-quickstart-templates#1181]
The https://github.com/azure/azure-portal-createuidefinition  is broken. Do you have an alternate link?

**Comment by singhkay** [comment]
@VybavaRamadoss Can you take a look at this?

**Comment by vladimirjoanovic** [comment]
look here now: https://github.com/Azure/azure-marketplace/wiki/Getting-Started-with-Solution-Templates

**Comment by brandubh** [comment]
Hi Vlad, still broken on my side

**Comment by vladimirjoanovic** [comment]
sorry Daniele - I thought you had access to the old link which means you only needed the new link.  turns out you didn't have access to the old link so you didn't have access to the new link either (explains why you didn't see the insight re-direct). you have access now.

**Comment by lodotek** [comment]
https://github.com/Azure/azure-quickstart-templates/tree/master/marketplace-samples/simple-Linux-VM still has a broken link pointing to https://github.com/azure/azure-portal-createuidefinition ... common MS, get your act together!

**Comment by lodotek** [comment]
Bump

**Comment by lodotek** [comment]
Why is this closed ?

**Comment by lodotek** [comment]
Not happy that this was close without any explanation...

**Comment by bmoore-msft** [comment]
@lodotek this is pretty old - what specifically are you looking for?
