### ISSUE TITLE
Compute Schedules  in Compute Instances do not work while redeploying

### ISSUE THREAD

**Issue by vishutyagi000** [Azure/azure-quickstart-templates#11830]
[machine-learning-compute-create-computeinstance](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-computeinstance)

### Issue Details
The above arm template works just fine for first time.But when we try to redeploy the same we get error.
I have attached an image .when we try to redeploy the arm template it complains about 'Schedule format'
### Repro steps (*if necessary, delete otherwise*)
1.Deploy the above template
2.Re-deploy the same template

![image](https://user-images.githubusercontent.com/55187637/132207823-34500dda-d0aa-4e35-875a-c32a50244884.png)

**Comment by vishutyagi000** [comment]
@bmoore-msft

**Comment by vijetajo** [comment]
Are you trying to PATCH compute through ARM template? Please use UpdateSchedules API instead

**Comment by vishutyagi000** [comment]
@vijetajo  @ninghu  But the problem is we have a main arm template that provision other resources alongwith  compute insatnces and if we add computes instances with schedules it fails and you know whenever we modify for example add any resource in arm template we need to redeploy it.During this redeployment it gives error we are deploying the arm template via a Azure pipeline.
An arm template should be like we can redeploy as many times we want.

Can you just took your quick start template and try to run it two times ,may it will clear things

**Comment by ninghu** [comment]
@vishutyagi000 : Thanks for sharing the context. Now I understand your problem. We will work on a fix for this issue shortly. Btw, what's the region of your machine learning workspace? We might be able to deploy the fix to that region first for you to verify.

**Comment by vishutyagi000** [comment]
@ninghu Thanks for the quick response, We are using WestEurope region for machine learning workspace

**Comment by ninghu** [comment]
@vishutyagi000 I see the fix has been landed in your workspace region. Please give a try when you are convenient. Thanks!

**Comment by vishutyagi000** [comment]
Thanks @ninghu ,It seems working now.

**Comment by vishutyagi000** [comment]
@ninghu ,It not giving error now but one thing i observed is ,its not updating schedules,means what ever schedule  created during first deployment  remains even if we change schedules in subsequent deployment

**Comment by ninghu** [comment]
@vishutyagi000 Thanks for the update. Yes, that's expected behavior for now. We don't support schedule update through arm template currently because it might accidentally override the schedules set by other people (i.e. CI assigned to user).
