### ISSUE TITLE
Issue in creation of VM with ARM Template

### ISSUE THREAD

**Issue by parth618** [Azure/azure-quickstart-templates#1189]
While deploying the ARM template for creation of virtual machines using 101-vm-simple-linux,101-vm-simple-windows i face the issue as: 
The virtual machine image source is not valid.
Failed to create virtual machine : The virtual machine image source is not valid.
![virtual image source invalid](https://cloud.githubusercontent.com/assets/17052093/12885876/66aa80e2-ce8f-11e5-8f94-c85cfedba536.PNG)

**Comment by singhkay** [comment]
@parth618 Both deployed fine for me using the "Deploy to Azure" buttons. Can you try deploying using the buttons and see if there's another issue you might be facing?

**Comment by parth618** [comment]
@singhkay yeah The "Deploy to Azure" button works fine for me too as it redirects us to the azure portal but on deployment of starter template with the ruby (using azure-sdk for ruby) . It generates this error.

**Comment by singhkay** [comment]
@parth618 In that case looks like something is up with the Ruby SDK. I suggest posting an issue here https://github.com/Azure/azure-sdk-for-ruby/issues
