### ISSUE TITLE
Exporting existing assets from the Azure Portal or Powershell

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure/azure-quickstart-templates#1192]
I'm a developer and not a System Admin so I'm pretty new Azure Resource Templates and I've made some progress but it's very slow and therefore not cost-effective for smaller deployments with the experience I have.

Is there a way for me to export an existing assets within a Resource Group ?

I'd really like to see a way for you to be able to configure items in the Portal and then export a script rather than hitting the Create Button in the same way that SQL Server Admin does.

[I know ServiceFabric configuration allows this already]

**Comment by singhkay** [comment]
@johnkattenhorn Alpha of the capture RG capability is underway here https://capturegroup.azurewebsites.net/

**Comment by johnkattenhorn** [comment]
Very cool, I know it's an early release but I'll give it a go.

Thanks
