### ISSUE TITLE
automatic private static ip

### ISSUE THREAD

**Issue by HSoulat** [Azure/azure-quickstart-templates#12078]
I'm searching a way to automate Private VNIC creation in static mode without having to maintain an external list of available IP.
-> Terraform is not helpful on that, so I would pass through ARM Template for VNIC creation.

It is clearly not supported by default but you are achieving that with the template vm-automatic-static-ip (https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.compute/vm-automatic-static-ip). Unfortunately this template is not only creating a VNIC but also some others resources.

**Comment by jbpaux** [comment]
Just remove other resources then 😄 
Create the nic then update it to static

**Comment by Klaas-** [comment]
So this seems to be a misconception about what "dynamic" means for a private IP in Azure. Creating a NIC in Azure with a "dynamic" private ip means the IP is assigned upon creation of the interface and only freed upon deletion of the interface.

This means it behaves exactly as "static" interfaces.

The only difference is that a "static" interface has a user assigned (as in input parameter) IP, a "dynamic" interface is automatically assigned a free IP from the subnet.

https://github.com/MicrosoftDocs/azure-docs/blob/4bc20bec0b678d282233f6a67eed633034ad24fa/articles/virtual-network/ip-services/private-ip-addresses.md?plain=1#L38-L54
https://github.com/MicrosoftDocs/azure-docs/blob/798be06dee9d57c838412a459d03e5f0b2afaf10/articles/virtual-network/virtual-network-network-interface.md?plain=1#L49
