### ISSUE TITLE
Deploy to Azure button does not work for "Very simple deployment of an Windows VM"

### ISSUE THREAD

**Issue by TimMurphy** [Azure/azure-quickstart-templates#1209]
After click **Deploy to Azure** button on `https://github.com/Azure/azure-quickstart-templates/tree/b1908e74259da56a92800cace97350af1f1fc32b/101-simple-windows-vm` the Azure portal reports:

```
// Error loading template from https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-simple-windows-vm/azuredeploy.json
```

**Comment by singhkay** [comment]
@TimMurphy It's loading for me. Looking at your Uri, tt looks like you might have clicked it from some other branch than master. Can you try again from here https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-windows

**Comment by TimMurphy** [comment]
My bad. Should have spotted that. Thank you for the following it up.
