### ISSUE TITLE
Self Signed Certificate in the WinRM on a Windows VM demo is created with an expiration date in the past. 

### ISSUE THREAD

**Issue by xandersherry** [Azure/azure-quickstart-templates#12100]
[vm-winrm-windows demo](https://github.com/Azure/azure-quickstart-templates/tree/3b3b0f0148d6602d614110026985cd692ba19258/demos/vm-winrm-windows)

### Issue Details
When running this demo, the self signed certificate that is created is given an expiration date of 2022-01-01, and as we are now past this date, the demo failed due to the expired certificate.  

The problem is line 51 of  [ConfigureWinRM.ps1](https://github.com/Azure/azure-quickstart-templates/blob/master/demos/vm-winrm-windows/ConfigureWinRM.ps1)  

I would suggest making the expiry date dynamic (current date + 1 year for instance) to prevent this from having to be manually bumped in the future.

**Comment by david-shearwater** [comment]
This is also breaking AZ DevOps task: AzureFileCopy@4 for me when using checking `Enable Copy Prerequisites`

**Comment by xandersherry** [comment]
I've created a PR to resolve this issue.  PR: #12101

**Comment by jbpaux** [comment]
You can close the issue if it's resolved @xandersherry

**Comment by xandersherry** [comment]
@jbpaux Thank you for the reminder.  Closing.
