### ISSUE TITLE
Office 365 Desktop VM - The argument 'scripts/DeployO365SilentWithVersion.ps1' to the -File parameter does not exist

### ISSUE THREAD

**Issue by truekonrads** [Azure/azure-quickstart-templates#12211]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Office 365 Desktop VM](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/office/windows-vm-o365)

### Issue Details
Deployment fails with:
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'SetupOffice'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '-196608'. The command had an error output of: 'The argument 'scripts/DeployO365SilentWithVersion.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.\r\n'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}
### Repro steps (*if necessary, delete otherwise*)
```
1. Click on Deploy button on github
2. Input password, name VM, click review+create
3. Observe error

![image](https://user-images.githubusercontent.com/1421150/155086296-bacdc3a1-bce6-4078-b2c2-00f752738b20.png)

**Comment by jbpaux** [comment]
Found the gotchas, script is downloaded in root folder of the extension. I push a PR for that :)
