### ISSUE TITLE
"logic-app-and-function-app" Azure Quickstart template vanished from Visual Studio, but template still exists in repo

### ISSUE THREAD

**Issue by ecfan** [Azure/azure-quickstart-templates#12323]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[logic-app-and-function-app](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.logic/logic-app-and-function-app)

### Repro steps (*if necessary, delete otherwise*)
This issue was originally reported in GitHub from the tutorial that uses the problem template: [GitHub #90065](https://github.com/MicrosoftDocs/azure-docs/issues/90065)

1. In Visual Studio (2019 in this case), create a new C# Azure Resource Group project. I'm not sure whether you need all the other requirements necessary for the tutorial, but just in case: [Prerequisites](https://docs.microsoft.com/en-us/azure/logic-apps/create-serverless-apps-visual-studio#prerequisites).

2. Under **Show templates from this location**, select **Azure QuickStart (github.com/Azure/azure-quickstart-templates)**.

3. When the prompt to select an Azure template appears, enter the search term `logic-app-and-function-app`.

   **Expected**
   In the Azure quickstart template list, the specified template should appear, for example:
   ![image](https://user-images.githubusercontent.com/13206671/159049414-e19ec295-070a-403b-8038-7a7093592df7.png)

   **Actual**
   No template appears:
   ![image](https://user-images.githubusercontent.com/13206671/159049306-84499244-08c5-41db-b9b2-81687c613e45.png)

**Comment by ecfan** [comment]
Including @Azure/azure-logicapps-team in case they can take action. Thanks!

**Comment by StephenWeatherford** [comment]
I'll take a look...

**Comment by StephenWeatherford** [comment]
Sorry for the delay, haven't forgotten.

**Comment by StephenWeatherford** [comment]
Unfortunately, I'm having to remove selecting quickstart templates from the VS dialog because github.com no longer allows non-authenticated access to its search API, and our priorities are such that I can take the time to implement this as new functionality.  

The template is still available [here](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.logic/logic-app-and-function-app), but it must be manually copy/pasted into the VS project's template file.

Sorry for the inconvenience.
