### ISSUE TITLE
Installation notes point to non-existent URL

### ISSUE THREAD

**Issue by auld** [Azure/azure-quickstart-templates#1243]
The installation notes section of the README.md file give  https://github.com/Azure/azure-quickstart-templates/tree/master/ubuntu-desktop for more information on setting up the jumpbox. However this URL does not exist and the information on how to connect via VNC is not detailed.

**Comment by auld** [comment]
This last issue is for https://github.com/Azure/azure-quickstart-templates/tree/master/mesos-swarm-marathon.

**Comment by rgardler** [comment]
Thanks for your feedback. The templates and docs have now been updated. There is no longer a need for VNC connection to a jumpbox (yay!) and we believe all links work. Please see the final resting place for this templates at 101-acs-swarm and 101-acs-mesos
