### ISSUE TITLE
Incorrect reference to resource (bicep code bug)

### ISSUE THREAD

**Issue by lwsrbrts** [Azure/azure-quickstart-templates#12563]
https://github.com/Azure/azure-quickstart-templates/blob/b5540e7aec62d49058aec78ca795edd3787fba47/managementgroup-deployments/create-subscription-resourcegroup/modules/.create.resources.wrapper.bicep#L25-L26

I think this is just a simple bug really and simple enough to resolve.

The reference in the above lines to ```${rg.name}``` returns the *name* of the ```rg``` module above it in the code. ```${rg.name}``` would enumerate as ```create-demo``` when run (if you don't change the input parameters).

I assume instead this should be:

```
 scope: resourceGroup(subscriptionId, resourceGroupName)
  name: 'nested-createResourceGroup-${resourceGroupName}'
```

If the deployment tried to deploy the storage account in to a resource group called ```create-demo``` - then that resource group wouldn't exist because it would be created as ```demo``` by the ```rg``` module.

Hopefully that makes sense.

**Comment by bmoore-msft** [comment]
It does make sense... I pushed a fix if you want to have a look...

**Comment by lwsrbrts** [comment]
Thank you.
