### ISSUE TITLE
Problem in finding bicep templates

### ISSUE THREAD

**Issue by zsteer** [Azure/azure-quickstart-templates#12570]
I am redirected from azure/bicep repo examples section but i am unable to find any bicep templates here in this repo. Is there a separate section for that? Or is there an assumption that we can pick the ARM templates from here and convert them to bicep ourselves?

Help will be appreciated as i am starting out in this area where I need to write a lot of code for infrastructure and those example bicep files were always a reference for me.

Thanks.

**Comment by Gordonby** [comment]
Many (but not all) of the template are bicep.

There is not a separate section.

Where there is a good sample of what you want, but it's just in ARM - then do a `bicep decompile` operation.

**Comment by bmoore-msft** [comment]
Try this:

https://docs.microsoft.com/en-us/samples/browse/?expanded=azure&products=azure-resource-manager&languages=bicep
