### ISSUE TITLE
Buildbot incorrectly reports invalid JSON

### ISSUE THREAD

**Issue by rgardler** [Azure/azure-quickstart-templates#1258]
My PR (#1256) failed validation for azuredeploy.json. However, visual checking, http://jsonlint.com, https://jsonformatter.curiousconcept.com/ and the Azure portal all disagree - each says it's valid.

If you can see what is wrong with it I'll happily fix the json, but to me it looks like a problem with the validator.

**Comment by rgardler** [comment]
It looks like this is actually a poorly formed error message - still investigation. will report back.

**Comment by singhkay** [comment]
@rgardler Looks like that PR doesn't even have an azuredeploy.json. Is that correct?

**Comment by rgardler** [comment]
The problem was introduced in an earlier PR pushed on a PR deadline for our preview release (sorry I cut corners). I noticed it when following the proper review cycle for later commits.

**Comment by rgardler** [comment]
I've just run all the checks again and (jsonlint, jsonlint.com and jsonformatter) none of them report an error. I'm at a loss.

**Comment by singhkay** [comment]
@rgardler Can you point to the file that is reporting errors?
