### ISSUE TITLE
101-acs-mesos readme walk through, click on sandbox in mesos fails with error message 

### ISSUE THREAD

**Issue by auld** [Azure/azure-quickstart-templates#1267]
Following the walk through for 101-acs-mesos most things work but whenever I click on any of the "sandbox" links in the mesos web page, I get the following message:

The slave's hostname, 'mesos-agent-58CAAA99-0', is not accessible from your network
The slave's port, '5051', is not accessible from your network
The slave timed out or went offline

I don't know if this is something I have done incorrectly or if it is a problem with the setup. 

I have 1 master and 1 agent. 

Thanks,
Will

**Comment by singhkay** [comment]
@rgardler @sauryadas Can you take a look at this?

**Comment by rgardler** [comment]
This is a known issue and will be resolved in production very soon. It is not something you have configured incorrectly.

You can navigate to the sandbox successfully from within the Marathon UI, the error only occurs in the Mesos UI.

If this addresses your issue please close this issue to indicate that is the case. Thanks.

**Comment by auld** [comment]
Closing issues based on last comment.
