### ISSUE TITLE
cannot find the "bosh-setup" template in https://azure.microsoft.com/en-us/documentation/templates/.

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#1276]
I cannot find the [bosh-setup](https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup) template in https://azure.microsoft.com/en-us/documentation/templates/.

**Comment by singhkay** [comment]
@bursteg tells me you should file a bug 

`If you haven’t already, please submit a bug/request using [UserSnap extension for Chrome](http://acomdocs.azurewebsites.net/articles/workitems-usersnap-get-started/) and we will get it queued up.`

**Comment by bingosummer** [comment]
Thanks @singhkay .
I'll file a bug.
