### ISSUE TITLE
Tableau Server Single Node deployment fails on Centos Linux

### ISSUE THREAD

**Issue by andrewd12345** [Azure/azure-quickstart-templates#12780]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Tableau Server Single Node](https://azure.microsoft.com/en-us/resources/templates/tableau-server-single-node/)

The template did not work and the release it is trying to download is out of date and has security issues.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CustomScript'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n\n[stderr]\n./config-linux.sh: illegal option -- e\n./config-linux.sh: line 37: printf: `Q': invalid format character\n./config-linux.sh: line 70: lsb_release: command not found\n--2022-08-10 23:34:08--  https://downloads.tableau.com/esdalt/2020.1.1/tableau-server-2020-1-1.x86_64.rpm\nResolving downloads.tableau.com (downloads.tableau.com)... 2.18.83.221\nConnecting to downloads.tableau.com (downloads.tableau.com)|2.18.83.221|:443... connected.\nHTTP request sent, awaiting response... 404 Not Found\n2022-08-10 23:34:14 ERROR 404: Not Found.\n\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "}]}

**Comment by bmoore-msft** [comment]
The sample was pretty old, I wasn't able to get it working so removed it from the repo...

**Comment by andrewd12345** [comment]
Thanks for the update Brian. Cheers, Andrew
