### ISSUE TITLE
Microsoft.Authorization/roleEligibilityScheduleRequests shows error with "A role assignment request with Id: already exists"

### ISSUE THREAD

**Issue by anoopkv39** [Azure/azure-quickstart-templates#12838]
{
  "$schema": "https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": 
  {
	"location": {
		"type": "String",
		"defaultvalue" : ""
	},
	"Owners-principalId": {
		"type": "string",
		"defaultValue" : ""
	},
	"managementGroupName": {
		"type": "string",
		"defaultValue": ""
	},
	"requestType": {
		"type": "string",
		"defaultValue": "AdminAssign"
	}
  },
  "variables": 
  {
	"managementGroupId" : "[resourceId('Microsoft.Management/managementGroups', parameters('ManagementGroupName'))]",	
	"Owner": "[subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '8e3af657-a8ff-443c-a75c-2fe8c4bcb635')]"
  },
  "resources": 
  [
	{
		"type": "Microsoft.Authorization/roleEligibilityScheduleRequests",
		"apiVersion": "2022-04-01-preview",
		"name": "613c5f25-e652-448e-9911-783767706d6b",
		"scope" : "[variables('managementGroupId')]",
		"properties": 
		{
			"principalId": "[parameters('Owners-principalId')]",
			"roleDefinitionId": "[variables('Owner')]",
			"requestType": "[parameters('requestType')]",
			"scheduleInfo": 
			{
				"startDateTime": "2022-08-13T08:32:07.0706351+10:00",
				"expiration": 
				{
					"type": "AfterDuration",
					"duration": "P365D"
				}
			}
		}
	}
  ],
  "outputs": {}
}

### Issue Details

New-AzManagementGroupDeployment : 7:14:46 AM - The deployment 'RBAC' failed with error(s). Showing 1 out of 1 error(s).
Status Message: A role assignment request with Id: 613c5f25-e652-448e-9911-783767706d6b already exists (Code:DeploymentOperationFailed)
CorrelationId: a1ae8126-09d6-41b7-8c38-0e6ed959384a
At line:1 char:1
+ New-AzManagementGroupDeployment -TemplateFile $TemplateFile -Location ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzManagementGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureManagementGroupDeploymentCmdlet

### Repro steps (*if necessary, delete otherwise*)
1. Running the template first time works fine.
2. Second execution throws above error
3. Using static GUID for role assignment name

**Comment by bmoore-msft** [comment]
@anoopkv39 - which sample is this?
