### ISSUE TITLE
HTTP error 404 - Unable to go past the VM extension stage

### ISSUE THREAD

**Issue by sudhiriyer** [Azure/azure-quickstart-templates#12839]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Ttableau-server-single-node](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/tableau/tableau-server-single-node)

### Tried using the deploy to azure button on Github. I got error 404 from the VMextension stage - 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CustomScript'. Error message: \"Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}

Upon seeing the version of Tableau that was being downloaded, I saw the URI was being constructed as - https://downloads.tableau.com/esdalt/2020.1.3/TableauServer-64bit-2020.1.3.exe which returned 404 not found on my browser.

So, I modified the default Tableau version to 2022.1.6 which is what Tableau's product download website suggests to download. I modified the ARM template to :

   "tableau_version": {
      "type": "string",
      "allowedValues": ["2020.1.3","2019.4.6","2019.3.7","2019.2.11","2022.1.6"],
      "metadata": {
        "description": "The version of Tableau Server to install."
      },
      "defaultValue": "2022.1.6"
    },

I thought this will make the extensions script reach out to : https://downloads.tableau.com/esdalt/2022.1.6/TableauServer-64bit-2022-1-6.exe which leads to a downloadable exe file.

I re-initiated the deployment. I still get the same error as above - HTTP 404. 

Appreciate if I can get some help in why I keep running into HTTP 404. 

PS - I am pretty new to ARM templates.

**Comment by bmoore-msft** [comment]
I've removed the sample as I couldn't get it working either - if you have other ideas or can get it working feel free to submit...
