### ISSUE TITLE
ARM Template for Deploy Shibboleth Identity Provider cluster on Windows no longer valid

### ISSUE THREAD

**Issue by ddowningms** [Azure/azure-quickstart-templates#12846]
The ARM Template for the cluster deployment doesn't seem to be valid.  I've tried both West US 2 and East US.

![image](https://user-images.githubusercontent.com/79298151/191107572-cf9b1dc5-b1e4-47c5-866f-47a158780ece.png)

Please update the template to use the latest versions of all resources.

Thank you.

**Comment by bmoore-msft** [comment]
The error is saying the size you requested is not available in the location - what size did you request?

**Comment by ddowningms** [comment]
I choose the default size.  The problem is not with the size, it's with the template.  Windows Server 2012 R2 is no longer an option in Azure.  The template needs to be updated with the latest and greatest versions of the Azure Resources necessary.  Resource Group, OS, Disk, ....

**Comment by bmoore-msft** [comment]
There are temporary capacity constraints with those sizes in a number of locations - I removed the size restrictions from the template so you can select any size.

**Comment by ddowningms** [comment]
Thank you sir!  The deployment succeeded.
