### ISSUE TITLE
Visual Studio - Azure Resource Group - Template using old AzureRmResourceGroupDeployment commands still after several years

### ISSUE THREAD

**Issue by kprpg** [Azure/azure-quickstart-templates#12845]
Any of the "Azure Resource Group" Templates that Visual Studio project provides - it generates deprecated PS command that powers the Deployment. 

### Issue Details
Visual Studio "Azure Resource Group" type of Project template still uses the below, even though it is 3-4 years since deprecated, and it has to be replaced with New-AzResourceGroupDeployment PS command.

New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFile).BaseName + '-' + ((Get-Date).ToUniversalTime()).ToString('MMdd-HHmm')) `
                                       -ResourceGroupName $ResourceGroupName `
                                       -TemplateFile $TemplateFile `
                                       -TemplateParameterFile $TemplateParametersFile `
                                       @OptionalParameters `
                                       -Force -Verbose `
                                       -ErrorVariable ErrorMessages
    if ($ErrorMessages) {
        Write-Output '', 'Template deployment returned the following errors:', @(@($ErrorMessages) | ForEach-Object { $_.Exception.Message.TrimEnd("`r`n") })
    }
}

Please change this boiler plate code to reflect the thing currently supported.

**Comment by bmoore-msft** [comment]
@kprpg - the script in VS is owned by VS, your best bet is likely to use the `Send Feedback` link from the help menu in VS
