### ISSUE TITLE
Bicep template for SFTP preview feature broken due to incorrect versions

### ISSUE THREAD

**Issue by michael-crawford** [Azure/azure-quickstart-templates#12849]
[SFTP](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.storage/storage-sftp)

### Issue Details
When I tried to use this Quickstart, it failed. At first I thought this was not supported by bicep, as a similar ARM template worked. I later realized this template is referencing old versions of the relevant modules which do not support these newer features. Once I updated to the latest versions, it worked. It's unclear how this got published in the first place, as I don't think those version ever supported the new features in the template.

### Repro steps (*if necessary, delete otherwise*)
1. Try to run the template with bicep, after enabling the new preview feature.
2.
3.
4.
5.

**Comment by bmoore-msft** [comment]
I'm assuming this was related to `azuredeploy.json` being compiled with an older version of bicep, though it seemed to work fine for me.  I updated it to 10.61, lmk if that's not working for you...
