### ISSUE TITLE
Could find url to the traefik dashboard in the portainer/traefik docker template

### ISSUE THREAD

**Issue by alphaxr6** [Azure/azure-quickstart-templates#12909]
[docker-portainer-traefik-windows-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/traefik/docker-portainer-traefik-windows-vm)

Hey,

I have a little issue regarding the template deployment for traefik and portainer.

I found the portainer URL to connect to the dashboard. Unfortunately, I couldn't find any dashboard URL for traefik.

The dashboard feature was activated (--api.dashboard=true). I tried:

- dsname/api
- dnsname/dashboard
- dnsname/traefik/api
- dnsname/traefik/dashboard
- dnsname/traefik/api/
- dnsname/traefik/dashboard/
- etc...

Thank you for the help :)

**Comment by bmoore-msft** [comment]
@tfenster ?

**Comment by tfenster** [comment]
@alphaxr6 did you set `traefik.enable=true` on line 28 in docker-compose.yml? You will find it below f:\compose. If you haven't done that, you need to change it and run `docker-compose up -d` from a terminal with working directory f:\compose as well
