### ISSUE TITLE
The template parameter 'existingDataFactoryVersion' at line '5' and column '35' is not provided. 

### ISSUE THREAD

**Issue by Enver-Adams** [Azure/azure-quickstart-templates#12932]
I am using the following ARM Template. It validates correctly and then fails during deployment with the below error.

Please advise; as manually editing the template to include 'existingDataFactoryVersion' with value of 'V2' results in a custom template where all links to the original ARM template is lost and the deployment fails. 

I can see in the opening preamble (Parameters) tfor this ARM template that existingDataFactoryVersion' is supposed to be declared BUT it seems missting from the template. 

https://learn.microsoft.com/en-us/samples/azure/azure-quickstart-templates/vms-with-selfhost-integration-runtime/

### Issue Details

**{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The value for the template parameter 'existingDataFactoryVersion' at line '5' and column '35' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'."}]}**

**Comment by bmoore-msft** [comment]
I don't see the issue with the template (and it passed the most recent automated test)... the error message sounds like a value wasn't provided for the param - are you deploying via portal?  (you have to explicitly provide the value in that case)...

**Comment by paul-dowling-promethean** [comment]
@bmoore-msft The [nested/IRInstall.json](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRInstall.json) file requires the `existingDataFactoryVersion` parameter, but it's been removed from the calling template. Generates an error on deployment via the portal.

**Comment by bmoore-msft** [comment]
Got it, thanks...  Should be fixed in #12950
