### ISSUE TITLE
The documentation refers to "Jumpbox" that does not exist

### ISSUE THREAD

**Issue by khenidak** [Azure/azure-quickstart-templates#1302]
the readme.md refers to jumpbox that does not actually gets created. The master LB contains NAT rules for ssh on 220X to 22 (for each master) that should be enough to manage the cluster.

please remove the references to jumpbox

**Comment by singhkay** [comment]
@khenidak Which template is this in reference to? Since this repo is a community effort, please feel free to submit a fix with the changes.
