### ISSUE TITLE
Question about 101-vm-from-user-image, creating VM using vhd on different account.

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-quickstart-templates#1303]
It is stated in the readme: https://github.com/Azure/azure-quickstart-templates/blob/364dcf26ce48f93692e2c9c0fc3f85f2d73c43ce/101-vm-from-user-image/README.md

 'Prerequisite - The Storage Account with the User Image VHD should already exist'

But if I use a VHD img stored in a different account other than the userImageStorageAccountName, it would report following failure:
{"error":{"code":"ConflictingUserInput","message":"Source and destination storage accounts for disk userImageVM-osDisk are different."}}

Also according to:
https://feedback.azure.com/forums/216843-virtual-machines/suggestions/6399760-vm-created-from-custom-image-should-be-able-to-sel#comments

Should the prerequisite be updated?

**Comment by singhkay** [comment]
@karataliu Definitely. Can you edit the text and send a PR?

**Comment by karataliu** [comment]
Not sure whether the text change is enough, regarding this change: https://github.com/Azure/azure-quickstart-templates/commit/0290284462ee041ffa2971c19160c12783570b63#diff-bb3c16727908ad12dd54ec7af3daa103L11

After that, userImageStorageAccountName is used for osDisk only, but the name is still user image. May be also reverting the userImage/osDisk part should do better.
