### ISSUE TITLE
github-enterprise template: NSG not associated with subnet/nic

### ISSUE THREAD

**Issue by LeCampusAzure** [Azure/azure-quickstart-templates#1304]
The github-enterprise template has a NSG with all the necessary rules inside, but it is not associated neither with the subnet or the VM's NIC. This opens an important security breach for this deployment.

**Comment by singhkay** [comment]
@LeCampusAzure I see it is associated to the subnet here https://github.com/Azure/azure-quickstart-templates/blob/master/github-enterprise/azuredeploy.json#L126

**Comment by gnawhleinad** [comment]
:wave: @LeCampusAzure! (And, thanks @singhkay for the comment and :point_right:.)

> This opens an important security breach for this deployment.

As @singhkay mentioned, we do associate the network security groups. Was this from inspection of the `.json` or did you see something on inspection after a deploy?
