### ISSUE TITLE
docker-simple-on-ubuntu with 14.04-Daily parameter fails

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-quickstart-templates#1305]
Deployment error is:
{"error":{"code":"ImageNotFound","target":"imageReference","message":"The platform image 'Canonical:UbuntuServer:14.04-DAILY:latest' is not available. Verify that all fields in the storage profile are correct."}}

**Comment by singhkay** [comment]
@gbowerman Thanks for the catch! Looks like 14.04-DAILY is no longer a valid option. Adding @gatneil for update

![image](https://cloud.githubusercontent.com/assets/6164178/13365202/7e6961e2-dc88-11e5-90c8-1204ec765375.png)

**Comment by gatneil** [comment]
Fixed with this PR: https://github.com/Azure/azure-quickstart-templates/pull/1563
@singhkay to review, then we're good to go :)
