### ISSUE TITLE
New Domain Template fails sicve Dec 30 update

### ISSUE THREAD

**Issue by M8ey-AU** [Azure/azure-quickstart-templates#13100]
Hey Team - The Azure Templates - application-workloads/active-directory/active-directory-new-domain no longer works.

Using this to create a new domain returns an error:

[Error parsing template details. Click here to open template repository.](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain)

The other Templates do work fine but not this one.

**Comment by alex-frankel** [comment]
The CI is supposed to generate the azuredeploy.json automatically when the PR is merged. I am not sure why it was not generated, but we will look into it. In the meantime, @mumian can you submit a new PR that includes azuredeploy.json?

**Comment by mumian** [comment]
PR created - https://github.com/Azure/azure-quickstart-templates/pull/13102

**Comment by alex-frankel** [comment]
Just merged @mumian 's PR. @M8ey-AU / @shashaa35 -- can you take a look?

**Comment by M8ey-AU** [comment]
Thanks – Any idea why Server 2019 wasnt used and the Template is for an older 2016?


Ian Melton Information Technology Systems
PO Box 90, Essendon, Victoria, 3040
M 0416 248 866
E ***@***.***
www.lucrumag.com.au
CONFIDENTIALITY NOTICE AND DISCLAIMER This email (including any attachment to it) is confidential and may also be privileged and exempt from disclosure under applicable law. Accordingly, if you are not the intended recipient, please notify us immediately and delete this email (including any attachment to it) from your computer system. You should also not disseminate or copy the email.  We do not assure the security of information electronically transmitted and your communication with us through such means signifies your acceptance of any risk attaching thereto. Any statement contained herein is not to be construed as an offer to enter into any contractual obligation nor an acceptance of any offer. Thank you.

**Comment by mumian** [comment]
I will create a PR to update the SKU.
