### ISSUE TITLE
101-mobile-app-create is not idempontent - works only once

### ISSUE THREAD

**Issue by MelvinVermeer** [Azure/azure-quickstart-templates#1345]
When this sample is ran for the first time, it completes succesfully.
But when you deploy the exact same template again it fails on : 

Resource Microsoft.NotificationHubs/namespaces/notificationHubs 'examplemobileapp-q6r5h6yqa3qbo-namespace/examplemobileapp-q6r5h6yqa3qbo-hub' failed with message 'Conflict'.

No additional information can be found in deployment logs other than 'Conflict'

**Comment by singhkay** [comment]
@tfitzmac @mattchenderson Can you take a look at this?

**Comment by tfitzmac** [comment]
@MelvinVermeer - thanks for reporting this issue. I am trying to track down the problem.

**Comment by sjkp** [comment]
@tfitzmac any update on this? I think it has to do with the revision property.

**Comment by mattchenderson** [comment]
Following up with the NH team.

**Comment by tfitzmac** [comment]
This looks like a bug in Notification Hubs. I deployed a hub through the portal marketplace, then retrieved the template that was used and re-deployed it. I get the conflict error.

@sjkp - I don't see this revision property. Which resource has that property?

**Comment by smithab** [comment]
@MelvinVermeer we have not made NotificationHubs as idempotent. So if you try to do a create on an already existing hub it will return conflict. I am making the fix on our side to not throw if the hub has already been created

**Comment by SychevIgor** [comment]
Probably, could be closed... because there are no more azure app service mobile apps. Simple Web Apps with all properties
