### ISSUE TITLE
SonarQube WebApp + PostgresSql goes into maintenance mode

### ISSUE THREAD

**Issue by njannink** [Azure/azure-quickstart-templates#13463]
This is already the second time this happened and I got no idea how to resolve this. I have deployed the following template

[SonarQube on Web App with PostgreSQL and VNet integration](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql-private-vnet)

And after some months my SonarQube installation goes into maintenance mode, by what I guess is by attempting to do an upgrade. The only way I then can fix this is by doing a new deployment and starting with a clean database. Any idea how to do a proper upgrade or how to make sure SonarQube doesn't do an upgrade?

**Comment by erudinsky** [comment]
Hey @njannink thanks for bringing this up. This is possible to address by 'SONAR_UPDATECENTER_ACTIVATE=false' variable. I am going to add it to the WebApp.
