### ISSUE TITLE
Error parsing template

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-quickstart-templates#1348]
Perhaps I'm doing this wrong. I have an existing github repo and copied the following files from the 201-web-app-github-deploy sample:

- azuredeploy.json
- azuredeploy.parameters.json
- metadata.json

To get started I haven't changed anything but my repoUrl in the azuredeploy.json file. When I deploy it I get: "Error parsing template. Please ensure template is valid JSON and has no comments."

Here is the repo: https://github.com/microServiceBus/microservicebus.node

**Comment by singhkay** [comment]
@wmmihaa Instead of https://github.com/microServiceBus/microservicebus.node.git you probably need https://github.com/microServiceBus/microservicebus.node

**Comment by wmmihaa** [comment]
Fair enough, but that doesn't explain the "Error parsing template. Please ensure template is valid JSON and has no comments." error...
I've updated the repoUrl, but the exception still comes up when I click the "Deploy to Azure" button.

**Comment by wmmihaa** [comment]
The problem was the URI to the json file was not pointing to the RAW json...

**Comment by singhkay** [comment]
@wmmihaa Glad you got it sorted out!

**Comment by wmmihaa** [comment]
@singhkay I'm stil struggling to get my deploy script working for a node.js site in github. The same script works with an MVC app, but not using a node.js site. Are there any special settings for node.js?

**Comment by azure2388** [comment]
Hi wmmihaa,
Could you please snd me the steps how the issue is fixed. I am struggling with the same issue
azure2388@gmail.com

**Comment by ricomak** [comment]
Hi wmmihaa,
Could you please snd me the steps how the issue is fixed. My email is rico.az103@outlook.com

**Comment by wmmihaa** [comment]
@azure2388 and @ricomak sorry mates this was three years ago, and I hardly remember the issue. Bu I seam to have fixed it:
>The problem was the URI to the json file was not pointing to the RAW json...

hth

**Comment by janaka** [comment]
> @azure2388 and @ricomak sorry mates this was three years ago, and I hardly remember the issue. Bu I seam to have fixed it:
> 
> > The problem was the URI to the json file was not pointing to the RAW json...
> 
> hth

you do know they are scam/phishing?! :)
