### ISSUE TITLE
ARM: VM creation template referring SSH keys from azure key vault

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-quickstart-templates#1350]
I have a PEM key added in key vault, and I want to use the key in VM provisioning.

 I want to reference the key added to vault into the provisioning script and I use format as below:

"sshRSAPublicKey": {
"reference": {
"keyVault": {
"id": "/subscriptions/xxxxxx/resourceGroups/vaultRG/providers/Microsoft.KeyVault/vaults/mmdvault"
},
"keyName": "qa-key"
}
},

But error is "The request content was invalid and could not be deserialized: 'Could not find member 'keyName' on object of type 'KeyVaultParameterReference'. Path 'properties.parameters.sshRSAPublicKey.reference.keyName'"

I use the same in OS profile of VM

"osProfile": {
"computerName": "[variables('vmName')]",
"adminUsername": "[parameters('adminUsername')]",
"linuxConfiguration": {
"disablePasswordAuthentication": "true",
"ssh": {
"publicKeys": [
{
"path": "[variables('sshKeyPath')]",
"keyData": "[variables('sshRSAPublicKey')]"
}
]
}
}
}
But when I refer secret i use "secretName" instead of keyName in parameters and it works.

can you please help me here.

**Comment by singhkay** [comment]
@infosatheesh2020 Can't use keys with VMs. Only secrets. Have a look at few of the templates around key vaults 

https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-keyvault-windows
https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-push-certificate-windows
https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-secure-password
