### ISSUE TITLE
Kafka-Ubuntu large cluster deployment ( https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-ubuntu-multidisks )

### ISSUE THREAD

**Issue by dsaurabhd** [Azure/azure-quickstart-templates#1351]
HI see an issue while deploying a large kafka cluster ( https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-ubuntu-multidisks) 

-------------------------------------------------------------------------------------------------------------------

Deployment template validation failed: 'The template parameters 'subnet' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'commonSettings, osSettings, storageSettings, adminPassword, machineSettingsbroker'. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'.

**Comment by singhkay** [comment]
Adding template author @CognosysTech can you take a look at this error?

**Comment by dsaurabhd** [comment]
Works well now.
