### ISSUE TITLE
[101-acs-mesos] error when trying to deploy ACS Mesos template

### ISSUE THREAD

**Issue by drywolf** [Azure/azure-quickstart-templates#1355]
Hi, I wanted to try out the new container services facilities, but I when I tried to deploy the `101-acs-mesos` template I get the following error and the deployment fails:

    {"error":{"code":"PropertyChangeNotAllowed","target":"agentProfile.dnsPrefix","message":"Changing property 'agentProfile.dnsPrefix' is not allowed."}}

I can't find anything about this error on the web. What could I do to figure out what is going wrong with the template and get my ACS setup running :smile: ?

**Comment by singhkay** [comment]
Adding ACS experts @rgardler @anhowe

**Comment by edevil** [comment]
+1

**Comment by drywolf** [comment]
I was able to sucessfully run the template. I think the problem was that I had not created any other virtual machine or service on my azure account.
After I created a Ubuntu virtual machine for testing it seems that my Azure accounts & subscription were associated with the necessary account policies (networking, storage, compute, ...).

I'm not sure if this really was the fix or if something else in the ARM backend was fixed in the meantime, but it is working ok for me now.

**Comment by singhkay** [comment]
@drywolf Neat! There is a registration that happens with various RPs when you try to create a resource for the first time. Not sure why this didn't happen with ACS. @edevil Can you try this as well?

cc: @rgardler @anhowe

**Comment by edevil** [comment]
Yes, now the deployment worked... Thanks.

**Comment by singhkay** [comment]
@edevil Interesting. Thanks for confirming!
