### ISSUE TITLE
Unable to deploy optimzation workbook

### ISSUE THREAD

**Issue by tobiasny** [Azure/azure-quickstart-templates#13624]
[Optimization workbook](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.costmanagement/optimization-workbook)

### Issue Details

I'm attempting to deploy the cost manangement optimization workbook in Azure using custom deployment. Pressing the `Deploy to Azure` gives me the following error message inside the custom deployment UI in the Azure portal:

```
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.costmanagement/optimization-workbook/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 
There was an error downloading from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.costmanagement/optimization-workbook/createUiDefinition.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint.
```

### Repro steps
1. Press `Deploy to Azure` button in [optimization workbook template readme](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.costmanagement/optimization-workbook)

**Comment by flanakin** [comment]
I was able to deploy it. Are you still seeing this error?

One thought: Could this be due to a firewall policy that's blocking the raw.githubusercontent.com domain?

**Comment by tobiasny** [comment]
Thanks for your swift reply @flanakin. You are correct, my network was blocking the  raw.githubusercontent.com domain. Problem resolved.
