### ISSUE TITLE
Using conditional statements in Template

### ISSUE THREAD

**Issue by nitin16** [Azure/azure-quickstart-templates#1367]
Is there any way to use conditional statements in templates?

for example I am building template which will have vms with data disks on QA and Production, but no data disks on Dev. Another scenario would be there are some extensions only needs to be installed in prod VMs but no where else. 

Any help is appreciated. 

Thanks, 
Nitin

**Comment by singhkay** [comment]
Sure, there are many examples of this. 

See this https://github.com/Azure/azure-quickstart-templates/blob/master/checkpoint-single-nic/azuredeploy.json#L11 and follow through on how ssh or password auth happens. 
For dynamic data disks see this - https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-dynamic-data-disks-selection
Another here where this template creates a new vnet or uses existing - https://github.com/Azure/azure-quickstart-templates/blob/master/mysql-replication/azuredeploy.json#L68

**Comment by nitin16** [comment]
Thanks. This helped.

**Comment by singhkay** [comment]
Awesome!

**Comment by jan-wang** [comment]
HI,
For the first example in comment 2, when I want use ssh key to deploy, I still need to input the password.
Do we have some ways to just input the one of them?
for example, if i choose ssh key, then I won't input the password.
