### ISSUE TITLE
azuredeploy.json in finops hub is out of date and not aligned to commited changes in bicep files

### ISSUE THREAD

**Issue by thecloudman** [Azure/azure-quickstart-templates#13725]
FinOps toolkit 0.2 - FinOps hub update , (https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.costmanagement/finops-hub)

### Issue Details 
azuredeploy.json has not been updated to reference changes made to datafactories bicep and as such is still deploying version 0.1.1 

   ],
                            "userProperties": [],
                            "typeProperties": {
                              "variableName": "metric",
                              "value": {
                                "value": "amortizedcost",
                                "type": "Expression"
                              }

Here value should be "focuscost" and o datafactory bicep should be used that was commited two days ago.

**Comment by flanakin** [comment]
I suspect the azuredeploy.json file is not getting updated when nested templates are updated.

@alex-frankel Is this a known gap? Is there a suggested workaround?
