### ISSUE TITLE
Invalid extension name in 201-vm-domain-join

### ISSUE THREAD

**Issue by adbertram** [Azure/azure-quickstart-templates#1375]
[201-vm-domain-join](https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-domain-join/azuredeploy.json)

### Issue Details

When I try this template, I get the error: 

statusCode:BadRequest serviceRequestId:56e7a5b5-742b-4d97-9ba3-d9748d53ae6d statusMessage:{"error":{"code":"InvalidParameter","target":"extensionName","message":"The entity name is invalid according to its validation rule: ^[^_\\W][\\w-._]{0,79}(?<![-.])$."}}

I noticed the extension name was "JsonADDomainExtension", but I don't see this as an available extension. Was this extension removed? If so, is there another extension I can use other than the CustomScriptExtension (or DSC) to add a VM to an existing domain?

**Comment by singhkay** [comment]
@adbertram Just to make sure, you deployed using the "Deploy to Azure" button and made no changes to the existing template?

**Comment by singhkay** [comment]
@adbertram I just deployed the template and it joined the domain successfully without any problems

**Comment by adbertram** [comment]
I apologize. I have not had the opportunity to get back to this until now. I did not deploy this directly to Azure. I must have goofed up the resource somehow.  Thank you so much for the attention to this.

**Comment by singhkay** [comment]
@adbertram No worries!
