### ISSUE TITLE
Bicep/Storage account with blob container - looking for template with no warning for using parent property 

### ISSUE THREAD

**Issue by felixtsem5** [Azure/azure-quickstart-templates#13771]
[Storage Blob Container Template](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.storage/storage-blob-container/main.bicep)

[Storage Multiple Blob Container Template](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.storage/storage-multi-blob-container/main.bicep)

### Issue Details
When creating a new storage account and blob container using templates similar to the above, I've received the warning message below. 
`Warning use-parent-property: Resource "container" has its name formatted as a child of resource "sa". The syntax can be simplified by using the parent property. [https://aka.ms/bicep/linter/use-parent-property]
`

The culprit is this, using the name of the storage account created first in the name of the blob container, instead of using the parent property as advised.
```
resource container 'Microsoft.Storage/storageAccounts/blobServices/containers@2022-05-01' = {
  name: '${sa.name}/default/${containerName}'
}
```

I am able to create what I needed using the below without any warnings.

```
resource sa 'Microsoft.Storage/storageAccounts@2022-09-01' = {
  name: '${storageAccountName}'
  location: location
  sku: {
    name: storageAccountType
  }
  kind: 'StorageV2'
  properties: {}
}

resource blob 'Microsoft.Storage/storageAccounts/blobServices@2022-05-01' = {
  parent: sa
  name: 'default'
}

resource container 'Microsoft.Storage/storageAccounts/blobServices/containers@2022-05-01' = {
  parent: blob
  name: 'containerName'
}
```

I am looking for the official guidance on how to do this without triggering the warning, and have the templates referenced above updated.

**Comment by mrajess** [comment]
Official guidance on creating child resources within a Bicep template:
https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/child-resource-name-type

**Comment by mrajess** [comment]
I just submitted a PR that resolves the errors you were seeing. The issue is that containers are actually a child of blobServices, and not of the storageAccount. The original sample was viable and would deploy, but as you saw would generate some alerts.
