### ISSUE TITLE
Free log analytics pricing tier no longer available

### ISSUE THREAD

**Issue by felixtsem5** [Azure/azure-quickstart-templates#13840]
[azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.insights/insights-alertrules-application-insights/azuredeploy.json)
[main.bicep](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.insights/insights-alertrules-application-insights/main.bicep)

### Issue Details
Free log analytics pricing tier no longer available.

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#free-trial-pricing-tier

Use one of the values here instead (except Free):
https://learn.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces?pivots=deployment-language-arm-template#workspacesku-1

Might need to get the Azure Docs fixed as well.

**Comment by mrajess** [comment]
I think that property might still be valid.

"Creating new workspaces in, or moving existing workspaces into, the legacy Free Trial pricing tier was possible only until July 1, 2022."

Implies that any workspaces created prior to July 1, 2022, are grandfathered in. There may still be workspaces out there with that property still set. But that's something for the Azure Monitor product group to answer.

**Comment by felixtsem5** [comment]
I tried deploying the above template with the **Deploy** button and it failed, with an error referencing the website about the free tier. Yes, the value itself can still be valid for existing workspaces, but the template can no longer be used for creating new deployments. I'd assume we want deployable templates in this repo?

**Comment by mrajess** [comment]
Ahhh. I see what you're saying. I missed the top links to the specific template you were referring to and focused in on the request to update documentation to remove that property. Yea, that template should be updated to parameterize the SKU for the workspace and to only allow certain values. I can probably do that in a few days, alternatively you could submit a PR too!

**Comment by felixtsem5** [comment]
OK here it is: https://github.com/Azure/azure-quickstart-templates/pull/13861
With a service widely used, I'd imagine you may have to scan through all the templates and find all the other places that will require the same fix.

**Comment by mrajess** [comment]
Awesome, thank you! I did a quick search over the repo for things in the insights directory and only found one other template referencing the free SKU. I'll look to see if there are any references elsewhere and get some PRs in on those at some point. Thanks for bringing this up!
