### ISSUE TITLE
elasticsearch template fails with invalid template

### ISSUE THREAD

**Issue by sandyplace** [Azure/azure-quickstart-templates#1398]
Used the default parameters.

The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '519958b7-ff4e-4204-92dd-d3dcd1e33f58'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

**Comment by singhkay** [comment]
@sandyplace Is this the template in question? https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch

**Comment by singhkay** [comment]
@hglkrijger Tried deployed it and ran into an error because of the location parameter not having all locations a resource group can be deployed in. Let's remove the location parameter and create a variable with resourceGroup().location

**Comment by sandyplace** [comment]
Yes. Sorry should have been more specific in my issue description.

**Comment by hglkrijger** [comment]
@singhkay Sure, I will look into this.

**Comment by mandarjadhav** [comment]
Facing the same issue with the latest template. 
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '83a46749-979e-402a-b6fa-37d7c63ae59a'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

**Comment by hglkrijger** [comment]
@mandarjadhav can you describe how you deploy and which parameters you select?

**Comment by mandarjadhav** [comment]
I am using default parameters.

**Comment by singhkay** [comment]
@mandarjadhav I can't repro it with the latest update. It deploy succesfully for me

![image](https://cloud.githubusercontent.com/assets/6164178/14054365/eba02d7c-f295-11e5-8ed0-82827a4e7661.png)
