### ISSUE TITLE
Update virtual network gateway from Basic to high performance. 

### ISSUE THREAD

**Issue by nitin16** [Azure/azure-quickstart-templates#1400]
Hi we have virtual network gateway for VPN as a basic tier. We wanted to upgrade it to high performance version. but we get exception saying "unable to parse sku.name and sku.tier."

Current definition:

          }
        }
      }
    ],
    "sku": {
      "name": "Basic",
      "tier": "Basic",
      "capacity": 0
    },
    "gatewayType": "Vpn",
    "vpnType": "PolicyBased",
    "enableBgp": false
  }
}

we are trying with our template:

    {
      "apiVersion": "2015-05-01-preview",
      "type": "Microsoft.Network/virtualNetworkGateways",
      "name": "[parameters('virtualNetworkGatewayName')]",
      "location": "[parameters('location')]",
      "dependsOn": [
        "[concat('Microsoft.Network/publicIPAddresses/', parameters('vpnGatewayPublicIPAddressName'))]",
        "[concat('Microsoft.Network/virtualNetworks/', parameters('virtualNetworkName'))]"
      ],
      "properties": {
        "ipConfigurations": [
          {
            "properties": {
              "privateIPAllocationMethod": "Dynamic",
              "subnet": {
                "id": "[variables('gatewaySubnetRef')]"
              },
              "publicIPAddress": {
                "id": "[resourceId('Microsoft.Network/publicIPAddresses', parameters('vpnGatewayPublicIPAddressName'))]"
              }
            },
            "name": "vnetGatewayConfig"
          }
        ],
        "sku": {
          "name": "premium",
          "tier": "premium", 
          "capacity": 0
        },
        "gatewayType": "Vpn",
        "vpnType": "[parameters('vpnType')]",
        "enableBgp": "false"
      },
      "tags": {
        "displayName": "Virtual Network Gateway"
      }
    }

**Comment by nitin16** [comment]
I found gatewaysize property on Azure reference but that is also not working. 

https://msdn.microsoft.com/en-us/library/azure/mt130667.aspx

**Comment by singhkay** [comment]
@amitsriva Can you help with Gateways?

**Comment by amitsriva** [comment]
The supported sku name and tier are Basic, Standard and HighPerformance. Please try with HighPerformance.

**Comment by singhkay** [comment]
Thanks @amitsriva! Closing, @nitin16 please reopen if this is still an issue.

**Comment by nitin16** [comment]
I could not do it on policy based VPN. Apparently highperformance mode only works for Route based VPNs. And to update I had to drop and recreate gateway.
