### ISSUE TITLE
How to verify admin password ?

### ISSUE THREAD

**Issue by jimyjohny** [Azure/azure-quickstart-templates#1403]
How to verify the password and confirm whether it meets the azure password policy for creating VM ? 
Using the below values, it verify whether the password contain capital and small letters only at the time of creating VM and not before. Any options available so that password is verified before the template deployment is started ?

    "parameters": {
        "adminPassword": {
            "type": "securestring",
     	    "minLength": 8,
            "metadata": {
                "description": "Password for the Virtual Machine."
            }

**Comment by singhkay** [comment]
Not currently in the template however the compute team is looking at doing some pre-deployment checks where this might surface as an error. No change will be needed from template authors for this.
