### ISSUE TITLE
Error creating a DataLake from quick start template

### ISSUE THREAD

**Issue by vkurpad** [Azure/azure-quickstart-templates#1440]
Deploy a new Data Lake Analytics account on a new Data Lake Store account. https://github.com/Azure/azure-quickstart-templates/tree/master/101-datalake-analytics

error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'."
  }

**Comment by singhkay** [comment]
@matt1883 Can you take a look at this?

**Comment by matt1883** [comment]
Hi @vkurpad, it looks like the subscription that you're using to deploy this ARM template has not joined the Azure Data Lake Analytics (ADLA) public preview. To join the public preview, please go to https://portal.azure.com , select your subscription, and follow the prompt to request preview access. I hope this helps!

**Comment by singhkay** [comment]
Thanks @matt1883. Can you add this information to the Readme files of the datalake templates?
