### ISSUE TITLE
[Question] Create Azure File Storage using ARM deployment

### ISSUE THREAD

**Issue by tdeheurles** [Azure/azure-quickstart-templates#1444]
I'm looking on how to create `Azure File Storage` with the `ARM deployment`.
(I'm talking of what is also named `Azure File Shares`)

Reading this [azure documentation](https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-how-to-use-files/), we can see this:

```
You can create Azure file shares using Azure Portal, the Azure Storage PowerShell cmdlets, 
the Azure Storage client libraries, or the Azure Storage REST API. 
Additionally, because these file shares are SMB shares, you can access them via standard 
and familiar file system APIs.
```

Can someone confirm it can't be done with ARM deployment please ?

**Comment by singhkay** [comment]
@tdeheurles That is correct. Files is a data plane operation for storage. ARM can only do management plane operation on storage i.e. storage accounts.

**Comment by mrmunch** [comment]
I wrote a little [blog post](http://www.bigdata-unleashed.com/20170206/arm-template) for a workaround on this issue (in german).
Short summary in english:

- write a script which creates fileshares & directories in an Azure Storage Account
- save this script file, e.g. on Github
- in the ARM Template: execute this script via CustomScript Extension for Linux VM
- this will create the fileshares & directories inside the *new* Storage Account (which is defined inside the same ARM Template)

**Comment by hobpet** [comment]
@mrmunch, this is fine if you are using VM, but not enough if you plan to use the share with a Docker container

**Comment by rcarmo** [comment]
The current solutions are sub-optimal. Even though ARM can only do management plane operations, the current best practice (to avoid leaving scripts with credentials all over the place) is to use either the CLI or Terraform to provision the shares directly using API calls.
