### ISSUE TITLE
apiVersion variable referenced, but does not exist.

### ISSUE THREAD

**Issue by mioteg** [Azure/azure-quickstart-templates#1457]
azure-quickstart-templates / 201-vmss-lapstack-autoscale / azuredeploy.json 
https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-lapstack-autoscale/azuredeploy.json

### Issue Details
Line 347 references the variable 'apiVersion', which no longer exists. It should probaly be 'storageApiVersion'.

### Repro steps (*if necessary, delete otherwise*)
1. Click Deploy to Azure.
2. Enter parameters.
3. Create,
4. Template validation fails.

**Comment by singhkay** [comment]
@gatneil @gbowerman Can you check?

**Comment by gbowerman** [comment]
Created PR for fix

**Comment by singhkay** [comment]
Pr merged @mioteg Thanks for reporting!
