### ISSUE TITLE
Issue with deploying template - but it worked yesterday?

### ISSUE THREAD

**Issue by Lazarix** [Azure/azure-quickstart-templates#1482]
[101-vm-user-image-data-disks](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-user-image-data-disks)

Tried to deploy the above template which worked over the last few days but not today. Tried all combinations of variables.

Issue with deployment template:

The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '936aa2ed-de33-4349-9471-587c63b251d5'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.

**Comment by qhdevon43** [comment]
Randomly saw your post, check out this post here which helped me solve my issue related to this error. 

https://github.com/Azure/azure-quickstart-templates/issues/1510

**Comment by singhkay** [comment]
Thanks for posting@qhdevon43 

@Lazarix You are probably running into the same issue as in #1510. Let me know if this isn't the case.
