### ISSUE TITLE
Setup an AzureFile into a Windows machine with WinRm

### ISSUE THREAD

**Issue by tdeheurles** [Azure/azure-quickstart-templates#1495]
### My problem
I'm trying to setup an azure file to share content across different VM.

I have followed the [winrm-windows-tutorial](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-windows) and the setup is fine.
After that setup, my script create a share file. 

I have no issue when setting up everything by hand into the Windows VM. 

My problem is when I try to setup this Share File by an automated script.

##### Official Azure Storage tutorial

```console
# Adding permanently credentials
cmdkey /add:$accountStorageName.file.core.windows.net `
     /user:$accountStorageName `
     /pass:$accountStorageKey
ISSUE: cannot use cmdkey with PSSession

net use y: \\$accountStorageName.file.core.windows.net\$shareFileName
```
This attempt doesn't work as we can't use cmdkey from remote. The error returned is `cannot use cmdkey with PSSession`.

##### Official Azure Storage tutorial without cmdkey

If I setup `net use` with `user` and `password`:
```console
net use y: `
     \\$accountStorageName.file.core.windows.net\$shareFileName `
     /user:$accountStorageName $accountStorageKey
```
The mount is created but is unavailable from the VM (connected with the same user as for the remote powershell session):
- The letter X is created from the VM and is working fine.
- The letter Y is created with Powershell Remote and is Unavailable.

Here is `net use` from the VM:
```
PS> net use
New connections will be remembered.


Status       Local     Remote                                                Network
-------------------------------------------------------------------------------------------------------
OK           X:        \\storageaccount.file.core.windows.net\artifacts      Microsoft Windows Network
Unavailable  Y:        \\storageaccount.file.core.windows.net\artifacts      Microsoft Windows Network
The command completed successfully.
```

##### Attempt with New-PSDrive
After some research I found [this post](https://social.technet.microsoft.com/Forums/en-US/87150a14-4a57-4aad-866e-4aded64b1f42/map-drive-to-nas-network-share-in-a-workgroup-environment?forum=NanoServer) telling to use `New-PSDrive` instead of `net use`.

```console
$sharePath      = "\\storageaccount.file.core.windows.net\artifacts"
$username       = "storageaccount"
$password       = "ewytaLnHBHM/b2wj5oewVaRl6vjzz8+b/2J6nDIYXCaLPa0esklTxvj6+5AQllbXDA79yPgqBJJpgbnxTRtqpg=="
$securePassword = $password | ConvertTo-SecureString -AsPlainText -Force
$credentials    = new-object -typename System.Management.Automation.PSCredential `
                     -argumentlist $username, $securePassword

New-PSDrive -Name "Z" -PSProvider "FileSystem" -Root $sharePath -Credential $credentials -Persist
```

And here is the result from the VM:
```console
PS C:\Users\tdeheurles> net use
New connections will be remembered.


Status       Local     Remote                                                 Network
--------------------------------------------------------------------------------------------------------
OK           X:        \\storageaccount.file.core.windows.net\artifacts    Microsoft Windows Network
Unavailable  Y:        \\storageaccount.file.core.windows.net\artifacts    Microsoft Windows Network
Unavailable  Z:        \\storageaccount.file.core.windows.net\artifacts    Microsoft Windows Network
```

**Comment by singhkay** [comment]
@tdeheurles The Azure storage forum on MSDN is probably a better option to get detailed response on this issue https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=windowsazuredata
