### ISSUE TITLE
Does virtual machine extensions provisioned  for already existing VM?

### ISSUE THREAD

**Issue by nitin16** [Azure/azure-quickstart-templates#1507]
Hi, 

We have a VM ARM template which runs a custom extension when we provision it. This extensions run fine and install framework correctly. 

By looking at verbose log it seems like it runs the extension every time we run deployment script even if VM is already present. Is this correct?

Also if it does run the extension every time, is there anyway to avoid it?

Thanks, 
Nitin

**Comment by singhkay** [comment]
Re: this

> By looking at verbose log it seems like it runs the extension every time we run deployment script even if VM is already present. Is this correct?

What is the deployment script you're running? is this the template?

**Comment by nitin16** [comment]
Yes. We have ARM template and running using PS script.

**Comment by singhkay** [comment]
@nitin16 Do you have a forceUpdate tag in the extension runs again? Otherwise ARM will try to spin install the extension again but see that it is already installed and skip that step. The Verbose log will show "running" status but then move to "succeeded"

**Comment by nitin16** [comment]
this helped. Thanks.

**Comment by BharathMannem** [comment]
Hi I am trying to run the PS script with ARM Template, but it is throwing error. Any suggestions.
Error.
12:29:08 - New-AzureRmResourceGroupDeployment : 12:29:08 - Resource Microsoft.Compute/virtualMachines 'BharathPS' failed with 
12:29:08 - message 'The resource operation completed with terminal provisioning state 'Failed'.'
12:29:08 - At D:\arm\azureresourcegroup2\azureresourcegroup2\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
12:29:08 - + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
12:29:08 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:29:08 -     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
12:29:08 -     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
12:29:08 -  
12:29:08 - New-AzureRmResourceGroupDeployment : 12:29:08 - VM has reported a failure when processing extension 
12:29:08 - 'CustomScriptExtension'. Error message: "Failed to download all specified files. Exiting. Error Message: The remote 
12:29:08 - server returned an error: (404) Not Found.".
12:29:08 - At D:\arm\azureresourcegroup2\azureresourcegroup2\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
12:29:08 - + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
12:29:08 - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:29:08 -     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
12:29:08 -     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

Snapshot of customacript in a VM
"resources": [
        {
          "apiVersion": "2015-06-15",
          "dependsOn": [
            "[concat('Microsoft.Compute/virtualMachines/', parameters('BharathPSName'))]"
          ],
          "location": "[resourceGroup().location]",
          "name": "CustomScriptExtension",
          "properties": {
            "publisher": "Microsoft.Compute",
            "type": "CustomScriptExtension",
            "typeHandlerVersion": "1.4",
            "settings": {
              "fileUris": [ "https://raw.githubusercontent.com/BharathMannem/PrankPowerShell/master/customScript.ps1" ],
              "commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -file ',parameters('scriptName'))]"
            }
          },
          "type": "extensions"
        }
      ]

**Comment by singhkay** [comment]
@BharathMannem Check the Guest Agent logs at `c:\windowsazure\logs` to see if there are any detailed error messages.

**Comment by BharathMannem** [comment]
@singhkay thanks for the suggestion, it is not working when i gave the github path, the error is "Files were not download", but i modified resource to use blob and it is working fine

**Comment by singhkay** [comment]
@BharathMannem Interesting, should've worked fine with the github link as well.

**Comment by suresank** [comment]
16:10:34 -     vmName: wintimzonevm3
16:10:34 -     adminUsername: azureuser
16:10:34 -     adminPassword: <securestring>
16:10:34 -     windowsOSVersion: 2012-R2-Datacenter
16:10:34 -     scriptFile: https://stgdomainjoineg.blob.core.windows.net/vhds/
16:10:34 -     scriptName: TimezoneSet.ps1

I get the same error as above if access a script from a storage account.  Error message: "Failed to download all specified files. Exiting.

Can someone help?

**Comment by gregjhogan** [comment]
@nitin16 @singhkays I have noticed that the custom script extension executes every time the VM comes up from the deprovisioned state.  So if the VM reboots for some reason everything is fine, but if you deprovision the VM and then start it up again it thinks it is starting for the first time and runs the custom script extension again.  Not sure if that is what you are running into, or if this is a bug or a feature.

**Comment by Deepudev13** [comment]
I am facing the same issue and I found when we create Azure Custom Script extension then it uploads scripts to Azure Storage account somewhere and then it assign that script uri from that storage account along with sas key with Read and Write permission.
This sas key gets expired within 2-3 days, when it gets expired then virtual machine can't download that script using custom script extension during virtual machine provisioning.
Here I am attaching below screen shot of custom script extension where URI is mentioned.

![image](https://user-images.githubusercontent.com/13680739/55409977-b4dbf680-5580-11e9-82d2-0ca271bdc132.png)

In this URI after my custom script, i.e., Set_TimeZone_AU.ps1, sas key is given
`?sv=2017-04-17&sr=c&sig=y%2FF8nqPG%2FgwpK4THjUbs3fxHTyR95G55%2FMDKTl5XxOw%3D&se=2019-04-03T04%3A14%3A27Z&sp=rw`

In this sas key one can easily find expiry date of this link as
`se=2019-04-03T04%3A14%3A27Z`

when you will decode this you will find this (to decode just search on internet URL Decoder online)
`se=2019-04-03T04:14:27Z` 

Here we get the expiry time in UTC format ( inthe end Z stands for Zulu Time Zone).

If I am correct with my findings then Microsoft should work with this expiry time and we should use script from where script is accessible all the time.

I am using below PowerShell command to set custom script in my Virtual Machine. But I am facing issue with Azure VMSS as I am not sure if there any such extension PowerShell command for Azure VMSS
`Set-AzVMCustomScriptExtension -ResourceGroupName $source_vm_rg_name 
	-VMName $source_vm_name 
	-Location $location 
	-FileUri "https://abcscripts.blob.core.windows.net/vmscripts/Generalize.ps1" 
	-Run 'Generalize.ps1' 
	-Name GeneralizeVMExtension`
