### ISSUE TITLE
template fails with invalid template 

### ISSUE THREAD

**Issue by qhdevon43** [Azure/azure-quickstart-templates#1510]
Using a template from the page below, I am getting a "The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '1e1e1dc6-dd62-40b1-b22b-a5f472af512e'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details." Error message. 

Whats weird is i used this exact template before to deploy a new user uploaded image and it worked great. Now all the sudden Im running into this error. I even cleared the cookies and switched browsers. Still getting the same error. Any help would be greatly appreciated.

 https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-from-user-image ,

**Comment by jason3fc** [comment]
I am getting the same problem trying it tonight as well.

**Comment by qhdevon43** [comment]
Its weird because I emailed azure support about a possible glitch with azure when using this template. ( it would reset my dns settings for my virtual network, it would change it from custom to azure dns set) but yea after I sent that ticket in i noticed that this template now does not work... ugh... now im regretting sending that ticket in.. I hope they didnt change something. Im really wanting to upload a vm using a template and now i cant because of this stupid error.

**Comment by jason3fc** [comment]
Seems to be working now. I tried again this morning and no issues.

**Comment by singhkay** [comment]
@jason3fc Glad you got it working!

@qhdevon43 @jason3fc The error usually shows up when there is an invalid storage account name or DNS name specified that would cause the template to fail later. The portal team is working on exposing the exact error rather than a generic message.

**Comment by qhdevon43** [comment]
awesome, I'll go ahead and try it right now and will report back in a bit,

**Comment by qhdevon43** [comment]
well by gosh darn... you are correct singkay, apparantly i had to change the DNS name of the virtual machine to something else and it started working... hmmm interesting but its working now, thanks guys!

**Comment by qhdevon43** [comment]
okay so aparantly the template failed because of some error, so i go back in to and re-create the info using the template and it failed again... ugh.. i even changed the DNS name to something different... any help guys?

**Comment by qhdevon43** [comment]
so i saw your edit where you said it could be the size of the VM , so i changed it and it went through but still failed, i guess i need to keep trying to find a VM size that will work with my windows 8.1 deployment. thanks

**Comment by qhdevon43** [comment]
I had to use Standard_D1_V2 for my VM to work.. apparantly the other VM size that i use was not available in my region... ugh.. lol Its working now guys you can close this as working!  :)

**Comment by singhkay** [comment]
@qhdevon43 Awesome! hopefully the feature exposing the actual error will actually make it through soon :)
