### ISSUE TITLE
ARM template access to resource group tags

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-quickstart-templates#1521]
It would be really useful if we could access the tags on the resource group in an ARM template.  Is there currently a way to access the tags through the [resourceGroup() function](https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#resourcegroup)?  If not could you add it?  Thanks!

**Comment by singhkay** [comment]
@rjmax @ravbhatnagar Another feature request for you :)

**Comment by rjmax** [comment]
Good idea!  Filed a bug to track this.

**Comment by singhkay** [comment]
Thanks @rjmax, I will close this here in the meantime.

**Comment by gregjhogan** [comment]
@rjmax is there a way for us to track when/if this gets implemented?  Thanks!

**Comment by gregjhogan** [comment]
Any update on this (or any way I can track this)?  The use case is we want to domain join VMs, and we want a unique, generated sequence number per resource group to inject into VM names so that there are no naming conflicts in AD.  Since VM names are limited to 15 characters, uniqueString() is not a great option because it is 13 characters, and we also would like to be able to keep our VM names consistent if we move them between resource groups or subscriptions.  Thanks!

**Comment by gregjhogan** [comment]
Looks like this is available now!  Thanks!!!
