### ISSUE TITLE
Shadow BlockChain has already been merged. But there does not seem Microsoft /documentation/templates

### ISSUE THREAD

**Issue by HyperSpaceChain** [Azure/azure-quickstart-templates#1524]
March 17, 2016 Shadow BlockChain have been merged.
https://github.com/Azure/azure-quickstart-templates/tree/master/shadow-on-ubuntu

But it was not found in the Shadow BlockChain 
https://azure.microsoft.com/en-us/documentation/templates

Shadow BlockChain homepage is   https://shadowproject.io/

Please enable Shadow find in the https://azure.microsoft.com/en-us/documentation/templates
Thanks.

**Comment by singhkay** [comment]
@HyperSpaceChain The listing indexer is owned by the Azure.com team. You should file a bug using one of the below methods

- [UserSnap extension for Chrome](http://acomdocs.azurewebsites.net/articles/workitems-usersnap-get-started/)
- [Request Form](https://acomportal.azure.net/#Workspaces/All/dashboard)

**Comment by HyperSpaceChain** [comment]
@singhkay thanks for your Reply. I created the Azure Active Directory account, tried to access [•Request form](https://acomportal.azure.net/#Workspaces/All/dashboard). But I don't have permissions to access ACOM portal. 
[•UserSnap extension for Chrome](http://acomdocs.azurewebsites.net/articles/workitems-usersnap-get-started/) & [•Request form](https://acomportal.azure.net/#Workspaces/All/dashboard). Each web page sends the following message:
 "You are not authorized for ACOM Docs." "You do not have permissions to access this page."

So I made a request to access Acom. The request has been recorded, I await the approval of acom administrator.
But I do not know how long to wait ...
If the access is approved, I will close the issue.
@singhkay Thank you for your help

**Comment by singhkay** [comment]
@HyperSpaceChain Interesting. I've created an issue on your behalf. You might not be able to access the issue # but I'll put it here for tracking `Issue #ACOM-2579`

**Comment by HyperSpaceChain** [comment]
Thanks @singhkay . I appreciate it!!

**Comment by singhkay** [comment]
@HyperSpaceChain Looks like there is a typo in the name in the metadata file which is causing this

![1](https://cloud.githubusercontent.com/assets/6164178/14758497/cc76903e-08b7-11e6-81ea-951740330452.png)

**Comment by HyperSpaceChain** [comment]
@singhkay Oh! I see! I'll PR!

**Comment by singhkay** [comment]
PR merged
