### ISSUE TITLE
What happens is the PowerShell script needs to reboot during a customscriptexecution?

### ISSUE THREAD

**Issue by paulieguk** [Azure/azure-quickstart-templates#1540]
https://github.com/Azure/azure-quickstart-templates/blob/875d139c16c9c023dce519e6dd48c707e3473346/201-vm-custom-script-windows/azuredeploy.json

This is more a question of behaviour.  Does CustomScript tolerate reboots.  Simple example, I have a powershell script that builds a domain controller, this will of course mean the VM will reboot.  Once the VM is back I wish to run another script that will create a load of user accounts.  If I use 3 scripts, the first one being a control script which calls Script2 to create the AD forest and Script3 which will create the users will script 3 run?

Thank you,
Paul

**Comment by enu235** [comment]
A custom script will not persist through reboot unless you have taken the steps needed to allow that like setting a Runonce or scheduled task to kick off the next portion of your script. This is why it would be better in your ARM templates use DSC for items like this that will persist through a reboot or reboots. Basically, don't script a DC build, DSC a DC build and the user creation. See the PowerShell/xActiveDirectory repo. Your exact scenario is in the example. https://github.com/PowerShell/xActiveDirectory. Also - https://github.com/Azure/azure-quickstart-templates/blob/master/active-directory-new-domain/azuredeploy.json

**Comment by paulieguk** [comment]
Hi Allan,

Thank you for your response.  I am not really a developer so I find the GitHub experience appalling (0 out 100).  It does not seem anywhere there is any usage information on how to pull the thing together in an ARM template.  Any help or pointers to other resources would be greatly appreciated.

Thank you,
Paul

**Comment by singhkay** [comment]
@paulieguk Why not use one of the existing templates that build domain controllers using the DSC configuration that survives reboots? 

- https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain
- https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain-ha-2-dc

**Comment by paulieguk** [comment]
Hi Kay,

Thank you.  I am just trying the first one.  Took some time to understand how they are working.  Currently testing the AD build and will then add user creation….

Paul

**Comment by paulieguk** [comment]
Thank you for your help here.
I am closing this as I have switch to CreateADPDC.ps1.  I am having an issue which I  have logged in the correct repository.  Thank you again
