### ISSUE TITLE
RDP into VMSS VM via NAT rules in load balancer doesn't work

### ISSUE THREAD

**Issue by lbrader** [Azure/azure-quickstart-templates#1558]
[201-vmss-windows-autoscale](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-windows-autoscale)

[201-vmss-windows-nat] (https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-windows-nat)

### Issue Details
 Both of these templates are fairly identical. One has a auto scale set, which is what I want to test with the Load Balancer. 

Regardless, I'm unable to RDP into any of the VM in the scaled set. 

Here's the instructions to log into the VM - using the load balancer.  Similar claims are made in the [overview article ](https://azure.microsoft.com/en-us/documentation/articles/virtual-machine-scale-sets-overview/)

"To connect from the load balancer to a VM in the scale set, you would go to the Azure Portal, find the load balancer of your scale set, examine the NAT rules, then connect using the NAT rule you want. For example, if there is a NAT rule on port 50000, you could RDP on port 50000 of the public IP to connect to that VM"

I should be able to connect to my VM with   IP:Port  or in my case 52.165.29.181:5002, should have logged me into a specific VM.

Instead the RDP returns the Error:
1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network

Are we missing rules for the front end of the load balancer?  I didn't see any. 
.

**Comment by singhkay** [comment]
@gatneil @gbowerman Can you check?

**Comment by gbowerman** [comment]
@lbrader Hi, I was able to connect to RDP to 52.165.29.181:50001 (BTW I would advise against sharing your IP address and ports in a public forum - though in this case it helped :-)).
It could be your NAT rules changed if the VM Scale Set "overprovision" property is set to "true" and some machines were removed after coming up. I recommend you check the current NAT rules on your load balancer.

**Comment by lbrader** [comment]
Thanks Guy,

Went and checked. It’s working on both test setups. Only thing that I change is to reboot my box.  And I did add a jump box to the setup you tried.

Since I spent an hour on validating this yesterday.  Just to make sure I’m not seeing things.  I just deployed another VMSS windows with auto scale.
And it worked.

Only thing different was the reboot.  I’ll take the hit :^) – thanks for following up on this item.

Agree on the address, but I wanted to find out if this was an issue. The setup was for testing.  It will go away today.

Where is the VM Scale Set “overprovision” property ? I don’t see it on the portal site.

Larry

**Comment by lbrader** [comment]
Closing this issue - as it's not being reproduce.  Turn it off / Turn it on.

**Comment by singhkay** [comment]
@lbrader Awesome! glad you figured it out.

**Comment by gbowerman** [comment]
@lbrader glad it's resolved. Regarding your question about autoprovision, it's a default virtualMachineScaleSets property in the 2016-03-30 Compute API, you'll see it in our VMSS templates in Azure Quickstart templates. The default, "true" means when you create a scale set of say 10 VMs, it will create more than 10 VMs, and then delete the extra ones. Doing this improves deployment reliability and performance (we take the first ones to be created), however the deleted VMs could result in temporary "gaps" in your NAT rules. Even if you create a scale set of 1 VM, initially it will tend to create 2 VMs and then delete one. You can opt out of this behavior by setting overprovision to "false".

**Comment by lbrader** [comment]
Ah.. Thanks for the clarification.  So this is why I end up with 1 in my Scale Set.
