### ISSUE TITLE
[Feature Request] Add a function to convert JSON to String

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#1559]
Can we add a function to convert a JSON object into string in the template?
Here is one scenario:

If I want to pass [CustomData](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-customdata) which is a JSON format, I need to convert them into string.
For now, I have to concat them manually. If we have a function for the convertion, it's better.

Thanks

**Comment by singhkay** [comment]
@rjmax @ravbhatnagar This one is for you guys!

**Comment by bingosummer** [comment]
@rjmax and @ravbhatnagar 
Please let me know if you need more information.

**Comment by trentmswanson** [comment]
The string() function in ARM template language will already convert JObject to string.

https://twitter.com/trentmswanson/status/684474697400979456
![tmp](https://cloud.githubusercontent.com/assets/1594373/14761921/46358e56-0922-11e6-9bcf-119929a67e84.png)

**Comment by bingosummer** [comment]
Thanks @trentmswanson . It works.

@singhkay 
Is this a new feature of string()?
It seems that the following document is not updated for converting JObject to string.
https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#string

**Comment by trentmswanson** [comment]
No problem. It was added ~4 months ago, and it would appear that it has not been documented yet. You should note that it works with JArray as well.

**Comment by bingosummer** [comment]
I think most people don't know this feature since it's not documented.

**Comment by singhkay** [comment]
Thanks for the comment @trentmswanson!  @tfitzmac  Can you get this documented?

**Comment by tfitzmac** [comment]
Yes, I'll add it today.

**Comment by singhkay** [comment]
@tfitzmac Awesome! thanks

**Comment by ivasilyev-servicetitan-com** [comment]
Hello @trentmswanson. 
I need to pass JSON data as CustomData using PowerShell Az module (Set-AzVMOperatingSystem in particular).
How do I need to convert my JSON to pass it correctly?
If I pass it as plain json, it gives an error `CannotConvertArgument,Microsoft.Azure.Commands.Compute.SetAzureVMOperatingSystemCommand`. On other hand, if I convert it to base64 before pass to AzureAPI - I will get base64 encoded content in C:\Azure\CustomData.bin file.
I understand I need to encode my JSON somehow but was not able to find info on how to do this properly.

**Comment by ivasilyev-servicetitan-com** [comment]
I found that if my JSON string will be one line like `{  "vmInfoName": "${vm_info_name}"}` it's passed to `Set-AzVMOperatingSystem` correctly.
If the value is formatted JSON with line breaks like this
```
{
  "vmInfoName": "${vm_info_name}"
}
```
- it returns the error.
I'd like to keep formatting as I want to have formatted file on target VM (in `C:\Azure\CustomData.bin`).
How can I achieve this?
