### ISSUE TITLE
201-vmss-windows-autoscale : scale set added extra and then later removed vms from my capacity

### ISSUE THREAD

**Issue by lbrader** [Azure/azure-quickstart-templates#1564]
[201-vmss-windows-autoscale ](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-windows-autoscale)

### Issue Details

I original provision a capacity to 3.   And the deployment was marked completed successfully.

When I checked it an hour later I found that my Scale set count was now 5, with corresponding NAT rules. And I could RDP into the boxes.  I logged into the original 3 to copy my agents to the deployed VM.  I logged into the 4th & 5th box to confirm they existed.

30 minutes later. I checked my deployment and now the scale set count is 2.  The # of NAT rules only had 2 rules now.   I lost one of the VM I was loading my agent on.  

Looking at the ARM template, I see that overprovision is set to "true".  So I can understand why I would get 5 machines. 
       "properties": { 
         "overprovision": "true", 
         "upgradePolicy": { 
           "mode": "Manual" 
         }, 

What really concerns me is that 3 boxes went away - after the deployment was completed. 

Ok.. As I was writing this issue up. I'm now down to 1 VM in the capacity set.

This is not usable as a solution.  What's going on?

**Comment by lbrader** [comment]
Thinking about this pattern - on a couple of different deployment.  The system is de-provisioning the VMs since they aren't being used by some criteria.    Since I was literally RDP in these boxes coping files to them - i'm not sure what your criteria are set.  

Is this a bug? Or a usage pattern issue?

**Comment by singhkay** [comment]
@lbrader This template integrates with autoscale which is why you're seeing the instances being deprovisioned. From the template readme 

> The Autoscale rules are configured as follows

>sample for CPU (\Processor\PercentProcessorTime) in each VM every 1 Minute
if the Percent Processor Time is greater than 50% for 5 Minutes, then the scale out action (add more VM instances, one at a time) is triggered
once the scale out action is completed, the cool down period is 1 Minute

cc: @gatneil @gbowerman
