### ISSUE TITLE
Mesos template deployment fails with a master nodes <> 1

### ISSUE THREAD

**Issue by ciberado** [Azure/azure-quickstart-templates#1567]
[Azure Container Service](https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-mesos) 

### Container service preview deployment failure

Looks like it's not possible to deploy a new mesos cluster if you specify 3 or 5 master nodes. It fails after a few minutes with this message: 

```
Provisiong of resource(s) for container service 'containerservice-xxxx' in resource group 'xxxx' failed with errors: InvalidTemplateDeployment: The template deployment 'xxxx' is not valid according to the validation procedure.
```` 

Attaching an image with  additional info:

![mesoserror](https://cloud.githubusercontent.com/assets/1154367/14431498/3e24bcd4-0006-11e6-82b2-3177bc0c20b1.png)

**Comment by singhkay** [comment]
@rgardler Can you take a look at this?

**Comment by ciberado** [comment]
Already solved by him, sorry: I forgot to update this thread. An increase
in the basic quota of cores is needed to deploy a multimaster cluster. The
error message is in this case not related to the cause because of a bug in
Azure.

**Comment by singhkay** [comment]
@ciberado Awesome, thanks for the update!
