### ISSUE TITLE
The template deployment 'Microsoft.Template' is not valid

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-quickstart-templates#1579]
[Slurm](https://github.com/Azure/azure-quickstart-templates/tree/master/slurm)

### Issue Details

Just by following the steps, I get this message: 

```
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '739f833b-f2d1-48a1-895d-16141bc04557'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details.
```

Can you check that you get proper results?

**Comment by pelagos** [comment]
I am having this issue as well. Any ideas?

**Comment by zfrenchee** [comment]
The way I managed to solve it is you need to make sure you have a storage account already set up (and make sure it's in the right geographic region) before going to make the cluster.

**Comment by coin8086** [comment]
For the first thing, ensure the template you're deploying is valid by a JSON Linter like https://jsonlint.com/. An invalid template may cause the issue.
