### ISSUE TITLE
why not set caching mode for data disks? Say, "ReadOnly"? Not tested yet, but seems enable caching will get better performance?

### ISSUE THREAD

**Issue by youxu71** [Azure/azure-quickstart-templates#1786]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by singhkay** [comment]
@youxu71 Write cache is not recommended. See towards the end - https://blogs.msdn.microsoft.com/windowsazurestorage/2012/06/27/exploring-windows-azure-drives-disks-and-images/

Also, please use the issue description format for asking a question. Helps us understand the issue better. Thanks!
