### ISSUE TITLE
ARM Template deployment via Visual Studio 2015 fails

### ISSUE THREAD

**Issue by Spsutar** [Azure/azure-quickstart-templates#1798]
Hi Team,

I am trying to deploy a template with 2 vms Loadbalanced in a single subnet and Availability set via Visual studio. But it fails with the below error. I also tried to pick an existing template from Visual Studio and deploy it and still the same error.

12:23:03 - Build started.
12:23:03 - Project "testproject.deployproj" (StageArtifacts target(s)):
12:23:03 - Project "testproject.deployproj" (ContentFilesProjectOutputGroup target(s)):
12:23:03 - Done building project "testproject.deployproj".
12:23:03 - Done building project "testproject.deployproj".
12:23:03 - Build succeeded.
12:23:03 - The following parameter values will be used for this deployment:
12:23:03 -     nge1Type: Standard_LRS
12:23:03 -     myAVsetName: AVsetAppSrv
12:23:03 -     vnetName: mywebVNET
12:23:03 -     nicNameprefix: web
12:23:03 -     VMAdminUserName: Ngadmin
12:23:03 -     VMAdminPassword: <securestring>
12:23:03 -     dnsNameforLBIP: mylbsdns
12:23:03 -     publicIPAddressName: myPublicIP
12:23:03 -     vmNamePrefix: myAppVM
12:23:03 -     myNGEwebWindowsOSVersion: 2012-R2-Datacenter
12:23:03 -     lbName: myAppLB
12:23:03 - Launching deployment PowerShell script with the following command:
12:23:03 - 'c:\users\soniya.m.sutar\documents\visual studio 2015\projects\testproject\testproject\Scripts\Deploy-AzureResourceGroup.ps1' -StorageAccountName '' -ResourceGroupName 'MyNG2Res' -ResourceGroupLocation 'northeurope' -TemplateFile 'c:\users\soniya.m.sutar\documents\visual studio 2015\projects\testproject\testproject\templates\azuredeploy.json' -TemplateParametersFile 'c:\users\soniya.m.sutar\documents\visual studio 2015\projects\testproject\testproject\templates\azuredeploy.parameters.json' -ArtifactStagingDirectory '..\bin\Debug\staging'
12:23:04 - [ERROR] Get-AzureEnvironment : The term 'Get-AzureEnvironment' is not recognized as 
12:23:04 - [ERROR] the name of a cmdlet, function, script file, or operable program. Check the 
12:23:04 - [ERROR] spelling of the name, or if a path was included, verify that the path is 
12:23:04 - [ERROR] correct and try again.
12:23:04 - [ERROR] At line:1 char:180
12:23:04 - [ERROR] + ... 'true' }; if ((Get-AzureEnvironment -Name 'AzureCloud') -eq $null) { 
12:23:04 - [ERROR] Set-AzureEn ...
12:23:04 - [ERROR] +                    ~~~~~~~~~~~~~~~~~~~~
12:23:04 - [ERROR]     + CategoryInfo          : ObjectNotFound: (Get-AzureEnvironment:String) [] 
12:23:04 - [ERROR]    , CommandNotFoundException
12:23:04 - [ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
12:23:04 - [ERROR]  
12:23:05 - [ERROR] Get-AzureEnvironment : The term 'Get-AzureEnvironment' is not recognized as 
12:23:05 - [ERROR] the name of a cmdlet, function, script file, or operable program. Check the 
12:23:05 - [ERROR] spelling of the name, or if a path was included, verify that the path is 
12:23:05 - [ERROR] correct and try again.
12:23:05 - [ERROR] At line:1 char:10190
12:23:05 - [ERROR] + ...  -Environment (Get-AzureEnvironment -Name 
12:23:05 - [ERROR] 'AzureCloud')));&'c:\users\soniya.m.su ...
12:23:05 - [ERROR] +                    ~~~~~~~~~~~~~~~~~~~~
12:23:05 - [ERROR]     + CategoryInfo          : ObjectNotFound: (Get-AzureEnvironment:String) [] 
12:23:05 - [ERROR]    , CommandNotFoundException
12:23:05 - [ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
12:23:05 - [ERROR]  
12:23:05 - [ERROR] New-AzureRmResourceGroup : Run Login-AzureRmAccount to login.
12:23:05 - [ERROR] At C:\users\soniya.m.sutar\documents\visual studio 
12:23:05 - [ERROR] 2015\projects\testproject\testproject\Scripts\Deploy-AzureResourceGroup.ps1:96 
12:23:05 - [ERROR] char:1
12:23:05 - [ERROR] + New-AzureRmResourceGroup -Name $ResourceGroupName -Location 
12:23:05 - [ERROR] $ResourceGroupLocati ...
12:23:05 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:23:05 - [ERROR] ~~~
12:23:05 - [ERROR]     + CategoryInfo          : InvalidOperation: (:) [New-AzureRmResourceGroup] 
12:23:05 - [ERROR]    , PSInvalidOperationException
12:23:05 - [ERROR]     + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Resour 
12:23:05 - [ERROR]    ces.NewAzureResourceGroupCommand
12:23:05 - [ERROR]  
12:23:05 - [ERROR] New-AzureRmResourceGroupDeployment : Cannot retrieve the dynamic parameters 
12:23:05 - [ERROR] for the cmdlet. Run Login-AzureRmAccount to login.
12:23:05 - [ERROR] At C:\users\soniya.m.sutar\documents\visual studio 
12:23:05 - [ERROR] 2015\projects\testproject\testproject\Scripts\Deploy-AzureResourceGroup.ps1:98 
12:23:05 - [ERROR] char:1
12:23:05 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem 
12:23:05 - [ERROR] $TemplateFile).BaseName ...
12:23:05 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:23:05 - [ERROR] ~~~
12:23:05 - [ERROR]     + CategoryInfo          : InvalidArgument: (:) [New-AzureRmResourceGroupDe 
12:23:05 - [ERROR]    ployment], ParameterBindingException
12:23:05 - [ERROR]     + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.Azure.Co 
12:23:05 - [ERROR]    mmands.Resources.NewAzureResourceGroupDeploymentCommand
12:23:05 - [ERROR]  
12:23:05 - 
12:23:05 - Deploying template using PowerShell script failed.
12:23:05 - Tell us about your experience at http://go.microsoft.com/fwlink/?LinkId=691202

My template is attached below:
[Azuredeploy.zip](https://github.com/Azure/azure-quickstart-templates/files/236053/Azuredeploy.zip)

**Comment by singhkay** [comment]
@Spsutar Looks like there is a problem with the azure powershell installation. Make sure you're on the latest PS build 

`[ERROR] Get-AzureEnvironment : The term 'Get-AzureEnvironment' is not recognized as `

**Comment by SteveBurkettNZ** [comment]
Try starting Visual Studio 2015 using 'Run As Administrator'.

**Comment by rifaterdemsahin** [comment]
thanks saved my life (:
