### ISSUE TITLE
Arm script Asp.Net 5 deploy

### ISSUE THREAD

**Issue by akuzhan** [Azure/azure-quickstart-templates#1799]
Hi Guys, 

I am trying to deploy Asp.Net 5 application via Arm script. 

I does not locate the packages into correct folders, surely something is going wrong with Asp.Net 5. 

4.5 deployment is working quite good. 

Do you have any idea how to deploy Asp.Net 5 application via Arm script? 

Cheers!

**Comment by singhkay** [comment]
@akuzhan MSDN forums or StackExchange might be a better venue for .NET 5 specific questions. https://social.msdn.microsoft.com/Forums/azure/en-US/home
