### ISSUE TITLE
Bosh template script should autogenerate strong passwords.

### ISSUE THREAD

**Issue by haydonryan** [Azure/azure-quickstart-templates#1860]
[bosh-setup](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/scripts/deploy_bosh.sh)
### Issue Details
As a best practice, we really should auto-generate bosh component passwords in the bosh.yml before deploying, ESPECIALLY the bosh-agent password.  

This is important at creation time, because if a new user uses the template to create microbosh, and then deploys more vms using bosh (ie Cloud Foundry etc) the agent password will be set on all of those VMs, and require updating.

**Comment by singhkay** [comment]
@bingosummer Can you take a look at this?

**Comment by bingosummer** [comment]
Thanks @haydonryan for addressing this.
Will do it.

**Comment by haydonryan** [comment]
I can submit a pr tomorrow evening for this. If you want.

**Comment by bingosummer** [comment]
Sure. We are happy to accept your pr.
Please loop me in when you summit your pr. Thanks.

**Comment by bingosummer** [comment]
@haydonryan 
The codes are done. I'm preparing a PR to fix it
