### ISSUE TITLE
201-insights-alertrules-servicehealth creates disabled alerts

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-quickstart-templates#1910]
[201-insights-alertrules-servicehealth](https://github.com/Azure/azure-quickstart-templates/blob/master/201-insights-alertrules-servicehealth)
### Issue Details

IsEnabled property is missing in the properties of the resource so Alerts are disabled after creation

Please set the property to true

> ```
> "resources": [{
>     "type": "Microsoft.Insights/alertRules",
>     "name": "[parameters('alertName')]",
>     "location": "[resourceGroup().location]",
>     "apiVersion": "2014-04-01",
>     "properties": {
>         "name": "[parameters('alertName')]",
>         "description": "[parameters('alertDescription')]",
>         "isEnabled": true,
>         "condition": {
>             "odata.type": "Microsoft.Azure.Management.Insights.Models.ManagementEventRuleCondition",
>             "dataSource": {
>                 "odata.type": "Microsoft.Azure.Management.Insights.Models.RuleManagementEventDataSource",
>                 "resourceProviderName": "Azure.Health",
>                 "status": "[parameters('status')]"
>             }
>         },
>         "action": {
>             "odata.type": "Microsoft.Azure.Management.Insights.Models.RuleEmailAction",
>             "sendToServiceOwners": "[parameters('sendToServiceOwners')]",
>             "customEmails":  "[variables('customEmails')]"
>         }
>     }
> }
> ```

**Comment by singhkay** [comment]
@nmackenzie Can you take a look at this?

**Comment by MCKLMT** [comment]
The template has been updated since. The bug has been fixed.
Might you close the issue @eosfor?
