### ISSUE TITLE
Separate moodledata folder

### ISSUE THREAD

**Issue by albertramsbottom** [Azure/azure-quickstart-templates#1937]
[moodle-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-singlevm-ubuntu)
### Issue Details

Sorry, more of an enhancement

Moodle is never run using a local moodledata folder due to size and security. This template needs an additional step that includes variables to choose to add an additional disk with size options for the moodledata folder.  I would imagine that this would require some mounting options such as fstab etc

Thanks

**Comment by singhkay** [comment]
@vinhub Can you take a look at this?

**Comment by vinhub** [comment]
@albertramsbottom Thanks for your comment. The single vm template creates the simplest installation of moodle with everything on one VM. The cluster template has the moodledata folder separated out in Azure Files storage and mounted on each of the vm's in the cluster. Would that one work for you?

We are also working on more advanced templates including hardening etc.

**Comment by rgardler** [comment]
@bmoore-msft This issue can be closed as won't fix.  For an HA Moodle solution see the [Scalable Cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-scalable-cluster-ubuntu) template which provides a scalable web front end and replicated moodledata storage (amongst many other HA improvements).
