### ISSUE TITLE
moodle-singlevm-ubuntu - Issues with newuserscript

### ISSUE THREAD

**Issue by albertramsbottom** [Azure/azure-quickstart-templates#1948]
moodle-singlevm-ubuntu 

### Issue Details

Hi, newbie at Github.

I have forked the repro and changed the "install_lamp_moodle.sh" for the "moodle-singlevm-ubuntu" to fit my needs but I cant seem to be able to test this as every-time the newuserscript part of the azuredeploy.json template (which I have locally stored), fails

I have changed the path to the installscript URI from  "installScriptUri": ""installScriptUri": "[concat('https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/moodle-singlevm-ubuntu/', variables('installScriptName'))]",

to

 "installScriptUri": "[concat('https://github.com/albertramsbottom/azure-quickstart-templates/blob/master/moodle-singlevm-ubuntu/', variables('installScriptName'))]", 

And I am using Azure power-shell to create the resource Group and run the template 

fails every time on a 404 error for the newuserscript

Obviously doing something very silly here. As I do not know Github I dont want to make changes to anything and thought that by forking the repro I could attempt this. And I have no idea where is newuser script lives, I assume its an extension.

And I aslo assume this has noting to do with the moodle-singlevm-ubuntu template and has more to do with my idiocy :)

Sorry #

**Comment by singhkay** [comment]
@albertramsbottom You need to use the raw link to the script file, otherwise it just gets the html page at the link you specified.
