### ISSUE TITLE
Doesn't set to Dynamic plan about Azure Functions

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-quickstart-templates#1954]
[101-function-app-create-dynamic](https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dynamic)
### Issue Details

This template can create Azrue Functions using Dynamic service plan, but it set to actually 'Standard App Service plan' after deploy.

**Comment by singhkay** [comment]
@mattchenderson Can you take a look at this?

**Comment by MCKLMT** [comment]
The template has been updated since. The bug is fixed.
Might you close your issue @buchizo?
