### ISSUE TITLE
NTP not correct for AzureChinaCloud

### ISSUE THREAD

**Issue by haydonryan** [Azure/azure-quickstart-templates#1958]
[Bosh.yml](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/bosh.yml#L122)

### Issue Details
NTP servers should be different for AzureChinaCloud...

1.cn.pool.ntp.org
1.asia.pool.ntp.org
0.asia.pool.ntp.org

**Comment by singhkay** [comment]
@bingosummer Can you take a look at this?

**Comment by bingosummer** [comment]
sure. will fix it.
