### ISSUE TITLE
The "Visualize" button is break for the given link

### ISSUE THREAD

**Issue by zxzxy1988** [Azure/azure-quickstart-templates#1961]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)
https://github.com/Azure/azure-quickstart-templates/tree/master/101-hdinsight-rserver-ssh-password
### Issue Details
The "Visualize" button is break for the link above

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by singhkay** [comment]
@zxzxy1988 VIsualize issues are handled by the project owners at https://github.com/ytechie/AzureResourceVisualizer
