### ISSUE TITLE
Not possible to add SQL alwayson AG to existing resource group

### ISSUE THREAD

**Issue by Lazarix** [Azure/azure-quickstart-templates#2001]
[Create a SQL Server 2014 Always On Availability Group in an existing Azure VNET and an existing Active Directory instance](https://github.com/Azure/azure-quickstart-templates/tree/master/sql-server-2014-alwayson-existing-vnet-and-ad)

### Issue Details

Not possible to deploy this template into an existing resource group. My existing resource group contains a network gateway that has the connection to the AD controller with the domain in it. I configured the correct DNS address to ensure the machines could talk to the domain.

When deploying the template, it complains that the location variable has not been set, despite me choosing an existing resource group with a location of East US.

The error is:

`Multiple error occurred: BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest. Please see details. (Code: MultipleErrorsOccurred) Deployment template validation failed: 'The value for the template parameter 'location' at line '82' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '83' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '5' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '5' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '5' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '26' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate) Deployment template validation failed: 'The value for the template parameter 'location' at line '69' and column '18' is not provided. Please see http://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code: InvalidTemplate)`

### Repro steps 
1. Deploy to azure
2. Configure all available parameters
3. Choose existing resource group (the one that has a connection to your AD server)
4. Accept license agreement
5. Submit job
6. Receive error

**Comment by Lazarix** [comment]
Tested it with creating a new resource group and that also failed with the same error.

**Comment by marcvaneijk** [comment]
Thanks for opening this issue @Lazarix 
@singhkay can you merge #1873?  The deployment fails because this template is using nested deployment resources pointing to the templates in the folder that is awaiting the location fix in #1873 
Tnx, Marc

**Comment by IanMoroney** [comment]
Thank you very much Marc, I look forward to this PR being approved.

**Comment by gbowerman** [comment]
Merged  #1873, can you test again?

**Comment by IanMoroney** [comment]
Thank you @gbowerman @marcvaneijk @MikeRayMSFT for this. Testing now.
It's deploying, so getting further than before.
Will let you know the results.

**Comment by IanMoroney** [comment]
Unfortunately it didn't work due to a new error. Detailed here: https://github.com/Azure/azure-quickstart-templates/issues/2008

**Comment by singhkay** [comment]
Closing since #2008 is fixed by #2009
