### ISSUE TITLE
Can't deploy SQL AlwaysOn template to existing domain

### ISSUE THREAD

**Issue by IanMoroney** [Azure/azure-quickstart-templates#2010]
[Create a SQL Server 2014 Always On Availability Group in an existing Azure VNET and an existing Active Directory instance](https://github.com/Azure/azure-quickstart-templates/tree/master/sql-server-2014-alwayson-existing-vnet-and-ad)

### Issue Details

VM has reported a failure when processing extension 'sqlAOPrepare'. Error message: \\\"A previous attempt to install Win8.1AndW2K12R2-KB3066437-x64.msu failed; please check the logs on the VM 

### Repro steps (*if necessary, delete otherwise*)
1. Deploy template
2. Wait for error.
3.
4.
5.

**Comment by IanMoroney** [comment]
Bug fixed in PR [2011](https://github.com/Azure/azure-quickstart-templates/pull/2011)

**Comment by singhkay** [comment]
@IanMoroney Thank you for reporting and following through with a fix!! :+1:

**Comment by IanMoroney** [comment]
A pleasure :)
