### ISSUE TITLE
"deisctl start platform" stuck at deis-store-monitor

### ISSUE THREAD

**Issue by scrypter** [Azure/azure-quickstart-templates#2012]
[ deis-cluster-coreos ](https://github.com/Azure/azure-quickstart-templates/tree/master/deis-cluster-coreos)

### Issue Details
When executing the `deisctl start platform`, the system sits in an infinite loop of auto-restart. This issue was found in the deis repo and can be found here (https://github.com/deis/deis/issues/4806). While the issue is working in the deis repo, the template in azure-quickstart-templates is still using the out of date version of Coreos.

### Repro steps
When following this blog post: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-deis-cluster/ the deis start platform fails.

**Comment by singhkay** [comment]
PR merged
