### ISSUE TITLE
Error creating event hub with no error message

### ISSUE THREAD

**Issue by steve-warwick** [Azure/azure-quickstart-templates#2022]
[{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
  "parameters": {
    "eventHubName": {
      "type": "string",
      "metadata": {
        "description": "Name of the Event Hub"
      }
    }
  },
  "variables": {
    "eventHubNamespace": "[concat('eventHub',uniqueString(resourceGroup().id))]",
    "location": "[resourceGroup().location]",
    "sbListenOnlyKeyName": "ListenOnlyKey",
    "ehVersion": "2014-09-01",
    "defaultSASKeyName": "RootManageSharedAccessKey",
    "authRuleResourceId": "[resourceId('Microsoft.Eventhub/namespaces/authorizationRules', variables('eventHubNamespace'), variables('defaultSASKeyName'))]",
    "sendAuthRuleResourceId": "[resourceId('Microsoft.Eventhub/namespaces/authorizationRules', variables('eventHubNamespace'), 'SendOnlyKey')]",
    "listenAuthRuleResourceId": "[resourceId('Microsoft.Eventhub/namespaces/authorizationRules', variables('eventHubNamespace'), 'ListenOnlyKey')]",
    "keyGeneratorTemplateUri": "https://raw.githubusercontent.com/sjkp/Azure.ARM.ServiceBus/master/Azure.ARM.ServiceBus/Templates/keygenerator.json"
  },
  "resources": [
    {
      "apiVersion": "2015-01-01",
      "name": "primaryKey",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "incremental",
        "templateLink": {
          "uri": "[variables('keyGeneratorTemplateUri')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "seed": { "value": "4236a5" }
        }
      }
    },
    {
      "apiVersion": "2015-01-01",
      "name": "secondaryKey",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "incremental",
        "templateLink": {
          "uri": "[variables('keyGeneratorTemplateUri')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "seed": { "value": "a13435" }
        }
      }
    },
    {
      "apiVersion": "2015-01-01",
      "name": "listenPrimaryKey",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "incremental",
        "templateLink": {
          "uri": "[variables('keyGeneratorTemplateUri')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "seed": { "value": "14224a5" }
        }
      }
    },
    {
      "apiVersion": "2015-01-01",
      "name": "listenSecondaryKey",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "incremental",
        "templateLink": {
          "uri": "[variables('keyGeneratorTemplateUri')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "seed": { "value": "dc33a8" }
        }
      }
    },
    {
      "apiVersion": "[variables('ehVersion')]",
      "name": "[variables('eventHubNamespace')]",
      "type": "Microsoft.EventHub/namespaces",
      "location": "[variables('location')]",
      "resources": [
        {
          "apiVersion": "[variables('ehVersion')]",
          "name": "[parameters('eventHubName')]",
          "type": "eventHubs",
          "dependsOn": [
            "[concat('Microsoft.EventHub/namespaces/', variables('eventHubNamespace'))]"
          ],
          "properties": {
            "path": "[parameters('eventHubName')]"
          },
          "resources": [
            {
              "apiVersion": "[variables('ehVersion')]",
              "name": "SendOnlyKey",
              "type": "AuthorizationRules",
              "dependsOn": [
                "[parameters('eventHubName')]"
              ],
              "properties": {
                "keyName": "SendOnlyKey",
                "claimType": "SharedAccessKey",
                "claimValue": "None",
                "primaryKey": "[reference('primaryKey').outputs.key.value]",
                "secondaryKey": "[reference('secondaryKey').outputs.key.value]",
                "rights": [ "Send" ],
                "revision": -1
              }
            },
            {
              "apiVersion": "[variables('ehVersion')]",
              "name": "ListenOnlyKey",
              "type": "AuthorizationRules",
              "dependsOn": [
                "[parameters('eventHubName')]"
              ],
              "properties": {
                "keyName": "ListenOnlyKey",
                "claimType": "SharedAccessKey",
                "claimValue": "None",
                "primaryKey": "[reference('listenPrimaryKey').outputs.key.value]",
                "secondaryKey": "[reference('listenSecondaryKey').outputs.key.value]",
                "rights": [ "Listen" ],
                "revision": -1
              }
            }
          ]
        }
      ]
    }
  ],
  "outputs": {
    "NamespaceDefaultConnectionString": {
      "type": "string",
      "value": "[listkeys(variables('authRuleResourceId'), variables('ehVersion')).primaryConnectionString]"
    },
    "SendOnlyConnectionString": {
      "type": "string",
      "value": "[listkeys(variables('sendAuthRuleResourceId'), variables('ehVersion')).primaryConnectionString]"
    },
    "ReceiveOnlyConnectionString": {
      "type": "string",
      "value": "[listkeys(variables('listenAuthRuleResourceId'), variables('ehVersion')).primaryConnectionString]"
    }
  }
}](Template link goes here)

### Issue Details
This arm template generates the following errors when run with no helpful explanation of what the problem is. It appears the event hub was successfully created with the expected keys.

16:35:15 - [VERBOSE] 4:35:15 PM - Template is valid.
16:35:17 - [VERBOSE] 4:35:17 PM - Create template deployment 'azuredeploy-0527-2335'.
16:35:27 - [VERBOSE] 4:35:27 PM - Resource Microsoft.Resources/deployments 'listenSecondaryKey' provisioning status is succeeded
16:35:27 - [VERBOSE] 4:35:27 PM - Resource Microsoft.Resources/deployments 'listenPrimaryKey' provisioning status is succeeded
16:35:27 - [VERBOSE] 4:35:27 PM - Resource Microsoft.EventHub/namespaces 'eventHubira6u6nvthti6' provisioning status is running
16:35:27 - [VERBOSE] 4:35:27 PM - Resource Microsoft.Resources/deployments 'primaryKey' provisioning status is succeeded
16:35:27 - [VERBOSE] 4:35:27 PM - Resource Microsoft.Resources/deployments 'secondaryKey' provisioning status is succeeded
16:37:37 - [VERBOSE] 4:37:37 PM - Resource Microsoft.EventHub/namespaces/eventHubs 'eventHubira6u6nvthti6/testEventHub' provisioning status is succeeded
16:37:37 - [VERBOSE] 4:37:37 PM - Resource Microsoft.Eventhub/namespaces/authorizationRules 'eventHubira6u6nvthti6/SendOnlyKey' provisioning status is running
16:37:37 - [VERBOSE] 4:37:37 PM - Resource Microsoft.Eventhub/namespaces/authorizationRules 'eventHubira6u6nvthti6/RootManageSharedAccessKey' provisioning status is running
16:37:37 - [ERROR] New-AzureRmResourceGroupDeployment : 4:37:37 PM - Resource 
16:37:37 - [ERROR] Microsoft.Eventhub/namespaces/authorizationRules 
16:37:37 - [ERROR] 'eventHubira6u6nvthti6/ListenOnlyKey' failed with message ''
16:37:37 - [ERROR] At C:\users\steve\documents\visual studio 
16:37:37 - [ERROR] 2015\projects\eventhubcreation\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
16:37:37 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem 
16:37:37 - [ERROR] $TemplateFile).BaseName ...
16:37:37 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:37:37 - [ERROR] ~~~
16:37:37 - [ERROR]     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeplo 
16:37:37 - [ERROR]    yment], Exception
16:37:37 - [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
16:37:37 - [ERROR]    rceGroupDeploymentCommand
16:37:37 - [ERROR]  
16:37:37 - [VERBOSE] 4:37:37 PM - Resource Microsoft.EventHub/namespaces 'eventHubira6u6nvthti6' provisioning status is succeeded
16:37:47 - [VERBOSE] 4:37:47 PM - Resource Microsoft.EventHub/namespaces/eventHubs/AuthorizationRules 'eventHubira6u6nvthti6/testEventHub/SendOnlyKey' provisioning status is succeeded
16:37:47 - [VERBOSE] 4:37:47 PM - Resource Microsoft.EventHub/namespaces/eventHubs/AuthorizationRules 'eventHubira6u6nvthti6/testEventHub/ListenOnlyKey' provisioning status is succeeded
16:38:40 - [ERROR] New-AzureRmResourceGroupDeployment : 4:38:40 PM - Resource 
16:38:40 - [ERROR] Microsoft.Eventhub/namespaces/authorizationRules 
16:38:40 - [ERROR] 'eventHubira6u6nvthti6/SendOnlyKey' failed with message ''
16:38:40 - [ERROR] At C:\users\steve\documents\visual studio 
16:38:40 - [ERROR] 2015\projects\eventhubcreation\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
16:38:40 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem 
16:38:40 - [ERROR] $TemplateFile).BaseName ...
16:38:40 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:38:40 - [ERROR] ~~~
16:38:40 - [ERROR]     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeplo 
16:38:40 - [ERROR]    yment], Exception
16:38:40 - [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
16:38:40 - [ERROR]    rceGroupDeploymentCommand
16:38:40 - [ERROR]  
16:38:40 - [VERBOSE] 4:38:40 PM - Resource Microsoft.Eventhub/namespaces/authorizationRules 'eventHubira6u6nvthti6/RootManageSharedAccessKey' provisioning status is succeeded
16:38:40 - [ERROR] New-AzureRmResourceGroupDeployment : 4:38:40 PM - "Template output evaluation 
16:38:40 - [ERROR] skipped: at least one resource deployment operation failed. Please list 
16:38:40 - [ERROR] deployment operations for details. Please see http://aka.ms/arm-debug for 
16:38:40 - [ERROR] usage details."
16:38:40 - [ERROR] At C:\users\steve\documents\visual studio 
16:38:40 - [ERROR] 2015\projects\eventhubcreation\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
16:38:40 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem 
16:38:40 - [ERROR] $TemplateFile).BaseName ...
16:38:40 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:38:40 - [ERROR] ~~~
16:38:40 - [ERROR]     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeplo 
16:38:40 - [ERROR]    yment], Exception
16:38:40 - [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
16:38:40 - [ERROR]    rceGroupDeploymentCommand
16:38:40 - [ERROR]  
16:38:40 - [ERROR] New-AzureRmResourceGroupDeployment : 'string' does not contain a definition 
16:38:40 - [ERROR] for 'error'
16:38:40 - [ERROR] At C:\users\steve\documents\visual studio 
16:38:40 - [ERROR] 2015\projects\eventhubcreation\Scripts\Deploy-AzureResourceGroup.ps1:98 char:1
16:38:40 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem 
16:38:40 - [ERROR] $TemplateFile).BaseName ...
16:38:40 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:38:40 - [ERROR] ~~~
16:38:40 - [ERROR]     + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeploym 
16:38:40 - [ERROR]    ent], RuntimeBinderException
16:38:40 - [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
16:38:40 - [ERROR]    rceGroupDeploymentCommand
16:38:40 - [ERROR]  
16:38:40 - 
16:38:40 - 
16:38:40 - 
16:38:40 - Deploying template using PowerShell script failed.
16:38:40 - Tell us about your experience at http://go.microsoft.com/fwlink/?LinkId=691202

### Repro steps (*if necessary, delete otherwise*)
1. Run the attached arm template

**Comment by singhkay** [comment]
@steve-warwick This doesn't look like a template from this repo. It's best to file a support case for investigation with this request.
