### ISSUE TITLE
101-acs-dcos Deployments not happening. 

### ISSUE THREAD

**Issue by spsiddarthan** [Azure/azure-quickstart-templates#2034]
[101-acs-dcos](https://gallery.azure.com/artifact/20151001/microsoft.acs.1.0.0/Artifacts/mainTemplate.json)

### Issue Details

I'm not able to deploy my application on the marathon UI.  The application keeps going to the waiting state.  Below is my application configuration (from the https://azure.microsoft.com/en-us/documentation/articles/container-service-mesos-marathon-rest/ tutorial)

```
{
  "id": "nginx",
  "cpus": 0.1,
  "mem": 16.0,
  "instances": 1,
    "acceptedResourceRoles": [
    "slave_public"
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "nginx",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 80, "hostPort": 80, "servicePort": 9000, "protocol": "tcp" }
      ]
    }
  }
}
```

Also, when I hit it http://localhost/mesos/slaves or http://localhost/mesos/master/slaves after creating the ssh tunnel, I get the following response:

```
{
    "slaves": []
}
```

Before, I used to get information about the slaves and their host ip's. I think this should be the root cause of the problem.

**Comment by Blackbaud-IanThomas** [comment]
This is happening to me today, too.

**Comment by rgardler** [comment]
We are debugging an issue. I'll update here as soon as we have something. This issue only affects new clusters.

**Comment by Blackbaud-IanThomas** [comment]
@rgardler: Thanks!  My team tears down and recreates the testing cluster each day, so this has been a big roadblock today.  I'll be very happy to hear your updates.

**Comment by rgardler** [comment]
Sorry for the inconvenience. The engineering team are making progress towards a fix.

**Comment by Blackbaud-IanThomas** [comment]
Awesome.

**Comment by Blackbaud-IanThomas** [comment]
@rgardler I just realized that you've also been involved with another issue involving ansible that I created.  Thanks for helping me out all over the place!

**Comment by spsiddarthan** [comment]
Thank you, @rgardler. Look forward to the fix.

**Comment by rgardler** [comment]
:-) I try - thanks for feeding back to us - always helpful (the eng. team have isolated the problem here and are working on a fix)

**Comment by Blackbaud-IanThomas** [comment]
Glad to help!

**Comment by rgardler** [comment]
DCOS agents stopped registering yesterday because of a new Ubuntu build.  We mitigated by 1:00pm PDT today and all DCOS clusters should correctly install. We've fully tested and believe this fix is complete. Your confirmation or otherwise would be appreciated.

**Comment by Blackbaud-IanThomas** [comment]
I just tested it out, and all seems to be working! @spsiddarthan will surely want to confirm as well. Thanks @rgardler!

**Comment by spsiddarthan** [comment]
Thank you, guys! Works as expected.
