### ISSUE TITLE
Snapshotting should be disabled by default.

### ISSUE THREAD

**Issue by haydonryan** [Azure/azure-quickstart-templates#2037]
[https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/bosh.yml#L93](Template link goes here)

### Issue Details
https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/bosh.yml#L93

Please set to false or remove (default is false).  We should not enable snapshots by default, especially while azure has snapshot limitations.

**Comment by bingosummer** [comment]
@haydonryan 

This issue is fixed by https://github.com/Azure/azure-quickstart-templates/commit/d9b447869fc645cb19d09811ebde89dfa7cd506f

**Comment by singhkay** [comment]
PR merged, closing.
