### ISSUE TITLE
deploy error when deploy 201-vmss-linux-jumpbox

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-quickstart-templates#2046]
### template 
201-vmss-linux-jumpbox
https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-linux-jumpbox

### Issue Details
I got following error.

```
Deployment template validation failed: 'The template parameter 'resourceLocation' is not found. Please see http://aka.ms/arm-template/#parameters for usage details.'. (Code: InvalidTemplate)
```

### Repro steps 
in template validation

**Comment by singhkay** [comment]
@takekazuomi Thank you for fixing!
