### ISSUE TITLE
101-acs-dcos: incorrect value for agentCount.maxValue

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-quickstart-templates#2048]
[101-acs-dcos](https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-dcos)

### Issue Details

All three `101-acs-*` templates specify `agentCount.maxValue`. Two of them (`101-acs-mesos` and `101-acs-swarm`) have 100. The `101-acs-dcos` has 40. The documentation in both `101-acs-dcos` and `101-acs-mesos` states `This value can be from 1 to 40` which is also inconsistent with the actual value in `101-acs-mesos`.

I suspect the correct value in all cases should be 100.

**Comment by rgardler** [comment]
Thank you for highlighting this. You are right, the correct value is 100. I'll resolve.
