### ISSUE TITLE
Update Bosh Deployment and Instructions for Concourse 1.2

### ISSUE THREAD

**Issue by emikuszewski** [Azure/azure-quickstart-templates#2076]
https://github.com/Azure/azure-quickstart-templates/tree/master/concourse-ci

Team -

Can we update this repo in regard to the Bosh deployment and install instructions for the newest version of Concourse (1.2).

Thanks,

-Ed

**Comment by singhkay** [comment]
@bingosummer Can you take a look?

**Comment by bingosummer** [comment]
Will estimate the cost to support the latest version of Concourse.

**Comment by bingosummer** [comment]
https://github.com/Azure/azure-quickstart-templates/pull/2251 is submitted to upgrade the version.
