### ISSUE TITLE
general issue with hardcoded endpoints

### ISSUE THREAD

**Issue by gitralf** [Azure/azure-quickstart-templates#2078]
general issue with hardcoded endpoints 

### Issue Details
Many templates use hardcoded "core.windows.net". For other Environments like China, German Cloud etc. other endpoints are needed and that requires manual search&replace in the templates. If there are guidelines for new templates, could someone include a suggestion for a better way, like putting that in a variable or autodetect it...

**Comment by marcvaneijk** [comment]
@gitralf you can use reference to get the endpoints from the API at runtime. Have a look at the item 9 in the best practices doc [here](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#best-practices). We are also fixing the existing templates, but that will take some time before all templates are fixed.
