### ISSUE TITLE
Elastic pool template request

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-quickstart-templates#2088]
It's not an issue, it's a template request.

I didn't find in a repository template where we are using elastic pools for sql database in a template. It would be nice to have this template

**Comment by singhkay** [comment]
@ninarn @weidaiMS Do you know who can take a look at this request?

**Comment by ninarn** [comment]
I also work on elastic pools, so I will look into this.

**Comment by ninarn** [comment]
@SychevIgor what are the main capabilities you are looking to have in an ARM template? It would be helpful to know what the high priority items are to you.

**Comment by SychevIgor** [comment]
@ninarn some context: I asked about this example, because one of my customers would like to migrate their app from WE to NE datacenter. As part of their app- they are using elastic pools.
Because I'm gouding this migration- I recomened create a arm template to speedup the deployment and avoid typos and so on. 
I provided them all templates like web apps, storage accounts, sql server and sql databases, but I didn't find the template for elastic pools. As a result- I just export template from the portal and clean up it. But it would be very useful, if for a next time I will can send the link to a right template with 1 sql server, few sql databases combined in a elastic pools.
If pricing tiers will be presented as a dropdown list, if I could set amount of database(not maximum db, copy section for database configuration) for a pool it would be awesome.

**Comment by mathieu-benoit** [comment]
Hi there (@ninarn), any update with this enhancement?
Here are some info for that: https://gist.github.com/billgib/d80c7687b17355d3c2ec8042323819ae
Thank you,

**Comment by mathieu-benoit** [comment]
Hi there, FYI I created this PR #2986. Let me know your feedback.

**Comment by mathieu-benoit** [comment]
Looks like we could close this Issue/Improvement since the PR #2986 has been merged into master and closed? CC: @bmoore-msft @ninarn @singhkays

**Comment by bmoore-msft** [comment]
yep - thx...
