### ISSUE TITLE
Unable to add UserPrincipalName during KeyVault Deployment using ARM Template

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-quickstart-templates#2099]
101-key-vault-create (https://github.com/Azure/azure-quickstart-templates/tree/master/101-key-vault-create)

### Issue Details

Unable to provide permission to KeyVault Secrets and Keys for a User Account.

### Repro steps (*if necessary, delete otherwise*)
1. Added a Parameter "UserPrincipalName" in the Template

"UserPrincipalName": {
            "type": "string",
            "defaultValue": "pradebban@abcd.com",
            "metadata": {
            "description": " AD User to grant permission to KeyVault Keys and Secrets "
            }
        },
2. Added the parameter in the Resources section

"accessPolicies": [
            {
                "tenantId": "[parameters('SubscriptionId')]",
                "objectId": "[parameters('servicePrincipalId')]",
                "UserPrincipalName": "[parameters('**UserPrincipalName**')]",
                "permissions": {
                    "keys": "[parameters('PermissionToKeys')]",
                    "secrets": "[parameters('PermissionToSecrets')]"
                    }
            }

3. Deployed using New-AzureRmResourceGroupDeployment
4. Got the result as below, which suggest it takes the parameter "**UserPrincipalName**"
![kvuserpermission](https://cloud.githubusercontent.com/assets/13054214/16018965/cc03cd8e-3174-11e6-8b34-5c1a5bf88e7d.png)
5. But when i issue Get-AzureRmKeyVault, i get the below which does not have any user permission changes applied in the deployment.
![kvuserpermission1](https://cloud.githubusercontent.com/assets/13054214/16018973/d49a9482-3174-11e6-8a19-cc7370142ff5.png)
Please let me know if am missing anything.
Thanks,
Pradebban Raja

**Comment by seanbamsft** [comment]
As described in the [documentation](https://msdn.microsoft.com/en-us/library/azure/Mt620025.aspx), access policies are specified in terms of the object ID of the identity that has access to the vault. Cmdlets like Set-AzureRmKeyVaultAccessPolicy perform the translation of a user principal name to an object ID by accessing the Azure AD Graph prior to calling ARM with the updated vault. You can use the Get-AzureRMADUser cmdlet to perform the same translation.

**Comment by Pradebban** [comment]
@seanbamsft - My bad; thanks and i was able to use the object id of the user account o set permissions.

Thanks,
Pradebban Raja
