### ISSUE TITLE
No quick start template for IOT Hub deployment

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-quickstart-templates#2106]
Hi,

Seems there is no quick start template available for IOT Hub deployment.
When i load the json, shared in this link (https://azure.microsoft.com/en-us/documentation/articles/iot-hub-rm-template-powershell/) i get the below errors,

![iothubtemplate](https://cloud.githubusercontent.com/assets/13054214/16058287/ca8da2f4-324b-11e6-92e8-1814eedbde28.jpg)

Please help with the same and direct to a new template if available.

Thanks,
Pradebban Raja

**Comment by Pradebban** [comment]
Along with this, there is no template download option available from portal.azure.com

The schema of resource type **'Microsoft.Devices/IotHubs' ****is not available**. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

**Comment by singhkay** [comment]
@Pradebban I see you created an issue on the schemas repo which is the right place for this https://github.com/Azure/azure-resource-manager-schemas/issues/179 

There is now an IOT template merged. See https://github.com/Azure/azure-quickstart-templates/pull/2086/files
