### ISSUE TITLE
Deployment template validation fails with latest template

### ISSUE THREAD

**Issue by kiranbhaga** [Azure/azure-quickstart-templates#2124]
Deployment template validation failed: 'The template resource 'elasticsearch-data-vm0' at line '111' and column '6' is not valid: Unable to evaluate template language function 'resourceId': all function arguments must be string literals. Please see https://aka.ms/arm-template-expressions/#resourceid for usage details..'. (Code: InvalidTemplate)

The template worked fine earlier in the week, but with latest I get the above error. Is it due to the latest commits? I see latest commits are using this resourceId function. 

Any inputs on how to get the template working again?

**Comment by kiranbhaga** [comment]
@philon-msft commit fixed this

**Comment by vishnu2017** [comment]
I am facing the same issue. What was the fix?

My current version of network interface is 2016-03-30
