### ISSUE TITLE
Is wrong description in the metadata

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-quickstart-templates#2139]
### Issue Details
In https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-freebsd
Is wrong description in the metadata
It is written with Linux but is correct FreeBSD

> "summary": "This template takes a minimum amount of parameters and deploys a Linux VM, using the latest patched version.",

**Comment by singhkay** [comment]
PR merged, closing
