### ISSUE TITLE
Request for new template, Linux VMSS with DSC

### ISSUE THREAD

**Issue by nielsweistra** [Azure/azure-quickstart-templates#2239]
Hi guys,

Could your provide an example of deploying a Linux VMss with the DSC extension enabled? There's an example for a single Linux vm with DSC, a Windows vmss or a single vm with dsc. But i'm missing a template based on a Linux vmss that uses the Azure Automation Service. 

I'm trying to create my own template but maybe DSC isn't supported yet on Linux vmss?

Kind Regards,

Niels Weistra

**Comment by nielsweistra** [comment]
Issue can be closed, figured out how to implement DSC in ARM.

**Comment by chiaz-git** [comment]
Could you please let know how you fixed dsc in template for Linux VMSS. I need to change hostname in VMSS and add DNS entries for VM communication.
