### ISSUE TITLE
201-web-app-ase-create: Location has an invalid value

### ISSUE THREAD

**Issue by philmea** [Azure/azure-quickstart-templates#2241]
**201-web-app-ase-create**
(https://github.com/Azure/azure-quickstart-templates/tree/master/201-web-app-ase-create)
### Issue Details

[ERROR] Microsoft.Web/hostingEnvironments 'philmeaASE' failed with message 'The 
[ERROR] parameter Location has an invalid value.'
### Repro steps
1. New deployment to resource group in "West US"

**Comment by MCKLMT** [comment]
I'm not able to reproduce this error. I used this template to successfully deploy an ASE in West US.
