### ISSUE TITLE
Add ability to specify an existing App Service Plan

### ISSUE THREAD

**Issue by nibras85** [Azure/azure-quickstart-templates#2243]
Slack notifications logic app: https://github.com/Azure/azure-quickstart-templates/tree/master/201-alert-to-slack-with-logic-app

This template creates a new free App Service Plan. It would be useful to specify an existing App Service Plan to use instead of creating a new one. Thanks.

**Comment by MCKLMT** [comment]
The template deploy a Logic App which is billed by actions executed / month. 
You can consult the pricing documentation here: https://azure.microsoft.com/en-us/pricing/details/logic-apps/

**Comment by nibras85** [comment]
@MCKLMT yes but Logic Apps can either bill by executions/month or be part of an App Service Plan. I was referring to the latter.

**Comment by MCKLMT** [comment]
The fix has been merged. Could you please close this issue @nibras85?

**Comment by nibras85** [comment]
Thanks a lot @MCKLMT
