### ISSUE TITLE
What does "HPC cluster with Linux compute nodes" do?

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-quickstart-templates#2275]
@sunbinzhu I was curious what your template did. Is there any chance you could add some documentation to the [README](https://github.com/Azure/azure-quickstart-templates/tree/master/create-hpc-cluster-linux-cn) to explain what this HPC cluster is? Does it use slurm to connect the nodes? How does it do HPC? I don't see a scheduler in the config.

**Comment by sunbinzhu** [comment]
@zfrenchee Sorry for the late reply, the series of create-hpc-cluster templates are used to deploy a Microsoft HPC cluster with Microsoft HPC Pack 2012 R2 Update 3, but not slurm.
