### ISSUE TITLE
Obtain Listkeys on Eventhubs

### ISSUE THREAD

**Issue by remcov250** [Azure/azure-quickstart-templates#2372]
Hello,

It is impossible to obtain the Shared Access Key within a JSON template using Listkeys.

Currently using:

Variables:
"sbResourceId": "[resourceId('Microsoft.ServiceBus/namespaces/eventhubs/authorizationRules',variables('eh01Name'),variables('sbKeyName'))]",

"sbVersion": "2014-09-01",
"eh01Name": "eventhubname",

Output:
  "outputs": {
    "listKeysOutput": {
      "value": "[listkeys(variables('sbResourceId'), variables('sbVersion'))]",
      "type": "object"
    }
  }

After trying to obtain this key, i receive the following error before deploying the template:

ERROR TYPE
Deployment template validation failed: 'The template variable 'sbResourceId' is not valid: Unable to evaluate template language function 'resourceId': the type 'Microsoft.ServiceBus/namespaces/eventhubs/authorizationRules/eventhubname' requires '4' resource name argument(s). Please see https://aka.ms/arm-template-expressions/#resourceid for usage details..'. (Code: InvalidTemplate)

What am i missing?
I need to obtain a key from eventhub to use it for Stream Analytics.

**Comment by remcov250** [comment]
Dependence was wrong configured

**Comment by d1mnewz** [comment]
Have you found the solution? Please share

**Comment by tappoz** [comment]
@d1mnewz I've put together this to define an Event Hub as an output for a Stream Analytics Job, hope it helps:

```
        "outputs": [{
            "Name": "EventHubOutputLable",
            "Properties": {
                "DataSource": {
                    "Type": "Microsoft.ServiceBus/EventHub",
                    "Properties": {
                        "eventHubName": "[parameters('eh_name')]",
                        "serviceBusNamespace": "[parameters('eh_namespace')]",
                        "sharedAccessPolicyKey": "[listKeys(resourceId('Microsoft.EventHub/namespaces/eventhubs/authorizationRules', parameters('eh_namespace'), parameters('eh_name'), 'super-user'),'2017-04-01').primaryKey]",
                        "sharedAccessPolicyName": "RootManageSharedAccessKey"
                    }
                },
                "Serialization": {
                    "Properties": {
                        "Encoding": "UTF8"
                    },
                    "Type": "Json"
                }
            }
        }]
```
