### ISSUE TITLE
sharepoint 3 vm - show version of sharepoint in README file

### ISSUE THREAD

**Issue by amol-karkhanis** [Azure/azure-quickstart-templates#2382]
[sharepoint-three-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-three-vm)
### Issue Details

Please specify in README.md that this template is for SharePoint 2013 farm. I thought it was for SharePoint 2016. I deployed this template to Azure using button on README.md and did not know it was for SharePoint 2013 only.
### Repro steps (_if necessary, delete otherwise_)
1. Clicked "Deploy in Azure" button on README.md
2. Filled in parameter information
3. Waited for deployment success
4. Logged in as sp_farm account to root site collection
5. Found out it was SharePoint 2013 (not SharePoint 2016)

**Comment by MCKLMT** [comment]
Just submitted a pull request to fix that #2826

**Comment by MCKLMT** [comment]
The pull request has been accepted and merged. You can close this issue.
