### ISSUE TITLE
Standard_D* not supported

### ISSUE THREAD

**Issue by gitralf** [Azure/azure-quickstart-templates#2431]
[viacoin-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/viacoin-blockchain-ubuntu)
### Issue Details

Standard_D\* is not available in certain clouds like Azure Germany, should be Standard_D*_v2

**Comment by MCKLMT** [comment]
The template has been modified since.
https://github.com/Azure/azure-quickstart-templates/tree/master/blockchain 

Could you confirm the issue stills valid or close it?

**Comment by gitralf** [comment]
looks good. losing it...
