### ISSUE TITLE
azuredeploy.json refers to "cluster-nodes-D14.json" which doesn't exist

### ISSUE THREAD

**Issue by aceptra** [Azure/azure-quickstart-templates#2454]
Trying the couchbase template, seems that the D14 vm type ref is broken...

azuredeploy.json refers to "cluster-nodes-D14.json" in "nested", but the only machine resource there close is titled "cluster-nodes-disabledD14.json".

**Comment by MCKLMT** [comment]
The fix has been merged.
Might you close the issue please?
