### ISSUE TITLE
Deployment using "Deploy to Azure" not working. Not using "Storage Account Name" parameter.

### ISSUE THREAD

**Issue by aceptra** [Azure/azure-quickstart-templates#2459]
Deployment using "Deploy to Azure" not working. Assuming it is using latest deployment scripts.
### Repro steps (_if necessary, delete otherwise_)
1. "Deploy to Azure"
2.  Modify parameters appropriately including default storage name of "cbstorage". I changed to "somelongnamestorage".
3. Preflight error check throws validation.
## 

**Preflight validation failed**
- The storage account named cbstoragejb is already taken. (Code: StorageAccountAlreadyTaken)
- The storage account named cbstorage0 is already taken. (Code: StorageAccountAlreadyTaken)

Obviously it isn't using the parameter as it should.

**Comment by MCKLMT** [comment]
The pull request has been accepted and merged. Could you close the issue?

**Comment by aceptra** [comment]
Closing.
