### ISSUE TITLE
elasticsearch template broken for ubuntu 16.04.0-LTS

### ISSUE THREAD

**Issue by abhishekvaid** [Azure/azure-quickstart-templates#2496]
I modified ubuntu version from 14.04.4-LTS to 16.04.0-LTS and installelasticsearch script broke.

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by singhkays** [comment]
@abhishekvaid The template is probably designed for 14.04. Due to difference between 14 & 16, the script might need to be updated. Since this is a community contributed repo, please feel free to explore what needs to be done to update the script and update the template.
