### ISSUE TITLE
template language expression 'triggerBody()['context']['portalLink']' cannot be evaluated because property 'context' doesn't exist

### ISSUE THREAD

**Issue by guya1976** [Azure/azure-quickstart-templates#2514]
HI, deploying the slack logic app : https://github.com/Azure/azure-quickstart-templates/tree/master/201-alert-to-slack-with-logic-app, returns an error trying to call the webhook URI (manual and via script) :

Reason
Code
InvalidTemplate
Message
Unable to process template language expressions in action 'Http' inputs at line '1' and column '855': 'The template language expression 'triggerBody()['context']['portalLink']' cannot be evaluated because property 'context' doesn't exist, available properties are 'WorkspaceId, AlertRuleName, SearchQuery, AlertThresholdOperator, AlertThresholdValue, SearchIntervalStartTimeUtc, SearchIntervalEndtimeUtc, ResultCount, SearchIntervalInSeconds, LinkToResults, Description'. Please see https://aka.ms/logicexpressions for usage details.'.

![capture](https://cloud.githubusercontent.com/assets/22340442/18702493/af52bc80-7fea-11e6-9f9e-3c3fdf6df72c.PNG)

**Comment by amrithyerramilli** [comment]
I am getting this same error right now - what is the solution to this?

**Comment by bjornicus** [comment]
After struggling with this for some time, it looks like the documented payload schema for the webhook is just wrong.  Changed the message that it was sending to slack to just send the whole "Body" of the incomming request, then pasted that back into the 'use sample payload to generate schema' box in the first step, and that works better.  Here's the schema it generated:

```
{
  "properties": {
    "data": {
      "properties": {
        "context": {
          "properties": {
            "activityLog": {
              "properties": {
                "authorization": {
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "scope": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "caller": {
                  "type": "string"
                },
                "channels": {
                  "type": "string"
                },
                "claims": {
                  "type": "string"
                },
                "correlationId": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "eventDataId": {
                  "type": "string"
                },
                "eventSource": {
                  "type": "string"
                },
                "eventTimestamp": {
                  "type": "string"
                },
                "level": {
                  "type": "string"
                },
                "operationId": {
                  "type": "string"
                },
                "operationName": {
                  "type": "string"
                },
                "resourceGroupName": {
                  "type": "string"
                },
                "resourceId": {
                  "type": "string"
                },
                "resourceProviderName": {
                  "type": "string"
                },
                "resourceType": {
                  "type": "string"
                },
                "status": {
                  "type": "string"
                },
                "subStatus": {
                  "type": "string"
                },
                "submissionTimestamp": {
                  "type": "string"
                },
                "subscriptionId": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          },
          "type": "object"
        },
        "properties": {
          "properties": {},
          "type": "object"
        },
        "status": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "schemaId": {
      "type": "string"
    }
  },
  "type": "object"
}
```

**Comment by andrew-best-diaxion** [comment]
Why is this closed? I'm having the same problem as @guya1976 posted originally.

**Comment by mack0196** [comment]
You can get the schema for common from the json content@ https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-common-schema-definitions

**Comment by bostrom** [comment]
This section contains the correct steps to get the correct schema for the incoming http request:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups-logic-app#create-a-metric-alert

**Comment by jamesholland-uk** [comment]
This is still [published in public](https://learn.microsoft.com/en-us/samples/azure/azure-quickstart-templates/alert-to-slack-with-logic-app/), and still broken, so either the template needs updating or take down the web page?
