### ISSUE TITLE
101-recovery-services-weekly-backup-policy-create fails due to faulty time format

### ISSUE THREAD

**Issue by Stijnc** [Azure/azure-quickstart-templates#2516]
[101-recovery-services-weekly-backup-policy-create](https://github.com/Azure/azure-quickstart-templates/tree/e911a2bca09df9be8def941baba9cbd30aebb889/101-recovery-services-weekly-backup-policy-create)

### Issue Details
1. The values for scheduleruntimes are in a wrong format. 
  Currently the time format is hh:mm, but should be yyyy-MM-ddThh:mm:ssZ
2. the properties "scheduleRunTimesNew" are not needed

see screenshots below;

1. deployment error using existing template
![oms_recoveryvault_nok](https://cloud.githubusercontent.com/assets/1662677/18716436/1fef5c82-801d-11e6-8e07-ce6ccfdbd821.PNG)

2. REST api get return values:
![oms_recovery_rest](https://cloud.githubusercontent.com/assets/1662677/18716445/27237862-801d-11e6-8b51-cb38f08c1c3c.PNG)

3. successful deployment using different format for scheduleruntimes
![oms_recoveryvault_ok](https://cloud.githubusercontent.com/assets/1662677/18716458/2df489e2-801d-11e6-9e18-f64deac92d18.PNG)

**Comment by singhkays** [comment]
PR merged, thanks for fixing!
