### ISSUE TITLE
Question: Why vmName is not included as parameter for simple vm deployment templates?

### ISSUE THREAD

**Issue by nilaydshah** [Azure/azure-quickstart-templates#2541]
[101-vm-simple-windows](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-windows)
[101-vm-simple-linux](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-linux)
[101-vm-simple-freebsd](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-freebsd)
### Question Details

Why vmName is not included as parameter for simple vm deployment templates?
### Why I want this?

I want to author template which will refer above mentioned templates as template link (based on my template param i.e. "windows","linux","freebsd","rhel" etc) and once vm is created, can configure backup for that vm. If it's only vm template, user can edit template variable for vmName, but if it's referred from another template as templateLink, user will not be able to modify variable of referred template.

**Comment by marcvaneijk** [comment]
We recommend to prevent linking of templates across scenarios folders. To achieve your desired template design you can copy the template into your scenario folder as nested templates to you main deployment template and make the desired changes in the same deployment scenario folder.
