### ISSUE TITLE
Fails on Windows azure-cli: seems to insist that an empty default value is an invalid one.

### ISSUE THREAD

**Issue by squillace** [Azure/azure-quickstart-templates#258]
This template works in the portal, but not using azure cli. I'll submit a pr for that, but it's up to you, I think, where the bug lies. IMHO, saying there IS a default value but that it's NOT one of the accepted values is not quite right....

**Comment by squillace** [comment]
$ azure group deployment create --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/redis-high-availability/azuredeploy.json redis s
econddeploy
info:    Executing command group deployment create
info:    Supply values for the following parameters
adminUsername: ops
adminPassword: 
+ Initializing template configurations and parameters
+ Creating a deployment
error:   Deployment template validation failed: 'The provided value for the template parameter 'location' at line '24' and column '22' is not valid.'.
info:    Error information has been recorded to c:\Users\rasquill\.azure\azure.err
error:   group deployment create command failed

**Comment by singhkay** [comment]
@squillace Sure, feel free to submit a PR for the fix

**Comment by squillace** [comment]
@singhkay will do. confirmed validation on windows; waiting for successful deployment with modified file.
