### ISSUE TITLE
The Travis CI validation tool is broken 

### ISSUE THREAD

**Issue by sazeesha** [Azure/azure-quickstart-templates#2660]
[Rule API](https://github.com/Azure/azure-quickstart-templates/pull/2645 )

The Travis CI build validation tool looks broken.
My PR https://github.com/Azure/azure-quickstart-templates/pull/2645 was failing validation but tried to run the template and it works correctly. Then I tried to send a PR with a template that is already merged but the validation still failed.

**Comment by singhkays** [comment]
Reran the job and it ran succesfully, closing.
