### ISSUE TITLE
201-specialized-vm-in-existing-vnet and dashes in VM names

### ISSUE THREAD

**Issue by mviets** [Azure/azure-quickstart-templates#2675]
[Create a specialized virtual machine in an existing virtual network](https://github.com/Azure/azure-quickstart-templates/tree/master/201-specialized-vm-in-existing-vnet)
### Issue Details

If you depoy the template to Azure and enter a VM Name with a dash (-), you get the following error message and are unable to continue:

Virtual machine name cannot contain non ASCII or special characters, must contain at lease one alphabet, and must be between 1 and 15 characters.

A dash is a supported VM Name character and thus it should be accepted. Can anyone please fix this or tell me how to do this myself? We are about to lift and shift about 100 VMs an ALL of them have a dash in the Name as by out naming convention.

Thanks in advance!

Kind regards

Marco

**Comment by reubensmither1** [comment]
I raised this with MS they have now fixed this.

thanks

Reuben

**Comment by mviets** [comment]
Great, thanks a lot!

**Comment by MCKLMT** [comment]
You can now close the issue.
