### ISSUE TITLE
201-vmss-lapstack-autoscale returns 500 error

### ISSUE THREAD

**Issue by mioteg** [Azure/azure-quickstart-templates#2681]
[201-vmss-lapstack-autoscale](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-lapstack-autoscale)
### Issue Details

After deploying the template browsing a 500 error is returned.
### Repro steps (_if necessary, delete otherwise_)
1. Deploy VMSS
2. Copy DNS name or IP
3. Open browser and browse to IP or DNS name

**Comment by MCKLMT** [comment]
I just successfully deployed the template. The webpage is well displayed.

**Comment by mioteg** [comment]
Confirmed. Must have been a temporary glitch. Tried deploying it several times back in October, none of them working.
