### ISSUE TITLE
Ethereum Consortium TX node fails with errors - 404 on some assets

### ISSUE THREAD

**Issue by cicorias** [Azure/azure-quickstart-templates#2749]
[ethereum-consortium-blockchain-network](https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network)

### Issue Details

Template fails with the following:

```
ethereum is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Fatal: Could not create the account: account already exists
--2016-11-11 15:06:58--  http://to/scripts/start-private-blockchain.sh
Resolving to (to)... 216.74.32.107
Connecting to to (to)|216.74.32.107|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-11 15:06:58 ERROR 404: Not Found.

Previous command failed on loop 5. Retrying...
One or more commands failed after 5 tries. Deployment failed.
```
.

### Repro steps (*if necessary, delete otherwise*)
1. Fill out template from marketplace
1.1 Use a D3_V2
2. Deploy
3. SSH into the box - TX node
4.Look at the config.log on TX

FYI @sidkri - for some reason, the artifact URL is thinks it is : http://to  - see above logs. This has happened on several attempted deployments today in West, and East2

**Comment by marcvaneijk** [comment]
adding @cavanes and @sidkri

**Comment by sidkri** [comment]
We identified the issue and @iwooden is working on the fix.  Thanks for finding this bug @cicorias !

**Comment by cicorias** [comment]
And I thought I was unique 🎱 @sidkri ..
