### ISSUE TITLE
201-vm-winrm-windows VM Name configuration

### ISSUE THREAD

**Issue by dsschnau** [Azure/azure-quickstart-templates#2763]
Hello,

The template [201-vm-winrm-windows](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-winrm-windows) only lets you create a VM with name 'MyWindowsVM'. Can this be made into a parameter for the template so we can name the VM something more useful?

Thank you!

**Comment by marcvaneijk** [comment]
Can you submit a PR with the proposed change?

**Comment by dsschnau** [comment]
Sure thing. PR #2795. I set up parameters for some of the other resource properties I'd like to be able to specify when using this template.

**Comment by MCKLMT** [comment]
The pull request has been merged. Could you close the issue?
