### ISSUE TITLE
How to add storage account list in template jason file?

### ISSUE THREAD

**Issue by wangjj1989** [Azure/azure-quickstart-templates#2766]
Hi all,
I wan to add a storage account parameter in the template, which is just like resource group: you can both create a new one  and you can choose one from the existing. How should I do that? 
I don't find any examples about this.
Could you provide me some examples? Thanks

**Comment by wangjj1989** [comment]
Hi all,
I wan to add a storage account parameter in the template, which is just like resource group: you can both create a new one  and you can choose one from the existing. How should I do that? 
I don't find any examples about this.
Could you provide me some examples? Thanks

**Comment by marcvaneijk** [comment]
You can achieve that scenario with the concat function and nested templates. Based on the specified parameter the URL of the nested template is constructed. For an example have a look at this template https://github.com/rjmax/ArmExamples/blob/master/NewOrExistingTemplate.json

**Comment by wangjj1989** [comment]
Thanks very much!

**Comment by wangjj1989** [comment]
Hi,
Is there a way or example to show how to implement this:
"a button to chose exist or new, and if you chose exist, the existed items  will be prompted by system", just exactly like resource group when we use template deploy through azure portal  .

**Comment by marcvaneijk** [comment]
The template deployment provides a textbox, a dropdown and a password box. You're unable to specify a button.

**Comment by wangjj1989** [comment]
I tried the template you mentioned in comment 2. In that template, we chose 'new' or 'existing', when we choose 'existing', the existed resources are not shown in dropdown box. 
But for resource group, if you chose 'use existing', the existed resource groups will be shown in the dropdown box.
I just want to know how to do that.

**Comment by marcvaneijk** [comment]
Its not possible to do that. Resource group is a predefined field. You can only use text, dropdown or password box. The dropdown will be populated with the allowedValues specified in the template.

**Comment by wangjj1989** [comment]
Ok. Got it.
Thanks.
