### ISSUE TITLE
active-directory-new-domain template should allow create WS2016 DC

### ISSUE THREAD

**Issue by mmarch** [Azure/azure-quickstart-templates#2800]
active-directory-new-domain
https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain

Should allow create WS2016 DC.

### Issue Details
Currently has storageProfile/imageReference/sku hardcoded to '2012-R2-Datacenter'
Expose this as a parameter, with default = WS2016.

**Comment by MCKLMT** [comment]
I just submitted a pull request ( #2804 ) to have the ability to choose the version of Windows Server (2012, 2012 R2 or 2016)

**Comment by MCKLMT** [comment]
@mmarch Could you close this issue given that the pull request has been merged please?
