### ISSUE TITLE
Example for placing vm into existing vnet

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-quickstart-templates#283]
I'm trying to figure out how to make resource templates that integrate with existing resources (such as storage accounts and virtual networks). OSDisks reference storage accounts simply using the storage account URL, so that one is easy. However, I'm having problems with deploying a vm into an existing vnet (the vnet lives in another resource group). I'm sure I'm missing something, since a hard requirement on vm and vnet in the same resource group would just be plain stupid, but I can't seem to figure it out. I'd love to see an example template for that scenario.

**Comment by singhkay** [comment]
@trondhindenes This might be what you're looking for https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-different-rg-vnet

**Comment by trondhindenes** [comment]
It is! Wonder how I managed to overlook that one. That said, without these templates I'd be completely lost. When can we expect some proper documentation of the various classes? AFAIK the online json schema hasn't been updated in ages either.

**Comment by singhkay** [comment]
You can find the API documentation for all the Resource Providers here https://msdn.microsoft.com/en-us/library/azure/dn948464.aspx. The JSON elements from there map directly to what's used in the templates. 

I believe @rjmax @clamanna from the ARM team are working on the JSON schema updates

**Comment by trondhindenes** [comment]
Thanks for the feedback!
