### ISSUE TITLE
vsts-fullbuild-ubuntu-vm dotnet version is outdated

### ISSUE THREAD

**Issue by alexschneider-ms** [Azure/azure-quickstart-templates#2834]
[vsts-fullbuild-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-fullbuild-ubuntu-vm)

### Issue Details

Version of dotnet sdk installed is outdated. [1.0.0-preview2-002875](https://github.com/Azure/azure-quickstart-templates/blob/master/vsts-fullbuild-ubuntu-vm/scripts/full-vstsbuild-install.sh#L111) is installed while dotnet-dev-1.0.0-preview2-003175 is the latest version.

**Comment by MCKLMT** [comment]
Does it make sense to change the link to always target the last release? 

https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-ubuntu.16.04-x64.latest.tar.gz

**Comment by MCKLMT** [comment]
Submitted a pull request (#2854) to fix this issue.

**Comment by paultbarham** [comment]
@MCKLMT Thanks for the request and PR.  I wanted to include Docker Engine and Compose as a capability on the build machine so was editing the file anyways and added your suggestion.  My PR is here: https://github.com/Azure/azure-quickstart-templates/pull/2857.  The new script will also use the more up-to-date agent which changed the command line args requiring a small change as well.  You can cancel your PR to avoid any conflicts with mine.  Thanks again!  Great suggestion to use 'latest' with .NET core.
