### ISSUE TITLE
Unable to deploy Service Fabric templates.

### ISSUE THREAD

**Issue by pms1969** [Azure/azure-quickstart-templates#2905]
### Issue Details

Unable to deploy the Service Fabric templates.  Specifically, but not limited to https://github.com/Azure/azure-quickstart-templates/tree/master/service-fabric-secure-cluster-5-node-1-nodetype

### Repro steps 
1.  Click on "deploy to azure."
2.  Error given: "Template has no resources. Edit the template to add resources."

might be related to our subscription?  It's free tier at present.  Any help appreciated.

**Comment by MCKLMT** [comment]
I can confirm the issue. The URLs up to the templates are invalids. I'll fix that.

**Comment by MCKLMT** [comment]
The fix has been merged. Might you close the issue please?
