### ISSUE TITLE
https://github.com/Azure/azure-quickstart-templates/tree/052db5feeba11f85d57f170d8202123511f72044/201-web-app-vm-dsc

### ISSUE THREAD

**Issue by nm7427** [Azure/azure-quickstart-templates#2922]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Issue Details 
1) The Configwebserver.zip script which is used to deploy the web application is getting executed on the provisioned VM so I am unable to deploy the web app Need help here 
2) The Configwebserver.zip script has parameter I am not sure where does this script these inputs to parameters like param (
  $MachineName,
  $WebDeployPackagePath,
  $UserName,
  $Password,
  $DbServerName,
  $DbName,
  $DbUserName,
  $DbPassword 

3) Plus as part of this Json script does the configwebserver.ps1 script will be copied to the provisioned VM ?

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by MCKLMT** [comment]
1. The template deployed successfully on my side. Was you able to identify an error message?

2. The parameters are passed within the template with the DSC extension.

3. The script is copied and executed on the VM. More informations [in the documentation.](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-extensions-dsc-overview)

**Comment by nm7427** [comment]
1) Ans --- The webapplication folder was copied in the VM  wwsroot folder but when I browse the with same with DNS name of host it get default web page of IIS server .

3) I did not find the Configwebserver.zip file copied on the VM , I am using Azure Power Shell script to invoke Json template I did not find any error on the console ,  Plus I checked the Outfile.txt file I did not find any error , I am not sure if there is any other way to look at the error , 

Ex of url http://nmish9.westus.cloudapp.azure.com/  where nmish9 is vm name . this leads me IIS default webpage ..

**Comment by MCKLMT** [comment]
Try the following URL: http://nmish9.westus.cloudapp.azure.com/webapplication
The application is not deployed in the root folder but in the "WebApplication" subfolder.
You may consult this blog post if you need help with DSC: https://blogs.msdn.microsoft.com/powershell/2014/08/07/introducing-the-azure-powershell-dsc-desired-state-configuration-extension/

**Comment by nm7427** [comment]
Hi 
Yeah you are right thanks for the help . Appreciate this
