### ISSUE TITLE
How to enable SSE on a storage account with ARM

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#3076]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[101-storage-account-create](https://github.com/Azure/azure-quickstart-templates/tree/master/101-storage-account-create)

### Issue Details

There is no example to create a storage account with SSE enabled already. From what I can tell, this can only happen through the portal.

**Comment by andwie** [comment]
There is an example here I believe:
https://github.com/Azure/azure-quickstart-templates/blob/74b46663040ea8b81ea91f2c33aa5a521ebe2abf/cloudbeesjenkins-dockerdatacenter/nested/blobstorage.json#L38

**Comment by aarsan** [comment]
Perfect. Thanks!
