### ISSUE TITLE
oms-azure-storage-analytics-solution AzAuto sku

### ISSUE THREAD

**Issue by jonsabo** [Azure/azure-quickstart-templates#3226]
[oms-azure-storage-analytics-solution](https://github.com/Azure/azure-quickstart-templates/tree/master/oms-azure-storage-analytics-solution)

### Issue Details
The SKU for the Azure Automation account is hard coded in the template, but the SKU must match the OMS workspace SKU, i.e. an OMS workspace SKUd at pernode must have an azure automation account SKUd at OMS (why one is pernode and one is OMS is beyond me, but that seems to be the situation). Currently the sku is always basic:

```
      "type": "Microsoft.Automation/automationAccounts",
      "properties": {
        "sku": {
          "name": "Basic"
}
```

But the workspace SKU is a parameter.

### Repro steps
1. Create an OMS workspace at the OMS SKU (which necessitates an Azure Automation account).
2. Deploy this solution into that template
3. Receive an error that the OMS and Azure automation accounts must match

I resolved this for my specific case by just changing the `Basic` to `OMS`. I think the real fix will just be parameterizing it out. I am not sure if we could decide what the correct SKU mappings would be in the template itself, but perhaps it is possible.

**Comment by krnese** [comment]
Hi @jonsabo. We recommend using a dedicated Automation account for this preview, hence you should not use an existing - linked automation account. Also, if set to Free, the ingestion is likely to stop due to the cap on automation minutes.

**Comment by jonsabo** [comment]
Ah gotcha, I think I was confused since the docs mentioned deploying into an existing workspace, and that the automation account must be in the same RG, so I just also assumed it should be using the linked automation account (which has the same requirements).

Understood on not deploying it into an existing automation account during preview, though I still think it is worth fixing before it goes GA.

**Comment by krnese** [comment]
Thanks @jonsabo . You can have multiple automation accounts within the same RG as the workspace, but only one can be linked. We don't want to mix the runbooks/modules etc for the preview solution, with an existing account that might be running production runbooks :-)
