### ISSUE TITLE
Missing parameter error when nesting a template within a template

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#3247]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

n/a

### Issue Details
When I try to nest a template inside of another template using the following resource:

"Microsoft.Resources/deployments" 

I get parameter xyz not found. I am not using a templatelink. I am trying to embed the entire template itself. I don't see an example of this anywhere in this repository but according to this document:

https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/deployments 
(first item under "DeploymentProperties object") we can do that. However, no example anywhere so I do not know if my syntax is correct. 

Is there any example of this anywhere?

thanks!

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by krnese** [comment]
@aarsan , is this the same conversation as we're having in the Yammer group?
