### ISSUE TITLE
201-dependency-between-scripts-using-extensions does not work

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#333]
1. When I deploy it, I got the message from portal:
{"error":{"code":"BadRequest","message":"Multiple extensions per handler not supported for OS type 'Linux'. Extension 'installmongo' with handler 'Microsoft.OSTCExtensions.CustomScriptForLinux' already added."}}
2. "fileUris" in azuredeploy.json should be https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-dependency-between-scripts-using-extensions/mongo-configure-ubuntu.sh.

**Comment by mahthi** [comment]
This issue now has been fixed. Please try and let us know if you see any more issues.

**Comment by bingosummer** [comment]
Thanks, @mahthi . For the first error, would you like to explain how to fix it?
I deployed another template which would deploy VMAccessForLinux extension twice. And it also failed with "Multiple extensions per handler not supported for OS type 'Linux'. Extension 'enablevmaccess0' with handler 'Microsoft.OSTCExtensions.VMAccessForLinux' already added."

**Comment by mahthi** [comment]
Bin – Can you look at this sample -https://github.com/Azure/azure-quickstart-templates/tree/master/201-dependency-between-scripts-using-extensions. You need to do this. ☺

**Comment by yuvarajduraisamy** [comment]
When I deploy  Json tempalete with two dsc extension    , I got the message from portal: {"error":{"code":"BadRequest","message":"Multiple extensions per handler not supported for OS type 'Windows'. Extension 'InstallDevVMPowerShellScript' with handler 'Microsoft.Compute.CustomScriptExtension' already added."}}

**Comment by mahthi** [comment]
That is not supported at this moment. You have to follow the sample as shown for now. Its in our backlog to support Multiple Configuration per Handler (DSC or CustomScript) soon.

Mahesh

**Comment by cyruszhang** [comment]
@mahthi is this features supported now? multiple configuration per handler (DSC)

**Comment by twoqubits** [comment]
@mahthi It's been a few years, multiple configuration per handler is still not supported?
