### ISSUE TITLE
mongo-on-centos failue

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#334]
I got this:
failure: repodata/repomd.xml from mongodb-org-3.0: [Errno 256] No more mirrors to try.
http://repo.mongodb.org/yum/redhat//mongodb-org/3.0/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by singhkay** [comment]
@bingosummer Was this error from the VM extension? Looks like the download link in the script might not be valid. Can you edit the link and see if it works? https://github.com/Azure/azure-quickstart-templates/blob/master/mongodb-on-centos/mongo-install-centos.sh 

Feel free to update the template as well

**Comment by rgardler** [comment]
Oops this didn't fix it and my commit seems to have closed the issue. Reopening.

I've not got time to further debug now but I note that the URL is wrong for the repository. Quickly looking at the instructions for how to do this (see http://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat/) the only difference I see now is the name of the yum.repos.d filename being created.

**Comment by khanhankkhan** [comment]
Hi, getting this error 

     failure: repodata/repomd.xml from mongodb-org-3.0: [Errno 256] No more mirrors to try.

from command

     sudo yum install mongodb-org

searching my error on google brought me here
