### ISSUE TITLE
Ethereum Consortium Network - Metamask EIP155 compat issue

### ISSUE THREAD

**Issue by kumavis** [Azure/azure-quickstart-templates#3404]
[Ethereum Consortium Network](https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network)

### Issue Details

Hello/
[MetaMask](https://metamask.io) dev here.
A user reported an issue in our slack with this azure deployment and our new [EIP155](https://github.com/ethereum/eips/issues/155) support.
This is known to work with recent vanilla geth for various chain ids, including some multibyte chain ids. I am not sure what chain ids are used by consortium configurations.

from the user:
> When I try to send ETH in metamask between accounts on a private network I am repeatedly getting failed (Invalid Sender). Is there a workaround?
>The Invalid Sender error occurs using the latest client 3.6.0 with the Ethereum Consortium Blockchain in Microsoft Azure MarketPlace.

sorry i dont have any additional information at this time

attn @sidkri @cavanes @iwooden

**Comment by sidkri** [comment]
@kumavis thanks for opening this issue and bringing this to our attention.  We have not made any specific changes to how we configure or start geth w.r.t. chain ids.  Looking into it now but could you suggest what may be needed for a private network?

**Comment by sidkri** [comment]
We allow the user to specify a networkID value and default it to "10101010".

**Comment by kumavis** [comment]
sounds like this was resolved by https://github.com/Azure/azure-quickstart-templates/pull/3411

**Comment by sidkri** [comment]
Thanks for closing the issue, we missed closing it after pushing out our update.  Yes, we resolved the issue by setting the chain ID in the genesis file.  It appears that Metamask determines the chain ID before submitting transactions and could have been treating private networks without chain ID defined as the public network?  Might be worth looking into for pre-EIP155 support.

**Comment by rinsharabi** [comment]
in my azure ethereum consortium network transaction node ,i check the genesis file. Both the network ID and Chain ID are same .Stilll not possible to send ether from ethereum coinbase account to metemask. Pls help me to resolve this issue.
