### ISSUE TITLE
Inconsistent behavior of ARM template storage solution

### ISSUE THREAD

**Issue by dewanymca** [Azure/azure-quickstart-templates#3409]
[oms-azure-storage-analytics-solution ](https://github.com/Azure/azure-quickstart-templates/tree/master/oms-azure-storage-analytics-solution)

### Issue Details
I tried using this GitHub solution to monitor the storage account in our subscription. I had an inconsistent experience, sometime it works without issue, sometime it doesn't. when I say It doesn't, I means schedule will not get created automatically and variable is also getting removed.

1) I think as part of the template, we are calling CleanUP which is removing the variables and other stuff. After this CreateSchedule is being ran and it fails. To really make it work, I need to remove the cleanup job run from template.

2) Other issue is that there is no clear documentation of what this solution does. This is a complex runbook so I think outlining what exact steps we can expect this is doing need to be documented.

3) Also CreateSchedule has errorperfernce as "Sliently Continue" so if it fails we don't know what happened. I had to go and change it to "Stop" and Remove Write-Verbose to see the output. 

I have reported same issue in Azure Automation Discussion which didn't land anywhere.

Thanks
Deepak Sanghi

P.S. To integration it with other solution, I have taken the script and ARM template and put it in our source control.(This is the only change). Also I am not using _artifactLocation provided as I have uploaded all script to publicly accessible blob and using that url in ARM template parameter file.

**Comment by Volkanco** [comment]
Thanks for the feedback 

I'm working on updating the solution. 
I'll remove that cleanup all together as I have implemented a better way to handle  this scenario in the new solutions.
