### ISSUE TITLE
VM deployment failures from template in US West

### ISSUE THREAD

**Issue by bkvarda** [Azure/azure-quickstart-templates#353]
I have a template that can deploy a large # of VMs at once...I typically use US West for region, and just yesterday I started receiving this error in Azure as VM deployments failed (but not all of the VMs, just most of them):

{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"ArtifactNotFound","message":"The VM extension with publisher 'Microsoft.WindowsAzure.GuestAgent', and type 'CRPProd', could not be found in location 'westus'."}]

I'm not really sure what this means...any ideas?

The template I'm using is here: https://github.com/bkvarda/sioazure/blob/master/sioazure/Templates/DeploymentTemplate.json

**Comment by singhkay** [comment]
@bkvarda There was an issue with the Image/Extension repository last night. Can you try again?

**Comment by bkvarda** [comment]
@singhkay  Just tried and everything appears to be working again. Thanks!

**Comment by singhkay** [comment]
@bkvarda Sounds good!
