### ISSUE TITLE
sharepoint-server-farm-ha fails

### ISSUE THREAD

**Issue by gitralf** [Azure/azure-quickstart-templates#3615]
sharepoint-server-farm-ha (https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-server-farm-ha)

### Issue Details
VM size needs to be adopted to _v2 (older versions are no longer deployed to new regions...)
SQl ImageOffer changed from SP1 to SP2
wmfversion has to be upgraded to 5

deployment fails at ConfigureSharePointServerHA.ps1: Cannot access the local farm. 

Any chance of updates?

**Comment by esener303** [comment]
similar problems here too

**Comment by gitralf** [comment]
Closing this since nobody reacted for the last 3 years...
