### ISSUE TITLE
acomghbot line numbers are out by 1

### ISSUE THREAD

**Issue by rgardler** [Azure/azure-quickstart-templates#376]
It looks like acomghbot has line numbers are off by 1 - see https://github.com/Azure/azure-quickstart-templates/pull/374#issuecomment-118729049 for an example

**Comment by singhkay** [comment]
Assigning to @bursteg. Guy, can you investigate this as a fix for the bot?

**Comment by singhkay** [comment]
Assigning to @rjmax for taking a look since this is coming from ARM template validation API
