### ISSUE TITLE
Ethereum Consorium template- unable to unlock accounts, private API is not exposed

### ISSUE THREAD

**Issue by amiturgman** [Azure/azure-quickstart-templates#3784]
ethereum-consortium-blockchain-network

### Issue Details
Hi, after deploying the template, I try to deploy a smart contract from my code on a remote machine using Node.js running against the deployment rpc endpoint.

The problem is that you don't expose the private api on the RPC (using --rpcapi=private) so there's no option to unlock the account.
Without being able to unlock accounts, the deployment is useless since you can practically do nothing (unless I'm missing something and there's a way to deploy contracts and sign/send transactions without unlocking accounts).

### Repro steps
1. Deploy the template
2. Try to unlock the coinbase account using web3 against the RPC endpoint (web3.eth.personal.unlockAccount)
3. You will get the following message: "The method personal_unlockAccount does not exist/is not available"

Please advise, this is a serious blocker.

Thanks,
Ami.

**Comment by tilowestermann** [comment]
Same issue here. (You should rename _private_ to _personal_).

Any update on this issue?

**Comment by tilowestermann** [comment]
After further investigation, geth is started with _db_, _eth_, net and _web3_ API's over the RPC, other APIs are provided over IPC only. So, in oder to unlock an account, SSH into your transaction node and call `geth attach`. Now you can do an `personal.unlockAccount(eth.coinbase)`.
