### ISSUE TITLE
VM into existing vnet & subnet: Value for reference id is missing

### ISSUE THREAD

**Issue by ecgg** [Azure/azure-quickstart-templates#3785]
[example.json](https://github.com/ecgg/azure-templates/blob/master/example.json)

### Issue Details

Trying to deploy the linked template into an existing vnet and subnet. I based myself on [https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-specialized-vhd-existing-vnet/azuredeploy.json](201-vm-specialized-vhd-existing-vnet)

I get the following error:

```
Deployment failed. {
  "error": {
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path Properties.NetworkProfile.networkInterfaces[0]."
      }
    ],
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request."
  }
}
```
I'm using Azure CLI 2.0 to push this

```
azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Linux) 3.6.2 (default, Jul 19 2017, 13:09:21) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

Python location '/usr/bin/python3'
```

### Repro steps (*if necessary, delete otherwise*)
1. az group deployment create -g default --template-file example.json

I'd appreciate any help on this

**Comment by zechariahks** [comment]
@ecgg ,

seems like you are passing "properties" in network profile object under virtual machine properties.  Instead of passing reference Id under "properties", try to pass it directly as "Id" (see below). 

**Your Json:**
"networkProfile" : {
               "networkInterfaces" : [
                  {
                     "properties" : {
                        "id" : "[resourceId('Microsoft.Network/networkInterfaces', variables('nicName'))]"
                     }
                  }
               ]
            },

**To be**

"networkProfile" : {
               "networkInterfaces" : [
                  {                    
                        "id" : "[resourceId('Microsoft.Network/networkInterfaces', variables('nicName'))]"                    
                  }
               ]
            },

**Comment by ecgg** [comment]
That worked - thank you @zechariahks !
