### ISSUE TITLE
Not Able to add Alert Rule for App Insight using ARM template

### ISSUE THREAD

**Issue by niravbhalodiya** [Azure/azure-quickstart-templates#3790]
[301-insights-alertrules-application-insights](https://github.com/janusznowak/azure-quickstart-templates/tree/feature/301-insights-alertrules-application-insights/301-insights-alertrules-application-insights)

I have created template to add alert rules as per below using above template as reference

{
      "copy": {
        "name": "alertruleloop",
        "count": "[length(parameters('alertrules'))]",
        "mode": "Serial",
        "batchSize": 1
      },
      "type": "microsoft.insights/alertrules",
      "name": "[parameters('alertrules')[copyIndex()].rulename]",
      "apiVersion": "2016-03-01",
      "location": "[parameters('location')]",
      "tags": {
      },
      "scale": null,
      "properties": {
        "name": "[parameters('alertrules')[copyIndex()].rulename]",
        "description": "[parameters('alertrules')[copyIndex()].description]",
        "isEnabled": "[parameters('alertrules')[copyIndex()].isEnabled]",
        "condition": {
          "odata.type": "Microsoft.Azure.Management.Insights.Models.ThresholdRuleCondition",
          "dataSource": {
            "odata.type": "Microsoft.Azure.Management.Insights.Models.RuleMetricDataSource",
            "resourceUri": "[resourceId('microsoft.insights/components/', parameters('appinsightname'))]",
            //"metricNamespace": null,
            "metricName": "[parameters('alertrules')[copyIndex()].metricName]"
          },
          "operator": "[parameters('alertrules')[copyIndex()].operator]",
          "threshold": "[parameters('alertrules')[copyIndex()].threshold]",
          "windowSize": "[parameters('alertrules')[copyIndex()].windowSize]",
          "timeAggregation": "Total"
        },
        "actions": {
          "odata.type": "Microsoft.Azure.Management.Insights.Models.RuleEmailAction",
          "sendToServiceOwners": "[parameters('alertrules')[copyIndex()].emailtoserviceowners]",
          "customEmails": "[parameters('customEmails')]"
        }
      },
      "dependsOn": [
        "[resourceId('microsoft.insights/components', parameters('appinsightname'))]"
      ]
    }

It is throwing error while deploy it using VS 2015. Below is error details

**- Resource microsoft.insights/alertrules 'rulename1' failed with message '{
"code": "UnsupportedRequestContent",
"message": "Request content is not well formed or supported."
}'**

But, If I do it usig PowerShell, it works as per below cmdlets

$mailTo = New-Object "System.Collections.Generic.List[String]"  
$mailTo.Add("abc@xyz.com")  

$action = New-AzureRmAlertRuleEmail -CustomEmails $mailTo  
$action.SendToServiceOwners = $false

**Add-AzureRmMetricAlertRule** -Name "rulename" -Description "ruledescription" `
 -ResourceGroup "RG" `
 -TargetResourceId "/subscriptions/subid/resourcegroups/rg name/providers/microsoft.insights/components/appinsightname" `
 -MetricName "name" `
 -Operator GreaterThanOrEqual  `
 -Threshold 1   `
 -WindowSize 00:05:00 -Location "East US" -TimeAggregationOperator Total -Actions $action 

Please help me to get is works using ARM template as I have large number of Rules(Azure Function Failure Matric Alert Rules) 

Thanks in Advance..

**Comment by brettplarson** [comment]
Also having this issue. Thanks.

**Comment by janzhang82** [comment]
I have the same error
  "code": "UnsupportedRequestContent",
  "message": "Request content is not well formed or supported."

**Comment by C123R** [comment]
Same issue while adding alert rules for the Application Insights Web Tests.

@niravbhalodiya : Do you have any workaround for this other than Powershell or CLI deployment ? thanks in advance.

**Comment by pokorourk** [comment]
I had a similar issue, and I was able to fix it by adding [ ] around the value for customEmails.

From: "customEmails": "[parameters('customEmails')]"
To: "customEmails": ["[parameters('customEmails')]"]

**Comment by MarekSven** [comment]
> 
> 
> I had a similar issue, and I was able to fix it by adding [ ] around the value for customEmails.
> 
> From: "customEmails": "[parameters('customEmails')]"
> To: "customEmails": ["[parameters('customEmails')]"]

Great! That was it exactly. You saved my day!

**Comment by itanex** [comment]
@niravbhalodiya 

Might I suggest closing this issue. The fix was due to a syntax error the customEmails parameter must be an array not a string.

[2016-03-01 Specification](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2016-03-01/Microsoft.Insights.json#L226)

Thanks!
