### ISSUE TITLE
Invalid schema on bosh-setup

### ISSUE THREAD

**Issue by squalrus** [Azure/azure-quickstart-templates#3860]
[bosh-setup](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/azuredeploy.json#L670)

### Issue Details

Template does not adhere to schema described in [resource-group-authoring-templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#resources) documentation. `"properties"` should be of type object.

**Comment by bmoore-msft** [comment]
This is actually "by design" - any property in ARM (regardless of type (string, array, object, etc)) can be replaced by an expression (parameter, variable, function).
