### ISSUE TITLE
How to redeploy the template?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#387]
If I failed to deploy a template for the first time, I want to re-deploy it. It seems I have to deploy it from scratch. Is there a way to re-deploy it with the previous parameters? Thanks.

**Comment by rgardler** [comment]
I don't believe there is a way to easily redeploy using previous settings. I'll communicate this to the portal team in the hope that the feature comes along one day.

Thanks for the feedback.
