### ISSUE TITLE
Is ARM support the Resource Provider "Microsoft.ClassicCompute"?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#394]
In 101-simple-linux-vm, I want to replace "Microsoft.Compute" with "Microsoft.ClassicCompute" to support V1 VM, but failed.

Is ARM support the Resource Provider "Microsoft.ClassicCompute", "Microsoft.ClassicStorage" and "Microsoft.ClassicNetwork"? Should I change the API version to "2015-06-01"?Thanks.

**Comment by singhkay** [comment]
Hi @bingosummer, deploying Classic resources through ARM templates is not supported.

**Comment by bingosummer** [comment]
Thanks for your response. Could I deploy classic resources directly by ARM ReSTful API, not templates?

**Comment by singhkay** [comment]
Sorry @bingosummer, the only supported API to deploy classic resources is the service management API https://msdn.microsoft.com/en-us/library/azure/jj157206.aspx
