### ISSUE TITLE
How to create V12 SQL Database

### ISSUE THREAD

**Issue by pbolduc** [Azure/azure-quickstart-templates#396]
The default templates will create a **web** edition SQL Database.  Is there an example to create a V12 database?

**Comment by singhkay** [comment]
@pbolduc Are you referring to this template? https://github.com/Azure/azure-quickstart-templates/tree/master/201-web-app-sql-database

**Comment by pbolduc** [comment]
Yes, that one is very similar to the one created by the Visual Studio resource manager template for web app+SQL Database.

**Comment by singhkay** [comment]
@tfitzmac Can you help here?

**Comment by tfitzmac** [comment]
I haven't had a chance to test this, but you could try passing a different id and edition to get the type of database you want. See https://msdn.microsoft.com/library/azure/dn505701.aspx

**Comment by pbolduc** [comment]
@tfitzmac  Thanks. This was one of the pieces I was missing. Another piece was specifying the version when creating the server.

            "name": "[parameters('serverName')]",
            "type": "Microsoft.Sql/servers",
            "location": "[parameters('serverLocation')]",
            "tags": {
                "displayName": "SqlServer"
            },
            "apiVersion": "2014-04-01-preview",
            "properties": {
                "administratorLogin": "[parameters('administratorLogin')]",
                "administratorLoginPassword": "[parameters('administratorLoginPassword')]",
                "version": "12.0"
            },

I was able to create the lowest level Server and Database with these values.

        "edition": {
            "type": "string",
            "defaultValue": "Basic"
        },
        "requestedServiceObjectiveId": {
            "type": "string",
            "defaultValue": "dd6d99bb-f193-4ec1-86f2-43d3bccbc49c"
        }

As the 'Web' and 'Business' editions are being retired and will not be available after Sept 2015, I recommend updating the SQL Database templates with defaults for Basic, Standard, and Premium editions by setting the allowedValues.

**Comment by singhkay** [comment]
@pbolduc Feel free to submit a PR with the recommended changes. We want everyone to feel comfortable in contributing to this repo! :)
