### ISSUE TITLE
Linux chef client extension not valid

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#397]
The type and typehandlerversion parameters ("LinuxChefClient" and "1204.12") shown in various Chef client examples seem to be invalid - Azure complains that the extension could not be found in the extension repository. I am guessing that the version has probably been updated since the the example templates were created. In general, does anyone know where to find a complete listing of all extensions and their versions? Also, the example templates should be updated.

Here is the example template I derived my template from, though they all appear to use the same type and version info:

https://github.com/Azure/azure-quickstart-templates/tree/b1908e74259da56a92800cace97350af1f1fc32b/chef-json-parameters-ubuntu-vm

Also, here is the Azure complaint:
Microsoft.Compute/virtualMachines/extensions 'hazelcast-vm/chefClient' failed 
17:35:31 - with message 'Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 
17:35:31 - 'LinuxChefClient', and type handler version '1204.12' could not be found in 
17:35:31 - the extension repository.'

**Comment by tfnaylor** [comment]
Figured it out. For anyone else interested the current LinuxChefClient extension version is 1207.12. Using this value causes the example template to work. You can find the current versions of all VM extensions using the following powershell command:
Get-AzureVMAvailableExtension

**Comment by rgardler** [comment]
Thank you @tfnaylor 

I'm reopening this issue as we need to replace the version number in the template so that it works for other people. I don't have the time to make the change and test it right now, but this issue, and the fix you found will remind us.

**Comment by singhkay** [comment]
Adding template author @KundanaP for the update

**Comment by rgardler** [comment]
I needed to use this template and hit this bug. Thank you @tfnaylor for documenting the fix. I applied to both the Chef templates.
