### ISSUE TITLE
201-traffic-manager-vm-zones - "publicIPAddresses' does not support availability zones"

### ISSUE THREAD

**Issue by jochenvw** [Azure/azure-quickstart-templates#3984]
**Template:** 201-traffic-manager-vm-zones
**Link:** [https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-traffic-manager-vm-zones/azuredeploy.json](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-traffic-manager-vm-zones/azuredeploy.json)
**Template contributor:** @bmoore-msft 

I used EastUS2 for the deploymentregion. The error message I get is:

`The resource type 'publicIPAddresses' does not support availability zones at location 'eastus2' and api-version '2017-08-01'. (Code: ResourceTypeNotSupportAvailabilityZones)`

![image](https://user-images.githubusercontent.com/17111555/31448555-05cb40c0-aea5-11e7-8ff1-8d310ffe2ec5.png)

**Comment by dmauser** [comment]
I got the same error. This feature is in Public Preview and you need to sign up to get it enabled in your subscription. Just follow the instruction here:
[Overview of Availability Zones in Azure (Preview)](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview)

Scroll to the middle of the page and follow steps under: **Get started with the Availability Zones preview**

I hope this helps.
DM

**Comment by jochenvw** [comment]
Thanks - that fixed it for me!
