### ISSUE TITLE
How to connect the PXC cluster

### ISSUE THREAD

**Issue by exile1205** [Azure/azure-quickstart-templates#399]
I used mysql-ha-pxc to build up pxc cluster.
I have tried several quickstart templates using the Deploy to Azure button and built up successfully.

I didn't figure out that how to connect to the cluster by "mysql -h 'azure dns' -u test -p" and then I tried to ping the public IP such like 'ping 138.91.147.179' and request was timed out.

**Comment by singhkay** [comment]
I've sent an email to the template author @liupeirong for help with this

**Comment by liupeirong** [comment]
First of all, was your deployment successful?  When you connect to 'azure dns', are you using the public IP/dns   provisioned by the template?  What password are you using to log in?  By default, it's the sst_auth info in my.cnf.template.  Of course in production, you would put your own my.cnf somewhere and point the template to it.

**Comment by singhkay** [comment]
Closing due to no update from OP. Please reopen if it's still an issue.
