### ISSUE TITLE
"Failed to download all specified files" error in customScript extension for Service Fabric Cluster

### ISSUE THREAD

**Issue by mdverde** [Azure/azure-quickstart-templates#4010]
service-fabric-secure-cluster-5-node-1-nodetype https://github.com/Azure/azure-quickstart-templates/tree/master/service-fabric-secure-cluster-5-node-1-nodetype

I need to deploy an Azure Service Fabric cluster and execute a custom script in the VM Scale set, so I added the "customScript" extension to the Microsoft.Compute/virtualMachineScaleSets section of the template. But when I try to deploy it I always get this error:

    New-AzureRmResourceGroupDeployment : 8:04:07 PM - VM has reported a failure when processing 
    extension 'customScript'. Error message: "Failed to download all specified files. Exiting. Error Message: 
    The remote server returned an error: (404) Not Found.".
    At line:1 char:1
    + New-AzureRmResourceGroupDeployment -ResourceGroupName "internal-rnd"  ...
    + 
        + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
        + FullyQualifiedErrorId : 
    Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

This is the section on the template

              {
                "name": "customScript",
                "properties": {
                  "publisher": "Microsoft.Compute",
                  "settings": {
                    "fileUris": [
                      "[concat(parameters('_artifactsLocation'), '/scripts/MyScript.ps1')]"
                    ]
                  },
                  "typeHandlerVersion": "1.8",
                  "autoUpgradeMinorVersion": true,
                  "protectedSettings": {
                    "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File MyScript.ps1"
                  },
                  "type": "CustomScriptExtension"
                }
              }

This is the folder where the template is, and inside the scripts folder is the MyScript.ps1 file.

![image](https://user-images.githubusercontent.com/18468967/31752426-1dca599c-b448-11e7-9915-772a1dc1d88e.png)

This is the Powershell command I'm using to deploy:

    New-AzureRmResourceGroupDeployment -ResourceGroupName "internal-rnd" -TemplateFile .\azuredeploy.json -TemplateParameterFile .\azuredeploy.parameters.json

And for I what I've read there no need to previously upload the scripts to an Azure Storage.

I've spent lots of hours trying different things and now I'm stuck. Am I doing something wrong?

Thanks in advance.

**Comment by jfuller28495** [comment]
I am also experiencing the same issue when deploying existing functional templates into a new environment. I know these templates have worked before, however when I attempted to deploy them into a new Azure tenant (accounting for the change in environmental variables) I reached this same issue.

**Comment by patild05** [comment]
I face the same error when I use the file from existing storage account or even from Git. Any comments?

**Comment by mdverde** [comment]
@jfuller28495, @patild05 :  What worked for me at the end was to upload the script file into an Azure Storage blob and to use a sasKey like this:

`             {
                "name": "customScript",
                "properties": {
                  "publisher": "Microsoft.Compute",
                  "settings": {
                    "fileUris": [
                      "[concat(parameters('_artifactsLocation'), parameters('scriptFileName'))]"
                    ]
                  },
                  "typeHandlerVersion": "1.8",
                  "autoUpgradeMinorVersion": true,
                  "protectedSettings": {
                    "commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File MyScript.ps1",	
					"storageAccountName": "[parameters('storageAccounts_customscriptteststorage_name')]",
                    "storageAccountKey": "[parameters('sasKey')]"

                  },
                  "type": "CustomScriptExtension"
                }
              }`

**Comment by subash544772** [comment]
@mdverde it does not work for me .i tried same thing what you have suggested .

**Comment by dopic** [comment]
Hi, I have the same problem.

I generate the SAS token using the cmdlet "New-AzureStorageBlobSASToken", and when I try to update my scale set with it, it fails.
Generally it works once or two times, but after that, it starts to raise the error: "The remote server returned an error: (403) Forbidden". (PS.: Every time that I try to execute the update, I use a brand new SAS token, its not the same).

If I take the same SAS token and try it on browser, it starts the download normally.

**Comment by majorvin** [comment]
@dopic  did you get it to work for you?

**Comment by Deepudev13** [comment]
I am also facing same issue!
Is there any resolution for this issue or closed without resolution!

**Comment by dogejim** [comment]
Fixed this on my end by going to blob container --> Overview --> Change access level --> Container (anonymous read access for containers and blobs)

**Comment by wenboyang214** [comment]
> Fixed this on my end by going to blob container --> Overview --> Change access level --> Container (anonymous read access for containers and blobs)

doing this will show others your script. it's not a recommended way. the storage account name and key here are design to avoid this.

**Comment by halradaideh** [comment]
any update here ?
/reopen

**Comment by dnyaneshwar-surywanshi** [comment]
I resolved the issue just append the SAS token with fileUris.

**Comment by agyss** [comment]
Solution is to use `protectedsettings` instead of `settings`. Only `fileUris` and `commandToExecute` are supported in the `settings` section...

The error message one receives is very bad IMHO and the documentation could be better, but it actually contains it as of today (28.05.2024):

```
You can set the following values in either public or protected settings. The extension rejects any configuration where these values are set in both public and protected settings.

 - commandToExecute
 - fileUris
```
