### ISSUE TITLE
The template language function 'split' expects its first parameter to be of type 'String'. The provided value is of type 'Uri'

### ISSUE THREAD

**Issue by graych** [Azure/azure-quickstart-templates#4077]
### Issue Details
We use linked templates extensively and publish them to a storage account protected by sas tokens.

We use a variable to strip off the sas token from the deployment().properties.templateLink.uri property so that we can pass it on to additional linked templates. 

This has worked fine for nearly a year, but this morning we started getting this error on all of our deployments.

`Deployment template validation failed: 'The template variable 'SharedTemplateSAS' is not valid: The template language function 'split' expects its first parameter to be of type 'String'. The provided value is of type 'Uri'.`

Here's an example template that reproduces the issue.

azuredeploy.json

`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "SASToken": {
            "type": "string"
          }
    },
    "variables": {
        "apiVersion": "2016-06-01",
        "templateLocation": "https://storageaccountwithlinkedtemplates.blob.core.windows.net/templates/"
    },
    "resources": [
        {
            "apiVersion": "[variables('apiVersion')]",
            "type": "Microsoft.Resources/deployments",
            "name": "[take(concat(deployment().name, '-internal'), 64)]",
            "properties": {
              "templateLink": {
                "uri": "[concat(variables('templateLocation'), 'split.json', parameters('SASToken'))]"
              },
              "parameters": {
              },
              "mode": "incremental"
            }
          }
    ]
}`

And this is the linked template which would have worked before today.

`{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "2.0.0",
  "parameters": {},
  "variables": {
    "apiVersion": "2016-06-01",
    "SharedTemplateSAS": "[concat('?',split(deployment().properties.templateLink.uri,'?')[1])]"
  },
  "resources": []
}`

As mentioned, we use linked templates protected by SAS tokens exclusively, this has broken nearly every one of our hundreds of templated deployments.

**Comment by JohnRusk** [comment]
I have the same problem

**Comment by graych** [comment]
After opening a support ticket today, it was determined that this was a bug in template validation.  The fix is being rolled out across the data centers.

**Comment by sc-mehrantoosi** [comment]
as a temp. workaround you can do the following:
`[concat('?',split(json(string(deployment().properties.templateLink)).uri,'?')[1])]`
this converts the object to json string and then converts it back to json, which makes the uri property string again.
