### ISSUE TITLE
URL for location specific DNS label

### ISSUE THREAD

**Issue by BarryJNewman** [Azure/azure-quickstart-templates#4140]
Anyway to get the DNS name label relative to location deployed? I want to inject it into my DSC configuration but not seeing where I can get the FQDN once the publicip/LB is created ( the location specific part ".usgovvirginia.cloudapp.usgovcloudapi.net") without hard coding it. Thank you in advance for any help!

**Comment by bmoore-msft** [comment]
See #14 in https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md
