### ISSUE TITLE
ARM Template for accelerated NIC ?

### ISSUE THREAD

**Issue by ChoOo7** [Azure/azure-quickstart-templates#4170]
Hello

Can you provide an example of how to create a Virtual Machine creation with an accelerated network interface ?

https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-powershell

Thanks

**Comment by FabienLavocat** [comment]
I've created a Pull Request for a simple Ubuntu machine with Accelerated Networking enabled:
https://github.com/Azure/azure-quickstart-templates/pull/4171
