### ISSUE TITLE
Moodle: does not ask for admin password

### ISSUE THREAD

**Issue by sonete** [Azure/azure-quickstart-templates#4179]
moodle-scalable-cluster-ubuntu https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-scalable-cluster-ubuntu

### Issue Details
No password field when deploying to azure. The moodle installation script expects more parameters than provided. For example $adminuser is not provided in the template (no option to input site admin password).

**Comment by rgardler** [comment]
Password are generated by the install scripts and output by the ARM template. For more information see the [README](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-scalable-cluster-ubuntu#using-the-created-stack). 

These values can be retrieved from the portal (via the deployment blade) or via the CLI, e.g.:

Retrieve all the outputs in JSON format:

```
az group deployment show --resource-group $MOODLE_RG_NAME --name $MOODLE_DEPLOYMENT_NAME --out json --query *.outputs
```

Retrieve just the database password

```
az group deployment show --resource-group $MOODLE_RG_NAME --name $MOODLE_DEPLOYMENT_NAME --out tsv --query *.outputs.databaseAdminPassword.value
```

Assign the database password to a variable (BASH):

```
MOODLE_DATABASE_DNS="$(az group deployment show --resource-group $MOODLE_RG_NAME --name $MOODLE_DEPLOYMENT_NAME --out tsv --query *.outputs.databaseDNS.value)"
```

I'll add the above examples to the README to make it more useful.

I agree that it would be good to allow users to define the passwords in parameters, I've added that to the backlog, but given the above information I'm going to close this issue. Feel free to reopen if this information does not unblock you.
