### ISSUE TITLE
azuredeploy-parameters.json versus azuredeploy.parameters.json

### ISSUE THREAD

**Issue by jangelfdez** [Azure/azure-quickstart-templates#420]
Hi!

the bot that checks the pull requests looks for a file called azuredeploy-parameters.json but the starter template includes a file called azuredeploy.parameters.json

It should be change to avoid confusion with that.

Regards

**Comment by singhkay** [comment]
Assigning to @bursteg for fixing in the bot. We're leaning towards azuredeploy.parameters.json here unless you or other contributors think there is another convention that is better?

**Comment by singhkay** [comment]
This is resolved, the bot will now check for azuredeploy.parameters.json
