### ISSUE TITLE
Prevent error from redundant deploy: Error: "role assignment already exists"

### ISSUE THREAD

**Issue by johnmehler** [Azure/azure-quickstart-templates#4205]
[Role Assignment template](https://github.com/toddkitta/azure-content/blob/master/articles/resource-manager-template-role.md)

### Issue Details
I was wondering about a technical issue with this template. When you deploy a web app or storage account with an ARM and it already exists, there is no error; the ARM just skips or updates the resource. With role assignments, if you try running it multiple times, you get an error: 

    "code": "RoleAssignmentExists",
    "message": "The role assignment already exists."

Is there a way to make the role assignment only deploy conditionally or to catch that particular error?

### Repro steps (*if necessary, delete otherwise*)
1. Make an ARM with a roleAssignments resource, example below.
2. "type": "Microsoft.Authorization/roleAssignments",
      "name": "[guid(parameters('featureName'), uniqueString(resourceGroup().id, deployment().name))]",
      "apiVersion": "2017-10-01-preview",
      "location": "[resourceGroup().location]",
      "condition": ""
      "properties": {
        "roleDefinitionId": "[concat(subscription().Id, '/providers/Microsoft.Authorization/roleDefinitions/x')]",
        "principalId": "x"
      }
3. Run twice, the second time it runs the role permission should already exist and it outputs an error and stops the build.

**Comment by johnmehler** [comment]
Update: it turns out that the build was only allowing the redundant builds to complete because I was using uniquestring() to create a new GUID every build. By using a GUID that stays static per ARM template, I resolved the issue.

**Comment by sagarkul** [comment]
> Update: it turns out that the build was only allowing the redundant builds to complete because I was using uniquestring() to create a new GUID every build. By using a GUID that stays static per ARM template, I resolved the issue.

can you provide updated resource json.
I am facing same problem.

**Comment by mcambal** [comment]
In my case it was caused by this "[guid(resourceGroup().id, deployment().name)]" due to I use dynamic deployment name. When I changed it just to "[guid(resourceGroup().id)]" everything works as expected
