### ISSUE TITLE
MPI support for SLURM quickstart template

### ISSUE THREAD

**Issue by aculich** [Azure/azure-quickstart-templates#422]
I see that MPI support is listed as a future work item in the [Deploy a Slurm Cluster on Azure](http://blogs.technet.com/b/windowshpc/archive/2015/06/06/deploy-a-slurm-cluster-on-azure.aspx) blog post.

Just wanted to register my interest in this feature for research groups that I am working with.

Thanks,
 Aaron

**Comment by singhkay** [comment]
Adding @YidingZhou to make sure this is captured

**Comment by YidingZhou** [comment]
@aculich Sure. When you asked about MPI, do you mean RDMA network or just MPI library?
You can deploy MPI library by yourself. 
Currently Ubuntu image doesn't have RDMA driver yet so it'll take some time to get a SLURM cluster that run on IB network.

**Comment by aculich** [comment]
@YidingZhou Both would be helpful:

1) A ready-to-go Ubuntu image on Azure with SLURM+MPI already built-in and configured would be helpful as a first step to get people off of an on-premise HPC environment into the cloud **without changing their code** is useful to a wide audience even if it isn't the highest performance (optimizing people time, not compute time). This is something that may be incorporated into our [Berkeley Common Environment (BCE)](http://bce.berkeley.edu/) image that we would like to deploy on Azure; I've opened an item in the [BCE issue tracker](https://github.com/ucberkeley/bce) for that.

2) When the RDMA driver + IB network on Azure is ready it will be really great to have step 1 already in place to switch people to a higher performance environment.
