### ISSUE TITLE
GEN-UNIQUE labels are not getting replaced

### ISSUE THREAD

**Issue by deepakbenny** [Azure/azure-quickstart-templates#4247]
apache2-on-ubuntu-vm - https://github.com/Azure/azure-quickstart-templates/tree/master/apache2-on-ubuntu-vm

### Issue Details

GEN-UNIQUE labels are not getting rendered.
azure-cli (2.0.26)

### Repro steps
1. `az group deployment create --resource-group examplegroup --template-file apache-ubuntu.json  --parameters azuredeploy.parameters.json`
2.
```
...
msrest.http_logger : Response content:
msrest.http_logger : b'{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. 
.....
  "error": {
    "code": "AccountNameInvalid",
    "message": "gen-unique-8 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only."
  }
}
```

**Comment by cocallaw** [comment]
@deepakbenny the GEN-UNIQUE values used in ARM templates are placeholders only, they are used to explicitly tell the Travis CI to generate a unique value when testing/ validating changes in PR's. (https://github.com/Azure/azure-quickstart-templates/wiki/defaultValue-vs.-azuredeploy.parameters.json-vs.-GEN-UNIQUE) When deploying for personal use, those values need to be replaces with unique values to your deployment. 

If you would like a unique string value generate when you deploy an ARM template you can use uniqueString, which will make hash string based on the what you hand into it in the template. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-string#uniquestring 

If this answers your issue, please close it out to help keep things clean and current. If you have any further question please let me know.
Thanks!

**Comment by deepakbenny** [comment]
got it, thanks!
