### ISSUE TITLE
unable to locate blade for docker-simple-on-ubuntu template

### ISSUE THREAD

**Issue by aculich** [Azure/azure-quickstart-templates#429]
The [docker-simple-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/docker-simple-on-ubuntu) template fails with this error message:

```
Unable to locate blade '##NOT_SPECIFIED##' in extension definition. Search path:'[0]HubsExtension-[1]##NOT_SPECIFIED##'.
```

**Comment by tfnaylor** [comment]
Unfortunately I cannot solve your specific problem, but I can tell you that I have seen this error in the past and it has had nothing to do with the deployment itself - it seems to be a bug in the Azure portal. In my case there was always an actual error occurring in the template deployment process and you have to go through the resource group logs to find what happened.

Hope this helps.

**Comment by singhkay** [comment]
Adding @tabrezm from the Portal team to see if there are any logs needed or if it's a known issue

**Comment by tabrezm** [comment]
@flanakin would need to weight in on this. The path for the part indicates that this is in Hubs.

**Comment by singhkay** [comment]
Closing as I was able to deploy the template and didn't repro this.
