### ISSUE TITLE
The bot that checks pull requests gives erroneous messages

### ISSUE THREAD

**Issue by rgardler** [Azure/azure-quickstart-templates#430]
If someone improves an existing template and issues a pull request the bot will respond:

"The following issues were detected in this pull request:

Template: CentOS-2nics-lb-cluster
•The 'githubUsername' property in metadata.json does not match the name of the author of the pull request (aculich)."

This is problematic in many ways. Firstly, the person issuing the pull request is not the original author and so the metadata property will be difference.

Secondly, providing credit for the original contributor, but not subsequent contributors misses the point of community contributions.

Finally, what if a subsequent contributor improves the template significantly and, as a result, the new version barely resembles the original. Do we change the author at this point? If so when do we change it and what does that say about the original contributor?

What's the solution?

Personally I would use Git history to identify authors but an alternative approach would be to allow multiple values in the metadata file.

Thoughts?

**Comment by singhkay** [comment]
I'm open to both solutions but we should also let others from the community chime on what they prefer. 
@ahmetalpbalkan @johngossman

**Comment by ahmetalpbalkan** [comment]
Azure documentation solves this problem by listing the initial author (you can use the file in the metadata) and contributors just by looking at commit history on that file to determine usernames

However all changes might not be about the template itself*, so maybe another field `"contributors"` in metadata.json can let people add themselves there.

*: for instance I recently fixed json indentation on all the repo, if you look at git logs I'm actually a contributor whereas I probably should not be listed as one. Therefore I think users adding themselves to the metadata makes more sense to me.

**Comment by singhkay** [comment]
@ahmetalpbalkan I think most folks new to Github don't immediately know how to discover the git history to discover who the author is. 

I was discussing with @bursteg this and we may not need a metadata file in the long term. Guy's team is working on a solution that can render YAML in markdown. So we'd be able to put the content of metadata files in the readmes so it's immediately rendered when you visit a 

In the meantime I think a contributor tag in the metadata file with comma separated values of usernames makes sense?

**Comment by ahmetalpbalkan** [comment]
> In the meantime I think a contributor tag in the metadata file with comma separated values of usernames makes sense?

Yes.

**Comment by bingosummer** [comment]
@singhkay How it progress? I think a contributor tag makes sense.

**Comment by singhkay** [comment]
@bingosummer The first issue has been fixed. Now the bot does not complain about another user editing the template. The other feature for contributor tag is currently in the @bursteg's backlog.

**Comment by rgardler** [comment]
Closing as we have confirmation that the issue is partially fixed and the remaining fix is on the backlog.
