### ISSUE TITLE
101-simple-linux-vm : Ubuntu 14.10 not available (new)

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#433]
Today my templates, which are in part based on the quick start template mentioned in the title above, started to fail with Azure complaining that Ubuntu 14.10 couldn't be found. The quick start template also fails with the same message:

{"error":{"code":"NotFound","target":"imageReference","message":"The platform image 'Canonical:UbuntuServer:14.10' is not available. Verify that all fields in the storage profile are correct."}}

Does anyone know where there is a catalog of all available resources and their current configuration parameters? This has happened to me before with a chef extension and I got lucky finding the correct version number.

**Comment by tfnaylor** [comment]
14.04.2-LTS still works so it seems to be just the 14.10 version. I would recommend removing 14.10 as the default since this will really trip people up.

**Comment by singhkay** [comment]
Thanks for the report @tfnaylor!! Ubuntu 14.10 went EOL on 7/23 (https://lists.ubuntu.com/archives/ubuntu-announce/2015-July/000197.html). I've purged this version from the repo.
