### ISSUE TITLE
The template fails to deploy in INDIA regions

### ISSUE THREAD

**Issue by ddexter26** [Azure/azure-quickstart-templates#4335]
{
  "error": {
    "code": "InvalidParameter",
    "target": "vmSize",
    "message": "The requested VM size Standard_D4 is not available in the current region. The sizes available in the current region are: Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_

**Comment by cocallaw** [comment]
@ddexter26 What template where you deploying that failed? 

The issue appears to be that the default VM SKU used by whatever template is/was not available in that region at that time. By updating the vmSize parameter to a VM SKU that is available in that region, you should be able to deploy without issue.

**Comment by ddexter26** [comment]
I don't remember, that was 3 months ago, but thanks. Now I check availability of the SKU before deploying.

I think the reason I opened this case was to have the owner of the template to also limit the regions as per the availability. Pre validation do not check SKU availability in selected region and then Template fails while creating the VM. If I Could find the template I'll repost, but this is good to close.

**Comment by ddexter26** [comment]
https://github.com/Azure/azure-quickstart-templates/blob/master/rds-deployment/azuredeploy.json
