### ISSUE TITLE
Can not access outside of VM

### ISSUE THREAD

**Issue by horvaticKarmak** [Azure/azure-quickstart-templates#4501]
When going to the 9000 port of the vm DNS name I get a connect refused

**Comment by cloudmelon** [comment]
This template deploys Linux machine which is available to be accessed by serial console currently in preview, with you defined administrator account and password, you can access it. Otherwise, it is accessible by SSH as well.

**Comment by horvaticKarmak** [comment]
This template deploys a Windows 2012 R2 VM on azure. It is configured to use port 443 instead of 9000. Doc needs to be updated
