### ISSUE TITLE
Input endpoints via template?

### ISSUE THREAD

**Issue by 4deeptech** [Azure/azure-quickstart-templates#452]
I created a VM using the portal and configured some endpoints to expose some special ports to the outside.  I wanted to see what the configuration looked like using Azure Resource Explorer(Preview) and it shows input endpoints under the networkProfile of the VM.  How can I set up these endpoints for a VM using a resource template?  I didn't see anything in the schema definitions about it.

excerpt from Resource Explorer (resources.azure.com) for my VM:

"networkProfile": {
      "inputEndpoints": [
        {
          "endpointName": "ESAdmin",
          "privatePort": 2113,
          "publicPort": 2113,
          "protocol": "tcp",
          "enableDirectServerReturn": false
        },
        {
          "endpointName": "ESTCP",
          "privatePort": 1113,
          "publicPort": 1113,
          "protocol": "tcp",
          "enableDirectServerReturn": false
        },
        {
          "endpointName": "Remote Desktop",
          "privatePort": 3389,
          "publicPort": 3389,
          "protocol": "tcp",
          "enableDirectServerReturn": false
        },
        {
          "endpointName": "WinRM",
          "privatePort": 5986,
          "publicPort": 5986,
          "protocol": "tcp",
          "enableDirectServerReturn": false
        }
      ]
}

**Comment by singhkay** [comment]
@4deeptech Is this a Microsoft.ClassicCompute or v1 VM? Network profile for Microsoft.Compute VMs doesn't have endpoints.

**Comment by 4deeptech** [comment]
Looking in the new portal, the virtual machine says (classic) in parenthesis under the name on the VM 'blade'.  It's a Standard A2 VM created a few months back.  Under Settings it has an item called Endpoints where I manually created public ports mapped to the private port.  I wanted to know how I could template this out for a new VM.  Doesn't do me much good to script only part of it if I have to manually do a few pieces every time.  I also really need to be able to set up Storage Spaces on it across some of the VM disks using Desired State Configuration too...I guess...that is next hurdle.

**Comment by singhkay** [comment]
@4deeptech These templates can't be used to work with classic VMs. For adding endpoints to it, PS or CLi is your best bet
