### ISSUE TITLE
Unable to deploy SonarQube - Validation error

### ISSUE THREAD

**Issue by felipecruz91** [Azure/azure-quickstart-templates#4574]
[sonarqube-azuresql](https://github.com/Azure/azure-quickstart-templates/tree/master/sonarqube-azuresql)

### Issue Details
I am trying to deploy a SonarQube VM with Azure SQL DB but I get an error in the Azure portal.

### Repro steps
1. Click on the "Deploy to Azure" button located in the README.md file.
2. An Azure portal window will appear. Populate the fields that appear in the Azure quickstart template.
3. Click on "Purchase"

Please see below the validation error:

{"telemetryId":"acdf70c5-e478-4159-99df-b7b10a62ecec","bladeInstanceId":"Blade_e4462c916f604d798254dda74a586e5d_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidTemplateDeployment","message":"The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '6001db1f-c047-4fd8-9c7a-d895404b8e4f'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.","details":[{"code":"InvalidParameter","target":"imageReference","message":"The following list of images referenced from the deployment template are not found: Publisher: Microsoft, Offer: JDK, Sku: JDK_8, Version: latest. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images.","innererror":{"internalErrorCode":"ReferencedImagesNotFound"}}]}

**Comment by StephanBis** [comment]
Has there been any progress regarding this issue?

**Comment by felipecruz91** [comment]
Haven't heard from Microsoft yet. As soon as I receive an answer back I will post it here ;)

**Comment by felipecruz91** [comment]
I've received an email with the updated [template ](https://drive.google.com/file/d/1WCRVc1yphrJOvHzNc3HAq1UXqkWEW26K/view?usp=sharing) and the following instructions:

1. Deploy the attached template by using PowerShell to do so ([Link](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy)) 
a. New-AzureRmResourceGroup -Name SonarQubeSample-RS01 -Location "South Central US"
b. New-AzureRmResourceGroupDeployment -Name InitialDeployment -ResourceGroupName SonarQubeSample-RS01 -TemplateFile ".\azuredeploy.json"
2. Provide the needed parameters for the template as described in GitHub **README** file 
a. We added a new parameter for the virtualMachineSize which currently default to Standard_D2_v3
b. However, you can choose any other size [https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes)
3. Once the deployment finished 
a. Please RDP to the machine 
b. Download Java JDK from Oracle http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html 
c. Install JDK (follow the wizard)
d. Restart the SonarQube Service by Open “Services” and restart the server normally 
4. Browse to public DNS for SonarQube VM using HTTPs

Hope this makes sense.
