### ISSUE TITLE
Virtual Network Gateway Template Parameters Not working

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-quickstart-templates#464]
The parameters in this template https://github.com/Azure/azure-quickstart-templates/tree/master/arm-asm-s2s need to nest the `description` field within a `metadata` object for each parameter. Otherwise the deployments via the `deploy to azure` button as well as the xplat-cli fail.

**Comment by singhkay** [comment]
Awesome! Thanks for submitting the fix @sedouard!
