### ISSUE TITLE
How can I get resource loops to start with a specific number?

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#475]
Is it possible to have them begin with "01" instead of "0"? I need to keep machine names the same number of characters but once I have more than 9, it goes up by a digit.

**Comment by singhkay** [comment]
@aarsan Can you try copyIndex(01) and see if it works. A use case is shown here but it's 4 instead of 04 https://github.com/Azure/azure-quickstart-templates/blob/master/docker-swarm-cluster/azuredeploy.json#L241 

cc: @rjmax @clamanna

**Comment by rjmax** [comment]
If you would like to pad, you can use our padLeft function. https://github.com/rjmax/ArmExamples/blob/master/padLeftSample.json

**Comment by aarsan** [comment]
Worked like a charm. Thanks!
