### ISSUE TITLE
how do you find out what APIs are supported by each provider?

### ISSUE THREAD

**Issue by mkliu** [Azure/azure-quickstart-templates#483]
I only got this link:
https://github.com/Azure/azure-resource-manager-schemas/

but for example i don't find key vault there.

**Comment by tfnaylor** [comment]
This is a common complaint and one I have made to Microsoft during a local (Southern California) Azure users group event dedicated to resource manager. The answer I got was that the documentation is lagging somewhat behind on this feature but that they are working on it. I got the sense that they understand that a comprehensive guide to all available resources and how to use them is required. Hopefully we will see it soon...

**Comment by singhkay** [comment]
@mkliu Take a look here https://msdn.microsoft.com/en-us/library/azure/dn948464.aspx

**Comment by mkliu** [comment]
@singhkay but that's only the restful API. Can I assume everything listed there (variable names etc) is supported in ARM?

**Comment by singhkay** [comment]
@mkliu Yes everything inside the properties bag of a REST API or a template resource is the same. For example compare creating a NIC in a template [here](https://github.com/Azure/azure-quickstart-templates/blob/master/101-networkinterface-with-publicip-vnet/azuredeploy.json#L100) with it's [REST API](https://msdn.microsoft.com/en-us/library/azure/mt163668.aspx)

**Comment by mkliu** [comment]
@singhkay thanks. Some are still missing like keyvault, 
If I create keyvault in the normal way and see it here: http://resources.azure.com. Can I assume the all the parameters are supported too?

**Comment by singhkay** [comment]
@mkliu Ya, I'm not sure why Key Vault is missing. I'll check with that team. Yes, Keyvault should show on ARM explorer. What parameters do you mean? Do you mean the ones that show up in GET on ARM explorer? Some of them might not be required for a PUT I think. If you are looking to create a Key Vault through a template look here - https://github.com/Azure/azure-quickstart-templates/tree/master/101-create-key-vault

Do note that you won't be able to manage the secrets and keys through templates as those are on the data layer rather than management layer. Similar to Storage Accounts and blob, tables etc.

**Comment by mkliu** [comment]
@singhkay meaning I can't create a secrete via ARM? I basically want to deploy a website from github, create sql server, put sql connection string to keyvault pass the info back to the website.

If I understand correctly, you are saying I can't put secretes via ARM? What's the recommended approach then together with ARM? I'm thinking of invoking ARM via Azure node.js SDK and then put the keys in node.js.

**Comment by singhkay** [comment]
@mkliu Right, you can't create secrets or keys via ARM, only Key Vaults themselves. This is same as only being able to create storage accounts and not blobs, tables via ARM.

Yes the node CLI or PS cmdlets are the easiest way to work with keys and secrets

    azure keyvault keyvault secret set [--vault-name] <vault-name> [--secret-name] <secret-name> [--value] <secret-value> [options]

**Comment by dvkwong** [comment]
Any update on getting more schema info?
