### ISSUE TITLE
How to deploy VMs in Existing Virtual Network without creating new one?

### ISSUE THREAD

**Issue by iamshital** [Azure/azure-quickstart-templates#497]
I have a preconfigured virtual network in azure and it is already connected to on premise network via dynamic gateway. I can deploy virtual machines inside VNET using powershell commands.

Equivalent PS command : 
New-AzureVM -ServiceName VNETVMS -VMs ( ( New-AzureVMConfig -Name VNETVMS-role-0 -InstanceSize Small -ImageName CENTOS67-WA2014-PREPARED-20150812 | Add-AzureProvisioningConfig -Linux -LinuxUser test -Password "L---e" | Set-AzureSubnet -SubnetNames Subnet2 |  Set-AzureEndpoint -Name "SSH" -LocalPort "22" -PublicPort "22" -Protocol "tcp" | Add-AzureEndpoint -Name "TCPtest" -LocalPort "750" -PublicPort "750" -Protocol "tcp" | Add-AzureEndpoint -Name "UDPtest" -LocalPort "990" -PublicPort "990" -Protocol "udp"  ) , ( New-AzureVMConfig -Name VNETVMS-role-1 -InstanceSize Small -ImageName CENTOS67-WA2014-PREPARED-20150812 | Add-AzureProvisioningConfig -Linux -LinuxUser test -Password "L---e" -SSHPublicKeys | Set-AzureSubnet -SubnetNames Subnet1 |  Set-AzureEndpoint -Name "SSH" -LocalPort "22" -PublicPort "222" -Protocol "tcp" | Add-AzureEndpoint -Name "TCPtest" -LocalPort "2750" -PublicPort "2750" -Protocol "tcp" | Add-AzureEndpoint -Name "UDPtest" -LocalPort "2990" -PublicPort "2990" -Protocol "udp"  ) )  -VNetName AzureDTAP02Net -DnsSettings (New-AzureDns -Name "DNSsettings" -IPAddress "192.168.3.120")

This command deploys two VMs in "AzureDTAP02Net" Virtual Network. How do I achieve this using Azure Resource Manager?

**Comment by singhkay** [comment]
Take a look at Ryan's neworExisting pattern example https://github.com/rjmax/ArmExamples/blob/master/NewOrExistingTemplate.json 

cc: @rjmax

**Comment by pdiniz13** [comment]
How do we incorporate the newOrExisting template into other azure templates that we want to deploy in an existing Virtual network

**Comment by cyl3392207** [comment]
The way to set up a VM in existing vNET is to hook up the nic to a existing subnet. You can do this in template. 

If you just need to deploy resources to existing network, then you don't need to use new or existing pattern. The pattern is used when you want to have a knob to control whether you want to use a new vNet or existing vNet.
