### ISSUE TITLE
DNS name error launching VM with template 201-vm-specialized-vhd-new-or-existing-vnet and 201-vm-generalized-vhd-new-or-existing-vnet

### ISSUE THREAD

**Issue by lyan-git** [Azure/azure-quickstart-templates#4970]
[template 201-vm-specialized-vhd-new-or-existing-vnet](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-specialized-vhd-new-or-existing-vnet)

### Issue Details
Got DNS name error when launching VM with template 201-vm-specialized-vhd-new-or-existing-vnet.
"Domain name labels must be all lower case, begin with a character, end in a character or number, and must be between 1 and 63 characters:
concat('vm-', uniqueString(resourceGroup().id))]"

### Repro steps (*if necessary, delete otherwise*)
1. Click Deploy to Azure on page https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-specialized-vhd-new-or-existing-vnet or 201-vm-generalized-vhd-new-or-existing-vnet
2. Fill up Resource Group, OS Disk Vhd uri, user name and password
3. Click agree to the term
4. Click purchase. Get the above error. Syntax of the above field looks good, but not sure why get error.

**Comment by bmoore-msft** [comment]
The template is fine - the portal blade that handles deployment is incorrectly validating the param... best option is to file a support ticket with the portal.
