### ISSUE TITLE
iFrame not working on Azure webapp

### ISSUE THREAD

**Issue by erwindemoel** [Azure/azure-quickstart-templates#5005]
Hi,

I wasn't sure where to post this, so I'm trying it here. We're trying to create an iFrame that links to an external page and hosting it under an Azure App Service.

You can see the page [here](http://www.meterinsight.com/test/).

When I open the page in Safari or Google Chrome on my iMac, it doesn't show the contents of the testpage www.w3schools.com like it was supposed to. Can anyone tell me why this simple sample is not working?

**Comment by John-Blair** [comment]
Hi @erwindemoel , Did you find out the reason? I have the same problem. Thanks.
