### ISSUE TITLE
bosh-setup - Lost on deployment

### ISSUE THREAD

**Issue by libby2cm** [Azure/azure-quickstart-templates#503]
Been trying to deploy azurebosh via the arm template, per the guide that is floating around, but apparently something has changed and it does not work the same. After deploying the template, it appears to be doing a regular bosh deployment vs using microbosh. After the rg is deployed, I install npm, azure cli, etc., & setup the SPN & such. I then update the ~/bosh.yml file to reflect subscription ID, app id, etc., then kick off the deploy_bosh.sh installer, which appears to succeed, but then because the guide directions are skewed, I don't know where the stemcell is that is to be uploaded.

Is the project in a state of flux now or something? Should I use the manual process?

**Comment by singhkay** [comment]
@libby2cm Are you using this template? https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup. 

I'm not familiar with bosh but I'll try to contact @bingosummer who might know this.

**Comment by bingosummer** [comment]
Thanks @singhkay for passing on this issue.

@libby2cm Thanks for you feedback.
The bosh-setup template is to setup bosh-init for Cloud Foundry on Azure Preview 2 and microbosh-setup is deprecated which is for Preview version. You can follow the guide  https://github.com/Azure/bosh-azure-cpi-release/blob/master/docs/template-guide.md.

You can find resource_pools.name[vms].stemcell.url in bosh.yml. That is the uri of the stemcell to replace STEMCELL-FOR-AZURE-URL in below command:
bosh upload stemcell STEMCELL-FOR-AZURE-URL

Any question or any uncomfortable usage about the template, please feel free to contact me. My email is binxi@microsoft.com.

**Comment by libby2cm** [comment]
Ah, OK.. figured I missed something somewhere!  I will email you, as I have a few more questions.  Thanks to all!

**Comment by bingosummer** [comment]
Except the email, you can also file an issue at https://github.com/Azure/bosh-azure-cpi-release/issues.

**Comment by libby2cm** [comment]
I starred it.. thanks!
