### ISSUE TITLE
Broken link in 101-vm-full-disk-encrypted-rhel to AzureDiskEncryptionPreRequisiteSetup.ps1.

### ISSUE THREAD

**Issue by out0xb2** [Azure/azure-quickstart-templates#5053]
[101-vm-full-disk-encrypted-rhel](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-full-disk-encrypted-rhel)

### Issue Details
Broken link.  The Prerequisites section has a broken link to AzureDiskEncryptionPreRequisiteSetup.ps1.
https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1 returns 404

### Repro steps (*if necessary, delete otherwise*)
1.  Start from https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-full-disk-encrypted-rhel
2.  Click on AzureDiskEncryptionPreRequisiteSetup.ps1
3.  Observe 404

**Comment by cmendible** [comment]
Hi @out0xb2  can you verify that everything is ok and close the issue?

**Comment by out0xb2** [comment]
Link fixed, thanks!
