### ISSUE TITLE
DomainJoin DSC Extension takes a really long time.

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#507]
Enabling the Azure Chef extension (while pointing to this Github account) takes upwards of 20 minutes for a machine to join the domain. Is there a known issue with the script?

**Comment by singhkay** [comment]
@aarsan Shouldn't be an issue. Usually scripts take a long time if the configuration they are trying to achieve takes a bit of time. The title mentions DSC extension but your post mentions Chef extension. Can you confirm what scenario you're trying to accomplish?
