### ISSUE TITLE
Can not deploy 201-vm-domain-join with New-AzureResourcegroup cmdlet

### ISSUE THREAD

**Issue by robplank** [Azure/azure-quickstart-templates#519]
When attempting to deploy the example 201-vm-domain-join or any template with a DSC Configuration line 'ConfigurationFunction' the New-AzureResourceGroup and New-AzureResourcegroupDeployment cmdlets return a terminating exception. 

if you use the preview portal's Custom deployment, no exceptions or errors occur at deployment time.

![image](https://cloud.githubusercontent.com/assets/12474044/9460022/9cc0e0fa-4ac7-11e5-9ace-d71d8025604e.png)

<B>Environment</B>
Windows 8.1
Windows powershell version 5.0.10105.0 
Azure Powershell module 0.9.7

**Comment by singhkay** [comment]
@robplank Can you verify what line 248 looks like in your local template file?

**Comment by robplank** [comment]
line 248:   "ConfigurationFunction": "CreateADPDC.ps1\CreateADPDC",

line 391:  "ConfigurationFunction": "Configuration.ps1\DomainJoin",

either of these lines will cause the powershell cmdlet to throw an exception

**Comment by singhkay** [comment]
@robplank Can you pull in the latest changes from master? This was fixed in #499 

Line 248 and 391 have \\ now which should resolve the above error
https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-domain-join/azuredeploy.json#L248

**Comment by robplank** [comment]
thanks!
