### ISSUE TITLE
Community Ask: How should we rename/move templates? 

### ISSUE THREAD

**Issue by singhkay** [Azure/azure-quickstart-templates#522]
Hi Community,

We're excited to see tremendous excitement regarding templates from you :) We want to make sure this repo continues to drive value for you and your voice is heard when we make changes that will affect the way you consume this resource. 

Over the past few weeks, we've been thinking about organizing the repo so it provides a better experience for those just getting started with templates. The intended learning pattern is to go through 101->201->Application templates however we've seen some templates that could be served better if they had a 101 or 201 prefix (e.g. windows-vm-push-certificate, windows-vm-custom-script). We realize that you might have taken a dependency on the URLs for these template folders and by renaming we would break you, leading to a 404. This brings me to our proposal for balancing our needs for organizing and your bookmarked URLs leading you to the right place. The proposed process will serve for any future renaming needs. 

1.	Create a new folder with the preferred name
2.	Move over all the files from the old folder to the new folder
3.	Create a readme.md file in the old folder with a URL to the new location
4.	Remove the old folder after 60 days

Please let us know your thoughts on the above process or any other solutions.

cc: @rgardler @johngossman

**Comment by rgardler** [comment]
Broken URLs in the GitHub repo are tolerable (history will help people find the new URL). It's a different story for website URLs. Since related here appear on Microsoft.com will we be able to create redirects there?

**Comment by desek** [comment]
I don't see any problem with the proposed method.

From a parctical point of view I always search based on resource types and specific keywords (ie. template functions and/or templateLink).
I pay very little attention to the folder name compared to the readme found based on the search.

**Comment by scottzilla** [comment]
I think the most frustrating thing for me is trying to find open/closed issues / PRs.

Since ALL of the templates are in the same repo, all issues / PRs for any of the templates show up in the same place, even though I might be looking for something specific to just one of the templates.

**Comment by singhkay** [comment]
@rgardler Yes, we should be able to remap the ACOM template page to the correct folder. 

@desek Thanks!

@scottzilla Are you asking trying to find issues/PR that affected a particular template? Have you instead tried to use the git history in the file of the template you want to get more hisotrical information?

**Comment by slapointe** [comment]
The proposed procedure for rename is OK to me but we'll need to constantly take a look here to see if the folder(s) we depends on has moved. Can you setup a notification of some sort (RSS or something else) that we could subscribe to? When a rename of a folder is performed, a process would update a file or use another mechanism to trigger a notification that we can consume and be notified as soon as it happen, this way we could be proactive instead of reactive for our dependencies.

I link one template here from my blog and was thinking about doing this more and more in the future. No problem having to go back and update my articles but I need a notification mechanism instead of having to check each day/week if a link I use is broken.

**Comment by singhkay** [comment]
@slapointe I'm not sure if such a notification mechanism exists. How about if we use the releases tab (https://github.com/Azure/azure-quickstart-templates/releases) on the root of the repo to maintain a table of movement of templates? Something like (Old URL -> New URL). 

Ideally, we want the users to use the Azure.com searchable index URLs for bookmarking templates and not have to take a dependency on direct Github folder URLs to avoid these issues.
