### ISSUE TITLE
"sql-server-2014-alwayson-existing-vnet-and-ad" template not working (  'storageAccountType' in the parameters file are not valid )

### ISSUE THREAD

**Issue by kjk129** [Azure/azure-quickstart-templates#5234]
[sql-server-2014-alwayson-existing-vnet-and-ad](Template link goes here)

### Issue Details

I attempted to deploy this template and it appears that the recent changes in master may have broken the template.  This error now occurs:

Code    : InvalidTemplate
Message : Deployment template validation failed: 'The template parameters 'storageAccountType' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only 
          supported parameters for this template are 'namePrefix, domainName, dnsServerName, adminUsername, adminPassword, sqlServerServiceAccountUserName, sqlServerServiceAccountPassword, diskType, nicSubnetUri, lbSubnetUri, sqlLBIPAddress, 
          sqlVMSize, sqlWitnessVMSize, _artifactsLocation, _artifactsLocationSasToken, windowsImagePublisher, windowsImageOffer, windowsImageSKU, windowsImageVersion, location'. Please see https://aka.ms/arm-deploy/#parameter-file for usage 
          details.'
  
I'm also receiving this error when using the  Test-AzureRmResourceGroupDeployment cmdlet.  My prefix is simply "test" so I'm not sure why it is preventing it.  If I remove the maxLength line from the parameter in azuredeploy.json, then it gets past this error and on to the one reported just above.

Message : Deployment template validation failed: 'The provided value for the template parameter 'namePrefix' at line '7' and column '23' is not valid. Length of the value should be less than or equal to '8'. Please see ....

**Comment by BluedeepGit** [comment]
There is a typo at line 156 of azuredeploy.json

must substitute "storageAccountType" with "diskType"

**Comment by kjk129** [comment]
Thank you for the response and indeed that was the problem!!   I am surprised that a validation error like that was pulled into the master branch.   On another note, I also get another validation error that doesn't add up.   I pass in "test" into the namePrefix parameter and get this error.   If I remove the maxLength validation line, it validates successfully.

Deployment template validation failed: 'The provided value for the template parameter 'namePrefix' at line '7' and column '23' is not valid. Length of the value should be less than or equal to '8'.

    "namePrefix": {
      "type": "string",
      "maxLength": 8,
      "metadata": {
        "description": "Naming prefix for each new resource created. 8-char max, lowercase alphanumeric"
      }
