### ISSUE TITLE
Why parameters connectionName and sharedKey in arm-asm-s2s template

### ISSUE THREAD

**Issue by tjmklaver** [Azure/azure-quickstart-templates#528]
In the arm-asm-s2s template (https://github.com/Azure/azure-quickstart-templates/tree/master/arm-asm-s2s) there are two parameters defined (connectionName, sharedKey). Why are these parameters defined in the template, because these parameters are not used in the resource section for creating the required resources. Any explanation would be great.

**Comment by singhkay** [comment]
Adding @telmosampaio who wrote the template for clarification

**Comment by telmosampaio** [comment]
Good question. The initial idea behind the template was to use them, but we decided to take it out and never changed the parameters list. You can ignore them for now. I will take them out, test, and republish.

**Comment by singhkay** [comment]
Thanks @telmosampaio please reference this issue in the PR. Closing for now.
