### ISSUE TITLE
AKS supported versions different from list in a template

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-quickstart-templates#5290]
AKS supported versions different from list in a template
https://github.com/Azure/azure-quickstart-templates/blob/master/101-aks/azuredeploy.json

Command:
az aks get-versions --location "north europe" --query 'orchestrators[].orchestratorVersion'
returned
[
  "1.7.15",
  "1.7.16",
  "1.8.14",
  "1.8.15",
  "1.9.9",
  "1.9.10",
  "1.10.7",
  "1.10.8",
  "1.11.2",
  "1.11.3"
]
In another hand in a template dropdown we see 

 "kubernetesVersion": {
      "type": "string",
      "defaultValue": "1.9.6",
      "allowedValues": [
        "1.7.7",
        "1.8.1",
        "1.9.1",
        "1.9.6"
      ],
      "metadata": {
        "description": "The version of Kubernetes."
      }
    }

**Comment by SeanEGray** [comment]
I'm happy to throw a PR in for this as it seems sensible.
This is something that's likely to be constantly changing, though, so there may need to be discussion around how this is kept up to date in the long term.
