### ISSUE TITLE
101-container-registry/azuredeploy.json referencing preview api

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-quickstart-templates#5291]
[101-container-registry/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/blob/f605b4b13a6d372d9f40142323e128b5e5e58440/101-container-registry/azuredeploy.json)

### Issue Details
https://github.com/Azure/azure-quickstart-templates/blob/f605b4b13a6d372d9f40142323e128b5e5e58440/101-container-registry/azuredeploy.json

Template using preview api with classic SKU, that will be depricated during next 6 months.

Based on official documentation, https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus Azure Container Registry support 4 SKU types (Basic, Standard, or Premium and Classic)
"1 The Classic SKU will be deprecated in March 2019. Use Basic, Standard, or Premium for all new container registries." (C)

Could you update template with GA version of provider, for example 

    {
      "name": "[parameters('registryName')]",
      "type": "Microsoft.ContainerRegistry/registries",
      "location": "[resourceGroup().location]",
      "apiVersion": "2017-10-01",
      "sku": {
        "name": "[parameters('registrySku')]"
      },
      "properties": {
        "adminUserEnabled": "[parameters('adminUserEnabled')]"
      },
      "tags": {
        "displayName": "Container Registry"
      }
    }

**Comment by jsturtevant** [comment]
Anyone working on this?  I am working on an example for replication and could make this update as well since I am in there :-)
