### ISSUE TITLE
Should downscale work?

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#530]
My template uses the copy function to create a variable number of VM and Nic's. I have noticed that upscaling works perfectly - if I redeploy with a new number (parameter) of nodes more get added. If I try to reduce the number, however, nothing gets removed. Is this the intended behavior?

**Comment by singhkay** [comment]
@tfnaylor Don't think this is a supported scenario. @rjmax can confirm

**Comment by Nepomuceno** [comment]
It you deploy with the complete option instead of incremental than you can scale down.

**Comment by tfnaylor** [comment]
I tried this using the recently (Aug 18) Resource Manager library and it worked perfectly. Thanks for the feedback.

**Comment by aarsan** [comment]
So you're saying if you deployed 10 servers (using copy count) in an ARM template, then modified that to 20 and redeployed, it will up the count to 20. Then, if you change your mode to complete and modify the count back to 10, it will remove 10 servers? Which servers will it remove? Does it remove them or destroy everything and redeploy 10 fresh servers?

**Comment by tfnaylor** [comment]
Based on my own personal experience, taking into account your scenario as described, the 10 newest servers (as well as their NIC's and associations with load balancer, etc.) will be removed. The first 10 will be unaffected by this operation and will remain running throughout.

**Comment by aarsan** [comment]
If that works, that is amazing. I will have to test that out. thanks!

**Comment by tfnaylor** [comment]
Yes, I was amazed as well. My scenario is particularly complicated because I also use the Linux Chef Client on each of my nodes. I was concerned that there would be some wonky effects on the Chef clients on the untouched nodes but this just didn't happen. 
BTW: In my case just leaving the deployment mode at "complete" seems to be the best approach  - no need to switch back and forth. The original deployment works fine using this setting as well.
Enjoy!

**Comment by singhkay** [comment]
Nice find guys! I thought this hadn't been implemented yet. Adding @rjmax and @clamanna to see if there is public documentation around this.

**Comment by rjmax** [comment]
The behavior for copy:{} is documented.  

We have documented the complete deployment mode in our REST API documentation, but haven't yet documented it for PowerShell or CLI because of the "risk" of accidentally deleting resources through a full deployment.  

We hope to add a feature which will "preview" what resources would be deleted before we run the deployment, but haven't implemented it yet.  

What are your thoughts on publicly documenting PS and CLI prior to adding the "what-if" protection/validation?

**Comment by madhana** [comment]
one thing i wonder is whether the "scale down" operation is VM availability aware. That is the approach described here i think will always remove the last "n" newly added resources, which is not always the right thing to do from an VM availability point of view. This is where VM Scale Sets implements this sort of scale down without compromising on VM availability - where in a scale down action would remove those VMs that (with best effort) will not impact the availability of the entire VMSS.
