### ISSUE TITLE
Error while deploying Create Cluster extension in sql-server alwayson cluster template

### ISSUE THREAD

**Issue by akashm31** [Azure/azure-quickstart-templates#541]
Gives the following error
statusMessage:{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CreateCluster'. Error message: \"DSC Configuration completed with error(s).\"."}]}}
Any hints ?

**Comment by singhkay** [comment]
I believe this will be fixed by this PR #542 

Adding @simongdavies to make sure

**Comment by simongdavies** [comment]
yes it does I updated the PR
