### ISSUE TITLE
201-web-app-sql-database: 'Subscription '' does not have the server 'myserver'.'

### ISSUE THREAD

**Issue by pascalberger** [Azure/azure-quickstart-templates#546]
I tried running the [201-web-app-sql-database](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-web-app-sql-database/azuredeploy.json) template using the following parameters:

    siteName: mySite
    hostingPlanName: myPlan
    siteLocation: West Europe
    serverName: myserver
    serverLocation: West Europe
    databaseName: mydatabase

I created a new resource group MyResourceGroup which I used for the deployment. Deployment failed with the following error:

    New-AzureResourceGroupDeployment : 15:17:22 - Resource Microsoft.Sql/servers 'myserver' failed with message
   'Subscription '' does not have the server 'myserver'.'
    At line:1 char:1
    + New-AzureResourceGroupDeployment -Name TestDeployment -ResourceGroupName MyRe ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroupDeployment], Exception
        + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

The SQL Server does not exists yet and I would expect it to be provisioned through the template. Any ideas what's causing this error?

**Comment by singhkay** [comment]
Adding @davidebbo for taking a look

**Comment by pascalberger** [comment]
@davidebbo Any news on this?

**Comment by davidebbo** [comment]
@pascalberger @singhkay had added me thinking this was a Web Apps related issue (which is my area). But looking at your error, it relates to a Microsoft.Sql/servers resource, so we'll need a SQL expert to comment.

**Comment by tfitzmac** [comment]
@pascalberger I re-tested this template with different parameter values and it worked. I am guessing the problem is related to your parameters. The site name and server name must be unique. When I ran the template with the parameters you specified, I get two Conflicts errors in the deployment operations because myserver and mySite were already used. I hope that helps. I will add better parameter descriptions to the template to emphasize those values must be unique.

**Comment by pascalberger** [comment]
@tfitzmac I don't think the problem lies with the names. I tried again and it worked once to provision the sql server, but failed shortly after with the same message.

If I look in the azure preview portal I can see this error in the notifications:

    statusCode:GatewayTimeout
    serviceRequestId:
    statusMessage:{"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.Sql' within the specified time period."}}

It seems like I hit a timeout and the "Subscription does not have the server" message is just a following error.

**Comment by singhkay** [comment]
@tfitzmac Any update on this?

**Comment by mloskot** [comment]
I have no idea if my problem is related to the **201-web-app-sql-database** template in any way, but I'm observing very similar error on attempt to deploy the default **Microsoft.SQL.NewDatabase** via portal.azure.com.

Provisioning failed twice with the same `BadRequest` status and the following `StatusMessage`:
```
{"code":"40647",
"message":"Subscription '' does not have the server 'ml-asql'.",
"target":null,"details":[{
  "code":"40647","message":"Subscription '' does not have the server 'ml-asql'.",
  "target":null,"severity":"16"}],
"innererror":[]}
```

**Comment by AaronWoodrow** [comment]
I ran into a similar issue and it turned out that it had to do with the SQL database version number. I was on East US with version V12 and it gave me the errors above. I switched the version in the template from 12.0 to 2.0 and it worked.
