### ISSUE TITLE
VMsize choice

### ISSUE THREAD

**Issue by svarukala** [Azure/azure-quickstart-templates#547]
Why is the VMSize choice limited to the DS series only? These are premium SSD based series. It would be great if other regular VM sizes are allowed - it will be helpful for testing/lab work.

**Comment by robplank** [comment]
have you tried using Standard_A# or Basic_A# ? example Standard_A1

**Comment by svarukala** [comment]
I should have mentioned the template I was trying. I was trying to deploy this template: https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-three-vm
If you look at the VMsize allowed values - it only allows Standard_D* series. So when I try to edit the parameters in Azure, I do not see other VMsize options like the A series.

**Comment by robplank** [comment]
just replace those values with your desired VM size values save the template and deploy via a Custom Deployment in the portal or Powershell

**Comment by singhkay** [comment]
@svarukala I see Standard_D* sizes as well, but as @robplank mentioned feel free to edit the template in Portal before submitting a deployment or edit this on your local disk before deploying with PS or CLI.
