### ISSUE TITLE
Can´t use my developer license.

### ISSUE THREAD

**Issue by so-lar** [Azure/azure-quickstart-templates#5515]
[101-aci-dynamicsnav] (https://github.com/Azure/azure-quickstart-templates/tree/master/101-aci-dynamicsnav)

@tfenster, is there a way to import my developer license to the container after it is deployed. If not, is there a way to import the license from the beginning?

**Comment by tfenster** [comment]
@d-larisch Do you have your license somewhere you can download it from like a OneDrive or Dropbox link? You could then just get a PowerShell session into the container, download it and do an Import-NAVServerLicense. Would that work for you?
