### ISSUE TITLE
DomainJoin DSC template fails frequently

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#556]
Roughly 20% of the time, the domainjoin DSC script fails with:

    [[xWaitForADDomain]WaitForDomain] Checking for domain 'relad.local' ...
    [[xWaitForADDomain]WaitForDomain] Domain 'relad.local' NOT found.

It does that 20 times and fails the DSC extension. However, when I log into the box to find out what happened, the box was actually successfully added to the domain.

**Comment by singhkay** [comment]
Sent an email to the DSC team to take a look at this

**Comment by scottzilla** [comment]
Thanks Kay!


Scott Nowicki | Practice Director, Cloud Application Development | 10th Magnitude<http://www.10thmagnitude.com/> | snowicki@10thmagnitude.com<mailto:snowicki@10thmagnitude.com> | 909.833.0090<tel:909.833.0090>

**Comment by TravisEz13** [comment]
I believe this is the same issue as
[xActiveDirectory issue 30](https://github.com/PowerShell/xActiveDirectory/issues/30)

**Comment by singhkay** [comment]
@aarsan There was a major update to this template today #600. Give it a try and see if it is still an issue
