### ISSUE TITLE
201-site-to-site-vpn multiple subnets 

### ISSUE THREAD

**Issue by robplank** [Azure/azure-quickstart-templates#563]
how can you define two local address Prefixs ? 

For example I want to connect to the local networks of 10.1.0.0/24 and 192.168.200./24 through a single S2S VPN.

**Comment by singhkay** [comment]
Adding template author @sedouard for this

**Comment by sedouard** [comment]
Hey @robplank, not super clear on your question. Are you trying to connect Azure VNet `10.1.0.0/24` and on-prem (or other cloud network) `192.168.200.0/24`? If that's the case, you'll need to setup those rules in your vpn software that you are using to connect to the gateway. For example [in my aws vpc example](https://github.com/sedouard/aws-vpc-to-azure-vnet), using Strongswan, you'd have to setup the left and right networks with the appropiate network CIDRs.

**Comment by robplank** [comment]
here is an example of the powershell equivalent 

 New-AzureLocalNetworkGateway -Name LocalSite -ResourceGroupName testrg -Location 'West US' -GatewayIpAddress '23.99.221.164' -AddressPrefix @('10.0.0.0/24','20.0.0.0/24')

I assume that the parameter would look like this

"localAddressPrefix": {
    "value": "10.1.0.0/24,192.168.200.0/24"

main goal of this question is to provide better documentation for everyone to use for more complex vpn deployments. 

this would be a great topic to blog about or create a documentation page on.

**Comment by singhkay** [comment]
@robplank Are you asking if you can specify multiple address prefixes in templates?

**Comment by robplank** [comment]
yes

**Comment by singhkay** [comment]
@robplank I'm not an expert on networking but what you specified above for PS, can you run it with a -Debug flag and see what the JSON call sent to server contains? If ithe above works, it'd be awesome if you submitted a PR to update the readme for this template!
