### ISSUE TITLE
201-site-to-site-vpn localNetworkGateways Resource fails to deploy

### ISSUE THREAD

**Issue by robplank** [Azure/azure-quickstart-templates#567]
using the azure deploy button to start a custom deployment results in the localnetworkgateway failing to deploy.

STATUSMESSAGE
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"InternalServerError","message":"An error occured.","details":[]}]}}
RESOURCE
localGateway

**Comment by singhkay** [comment]
Adding the template author @sedouard for taking a look at this

**Comment by sedouard** [comment]
hey @robplank, using the xplat cli, as well as the deploy2azure button, I can deploy the template successfully with the following parameters:

```
{
  "location": {
    "value": "West US"
  },
  "adminUsername": {
    "value": "ubuntu"
  },
  "localGatewayIpAddress": {
    "value": "52.25.48.88"
  },
  "localAddressPrefix": {
    "value": "10.0.0.0/24"
  },
  "azureVNetAddressPrefix": {
    "value": "10.3.0.0/16"
  },
  "subnetPrefix": {
    "value": "10.3.0.0/24"
  },
  "gatewaySubnetPrefix": {
    "value": "10.3.200.0/29"
  },
  "adminPassword": {
    "value": "azure@1234"
  },
  "newStorageAccountName": {
    "value": "sedouardvpcdemo"
  },
  "sharedKey": {
    "value": "abc123"
  }
}
```

Can you verify?
