### ISSUE TITLE
active-directory-new-domain template fails on /CreateADForest

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#571]
This template consistently fails on:

    Resource Microsoft.Compute/virtualMachines/extensions 'adDC/CreateADForest' failed with message 'The resource operation completed with terminal provisioning state 'Failed'.'

After the above failure, I am unable to RDP into the server. It returns an error about the server not having Network Level Authentication on. Even after restarting the server (via the Azure Portal), I still receive the same error. This happened with DSC handler 1.7, 1.9, 2.3, and 2.4. 

I ran this again with 2.3 but this time, I RDP's into the machine as soon as it was provisioned and watched the DSC extension logs. It went all the way to the part where it says it created the forest but failed when it tried to write the status back to azure:

    VERBOSE: [2015-09-02T21:37:18] Event Source assembly is not loaded for telemetry... Unable to find type [AzureDsc.AzureDscTelemetryEventSource].

It then never rebooted the machine and I was unable to find any of the AD admin tools. I rebooted the machine and when it came back up, I was still able to login but Server Manager stated that the machine still needed to be promoted to a domain controller. I let it sit (while I typed this post) and then when I went to manually promote it to a DC, it said that it already was. It seems like a final reboot was missing but I cannot be sure.

**Comment by singhkay** [comment]
@aarsan sent an email to the DSC team to take a look

**Comment by aarsan** [comment]
Is there a public repo for the DSC extensions? I can't seem to find it.

**Comment by TravisEz13** [comment]
There is not a public repro for the Azure DSC Extension.

Could you zip the following folders C:\Packages\Plugins\Microsoft.Powershell.Dsc folder and send them to me? 

* C:\Packages\Plugins\Microsoft.Powershell.Dsc
    * This will include your configuration files and settings, but not the cert to decrypt any protected settings.   If this is a problem, email me and we can discuss how to mitigate.
* C:\WindowsAzure\Logs
