### ISSUE TITLE
Deployment error for logic app template

### ISSUE THREAD

**Issue by sopatwar** [Azure/azure-quickstart-templates#5781]
[201-alert-to-queue-with-logic-app](https://github.com/Azure/azure-quickstart-templates/tree/master/201-alert-to-queue-with-logic-app)

### Issue Details
This template throws an error during deployment.
The cause is incorrect name ("Send_message.") in the actions block of azuredeploy.json (line 84).
It seems that the name cannot end in a period.

**Comment by marlonsingleton** [comment]
submitted pull request #5783

**Comment by marlonsingleton** [comment]
Issue fixed. Pull request #5783 has been merged.

**Comment by sopatwar** [comment]
@marlonsingleton Thanks for fixing this!
