### ISSUE TITLE
How can I move a VM from one backendpool to another?

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-quickstart-templates#581]
Is there a way (via ARM template) to update a loadbalancer's backend pool? I have 2 back end pools (stage , prod). Periodically, I need to remove a VM from the stage pool and add it to the prod pool. I don't see any examples of how to do this. Is this possible?

**Comment by singhkay** [comment]
@ypitsch Can you help here?

**Comment by ypitsch** [comment]
Hi, this feature is not yet there. We are working on runtime APIs that will allow you to do such operations
