### ISSUE TITLE
Highlight in templates that ACS deprecated 

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-quickstart-templates#5817]
In a documentation, Microsoft highlighted that ACS deprecated. It will be right, if Microsoft will somehow mention it here as well.
It could be a text in a readme files, or suffix on a template name like "101-acs-swarm_deprecated" 

![image](https://user-images.githubusercontent.com/578954/52916645-3f2f0a80-32f3-11e9-8087-c1d229a63b2d.png)

### Issue Details

https://github.com/Azure/azure-quickstart-templates/blob/master/301-jenkins-acr-spinnaker-k8s/azuredeploy.json
https://github.com/Azure/azure-quickstart-templates/blob/master/201-spinnaker-acr-k8s/azuredeploy.json
https://github.com/Azure/azure-quickstart-templates/blob/master/101-acs-dcos/azuredeploy.json
https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-kubernetes
https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-swarm

**Comment by marlonsingleton** [comment]
Hi @SychevIgor I was able to get this issue for 101 templates merged.
