### ISSUE TITLE
Can not create a template using Azure CLI

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#584]
When I create a template (101-simple-linux-vm) using Azure CLI;
azure group create -n "xxx" -l "xxx" -d "xxx" -f azuredeploy.json -e azuredeploy.parameters.json
I got:
error:   The request content was invalid and could not be deserialized: 'Error converting value "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 4273.'.

I think it maybe has nothing to do with specific template.

**Comment by ahmetalpbalkan** [comment]
@bingosummer What version of azure cli are you running?

Also can you please open an issue at this repo: https://github.com/Azure/azure-xplat-cli/issues ?

**Comment by bingosummer** [comment]
@ahmetalpbalkan 
$ azure -v
0.9.8

**Comment by ahmetalpbalkan** [comment]
thanks, I was able to reproduce this myself, now I'm not alone :) following up internally..

**Comment by ravick** [comment]
I ran into simillar issue via code, looks like the parameters json mentioned in samples is like this:
{
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": { "value": "mytestvm1" },
    ...
  }
}

while, what you may need to provide is just the following, just the name and values:

{
    "vmName": { "value": "mytestvm1" },
     ...
}

**Comment by ahmetalpbalkan** [comment]
@ravick @bingosummer can you please deleting the `$HOME/.streamline` directory and try again. Looks like this was a bug in the CLI, we'll be fixing in this version. In the meanwhile the workaround may help:

    rm -rf ~/.streamline

**Comment by bingosummer** [comment]
Thanks @ahmetalpbalkan . The workaround works for me. Feel free to close this issue after you fix the bug.
