### ISSUE TITLE
Resource SP/ConfigureSPVM fails

### ISSUE THREAD

**Issue by m-deckert** [Azure/azure-quickstart-templates#5844]
[sharepoint-adfs](https://github.com/Azure/azure-quickstart-templates/tree/master/sharepoint-adfs)

### Issue Details
I got the following error when deploying the template:

DSC Configuration 'ConfigureSPVM' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xRemoteFile failed to execute Set-TargetResource functionality with error message: Invoking web request failed with error. The remote name could not be resolved: 'github-production-release-asset-2e65be.s3.amazonaws.com' F:\\\\Setup\\\\LDAPCP.wsp: The specified file was not found. PowerShell DSC resource MSFT_SPFarmSolution failed to execute Set-TargetResource functionality with error message: Cannot index into a null array.

The deployment parameters were:

{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sharePointVersion": {
      "value": "2016"
    },
    "dnsLabelPrefix": {
      "value": "mc"
    },
    "domainFQDN": {
      "value": "bu6.fme.local"
    },
    "addFrontEndToFarm": {
      "value": "Yes"
    },
    "adminUserName": {
      "value": "spadmin"
    },
    "adminPassword": {
      "value": "*********"
    },
    "serviceAccountsPassword": {
      "value": "*********"
    },
    "vmDCStorageAccountType": {
      "value": "Standard_LRS"
    },
    "vmDCSize": {
      "value": "Standard_F4"
    },
    "vmSQLStorageAccountType": {
      "value": "Premium_LRS"
    },
    "vmSQLSize": {
      "value": "Standard_DS2_v2"
    },
    "vmSPStorageAccountType": {
      "value": "Premium_LRS"
    },
    "vmSPSize": {
      "value": "Standard_DS3_v2"
    },
    "vmsTimeZone": {
      "value": "Central Europe Standard Time"
    },
    "vmsAutoShutdownTime": {
      "value": "1900"
    },
    "location": {
      "value": "[resourceGroup().location]"
    }
  }
}

**Comment by Yvand** [comment]
@m-deckert This issue indeed occurs from time to time, because somehow SharePoint VM is not able to download LDAPCP.wsp from GitHub.
There is not much to do about it, except maybe implement a retry mechanism in [xRemoteFile resource](https://github.com/PowerShell/xPSDesiredStateConfiguration/tree/dev/DSCResources/MSFT_xRemoteFile).

Note that after this error, DSC engine will re-apply the configuration automatically and most likely succeed, although Azure will not be notified and will keep reporting the failure.

**Comment by m-deckert** [comment]
Okay, thanks for the response. I tried the template again and now it works like a charm :-)
