### ISSUE TITLE
"condition": false in template

### ISSUE THREAD

**Issue by pplu** [Azure/azure-quickstart-templates#5850]
In https://github.com/Azure/azure-quickstart-templates/blob/master/101-container-registry-geo-replication/azuredeploy.json#L66 there is a `"condition": false` statement. condition should be an expression, as stated in https://docs.microsoft.com/es-es/azure/architecture/building-blocks/extending-templates/conditional-deploy.

If it's not an expression, what behaviour does it have when the value is a boolean? And when it's an integer? and a string?

**Comment by marlonsingleton** [comment]
@pplu 

The condition is intended be an expression that evaluates to a boolean. However, hard coding a boolean value is accepted but defeats the functions purpose. I'll update and submit a PR.

An Integer or string will throw an error.
Evaluation result of language expression '1' is type 'Integer', expected type is 'Boolean'.
Evaluation result of language expression 'string' is type 'String', expected type is 'Boolean'.

**Comment by pplu** [comment]
Thanks for the clarification
