### ISSUE TITLE
Broken link in 201-encrypt-running-linux-vm/README.md to AzureDiskEncryptionPreRequisiteSetup.ps1

### ISSUE THREAD

**Issue by SteveParson** [Azure/azure-quickstart-templates#5857]
[201-encrypt-running-linux-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/201-encrypt-running-linux-vm)

### Issue Details
The link to AzureDiskEncryptionPreRequisiteSetup.ps1 is broken in [README.md](https://github.com/Azure/azure-quickstart-templates/blob/master/201-encrypt-running-linux-vm/README.md). This file appears to have be removed from the master branch at some time, however it is still present in older  commits such as [here](https://github.com/Azure/azure-powershell/blob/10fc37e9141af3fde6f6f79b9d46339b73cf847d/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1)

### Repro steps (*if necessary, delete otherwise*)
1. Visit  [README.md](https://github.com/Azure/azure-quickstart-templates/blob/master/201-encrypt-running-linux-vm/README.md).
2. Click on [AzureDiskEncryptionPreRequisiteSetup.ps1](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1)
3. Observe 404

**Comment by marlonsingleton** [comment]
This link has been updated. Thanks!
