### ISSUE TITLE
101-webapp-custom-deployment-slots: slot-specific app settings?

### ISSUE THREAD

**Issue by VictorioBerra** [Azure/azure-quickstart-templates#5882]
[101-webapp-custom-deployment-slots](https://github.com/Azure/azure-quickstart-templates/tree/master/101-webapp-custom-deployment-slots)

### Issue Details
What is the best way to add slot-specific app settings? For example, I might have a connection string that needs to be different for each slot, and to stick to the slot and not carry over on a swap.

My ideas:
1. Environment array becomes an array of objects with detailed configuration stuff.
2. Can no longer use an array. Must introduce resources for specific slot configs. 

Follow up question: Why glue the word "Portal" to everything? What is portal in this sense? Now my web app name is MySitePortal instead of MySite.

**Comment by VictorioBerra** [comment]
@bmoore-msft @SriRamTKS

**Comment by SriRamTKS** [comment]
1. Sure, we can do that. The intention of this template was to keep things simple.
2. For slot-specific app settings, the config has to be made to be dependent on the parent site rather than the slot, as mentioned here: https://stackoverflow.com/a/44371143
But, sure enough, that's also a great improvement.

The reason for appending 'Portal' was to ensure that the concat does return a valid string even if the baseResourceName wasn't supplied or was too short. But, you can always change that and remove the word 'Portal'.

@VictorioBerra

**Comment by VictorioBerra** [comment]
@SriRamTKS thanks a lot that was very helpful. The nested resource arrays is something i didn't know was possible (although I will admit I am still green to ARM templates). That adds a little confusion for sure.

**Comment by VictorioBerra** [comment]
Little follow up @SriRamTKS [I cant find any docs at all on "microsoft.web/sites/slots/config"](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/allversions), the post you liked is "Oct 31 '16" so I am assuming Microsoft depreciated that? For example, they show using an `"appSettings"` node under properties. I have not tested if that checks the "slot setting" checkbox yet. Why is this not documented?

**Comment by VictorioBerra** [comment]
@SriRamTKS This just clicked for me... hopefully this helps someone else.

You can only specify a setting as a slot setting GLOBALL FOR THE WHOLE SITE. You might be saying "duh" right now, because you sent me the StackOverflow post and you said "For slot-specific app settings, the config has to be made to be dependent on the parent "site" rather than the "slot""

But consider this: 

![image](https://user-images.githubusercontent.com/2934507/54152401-248c1500-440b-11e9-8337-8410dff4f1ae.png)

If you just look at the UI, you might think that this checkbox only effects this slot. But it actually changes ALL slots, not just the one you intend to swap to or from.

## Template payload
```json
        {
          "apiVersion": "2015-08-01",
          "type": "config",
          "name": "slotconfignames",
          "location": "[parameters('location')]",
          "comments": "This specifies a list of app setting names across ALL sites and slots that will be sticky.",
          "properties": {
            "appSettingNames": [
              "123STICKY"
            ]
          },
          "dependsOn": [
            "[resourceId('Microsoft.Web/sites', variables('webAppName'))]"
          ]
        },
```

Why this sucks for us: We cant have one slot be setup to apply its settings while keeping the others sticky.

**Comment by SriRamTKS** [comment]
Thanks for the useful update, @VictorioBerra 

In fact, we moved away from making "slots" as "environments". We decided to dedicate a full "Site" for every environment. But, we also have just one "slot" for every environment ("Site"), as the slot helps in hot swapping the active and passive bits.

**Comment by VictorioBerra** [comment]
@SriRamTKS that doesn't seem like a bad idea. What about slots caused issues for you guys? Do you guys use ARM templates along with CI/CD?
