### ISSUE TITLE
201-vmss-bottle-autoscale - Cannot deploy template az01-vmsss is invalid properties.dnsSettings.domainNameLabel

### ISSUE THREAD

**Issue by kodubeau** [Azure/azure-quickstart-templates#5905]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Issue Details
Unable to deploy Template
Value 'az01-vmss' used in property 'properties.dnsSettings.domainNameLabel'of resource 'az01-vmsspip' (Microsoft.network/publicipaddresses) is invalid.

**Comment by marlonsingleton** [comment]
@kodubeau I just deployed this template without issue. Try removing the "01-" from your vmss name. In this template it's being used as the domainNameLabel as well.

**Comment by kodubeau** [comment]
Worked thank you!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kodubeau** [comment]
Worked thank you!
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kodubeau** [comment]
Used a different vmss name "az01-koko" in my instance.
