### ISSUE TITLE
The template deployment failed with in few minutes...

### ISSUE THREAD

**Issue by VIJAYDUSI** [Azure/azure-quickstart-templates#609]
![mesos-fail](https://cloud.githubusercontent.com/assets/13890603/9892457/c4d51388-5bc3-11e5-8ab1-1f10188b3230.JPG)
![mesos-inputs](https://cloud.githubusercontent.com/assets/13890603/9892481/17977b56-5bc4-11e5-9990-8b8835c322c5.JPG)
I am trying to deploy the template with Windows as Jump box and it failed within few minutes in to execution.  I have attached the failure screenshots (with inputs provided and the failure message event).

Any thoughts?

**Comment by rgardler** [comment]
Which template is this? It looks likes it is the Mesos one, can you please confirm?

**Comment by VIJAYDUSI** [comment]
Yes..it is Mesos only
https://github.com/Azure/azure-quickstart-templates/tree/master/mesos-swarm-marathon

Sent from my Windows Phone
________________________________

**Comment by rgardler** [comment]
I just deployed the template with no errors. Perhaps this was an intermittent problem. (the difference I had was that I had more agents and masters and of course DNS names and username).

The error message is not very helpful so I'm afraid I can't help any more at the moment. Perhaps just try again and if you get the same error we'll get someone to look at the logs.

In the meantime we are working on getting better error messages for one or two cases where they are not descriptive (like this).

**Comment by VIJAYDUSI** [comment]
Thank you and I will try again.

Sent from my Windows Phone
________________________________

**Comment by VIJAYDUSI** [comment]
I have tried again today with one change as number of agents to 2 (instead of 1 ) .. and it failed again .. also the debug info is not that much helpful to check what’s going on..

[cid:image002.jpg@01D0F068.B1E515F0]

Thanks,
Vijay

From: Vijay Dusi
Sent: Tuesday, September 15, 2015 8:30 PM
To: Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Subject: RE: [azure-quickstart-templates] The template deployment failed with in few minutes... (#609)

Thank you and I will try again.

Sent from my Windows Phone
________________________________

**Comment by singhkay** [comment]
@VIJAYDUSI There have been a bunch of updates on this template (https://github.com/Azure/azure-quickstart-templates/tree/master/mesos-swarm-marathon) from folks on the team and at Mesos. Can you check again? 

CC: @anhowe @artemharutyunyan

**Comment by rgardler** [comment]
@VIJAYDUSI are you still seeing this problem, I am unable to reproduce.

I'll leave the issue open for at least another 7 days, if no further information is provided I'll close as not-reproducible.

**Comment by VIJAYDUSI** [comment]
+ Mahendra..

Thanks,
Vijay
