### ISSUE TITLE
201-key-vault-secret-create parameter file doesn't match template

### ISSUE THREAD

**Issue by rowong** [Azure/azure-quickstart-templates#6097]
[201-key-vault-secret-create](https://github.com/Azure/azure-quickstart-templates/tree/master/201-key-vault-secret-create)

### Issue Details
The template file for 201-key-vault-secret-create has the parameter "keyVaultName" that is not present in the parameters file which only has 3 parameters "name" and objectId, and "secretsObject".  I suspect name should be keyVaultName?

### Repro steps (*if necessary, delete otherwise*)
1.  Open the template file https://github.com/Azure/azure-quickstart-templates/blob/master/201-key-vault-secret-create/azuredeploy.json
2.  Open the parameters file https://github.com/Azure/azure-quickstart-templates/blob/master/201-key-vault-secret-create/azuredeploy.parameters.json
3.  Compare the inputs required in the template file with the provided parameters in the parameters file
4.  The keyVaultName parameter is missing from the parameter file

**Comment by cocallaw** [comment]
@rowong PR https://github.com/Azure/azure-quickstart-templates/pull/6236 has been submitted for review to correct this.

**Comment by krishna9090** [comment]
No

**Comment by cocallaw** [comment]
@rowong PR https://github.com/Azure/azure-quickstart-templates/pull/6236 has been merged by @bmoore-msft fixing this issue.

**Comment by cocallaw** [comment]
@bmoore-msft can you close this issue as it has been resolved in https://github.com/Azure/azure-quickstart-templates/pull/6236
