### ISSUE TITLE
 sql-server-2014-alwayson-dsc Fails

### ISSUE THREAD

**Issue by timomta** [Azure/azure-quickstart-templates#611]
I am attempting to use this template: https://github.com/Azure/azure-quickstart-templates/tree/master/sql-server-2014-alwayson-dsc

We have multiple people hitting an error during deployment (I asked others to independently try deployment). I have tried East US, East US 2, and eastus2 for location, but can’t get a successful run.

PS D:\AzureTemplates\azure-quickstart-templates\sql-server-2014-alwayson-dsc> New-AzureResourceGroup -Name "tomtasqlgroup2" -Location "eastus2"  -TemplateParameterFile .\azuredeploy-parameters.json -TemplateFile .\azuredeploy.json

cmdlet New-AzureResourceGroup at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
newStorageAccountNamePrefix: tomta2sqlstore
locationFromTemplate: eastus2
adminPassword: ********
sqlServerServiceAccountPassword: ********
dnsPrefix: tomta2sql
WARNING: The deployment parameters in New-AzureResourceGroup cmdlet is being deprecated and will be removed in a future
release. Please use New-AzureResourceGroupDeployment to submit deployments.
WARNING: The output object of this cmdlet will be modified in a future release.
VERBOSE: 2:34:22 PM - Created resource group 'tomtasqlgroup2' in location 'eastus2'
VERBOSE: 2:34:22 PM - Template is valid.
VERBOSE: 2:34:23 PM - Create template deployment 'azuredeploy'.
VERBOSE: 2:34:29 PM - Resource Microsoft.Compute/availabilitySets 'adAvailabiltySet' provisioning status is succeeded
VERBOSE: 2:34:29 PM - Resource Microsoft.Network/publicIPAddresses 'publicIP' provisioning status is running
VERBOSE: 2:34:29 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore0' provisioning status is running
VERBOSE: 2:34:29 PM - Resource Microsoft.Compute/availabilitySets 'sqlAvailabiltySet' provisioning status is succeeded
VERBOSE: 2:34:32 PM - Resource Microsoft.Network/virtualNetworks 'sqlAlwaysOnVNET' provisioning status is running
VERBOSE: 2:34:32 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore1' provisioning status is running
VERBOSE: 2:34:32 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore2' provisioning status is running
VERBOSE: 2:34:42 PM - Resource Microsoft.Network/publicIPAddresses 'publicIP' provisioning status is succeeded
VERBOSE: 2:34:47 PM - Resource Microsoft.Network/virtualNetworks 'sqlAlwaysOnVNET' provisioning status is succeeded
VERBOSE: 2:34:52 PM - Resource Microsoft.Network/networkInterfaces 'sql-0-nic' provisioning status is succeeded
VERBOSE: 2:34:52 PM - Resource Microsoft.Network/networkInterfaces 'sql-w-nic' provisioning status is succeeded
VERBOSE: 2:34:52 PM - Resource Microsoft.Network/loadBalancers 'publicLoadBalancer' provisioning status is succeeded
VERBOSE: 2:34:52 PM - Resource Microsoft.Network/loadBalancers 'sqlLoadBalancer' provisioning status is succeeded
VERBOSE: 2:34:54 PM - Resource Microsoft.Network/networkInterfaces 'dc-pdc-nic' provisioning status is succeeded
VERBOSE: 2:34:54 PM - Resource Microsoft.Network/networkInterfaces 'dc-bdc-nic' provisioning status is succeeded
VERBOSE: 2:34:54 PM - Resource Microsoft.Network/networkInterfaces 'sql-1-nic' provisioning status is succeeded
VERBOSE: 2:34:54 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore0' provisioning status is succeeded
VERBOSE: 2:34:59 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore1' provisioning status is succeeded
VERBOSE: 2:34:59 PM - Resource Microsoft.Storage/storageAccounts 'tomta2sqlstore2' provisioning status is succeeded
VERBOSE: 2:35:01 PM - Resource Microsoft.Compute/virtualMachines 'dc-pdc' provisioning status is running
VERBOSE: 2:38:47 PM - Resource Microsoft.Compute/virtualMachines 'dc-pdc' provisioning status is succeeded
VERBOSE: 2:38:49 PM - Resource Microsoft.Compute/virtualMachines/extensions 'dc-pdc/InstallDomainController'
provisioning status is running
VERBOSE: 2:51:51 PM - Resource Microsoft.Compute/virtualMachines/extensions 'dc-pdc/InstallDomainController'
provisioning status is succeeded
New-AzureResourceGroup : 2:51:53 PM - Resource Microsoft.Resources/deployments 'UpdateVNetDNS1' failed with message
'Deployment template validation failed: 'The provided value for the template parameter 'location' at line '5' and
column '18' is not valid.'.'
At line:1 char:1
+ New-AzureResourceGroup -Name "tomtasqlgroup2" -Location "eastus2"  -T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroup], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupCommand

**Comment by singhkay** [comment]
Hi @timomta. @honcao made a big update to this template today to fix a bunch of issues #600. Please give it a try now and reopen if there are still an issue.
