### ISSUE TITLE
[Question] How to create cusomized multiple loadBalancingRules?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#613]
We can create loadBalancingRules just like the following link.
https://github.com/Azure/azure-quickstart-templates/blob/master/101-create-internal-loadbalancer/azuredeploy.json#L118

If customers want to create mutiple loadBalancingRules and the count is determined as a parameter, how should I create an array of the rules? It should be like:
```
"loadBalancingRules": [
  {
    "properties":
      {
        ...
        "protocol": "Tcp",
        "frontendPort": 80,
        "backendPort": 80,
        "idleTimeoutInMinutes": 15
      },
    "Name": "lbrule-1"
  },
  {
    "properties":
      {
        ...
        "protocol": "Tcp",
        "frontendPort": 22,
        "backendPort": 22,
        "idleTimeoutInMinutes": 30
      },
    "Name": "lbrule-2"
  }
]
```

I tried the copyIndex() function referring to [Create multiple instances of resources in Azure Resource Manager](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-multiple/), but it is for creating multiple resources instead of an array configuration in one resource.

**Comment by singhkay** [comment]
@ypitsch Can you help here?

**Comment by ypitsch** [comment]
Hi,
We only support PUT for inboundNatRules, not for loadBalancingRules (or any other child resource of the LB)

**Comment by bingosummer** [comment]
@ypitsch Thanks for your response.
What does "PUT for inboundNatRules" mean?
Would the requirement in my question be in the road map?

**Comment by ypitsch** [comment]
Hi, 
CopyIndex works only not LB rules. It's not in the roadmap but thanks for sharing, we will evaluate your request

**Comment by bingosummer** [comment]
Got it.
