### ISSUE TITLE
hdinsight-linux-with-edge-node deployment may be hard to remove

### ISSUE THREAD

**Issue by benjguin** [Azure/azure-quickstart-templates#623]
I tried to deploy from hdinsight-linux-with-edge-node with a resource group named afac34. 
Then I tried to remove the whole resource group.
It didn't work. I suspect the storage accounts were removed before the HDInsight cluster, which caused the issue.

**Comment by singhkay** [comment]
@benjguin Are you still not able to delete the resource group?

**Comment by benjguin** [comment]
I have a support ticket open on Azure. I'll update this issue when the issue is fixed. I know suspect it's not related to the template itself.
Thanks
