### ISSUE TITLE
Can/How do you deploy multiple connectors to ISE?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-quickstart-templates#6376]
[Provision an Integration Service Environment with a VNET, subnets, and managed connectors](https://github.com/Azure/azure-quickstart-templates/tree/master/201-integration-service-environment)

### Issue Details
It's not clear from the readme or the template comments how to deploy multiple connectors to the ISE; do you comma-separate? semicolon separate? Is it not possible? Should provide guidance here.

Additionally if it's not possible, it should be :)

**Comment by brandonh-msft** [comment]
cc @nzthiago

**Comment by brandonh-msft** [comment]
Found thru trial & error it's expecting _only_ JSON array format (not even single string). PR incoming

**Comment by nzthiago** [comment]
The managedConnectors parameter is of type "array":
https://github.com/Azure/azure-quickstart-templates/blob/master/201-integration-service-environment/azuredeploy.json#L26

it's a typical ARM parameter type, so didn't feel like needed documenting regular ARM syntax. But good to have the clarification in the readme and parameter metadata.
