### ISSUE TITLE
101-subnet-add-vnet-existing needs to have Vnet defined in the template

### ISSUE THREAD

**Issue by mjazwiecki** [Azure/azure-quickstart-templates#6400]
Hi all, 

Is it really possible to add subnet to existing Vnet using this template? Maybe I am missing something but it seems there needs to be Vnet included in the template so this [template](https://github.com/Azure/azure-quickstart-templates/blob/master/101-subnet-add-vnet-existing/azuredeploy.jso) is confusing.

**Comment by edm-ms** [comment]
This template prompts for the name of your existing VNET. Notice the parameter value existingVNETName

  "parameters": {
    "**existingVNETName**": {
      "type": "string",
      "metadata": {
        "description": "Name of the VNET to add a subnet to"
      }


And then the reference to the resource:

      "type": "Microsoft.Network/virtualNetworks/subnets",
      "name": "[concat(parameters('**existingVNETName**'), '/', parameters('newSubnetName'))]",
