### ISSUE TITLE
Azuredeploy.json must use the location parameter

### ISSUE THREAD

**Issue by ivann14** [Azure/azure-quickstart-templates#6424]
### Issue Details
I am creating a template (https://github.com/Azure/azure-quickstart-templates/pull/6423) and I would like to publish it in this repository, however, I am getting the "azuredeploy.json must use the location parameter, not resourceGroup().location (except when used as a default value)" in your Best Practices Tests. For that reason, I checked how other templates solved this issue. I found for example '201-aci-wordpress' template that is using the location parameter. After I click on 'deploy to Azure button' I am redirected to the Azure portal that looks like this 
![image](https://user-images.githubusercontent.com/17337843/63180944-8d795800-c04f-11e9-90ee-f03180eed62f.png).

I consider not having the location value resolved as a problem because then anyone using my template has to look for a correct location value. Moreover, I would prefer not to even bother anyone with filling this value as they have already picked the location through the resource group. Therefore I tried to use it in a variable but that does not work as well.

Thank you

**Comment by bmoore-msft** [comment]
The resourceGroup location need not be the same as the location for the resources, so that's why they are 1) separate and 2) use a defaultValue... so this is intentional.
