### ISSUE TITLE
Requested Template: Application Gateway with SSL and NAT Rules

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#643]
Hopefully this is a suitable forum (GitHub issues) for requesting an example template. If it isn't then please direct me elsewhere.

The Application Gateway looks very interesting as a load balancer replacement that also handles SSL offloading. An example template that shows how to assign the SSL certificate would be very useful. Also useful would be an example of how to apply inbound NAT rules to the Application Gateway.

**Comment by singhkay** [comment]
Adding @puneetsaraswat who wrote the Application Gateway template. @puneetsaraswat Is this something you can take a look at writing?

**Comment by singhkay** [comment]
@tfnaylor Take a look at PR #666. This was merged a few days ago. let me know if satisfies your scenario.

**Comment by tfnaylor** [comment]
This looks really good - I will give it a try when I get an opportunity at some point over the next couple of weeks. Thank you very much!
