### ISSUE TITLE
SQLAuditSettings Deployment Error - BlobAuditingNoServerIdentity - The server identity is not correctly configured on server

### ISSUE THREAD

**Issue by frankkilcommins** [Azure/azure-quickstart-templates#6471]
[201-sql-auditing-server-policy-to-oms](https://github.com/Azure/azure-quickstart-templates/tree/master/201-sql-auditing-server-policy-to-oms)

### Issue Details
As of September 1st, we receive a conflict error during deployments where we have sqlAuditSettings enabled towards Log Analytics. The ARM template settings are very similar to the ones used in the sample template.

I wonder is this is a result of the retirement of classic alerts support although there is no documented reference or relationship between the two services? Timing wise it's bang on. I also tried to redeploy a successful release from last week and that fails with the same error. Tried both on-top of existing resources and also cleared out the Resource Group and did full fresh release again with same error.

**Error Details**
**BlobAuditingNoServerIdentity** - The server identity is not correctly configured on server '_Server Name_'. Please re-configure Identitity on the server

### Relevant ARM Resources
**OMS Workspace**
`    {
      "name": "[variables('omsWorkspaceName')]",
      "type": "Microsoft.OperationalInsights/workspaces",
      "apiVersion": "2017-04-26-preview",
      "location": "[resourceGroup().location]",
      "properties": {
        "sku": {
          "name": "[parameters('omsSku')]"
        }
      }
    }`
**DB Diagnostics Settings**
`        {
          "type": "databases/providers/diagnosticSettings",
          "name": "[concat(variables('SqlDatabaseName'),'/microsoft.insights/',variables('diagnosticsSettingName'))]",
          "dependsOn": [
            "[variables('SQLServerName')]",
            "[concat('Microsoft.OperationalInsights/workspaces/', variables('omsWorkspaceName'))]",
            "[concat('Microsoft.Sql/servers/', variables('SQLServerName'), '/databases/',variables('SqlDatabaseName'))]"
          ],
          "apiVersion": "2017-05-01-preview",
          "properties": {
            "name": "[variables('diagnosticsSettingName')]",
            "workspaceId": "[resourceId('Microsoft.OperationalInsights/workspaces', variables('omsWorkspaceName'))]",
            "logs": [
              {
                "category": "SQLSecurityAuditEvents",
                "enabled": true,
                "retentionPolicy": {
                  "days": 0,
                  "enabled": false
                }
              }
            ]
          }
        }`

**AuditSettings**
`        {
          "apiVersion": "2017-03-01-preview",
          "type": "auditingSettings",
          "name": "DefaultAuditingSettings",
          "dependsOn": [
            "[variables('SQLServerName')]",
            "[concat('Microsoft.Sql/servers/', variables('SQLServerName'), '/databases/',variables('SqlDatabaseName'))]"
          ],
          "properties": {
            "State": "Enabled",
            "auditActionsAndGroups": null,
            "auditActions": [ "INSERT, UPDATE, DELETE" ],
            "isAzureMonitorTargetEnabled": true
          }
        }`

If I remove the resources above, the deployment succeeds.

**Comment by lubalibu** [comment]
There is a bug that occurs when server level Auditing is enabled to Log Analytics or event hub targets only. 
A workaround is to add "storageAccountAccessKey": "1"
property to the auditing settings.
This bug will be fixed in several weeks.

**Comment by amrik2309** [comment]
> There is a bug that occurs when server level Auditing is enabled to Log Analytics or event hub targets only.
> A workaround is to add "storageAccountAccessKey": "1"
> property to the auditing settings.
> This bug will be fixed in several weeks.

Does that mean that we cant point the logs to Log analytics at the moment ? Only Storage Account ?

**Comment by frankkilcommins** [comment]
Still waiting on confirmation to same. The workaround settings allow for ARM template to deploy successfully but logs are not sent to Log Analytics and looking via Azure portal the connection to Log Analytics is not checked. Trying to manually set gives the same error as I originally posted.

**Comment by lubalibu** [comment]
The workaround:
{
                    "type": "auditingSettings",
                    "apiVersion": "2017-03-01-preview",
                    "name": "DefaultAuditingSettings",
                    "dependsOn": [
                        "[resourceId('Microsoft.Sql/servers/', parameters('sqlServerName'))]"
                    ],
                    "properties": {
                        "State": "Enabled",
                        "auditActionsAndGroups": null,
                        "isAzureMonitorTargetEnabled": true,
                        "storageAccountAccessKey": "1"
                    }
                }

is setting Auditing to Log analytics (not setting to storage account).  You should see in the Portal that auditing in enabled on the server to Log Analytics (please verify that your template also creates diagnostic settings on the master database with SQLSecurityAuditEvents category).
You should also see your audit logs in Log analytics workspace.

**Comment by amrik2309** [comment]
> The workaround: { "type": "auditingSettings", "apiVersion": "2017-03-01-preview", "name": "DefaultAuditingSettings", "dependsOn": [ "[resourceId('Microsoft.Sql/servers/', parameters('sqlServerName'))]" ], "properties": { "State": "Enabled", "auditActionsAndGroups": null, "isAzureMonitorTargetEnabled": true, "storageAccountAccessKey": "1" } } is setting Auditing to Log analytics (not setting to storage account). You should see in the Portal that auditing in enabled on the server to Log Analytics (please verify that your template also creates diagnostic settings on the master database with SQLSecurityAuditEvents category). You should also see your audit logs in Log analytics workspace. From: Frank Kilcommins <notifications@github.com> Sent: Tuesday, September 17, 2019 4:37 PM To: Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com> Cc: Luba Libov <lubalibu@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [Azure/azure-quickstart-templates] SQLAuditSettings Deployment Error - BlobAuditingNoServerIdentity - The server identity is not correctly configured on server (#6471) Still waiting on confirmation to same. The workaround settings allow for ARM template to deploy successfully but logs are not sent to Log Analytics and looking via Azure portal the connection to Log Analytics is not checked. Trying to manually set gives the same error as I originally posted. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-quickstart-templates%2Fissues%2F6471%3Femail_source%3Dnotifications%26email_token%3DAJPFQ6V7RA6KXIANZX5P4U3QKDMPFA5CNFSM4ITEFRC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD64RPPA%23issuecomment-532223932&data=02%7C01%7Clubalibu%40microsoft.com%7C92bb5485334f488ebd2b08d73b74185f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637043242129702746&sdata=dNvnFfwkDOmlU%2FtL1pg7qX8UhVSPvh%2Bk7BEDQDSEOEI%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJPFQ6Q6OX4WTGV6YYQT3QDQKDMPFANCNFSM4ITEFRCQ&data=02%7C01%7Clubalibu%40microsoft.com%7C92bb5485334f488ebd2b08d73b74185f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637043242129712704&sdata=9S3W8%2B6YpwdrYLnjwNdjsj9OZQ88XTGi928CraiXX28%3D&reserved=0>.

When I added master database as dependency, it fails to execute the template saying that it couldnt find the master database. So I am not sure, how to do it.

**Comment by lubalibu** [comment]
@amrik2309 Please take a look at the template [201-sql-auditing-server-policy-to-oms](https://github.com/Azure/azure-quickstart-templates/tree/master/201-sql-auditing-server-policy-to-oms) it contains the dependencies and the configuration of the master database resource: 
{
	"type": "databases",
	"apiVersion": "2017-03-01-preview",
	"location": "[parameters('location')]",
	"dependsOn": ["[parameters('sqlServerName')]"],
	"name": "master",
	"properties": {
	}
},
{
	"type": "databases/providers/diagnosticSettings",
	"name": "[concat('master/microsoft.insights/',variables('diagnosticSettingsName'))]",
	"dependsOn": ["[parameters('sqlServerName')]",
	"[concat('Microsoft.OperationalInsights/workspaces/', parameters('omsWorkspaceName'))]",
	"[concat('Microsoft.Sql/servers/', parameters('sqlServerName'), '/databases/master')]"],
...

**Comment by feiyushi** [comment]
@lubalibu Hi, wonder if any workaround in the Azure portal?

**Comment by lubalibu** [comment]
You can use one of the following workarounds:
1. Select storage account beside the LA or the Event hub target.
2. Create a Managed Identity on the server and set auditing:
    PowerShell : Set-AzureRmSqlServer  -ResourceGroupName <RGName> -ServerName <serverName> -AssignIdentity

This issue will be fixed worldwide in a few days.

**Comment by frankkilcommins** [comment]
@lubalibu - i can at least confirm that for my templates the workaround (and dependencies on master db) are working as expected. Please keep me up to date when the workaround can be removed.

**Comment by lubalibu** [comment]
@frankkilcommins- Issue is fixed worldwide.

**Comment by frankkilcommins** [comment]
Verified that issue is resolved and workaround can be removed from ARM templates

**Comment by bitsofinfo** [comment]
not fixed, still an issue
