### ISSUE TITLE
Catch-22 with _artifactsLocationSasToken: azure-quickstart-templates/test/template-validation-tests vs. az-group-deploy.sh -v

### ISSUE THREAD

**Issue by edburns** [Azure/azure-quickstart-templates#6481]
This bug comes to you from the "very frustrating for users" department.
Users use the tools we give them to ensure smooth entry to the Azure
marketplace, including the
`azure-quickstart-templates/test/template-validation-tests`
(template-validation-tests) and `az-group-deploy.sh -v` script.

In my case, I used the `template-validation-tests` against my
`mainTemplate.json` and `createUiDefinition.json` and they all passed.
Then I ran those same two files against `az-group-deploy.sh -v` and it
failed with this error:

```

"message": "Deployment template validation failed: 'The template
parameters '_artifactsLocationSasToken' in the parameters file are not
valid; they are not present in the original template and can therefore
not be provided at deployment time. The only supported parameters for
this template are '_artifactsLocation, adminUsername,
authenticationType, adminPasswordOrKey, acceptOTNLicenseAgreement,
otnAccountUsername, otnAccountPassword, wlsDomainName, wlsUserName,
wlsPassword, managedServerPrefix, dnsLabelPrefix, linuxOSVersion,
numberOfInstances, adminVMName, location, vmSizeSelect'. Please see
https://aka.ms/arm-deploy/#parameter-file for usage details.'.",

```

So, I added this parameter:

```

"_artifactsLocationSasToken": {
    "type": "securestring",
    "metadata": {
        "description": "The sasToken required to access _artifactsLocation.  When the template is deployed using the accompanying scripts, a sasToken will be automatically generated. Use the defaultValue if the staging location is not secured."
    },
    "defaultValue": ""
}

```

but now the `template-validation-tests` fail with this message:

```

1) template files - parameters tests - parameter
_artifactslocationsastoken must be used in file mainTemplate.json:

  AssertionError: unused parameter "_artifactslocationsastoken" in file mainTemplate.json
    at Context.<anonymous> (test/mainTemplateTests.js:107:13)

```

Unless I'm missing something, it seems the `template-validation-tests`
need to be modified to not fail when encountering the
`_artifactsLocationSasToken` unused parameter.

**Comment by bmoore-msft** [comment]
_artifactsLocationSasToken must actually be used for non-marketplace deployment tests...  So I think once you factor that in, the tests are correct.

**Comment by amit-sycomp** [comment]
Hello, edburns,

How you have fixed that? Any suggestion
