### ISSUE TITLE
Missed Opportunity for Correctness in Static Validation

### ISSUE THREAD

**Issue by edburns** [Azure/azure-quickstart-templates#6483]
Consider this statement about the static validation checks for templates
on
<https://docs.microsoft.com/en-us/azure/managed-applications/test-createuidefinition>

   "and makes sure the output values of the portal interface match the
   parameters of your template."

I have observed that the matching check seems not to consider the type
of the value output from `createUiDefinition.json` with respect to the
expected input parameter type in `mainTemplate.json`.

For example, consider this `parameters.basics` array element:

```
{
    "name": "numberOfInstances",
    "type": "Microsoft.Common.TextBox",
    "label": "Number of VMs",
    "defaultValue": "4",
    "toolTip": "The number of VMs to create, with one WebLogic node per VM",
    "constraints": {
        "required": true,
        "regex": "^(2|3|4|5)$",
        "validationMessage": "Number of VMs to deploy, limit 5 since this offer is using a single storage account."
    },
    "visible": true
}
```
with this element in the `outputs` array:

```
"numberOfInstances": "[basics('numberOfInstances')]",
```

This matches up with the following member in the `parameters` dictionary
in `mainTemplate.json`:

```
"numberOfInstances": {
        "type": "int",
        "defaultValue": 2,
        "minValue": 2,
        "maxValue": 5,
        "metadata": {
                "description": "Number of VMs to deploy, limit 5 since this sample is using a single storage account"
        }
}
```

The static validation checks did not catch this type mismatch, but when
trying to actually run the offer in the Azure portal, you get this
error:

```
Validation failed, see errors below.
InvalidTemplateDeployment template validation failed: 'The provided value for the template parameter 'numberOfInstances' at line '97' and column '26' is not valid.'.
```

This problem is fixed by modifying the entry in the `outputs` array in
`createUiDefinition.json` as show next.

```
"numberOfInstances": "[int(basics('numberOfInstances'))]",
```

I assert the static validation checks should be enhanced to catch this
type mismatch error

**Comment by bmoore-msft** [comment]
Currently we want to scope the tests to catch things that would not be caught otherwise - something like this is syntactical and would be caught as soon as anyone tries to deploy the template (will be caught by ARM's /validate method).  Another example are things that "will deploy" but don't follow best practices (like hard coding location)…

Otherwise we will eventually end up duplicating a lot of code in ARM's template engine.
