### ISSUE TITLE
Microsoft.Sql servers/securityAlertPolicies

### ISSUE THREAD

**Issue by amrik2309** [Azure/azure-quickstart-templates#6532]
I am hitting an issue in the template below :
https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2017-03-01-preview/servers/securityalertpolicies

If I specify an email address in the below, the template fils to deploy.

"emailAddresses": [
      "string"
    ],

The way, I used is the following :-
"emailAddresses": [parameters('emailaddresses')]
and 
"emailAddresses": "abc@abc.com.au"

However, if I leave the value empty, the template succeeds without any error. I am getting the following errors :-

   { "id": "/subscriptions/<subscriptionID>/resourceGroups/<resourcegroup>/providers/Microsoft.Resources/deployments/<userid>/operations/E85F3C56CFD42A26", "operationId": "E85F3C56CFD42A26", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-09-23T13:22:57.3676546Z", "duration": "PT0.7010511S", "trackingId": "80dbbe4b-c85c-4af9-bd5f-d8b7dee49d1b", "statusCode": "BadRequest", "statusMessage": { "error": { "details": [ { "code": "InvalidResourceIdSegment", "message": "", "target": "parameters.properties.emailAddresses" } ], "code": "InvalidResourceIdSegment", "message": "The 'parameters.properties.emailAddresses' segment in the url is invalid." } }, "targetResource": { "id": "/subscriptions/<subscriptionID>/resourceGroups/<resourcegroup>/providers/Microsoft.Sql/servers/<sqlserver>/securityAlertPolicies/SecurityAlertPolicies", "resourceType": "Microsoft.Sql/servers/securityAlertPolicies", "resourceName": "sqlserverpft3fcti5rtaa/SecurityAlertPolicies" } }}
-------------------------------------------------------------
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"details\": [\r\n {\r\n \"code\": \"InvalidResourceIdSegment\",\r\n \"message\": \"\",\r\n \"target\": \"parameters.properties.emailAddresses\"\r\n }\r\n ],\r\n \"code\": \"InvalidResourceIdSegment\",\r\n \"message\": \"The 'parameters.properties.emailAddresses' segment in the url is invalid.\"\r\n }\r\n}"}]}

-----------------------------------------------------------

**Comment by amrik2309** [comment]
Alright, I got that working and it seems, I was hitting a syntax error. I was missing out on square brackets, this being an array. 

"emailAddresses": ["[parameters('alertEmailAddress')]"],

**Comment by DillyBabu** [comment]
There is no proper documentation available for this on how to use for multiple email addresses.
Took almost 5 hours to find a solution.
Solution:
"Emailaddresses": {
"Type":"string",
"Defaultvalue": "a@contoso.com;b@contoso.com;c@contoso.com"
}
Resource property
"Emailaddresses": "[parameters ('emailAddresses')]

Can be useful to someone . Thanks!👍
