### ISSUE TITLE
Deplyment of this template failed due to validation procedure

### ISSUE THREAD

**Issue by jlacarriere** [Azure/azure-quickstart-templates#6570]
Hello,

I am reporting a problem in this template.  After follwoing the deployment procedure:
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-rm-template

I was not able to pass the validation. Here is the report:

{
  "telemetryId": "12c10ac9-c7c5-4e72-8e38-9486f86270e4",
  "bladeInstanceId": "Blade_0ee3a7a3bc0942389d42d1ff91b38744_40_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplateDeployment",
  "message": **"The template deployment 'Microsoft.Template' is not valid according to the validation procedure.** The tracking id is 'c27682eb-c473-4b4a-8179-64b64f53f815'. See inner errors for details.",
  "details": [
    {
      "code": "InvalidParameter",
      "message": "Provisioning of resource(s) for container service aks101cluster in resource group HNR-k8s failed. Message: {\n  \"code\": \"InvalidParameter\",\n  \"message\": \"The value of parameter linuxProfile.ssh.publicKeys.keyData is invalid. Please see https://aka.ms/aks-naming-rules for more details.\",\n  \"target\": \"linuxProfile.ssh.publicKeys.keyData\"\n }. Details: "
    }
  ]
}

![image](https://user-images.githubusercontent.com/43141742/66056478-71fed980-e537-11e9-91ee-2a79ce0645bf.png)

Is it because of the linusadminusername really that is too simple?

**Comment by gottagetgit** [comment]
It says your public key is not a valid format. Start there.

**Comment by MCKLMT** [comment]
@jlacarriere Can you test again or close the issue?
