### ISSUE TITLE
sql-server-2014-alwayson-dsc fails in PrepareAlwaysOnSqlServer.ps1::94::9::xFirewall step

### ISSUE THREAD

**Issue by uday31in** [Azure/azure-quickstart-templates#683]
Job {387ABDE3-6B3B-11E5-80C9-000D3AB0D140} : 
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 0x1. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [xFirewall]DatabaseEngineFirewallRule and SourceInfo is C:\Packages\Plugins\Microsoft.Powershell.DSC\1.7.0.0\DSCWork\PrepareAlwaysOnSqlServer.ps1.0\PrepareAlwaysOnSqlServer.ps1::94::9::xFirewall. ErrorMessage is Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.Collections.IList'.
Parameter name: value.

**Comment by singhkay** [comment]
@honcao can you take a look at this?

**Comment by honcao** [comment]
I will investigate this today.

**Comment by singhkay** [comment]
@uday31in PR #779 has been opened to fix some issues with this template. If this still doesn't work for you, please reopen this issue.
