### ISSUE TITLE
Deployment to resource group 'Default-Storage-SouthCentralUS' failed.

### ISSUE THREAD

**Issue by josephwinston** [Azure/azure-quickstart-templates#688]
I'm attempting to follow the instructions at:

https://github.com/Azure/azure-quickstart-templates/blob/master/docker-swarm-cluster/README.md

After filling out all the required parameters, assigning the correct subscription, selecting  an existing or a new resource group, and then accepting the legal terms, I then press the create button.

After a short while, the bell icon shows that an error has occurred.  Drilling down on the details presents the dialog with the status message is: "Error", which doesn't give a neophyte much hints on what needs to be done.  

Perhaps a URL could instead be presented that give a new user ideas on what might be wrong.

**Comment by singhkay** [comment]
Adding @ahmetalpbalkan to help with this

**Comment by ahmetalpbalkan** [comment]
@josephwinston can you please send a screenshot? I couldn't imagine what's going on.

**Comment by josephwinston** [comment]
![step1](https://cloud.githubusercontent.com/assets/226217/10321370/e5e82684-6c3d-11e5-82ee-a5bba99ef0c7.jpg)
![step2](https://cloud.githubusercontent.com/assets/226217/10321373/e7b80e02-6c3d-11e5-8cd4-04c9ed061510.jpg)
![step3](https://cloud.githubusercontent.com/assets/226217/10321382/f142aafe-6c3d-11e5-86cd-476a9e125aa1.jpg)
![step4](https://cloud.githubusercontent.com/assets/226217/10321384/f48b81ae-6c3d-11e5-80be-a4f5c0d7b423.jpg)
![step5](https://cloud.githubusercontent.com/assets/226217/10321388/f7d38622-6c3d-11e5-8fc9-4ce7597c511d.jpg)
![step6](https://cloud.githubusercontent.com/assets/226217/10321390/faa2f2f2-6c3d-11e5-8cc6-df2b76f1503e.jpg)

**Comment by ahmetalpbalkan** [comment]
@josephwinston can you please click on `back-40` (if it is not clickable, please click to "Resource Groups" from left sidebar, and you can see the same deployment UI, then `back-40` should be clickable).

My guess is, `back-40` is not a valid storage account name (it contains dash) and it has to be globally unique. Please try with another value.

**Comment by josephwinston** [comment]
Good catch.  Please close
