### ISSUE TITLE
getting 404 using the button "deploy to azure"

### ISSUE THREAD

**Issue by ewekansige** [Azure/azure-quickstart-templates#7057]
[Deploy a slurm cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/slurm)

### Issue Details

Using the "Deploy to azure" button in https://github.com/Azure/azure-quickstart-templates/tree/master/slurm doesn't lead to a successful deployment.

The issue is caused by the link that is auto-filled in _artifacts location:
![image](https://user-images.githubusercontent.com/39995110/71108129-775fdd80-2190-11ea-9370-bd026413190f.png)

It is currently "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/slurm" which returns a 404 when attempting the deployment. It should be "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/slurm/azuredeploy.json"

Please fix it or add a comment to guide anyone who might run into this issue. Thanks.

### Repro steps (*if necessary, delete otherwise*)
1. To reproduce the issue, follow "Exercise 2: Deploy an HPC cluster", steps 1 & 2 in this lab: 
https://github.com/microsoft/computerscience/blob/master/Labs/Azure%20Services/VM%20Scaling/VM%20Scaling.md

**Comment by MihaMarkic** [comment]
This fix doesn't work as if it is applied, then .sh won't download slurm.template.conf file and it won't setup slurm.conf at all.
OTOH if not applied, then template deploy fails sooner

**Comment by MCKLMT** [comment]
@ewekansige The issue has been solved. Can you close it?
