### ISSUE TITLE
101-storage-blob-container - "tier": "Standard" is not defined in schema

### ISSUE THREAD

**Issue by mjcarrabine** [Azure/azure-quickstart-templates#7058]
[101-storage-blob-container](https://github.com/Azure/azure-quickstart-templates/blob/master/101-storage-blob-container/azuredeploy.json)

### Issue Details
In the snippet shown below, `"sku"` contains a `"tier": "Standard"` property that does not seem to be defined in any version of the storageAccounts schema. The schema can be found [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts).

If it is not defined in the schema, why is it used here?

```json
{
            "name": "[parameters('storageAccountName')]",
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2018-07-01",
            "location": "[parameters('location')]",
            "kind": "StorageV2",
            "sku": {
                "name": "Standard_LRS",
                "tier": "Standard"
            },
            "properties": {
                "accessTier": "Hot"
            },
            "resources": [
                {
                    "name": "[concat('default/', parameters('containerName'))]",
                    "type": "blobServices/containers",
                    "apiVersion": "2018-07-01",
                    "dependsOn": [
                        "[parameters('storageAccountName')]"
                    ]
                }
            ]
        }
```

**Comment by MCKLMT** [comment]
@mjcarrabine This issue is outdated. Can you close it?

**Comment by mjcarrabine** [comment]
Sure thing @MCKLMT.

The `tier` property is still not in the schema, but it is included when you choose Export Template in the Azure Portal UI. Interesting.

However, I will close it because it isn't breaking anything for me.
