### ISSUE TITLE
looking for SAS Viya Quickstart Template for Azure on a single machine deployment

### ISSUE THREAD

**Issue by satelitexp** [Azure/azure-quickstart-templates#7118]
[SAS Viya Quickstart Template for Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3a%2f%2fraw.githubusercontent.com%2fAzure%2fazure-quickstart-templates%2fmaster%2fsas-viya%2fazuredeploy.json)

###I am looking for a similar template but for a single machine (SMP) instead for 3 separate machines, for ansible, controller, and services.

**Comment by bmoore-msft** [comment]
ping @sassoftware - github@sas.com
