### ISSUE TITLE
Test test/arm-ttk/testcases/deploymentTemplate/ResourceIds-should-not-contain.test.ps1 started failing, input unchanged

### ISSUE THREAD

**Issue by edburns** [Azure/azure-quickstart-templates#7121]
Consider this "outputs" dictionary from a `mainTemplate.json`:

```
"outputs": {
    "adminHostName": {
        "type": "string",
        "value": "[reference(concat(parameters('adminVMName'),variables('publicIPAddressName'))).dnsSettings.fqdn]"
    }
}
```

Test `ResourceIds-should-not-contain.test.ps1` started failing on the `adminHostName` entry, with this error:

```
[-] ResourceIds should not contain (140 ms) 
    Using "[reference(concat(" is not allowed - found on line: 353 for property: value
```

Looking at the [relevant reference documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#reference), I see this text:

   Typically, you use the reference function to return a particular
   value from an object, such as the blob endpoint URI or fully
   qualified domain name.

   JSON

   "outputs": {
       "BlobUri": {
           "value": "[reference(concat('Microsoft.Storage/storageAccounts/', parameters('storageAccountName')), '2016-01-01').primaryEndpoints.blob]",
           "type" : "string"
       },
       "FQDN": {
           "value": "[reference(concat('Microsoft.Network/publicIPAddresses/', parameters('ipAddressName')), '2016-03-30').dnsSettings.fqdn]",
           "type" : "string"
       }
   }
   
   
As far as I can see, the documentation example and my `adminHostName`
are both valid, according to the reference documentation, yet commit
787a17e7d of `ResourceIds-should-not -contain.test.ps1` added this to the
test.

```
@([Regex]::Matches($TemplateText, "\s{0,}\[\s{0,}reference\s{0,}\(\s{0,}concat\s{0,}\(")) +              # reference(concat(
```

Please advise.  Is the documentation incorrect?  Am I missing something in my code?

Thanks,

Ed

**Comment by edburns** [comment]
I worked around this by declaring this in my `variables`:

```
		"publicIPAddressName": "_PublicIP",
		"outputAdminHostName": "[concat(parameters('adminVMName'),variables('publicIPAddressName'))]",
```

And this in my `outputs`:

```
		"adminHostName": {
			"type": "string",
			"value": "[reference(variables('outputAdminHostName')).dnsSettings.fqdn]"
		},
```

However, I still think there is a documentation issue.   @Olgaian , can you please weigh in?  If the docs need changing, I'll make a PR on that.  Please let me know.

**Comment by teom10** [comment]
> I worked around this by declaring this in my `variables`:
> 
> ```
> 		"publicIPAddressName": "_PublicIP",
> 		"outputAdminHostName": "[concat(parameters('adminVMName'),variables('publicIPAddressName'))]",
> ```
> 
> And this in my `outputs`:
> 
> ```
> 		"adminHostName": {
> 			"type": "string",
> 			"value": "[reference(variables('outputAdminHostName')).dnsSettings.fqdn]"
> 		},
> ```
> 
> However, I still think there is a documentation issue. @Olgaian , can you please weigh in? If the docs need changing, I'll make a PR on that. Please let me know.

I implemented the same work around, thanks @edburns!
