### ISSUE TITLE
It's not possible to execute the template "101-vms-with-selfhost-integration-runtime" using a storage account

### ISSUE THREAD

**Issue by crisansou** [Azure/azure-quickstart-templates#7124]
Hi,

I'm trying to use the template (https://github.com/Azure/azure-quickstart-templates/tree/master/101-vms-with-selfhost-integration-runtime
) to create a logical selfhost IR in Data Factory and I created a storage account to store the scripts. 

I changed the script "azuredeploy.json" to put the storage account and SAS token:

"_artifactsLocation": {
      "type": "string",
      "metadata": {
        "description": "The base URI where artifacts required by this template are located."
      },
      **"defaultValue": "https://stgxxxxx.blob.core.windows.net/ir-scripts/"**
      //"defaultValue": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vms-with-selfhost-integration-runtime/"
    },
"_artifactsLocationSasToken": {
      "type": "securestring",
      "metadata": {
        "description": "The sasToken required to access _artifactsLocation.  When the template is deployed using the accompanying scripts, a sasToken will be automatically generated."
      },
      **"defaultValue": "?sv=2019-02-02&ss=bfqt&srt=sco&sp=rl&se=2030-01-01T03:00:00Z&st=2020-01-07T16:26:37Z&spr=https&sig=dP1sB%2FRGBtv%2F2XXXXXXXXXXXXX%3D"**
      //"defaultValue": ""
    }
  }

But when I ran the template an error occurred in "Microsoft.Compute / virtualMachines / extensions" from "IRInstall.json", the file "gatewayInstall.ps1" wasn't found:

[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Windows PowerShell \r\nCopyright (C) 2016 Microsoft Corporation. All rights reserved.\r\n\r\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "The argument 'gatewayInstall.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.\r\n"
    }
]

I tried to put the "storageAccountName" and "storageAccountKey" parameters in the "IRInstall.json" file as suggested in link "https://github.com/Azure/azure-quickstart-templates/issues/4010" but I received another error message:

"VM has reported a failure when processing extension 'vm0-integrationinstallGW'. Error message: \\\"Failed to download all specified files. Exiting. Error Message: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters"

Does anyone know how to successfully run this template using a storage account?

Best regards,
Cristina

**Comment by bmoore-msft** [comment]
this should be working now - use the scripts in the root of the repo if you run into trouble
