### ISSUE TITLE
101-front-door-create-multiple-backends failing to deploy

### ISSUE THREAD

**Issue by fegonfe** [Azure/azure-quickstart-templates#7137]
[101-front-door-create-multiple-backends](https://github.com/Azure/azure-quickstart-templates/tree/master/101-front-door-create-multiple-backends)

### Issue Details
Template fails with the following message:
`Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Object'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'. (Code: InvalidTemplate)`
### Repro steps (*if necessary, delete otherwise*)
1. click deploy to azure
2. select resource group, fill name and backend pool names
3. click I agree
4. click Purchase

**Comment by bmoore-msft** [comment]
the backend address pool params are not names/strings - they are object params, so you need to enter json objects for those param values (not strings).  To try it out, copy/paste the param values in the param file into param control in the portal.
