### ISSUE TITLE
Why not use Pester for ARM-TTK?

### ISSUE THREAD

**Issue by Makovec** [Azure/azure-quickstart-templates#7138]
[test/arm-ttk](https://github.com/Azure/azure-quickstart-templates/tree/master/test/arm-ttk)

### Issue Details

Why you use native PowerShell instead of Pester tests? Is it related to the complexity of some functions? As I use similar approach for my templates but using Pester directly. I think then it will be easier to maintain TTK and more people will eventually help.

**Comment by bmoore-msft** [comment]
We did look at pester and it didn't add much beyond "regular" PS so didn't want to build the dependency.  You can use it as an output option.
 
But if you can write PS, you can write tests for the TTK.

**Comment by Makovec** [comment]
It is true, but the general idea of testing tools is a bit different. Of course you can do the same with "native" PowerShell (the same is true for other programming languages).
I was thinking more about the consistency of "tests". That I was surprised to not see the format I expected. But understand that ARM is like "different language" and you can check it any supported way. 
OK for me.
