### ISSUE TITLE
Connecting Two Resource Groups

### ISSUE THREAD

**Issue by tfnaylor** [Azure/azure-quickstart-templates#714]
I have a case where I have two separate VM clusters that have different lifecycles, which would indicate to me that they should exist in two separate resource groups. What I am looking for is guidance/examples for how to establish communications between VM's that reside in two separate resource groups.

**Comment by avaranovich** [comment]
Did you try to reference resources using full resource IDs? (opposite to variables specific to a current resource group)

**Comment by tfnaylor** [comment]
Actually, it never occurred to me that this might be possible. Thanks very much for this suggestion - I will investigate to see if this works in our particular use-case. Thanks again.
