### ISSUE TITLE
Flow Logs Version 2

### ISSUE THREAD

**Issue by tw3lveparsecs** [Azure/azure-quickstart-templates#7178]
[101-networkwatcher-flowLogs-create](https://github.com/Azure/azure-quickstart-templates/blob/master/101-networkwatcher-flowLogs-create/azuredeploy.json)

### Issue Details
Template deploys successfully when setting the flow logs version to "2", but when checking the flow logs version in the Azure portal it is still set to version 1.

### Repro steps
1. Deployed template with default value
2. Modified template and set: "version": "2"
3. Modified template and set: "version": 2

`"format": {
                                            "type": "JSON",
                                            "version": 2
                                        }`

All attempts end up in the same result.

**Comment by MCKLMT** [comment]
I'm not able to reproduce the described behavior. Please check on your side.

**Comment by tw3lveparsecs** [comment]
Yep doesn't seem to be an issue anymore.
