### ISSUE TITLE
Deployment of 201-vm-linux-jupyterhub is failing.

### ISSUE THREAD

**Issue by georgebisbas** [Azure/azure-quickstart-templates#7185]
[201-vm-linux-jupyterhub](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-linux-jupyterhub)

### Issue Details
Dear all at Azure,

I am trying to deploy 201-vm-linux-jupyterhub under my Azure subscription,
however deployment always fails with:
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'installscript'. Error message: \\\"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: unexpected status code: actual=404 expected=200\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}
```

### Repro steps (*if necessary, delete otherwise*)
1. I clicked the Deploy to Azure button here: https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-linux-jupyterhub

Question: Are there any prerequisites I need to take into account before I click deploy?

P.S. I am fairly new to Azure and familiar in the level of Basic Azure Fundamentals. Any help would be valuable and highly appreciated. Thank you in advance,
George Bisbas

**Comment by georgebisbas** [comment]
Hi @leestott,

any chance you have some info about this?
I can see you are the author, so I suspect you
could provide some help for me. 

Thank you in advance,
George Bisbas

**Comment by leestott** [comment]
Hi @georgebisbas so this looks like a permission failure what type of subscription are you deploying this too and what size VM are you selecting? Does the 101 JupyterHub deployment work as this uses smaller VM sizes. Which should be permitted on all subscriptions.

**Comment by georgebisbas** [comment]
Hi @leestott, thanks for the heads up.
We have an Azure Sponsorship. I have tried with most of the smaller VMs proposed. I can confirm that 101 is being deployed, however I cannot see any Jupyterhub available use there.

**Comment by leestott** [comment]
Are you following the post deployment steps https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-linux-Jupyterhub/README.md and connecting to the IP

**Comment by leestott** [comment]
@georgebisbas you need to wait approx 10 mins after the VM deployed to allow the Jupyterhub to be full installed as this is done with a VM custom extension script. You should be able to see disk activity in the Azure Portal and once the script has run you can access the Jupyterhub via the public IP address.

**Comment by georgebisbas** [comment]
Hi @leestott, so the deployment is being succesfull, but nothing seems to be happening after that. Disk activity is always zero, after half an hour. So I cannot run the post deployment steps,  `sudo tljh`...

**Comment by georgebisbas** [comment]
So by navigating to HOME> VM>installscript,

I can see that:
```
Enable succeeded: [stdout] [stderr] install.sh: line 1: !/bin/bash: No such file or directory install.sh: line 3: bootstrap.py: command not found 
```

**Comment by georgebisbas** [comment]
Hi @leestott , 
following this: http://tljh.jupyter.org/en/latest/install/azure.html
I managed to make things work. Indeed in this approach the post-installation script did work as expected.

**Comment by leestott** [comment]
@georgebisbas  thanks yes the main http://tljh.jupyter.org/en/latest/install/azure.html has been fixed and I am trying figure out why the post execution isnt working on the 201-vm-linux-jupyterhub as a quick fix you can manually run 

sudo apt install python3 python3-dev git curl

curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin <admin-user-name>  

And this will install Jupyter onto the server.

**Comment by georgebisbas** [comment]
Thanks for the info @leestott !

**Comment by leestott** [comment]
@bmoore-msft  this can be closed instructions updated to include script if install fails with a curl from latest TLJH Installer.

**Comment by georgebisbas** [comment]
I agree this can be closed. I would like to thank everyone for the support.
