### ISSUE TITLE
(101-loadbalancer-with-nat-rule/azuredeploy.json) errors

### ISSUE THREAD

**Issue by drewhildebrand** [Azure/azure-quickstart-templates#719]
1) loadBalancerBackendAddressPools & loadBalancerInboundNatRules (lines 114-127) are at the wrong level.  They are currently at the same level as properties, but they should be INSIDE the properties block, at the same level as subnet.  When you deploy that script azure just ignores those 2 blocks of json and does not report any errors.

2) /inboundNatRule/RDP')]" (line 123) should be plural not singular.  inboundNatRules

**Comment by singhkay** [comment]
@ypitsch Can you take a look at this?

**Comment by ypitsch** [comment]
Fixed. Thanks!
