### ISSUE TITLE
Data disk and NIC names?

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-quickstart-templates#7192]
Hi
I'm going nuts trying to understand how to use a VM template with both the template and parameter files to create multiple VMs.
I don't understand how I can use these files to auto generate the names for the nic and the Data Disks.
I managed to create the nic name by removing it completely from the parameters and by setting the NIC name to 
`"nicName": "[concat(parameters('virtualMachineName'), substring(uniqueString(resourceGroup().id),0,4))]"`

However I have no idea how to do this for the Data disks since it's a nested property and it seems i can't use functions inside the parameters file. If i use concat inside the parameters file, it takes it literally.

I donwloaded the .json from a normal deploy from the portal but it came with the already calculated values (VMName_DataDisk_lunnumber, VMName+randomnumbers for nic)
Please, help me understand how I can automate these properties instead of being static.

**Comment by MCKLMT** [comment]
Please share template used to get help.
