### ISSUE TITLE
TypeHandlerVersion Error

### ISSUE THREAD

**Issue by prateekjain0608** [Azure/azure-quickstart-templates#720]
[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'createadforest'. Error message: \"A previous attempt to install WindowsBlue-KB3055381-x64.msu failed; please check the logs on the VM (C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.Powershell.DSC\\1.9.0.0)\"."}]}}

This is the error I am getting when finally the extension is processed. I figured out that this was due to the type handler version. But if i put the latest version (2.7) then the ADDC VM does not get updated as domain controller. Then obviously, the DomainJoin script fails too.

**Comment by drewnicholas1111** [comment]
Hello, I was seeing if you were able to figure this error out? I am trying to do a domain join and getting the same error.

**Comment by prateekjain0608** [comment]
Hey,
You need to put in version 2.7 instead of 1.9. That will do.

Please note that do not change the type handler version from 1.7 to 2.7 as
it will create some problems.

Only change the versions which are 1.9 to 2.7

**Comment by drewnicholas1111** [comment]
Are you saying the SDK on my computer or on the virtual machine? I have the 2.7 SDK on my local environment.

**Comment by prateekjain0608** [comment]
In the quick start template, JSON script where the DSC extension is
created.

**Comment by singhkay** [comment]
@prateekjain0608 I think DSC 2.8 is released now. Can you try with that?

**Comment by prateekjain0608** [comment]
Surely, will try.
It should work with that too.
