### ISSUE TITLE
convert arm template output array to string to be consumed by terraform

### ISSUE THREAD

**Issue by fgarcia-cnb** [Azure/azure-quickstart-templates#7215]
We have an arm template with the following outputs (static list of managed identities) to be consumed by terraform:

```jsonc
"outputs": {
        "managedIdentity1": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 1), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[0].name, '2016-08-01', 'Full').identity.principalId]"
        },
        "managedIdentity2": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 2), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[1].name, '2016-08-01', 'Full').identity.principalId]"
        },
        "managedIdentity3": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 3), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[2].name, '2016-08-01', 'Full').identity.principalId]"
        }
//continues,
```
I'd like to refactor this to be a dynamic list that will match the webAppCountNum. I believe I can accomplish this using [output iteration](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/copy-outputs), although there might be an issue using the reference function with count (haven't tested yet):
from [msdoc](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#reference)
> You can't use it with count because the count must be determined before the reference function is resolved.

there is also a separate issue where terraform [can only access scalar outputs](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html#outputs)

with all these limitations...
### is there a way to generate this dynamic output list and have it be consumable by terraform?
My idea was to convert the output array into a comma delimited string and have terraform split the data, but the restrictions on the "reference" function limit its use. If i could generate the array, i could probably convert it using [this method](https://stackoverflow.com/questions/48324984/convert-array-parameter-values-to-comma-separated-string)

**Comment by bmoore-msft** [comment]
you can use reference() in copy output... docs have a sample, here's another: https://github.com/bmoore-msft/AzureRM-Samples/blob/master/copy-output/azuredeploy.json#L66

@tfitzmac - can you check into the docs issue where we mention this can't be done in a loop (docs are wrong)

**Comment by tfitzmac** [comment]
@bmoore-msft - yes, I'll fix that.

**Comment by tfitzmac** [comment]
@bmoore-msft - I see that what I was trying to say was that you can use reference when setting the count property, like "count": "[length(reference('someResource').someArray)]". I would assume that limitation still exists, but I'll clarify the text in the doc.

**Comment by bmoore-msft** [comment]
you are correct, you cannot use a runtime function for the copy property's direct descendants. (only in the input)

**Comment by fgarcia-cnb** [comment]
i guess the bigger constraint is that terraform only likes scalar outputs. i cant use an output array. is there a way to use the resource function to get a list of all managed identities, and join them with a comma and output as a single comma-separated string?

**Comment by bmoore-msft** [comment]
Probably best to direct that question to TF
