### ISSUE TITLE
Promises linux but runs on windows: 201-web-app-java-tomcat 

### ISSUE THREAD

**Issue by ricksbrown** [Azure/azure-quickstart-templates#7296]
201-web-app-java-tomcat promises this:

>> This template deploys a simple Linux Web Application with Java 8 and Tomcat 9 enabled allowing you to run Java applications in Azure.

However it runs on windows.

**Comment by bmoore-msft** [comment]
@leestott

**Comment by leestott** [comment]
Apologies issue with metadata.json listing OS as linux changed this to say windows and PR submitted.
