### ISSUE TITLE
Issue in the quick-start-template regarding ADFv2 availability

### ISSUE THREAD

**Issue by tioumen** [Azure/azure-quickstart-templates#7330]
#6460 # Issue Details

Readme regarding data factory is mentionning only availability for ADFv2 is available in US. It is working for other locations, west and north europe for instance.

Link to the document/README : https://github.com/Azure/azure-quickstart-templates/blob/master/101-data-factory-v2-blob-to-blob-copy/README.md

**Comment by MCKLMT** [comment]
I don't understand the issue. The README file does not mention this sentence.
Can you explain?

**Comment by tioumen** [comment]
Removed since this commit : 5e7525c2d463d0bb8cc63d3ecdfc5538b05cabdc

**Comment by MCKLMT** [comment]
So please close the issue

**Comment by tioumen** [comment]
Fixed
