### ISSUE TITLE
101-acsengine-swarmmode: minor problems

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-quickstart-templates#7354]
[101-acsengine-swarmmode](https://github.com/Azure/azure-quickstart-templates/blob/master/101-acsengine-swarmmode/azuredeploy.json)

### Issue Details
1) frontendPort should be an integer
2) Microsoft.Compute/virtualMachines/extensions missing required properties autoUpgradeMinorVersion and protectedSettings

### Repro steps (*if necessary, delete otherwise*)
1. Load file in vscode with ARM tools extension
2. Upgrade apiVersion for inboundNatRules to 2019-12-01 (2 places)
3. errors:
OneOf (Require 1 match, following 2 not matched):
    Value must match the regular expression ^\[([^\[].*)?\]$
    integer
Missing required property "autoUpgradeMinorVersion"
Missing required property "protectedSettings"

**Comment by MCKLMT** [comment]
@StephenWeatherford Can you close the issue?

**Comment by StephenWeatherford** [comment]
thx
