### ISSUE TITLE
101-vm-with-rdp-port - new Subnet-nsg blocks RDP access 

### ISSUE THREAD

**Issue by begler1** [Azure/azure-quickstart-templates#7356]
101-vm-with-rdp-port https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-with-rdp-port 

### Issue Details
new Subnet-nsg blocks RDP access

After deploying the template, attempted to use Load Balancer to access the VM through Port 50001 which should NAT to Port 3389 for RDP but it is blocked by new Subnet-nsg (DenyAllInBound Rule according to NSG Logs). This template worked OK before latest update March 2020. 

To fix:
Add an Allow RDP Inbound rule to Subnet-nsg for Port 3389. 
Then use Load Balancer again to access the VM through Port 50001 which NATs to Port 3389 for RDP. Fully tested as successful.

See attached screenshots from Network Watcher below before and after Fix.
![Screenshot (5013)](https://user-images.githubusercontent.com/22414394/77996838-62045e80-72fc-11ea-88b6-59eba4d9bf2e.png)
![Screenshot (5016)](https://user-images.githubusercontent.com/22414394/77996918-89f3c200-72fc-11ea-94c3-fac51a4c2f40.png)
![Screenshot (5021)](https://user-images.githubusercontent.com/22414394/77997015-b4de1600-72fc-11ea-8ae2-644ff07b753d.png)

**Comment by bmoore-msft** [comment]
@JohnathonMohr - can you have a look?

**Comment by JohnathonMohr** [comment]
Thanks @begler1 for bringing this to our attention.  The intent was to have traffic flow through the default NSG rule 65001: AllowAzureLoadBalancerInBound.  Apparently this isn't working as desired, so the NSG needs updating.  I have a PR open here: https://github.com/Azure/azure-quickstart-templates/pull/7376.

**Comment by bmoore-msft** [comment]
#7376 has been merged
