### ISSUE TITLE
'Template parameter JToken type is not valid. Expected 'Integer'. Actual 'String' While creating ASE in terraform  v0.11.7

### ISSUE THREAD

**Issue by prathap9000** [Azure/azure-quickstart-templates#7366]
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "aseName": {
            "type": "string",
            "metadata": {
                "description": "Name of the App Service Environment"
            }
        },
        "aseLocation": { 
            "type": "string",
            "defaultValue": "South Central US",
            "metadata": { 
                "description": "Location of the App Service Environment" 
            } 
         },
        "existingVirtualNetworkName": {
            "type": "string",
            "metadata": {
              "description": "Name of the existing VNET"
            }
        },
        "existingVirtualNetworkResourceGroup": {
            "type": "string",
            "metadata": {
              "description": "Name of the existing VNET resource group"
            }
        },
        "subnetName": {
            "type": "string",
            "metadata": {
                "description": "Subnet name that will contain the App Service Environment"
            }
        },
        "internalLoadBalancingMode": {
            "type": "int",
            "defaultValue": 3,
            "allowedValues": [0,1,2,3],
            "metadata": {
                "description": "0 = public VIP only, 1 = only ports 80/443 are mapped to ILB VIP, 2 = only FTP ports are mapped to ILB VIP, 3 = both ports 80/443 and FTP ports are mapped to an ILB VIP."
            }
        },
        "dnsSuffix": {
            "type": "string",
            "metadata": {
                "description": "Used *only* when deploying an ILB enabled ASE.  Set this to the root domain associated with the ASE.  For example: contoso.com"
            }
        }
    },
    "variables":{
        "vnetID": "[resourceId(parameters('existingVirtualNetworkResourceGroup'), 'Microsoft.Network/virtualNetworks', parameters('existingVirtualNetworkName'))]"
    },
    "resources": [
      {
        "apiVersion": "2015-08-01",
        "type": "Microsoft.Web/hostingEnvironments",
        "name": "[parameters('aseName')]",
        "kind": "ASEV2",
        "location": "[parameters('aseLocation')]",
        "properties": {
          "name": "[parameters('aseName')]",
          "location": "[parameters('aseLocation')]",
          "ipSslAddressCount": 0,
          "internalLoadBalancingMode": "[parameters('internalLoadBalancingMode')]",
          "dnsSuffix" : "[parameters('dnsSuffix')]",
          "virtualNetwork": {
            "Id": "[variables('vnetID')]",
            "Subnet": "[parameters('subnetName')]"
          }
        }
      }
    ]
}

### Issue Details
when i ran terraform with template deployment for above template i am getting this error
* azurerm_template_deployment.deploy: Error validating Template for Deployment "mydeployment" (Resource Group "*****"): Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Integer'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'

i have passed below parameters

parameters = {
    "aseName" = "MyASE"
    "aseLocation" = "${var.location}"
    "existingVirtualNetworkName"="${azurerm_virtual_network.vnet.name}"
    "subnetName"="${azurerm_subnet.ase_subnet.name}"    
    "internalLoadBalancingMode"="0"
    "existingVirtualNetworkResourceGroup"="${var.resource_group_name}"
    "dnsSuffix"= ""
  }

**Comment by bmoore-msft** [comment]
I'm not very familiar with TF - but it looks like your internalLoadBalancingMode parameter is a string, and you have it deinfed as an int in the template.

**Comment by prathap9000** [comment]
even if i changed it to integer also still same issue

**Comment by bmoore-msft** [comment]
Sounds like a TF bug, I would reach out to them
