### ISSUE TITLE
Traefik is stops

### ISSUE THREAD

**Issue by BozidarP** [Azure/azure-quickstart-templates#7400]
I have installed all environment, have 6-7 containers in VM on Azure:

I use:  http://aka.ms/getbc, use traeffik and specify an email for letsencrypt.

Its works great, until today, I cannot start traefik .
Any suggest what to do?

![image](https://user-images.githubusercontent.com/44054400/79369682-a70dcf00-7f51-11ea-9e73-da2fe8a45aae.png)

**Comment by freddydk** [comment]
https://www.github.com/microsoft/navcontainerhelper/issues would be a better place for this.

**Comment by BozidarP** [comment]
Its moved.
