### ISSUE TITLE
VM has reported a failure when processing extension 'nfinit'

### ISSUE THREAD

**Issue by Niel27** [Azure/azure-quickstart-templates#7402]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Issue Details
When deploying the template am getting an error saying VM has reported a failure when processing extension 'nfinit'. Both jumpboxVM and cluster failed. Anyone knowing the solution kindly assist.

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by MCKLMT** [comment]
Which template is it?

**Comment by Niel27** [comment]
> Which template is it?
The nextflow-genomics-cluster-ubuntu in azure

**Comment by MCKLMT** [comment]
@Niel27 I'm not able to deploy the template using the deploy button. Is it OK for you?

**Comment by Niel27** [comment]
@MCKLMT  now am not able to do that too saw one solution am trying to find where exactly to remove the quotes.

#7491

**Comment by MCKLMT** [comment]
I have submitted a pull request (#7990) to solve the issue.

**Comment by MCKLMT** [comment]
@Niel27 The pull request has been accepted and merged. Can you try to deploy again? 🤞🏻

**Comment by Niel27** [comment]
Hi @MCKLMT ,

Yes it working now, does your deployment run successfully? am getting an error that says

"Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '76ddaf54-fc73-45ca-86e3-8a8e61b825d4'."

**Comment by MCKLMT** [comment]
Yes, my deployment was successful.

**Comment by Niel27** [comment]
Okay am getting an error may be because am using the free subscription

**Comment by Niel27** [comment]
@MCKLMT 

Thanks its working now I had to change vm size.

**Comment by MCKLMT** [comment]
Great! Can you close the issue?
