### ISSUE TITLE
undocumented resource type?

### ISSUE THREAD

**Issue by pietersap** [Azure/azure-quickstart-templates#7426]
referring to [this quickstart template](https://github.com/Azure/azure-quickstart-templates/blob/master/101-app-service-regional-vnet-integration/azuredeploy.json)

Is it possible that the resource type ```Microsoft.Network/virtualNetworks/subnets``` is [not documented](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/allversions)?

**Comment by bmoore-msft** [comment]
See: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2020-04-01/virtualnetworks/subnets
