### ISSUE TITLE
101-SQL-Injection-Attack-Prevention

### ISSUE THREAD

**Issue by junichia** [Azure/azure-quickstart-templates#7459]
[Template Name goes here](Template link goes here)
101-SQL-Injection-Attack-Prevention

### Issue Details
Error occurs as below when deploying template. 

Error encountered during the service operation. ; Exception Microsoft.SqlServer.Management.Dac.Services.ServiceException:Unexpected exception encountered while retrieving metadata for blob amp;#39;https://templatebotstorage.blob.core.windows.net/bacpacs/contosoclinic.bacpac

I did followings to resolve.

1. created new storage account
2. create bacpacs container
3. download Clinic.bacpac file from https://github.com/Microsoft/sql-server-samples/blob/master/samples/features/security/contoso-clinic/setup/Clinic.bacpac
4. rename Clinic.bacpac to contosoclinic.bacpac
5. upload contosoclinic.bacpac
6. modify anonymous security of container
7. replace bacpacurl value in the azuredeploy.json
8. deploy template

**Comment by bmoore-msft** [comment]
#7582
