### ISSUE TITLE
The deploy doesn't work from readme files

### ISSUE THREAD

**Issue by k0rvih** [Azure/azure-quickstart-templates#7460]
### Issue Details
I've tried to deploy some templates from the repo but I was redirected to the page with a picture. 
**Deploy to Azure** doesn't initiate any deploy, just open a new tab with a picture.
It looks like the link is wrong for all the deploy buttons.

**Comment by begler1** [comment]
I get the same behavior. Redirects to the following URL: 

https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true  

Tested on Edge and Chrome with same results.

![Screenshot (5069)](https://user-images.githubusercontent.com/22414394/80279017-d696a700-86c8-11ea-9ba5-ecf817144248.png)

**Comment by KingKongPhoey** [comment]
Go back to previous version works

**Comment by mct370770** [comment]
Somebody has here committed changes that breaks the "Deploy to Azure" and "Visualize" - and appearently these people has not tested if their changes worked before committing!

May I introduce these people in some fancy technology called "Change Management"?

**Comment by bmoore-msft** [comment]
should be fixed now
