### ISSUE TITLE
Visualize - blank

### ISSUE THREAD

**Issue by jaydarius** [Azure/azure-quickstart-templates#7461]
101 simple windows vm - https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-windows/

### Repro steps (*if necessary, delete otherwise*)
1. Click on Visualize 
2. New tab opens
3. See in new tab nothing except blue Visualize button
![image](https://user-images.githubusercontent.com/31786606/80285633-f8555580-86eb-11ea-84bd-a3ff2a77f346.png)

**Comment by matejkooo** [comment]
The same problem with all templates

**Comment by KingKongPhoey** [comment]
Same Problem for me

**Comment by sbollap1** [comment]
one more thing I don't understand is why there are two "resources" : in the file never seen that before

**Comment by bmoore-msft** [comment]
should be fixed now
