### ISSUE TITLE
Link broken in last update of azure-quickstart-templates / 201-vmss-bottle-autoscale

### ISSUE THREAD

**Issue by mct370770** [Azure/azure-quickstart-templates#7462]
[Template Name goes here](Template link goes here)
azure-quickstart-templates / 201-vmss-bottle-autoscale

### Issue Details
The links "Deploy to Azure" and "Visualize" is broken - they only shows the vsg file

### Repro steps (*if necessary, delete otherwise*)
1. Click on either link 
2. Somebody has here committed changes that breaks the "Deploy to Azure" and "Visualize" - and appearently these people has not tested if their changes worked before committing!

May I introduce these people in some fancy technology called "Change Management"?

**Comment by Exnav29** [comment]
I am experiencing the same issue now.

**Comment by bmoore-msft** [comment]
should be fixed now
