### ISSUE TITLE
Budget unable to filter on tags

### ISSUE THREAD

**Issue by sporter83** [Azure/azure-quickstart-templates#7469]
[create-budget](https://github.com/Azure/azure-quickstart-templates/tree/master/create-budget)

### Issue Details
Hi! - we've been unable to add any form of filtering on tags via ARM template (example: [New-Billing.txt](https://github.com/Azure/azure-quickstart-templates/files/4552378/New-Billing.txt)), we've tried adding;
```JSON
    *"filters": {
       "tags": {
          "tagname": "[parameters('tagvalue')]"
       }
    }*
```
Without the "filters" section the template works as expected. We have tried a few variants of the above section but all have been unsuccessful, mostly met with a "error 401 - unauthorized" or sometimes a "400 - Invalid budget configuration, please use filter interface with 2019-05-01-preview version".

We can create a budget along with tag filtering via the portal UI wizard, but this does not give the ARM template at the end to be able to copy from.

Digging into the [schema](https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#) it looks like this should be possible, but is there any known way to get this working?

Thanks,
- Shaun.

**Comment by bmoore-msft** [comment]
@sporter83 - Can you try posting this in the docs forum or tweet @AzureSupport?

**Comment by TiloGit** [comment]
see https://github.com/Azure/azure-cli/issues/29950
