### ISSUE TITLE
Gets hang when you click on "Deploy in azure" or visualize option. New tab gets opened but nothing works further. 

### ISSUE THREAD

**Issue by bhaskardixit26** [Azure/azure-quickstart-templates#7480]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by bhaskardixit26** [comment]
Gets hang when you click on "Deploy in azure" or visualize option. New tab gets opened but nothing works further.

**Comment by joeyleondlovu** [comment]
Hit the same issue as soon as I select Visualize I get a blank page

**Comment by bmoore-msft** [comment]
this should be fixed now
