### ISSUE TITLE
101-webapp-linux-sonarqube-azuresql template vm.max_map_count error

### ISSUE THREAD

**Issue by FastLee** [Azure/azure-quickstart-templates#7481]
[Template Name goes here](Template link goes here)

### Issue Details
After deploying the template and running sonar qube I'm getting
a ":( Application Error" message.
The log is showing the following error:
`max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

### Repro steps (*if necessary, delete otherwise*)
1. Ran the template
2. SonarQube version 7.9
3. Opened the browser, pointing to the app
4. Retrieved the _default_docker.log file
5. The Radarqube documentation indicates that the vm.max_map_count has to be set using sysctl command.

**Comment by RanojitMitra** [comment]
I have faced the same issue and it seems you cannot change the run time environment (vm.max_map_count) of Azure Web Apps, you can only have access to view the environment.

**Comment by Bjego** [comment]
Is anyone taking care of these templates?
I've tried it as well - also with a docker compose config to set the values. But Azure doesn't seem to like changing the requried hosting options.

**Comment by sam-quant** [comment]
+1 the same issue, any ideas how to run it with Azure Web apps?

**Comment by cjwelliott** [comment]
+1 same issue. Unusable in Azure

**Comment by sylvain-combe-sonarsource** [comment]
Hello here
SonarQube container official image enforces MMAP prerequisites so that it embedded ElasticSearch node performs as expected.
To fix this issue, applying the following snippet from the [ElasticSearch template script](https://github.com/Azure/azure-quickstart-templates/blob/master/elasticsearch/scripts/elasticsearch-ubuntu-install.sh) seems the way to go:
```
# Increase maximum mmap count
echo "vm.max_map_count = 262144" >> /etc/sysctl.conf
```

**Comment by MarkusBrgr** [comment]
+1 having the same Issue.

@sylvain-combe-sonarsource Where would you execute this command?

**Comment by sylvain-combe-sonarsource** [comment]
Hello @MarkusBrgr 
this command needs to be called on the host.
The ElastiSearch template is configuring the right script to run depending on the target OS from its main [quickstart json file](elasticsearch/azuredeploy.json).
A proper way to update this SonarQube template would be to provide similar (simplified) scripts pushing this parameter in an automated way. I miss the proper know-how to propose this fix myself (and the time to learn it at the moment).

Best.
Sylvain

**Comment by PlagueHO** [comment]
I created the original ARM template here, but hadn't noticed that recent versions of Sonarqube (7.8 and above to be precise) included ElasticSearch.

I've been researching solutions and it seems that all indicate that SQ 7.8 and above requires `vm.max_map_count = 262144` being set on the host (to allow ES to start). See https://github.com/sonarsource/docker-sonarqube/issues/279

However, as far as I can tell this is not something that can be set on Azure App Service for Linux Containers. So it isn't a limitation of ARM, it _appears_ to be a limitation of Azure App Service.

Some other changes to this template that I'd suggest:
1. Change the ARM template `sonarqubeImageVersion` parameter to only allow image versions that actually work -or- change the default value for `sonarqubeImageVersion` to `7.7-community` (the most recent working version).
2. Change the `firewallrules` on the database to allow only traffic from Azure - not *. This will tighten up the default security.
3. Improve the SQL connection string by adding: `;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;` as per current Azure SQL Server connection string generated by the portal.
4. Add a note to the README.md indicating that versions SQ versions 7.8 and above are not currently working - or something to that effect.
5. Add another configuration to the WebApp: `"sonar.path.data": "/home/sonarqube/data"` - this will configure Sonarqube to use the persistent shared volume mounted as part of the Azure App Service for any data that it can be helpful to persist between restarts. This will only reduce the time it takes to start up after an App Service restart.

Not sure if anyone has any views on this or recommendations?

**Comment by Japeth** [comment]
I want to add, since I recently ran into this issue as well and am trying to run a container of SQ in Azure.

-Dnode.store.allow_mmapfs=false is for SonarQube < 8.x
I was upgrading our SQ instance from 7.6.x to 9.2.x
For the first upgrade to 7.9.1 LTS, I had had to use allow_mmapfs
After that, upgrading to 8.9.1 and then to 9.2 I had to use -Dnode.store.allow_mmap=false

ALSO,
in Azure, you don't need to roll your own container based off the official dockerhub one. You can just use the dockerhub official image, and set a Configuration Setting/Environment Var for the container of:
SONAR_SEARCH_JAVAADDITIONALOPTS = -Dnode.store.allow_mmap=false

Hope this helps anyone else that stumbled down this rabbithole!

**Comment by pheeling** [comment]
@Japeth Hi
I'm running into the same issue. Have you tried to it with an ARM template or your own yml file? If so can you share you're templates.

Thanks for a feedback.

Best regards Philipp

**Comment by cesarmiggiolaro** [comment]
@PlagueHO thanks for you answer, I set ` SONAR_SEARCH_JAVAADDITIONALOPTS = -Dnode.store.allow_mmap=false` and it worked for me.

**Comment by g7crservice-sajid-f** [comment]
I want to use **sonarqube:9.9.4-community**, can someone update whether the **elastic limitation is fixed?**
