### ISSUE TITLE
Deploy to Azure button is not working. 

### ISSUE THREAD

**Issue by jupata89** [Azure/azure-quickstart-templates#7491]
[active-directory-new-domain)

### Repro steps (*if necessary, delete otherwise*)
1. Click Deploy to Azure or any other button
2. It doesn't deploy
![image](https://user-images.githubusercontent.com/56523966/80897480-b06f9900-8cbe-11ea-84db-95a870285ed2.png)

**Comment by rajakasinathan** [comment]
Same for me as well.

**Comment by al-lac** [comment]
Should be resolved by #7502.

**Comment by rajakasinathan** [comment]
Thanks for resolving it. I used the previous version.

**Comment by bmoore-msft** [comment]
thanks @al-lac
