### ISSUE TITLE
Deploy a simple Windows VM template is not publicly accessible

### ISSUE THREAD

**Issue by andreprawira** [Azure/azure-quickstart-templates#7503]
[Deploy a simple Windows VM](https://azure.microsoft.com/en-us/resources/templates/101-vm-simple-windows/)

### Issue Details
I tried to deploy a simple Windows VM, but I got this response instead "There was an error loading the template from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-windows/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments."
### Repro steps (*if necessary, delete otherwise*)
1. Go to https://azure.microsoft.com/en-us/resources/templates/101-vm-simple-windows/
2. Click "Deploy to Azure"
3. Sign in to Azure portal
4. Got the error message

**Comment by bmoore-msft** [comment]
I'm not seeing this now... it's possible it was a transient issue /w github or portal.... if you see it again, feel free to reopen or file an issue in the portal
