### ISSUE TITLE
Recommend TightVNC in docs

### ISSUE THREAD

**Issue by EgoAleSum** [Azure/azure-quickstart-templates#753]
The page https://github.com/Azure/azure-quickstart-templates/tree/master/ubuntu-desktop provides instruction on how to connect to a Linux VM via VNC over a SSH tunnel. The guide uses a complicate setup with two different applications (PuTTY and a VNC client).

A better alternative (i.e. easier and thus more user-friendly) would be using TightVNC, which has built-in support for SSH tunneling: http://www.tightvnc.com

**Comment by singhkay** [comment]
@EgoAleSum Good suggestion! Feel free to edit the file and add an alternative guide :) We welcome community contributions and improvements! 

cc: @anhowe if he wants to take a crack at it

**Comment by anhowe** [comment]
Thanks for the suggestion @EgoAleSum I have researched this in great detail in the past, and tight vnc did not match the perf and quality of using vnc over a compressed ssh tunnel across Linux, windows, and mac and across various sizes of internet pipes.  

My research is a few years old, so if there has been recent improvements in tight vnc across all platforms and it can be demo'd that it is noticeably better than vnc over a compressed ssh tunnel, we'll consider this.

Thanks, Anthony

-----Original Message-----

**Comment by EgoAleSum** [comment]
Hi Anthony, thank you a lot for the detailed answer. I completely understand your point about performances - I'm not sure TightVNC offers that indeed.

In this case, may I then suggest listing TightVNC as an alternative option? I can see certain scenarios in which users need a quick fix and are not too concerned with the quality of the connection - so anything more user-friendly would help.

I can create a PR if you are interested.

**Comment by singhkay** [comment]
@EgoAleSum Sure, please go ahead and create a PR detailing an alternative guide on how to use TightVNC for this
