### ISSUE TITLE
Template syntax error

### ISSUE THREAD

**Issue by mattmelton** [Azure/azure-quickstart-templates#7534]
[New webapp custom domain and ssl](https://github.com/Azure/azure-quickstart-templates/blob/master/webapp-keyvault-ssl/azuredeploy.json#L113)

### Issue Details

Missing opening square bracket in value:
`"siteName": "parameters('webAppName'))]",` should be `"siteName": "[parameters('webAppName'))]",`

**Comment by bmoore-msft** [comment]
merged
