### ISSUE TITLE
create budget template missing detail on multiple notifications

### ISSUE THREAD

**Issue by pmozbert** [Azure/azure-quickstart-templates#7543]
[create-budget](https://github.com/Azure/azure-quickstart-templates/tree/master/create-budget)

### Issue Details
The deploy.json template shows a notification array with a single item named "First-Notification".  It is not documented whether the names of notification items are fixed, or if any string can be used.  Is the order of notifications based on the threshold value, or on the name?  Does the next name need to be "Second-Notification"?

**Comment by bmoore-msft** [comment]
The documentation shows the notifications as a dictionary object, which means the name can be anything.  I don't see anything that indicates the order of notifications, just the threshold.  I would recommend asking in the docs forum or StackOverflow - could also tweet @AzureSupport.
