### ISSUE TITLE
101-cosmosdb-create vs 101-cosmosdb-sql

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-quickstart-templates#7581]
Templates in question:

- https://github.com/Azure/azure-quickstart-templates/tree/master/101-cosmosdb-create
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-cosmosdb-sql

### Issue Details

Both are near identical, basically the only difference is in the API version.

It might be confusing for the customers, especially who just start. Should one of them be deleted?
If yes then it probably should be the "create" one as it uses an older API version.

/cc @markjbrown, @bmoore-msft.

**Comment by markjbrown** [comment]
The first one was created by @SnehaGunda and is used for our [ARM Template QuickStart doc](https://docs.microsoft.com/en-us/azure/cosmos-db/quick-create-template).

But yes agree it's largely duplicative and the quickstart doc could use the other one which I maintain and keep up to date.

**Comment by bmoore-msft** [comment]
@markjbrown - can you submit the PR to delete when the docs are updated

**Comment by markjbrown** [comment]
Yes sure. Give us a week or so if ok. We've got a ton of things to clean up after BUILD but will get to it.

Thanks!

**Comment by bmoore-msft** [comment]
sounds good - no rush, just don't want to forget...

**Comment by markjbrown** [comment]
Just submitted a PR to remove this template.
https://github.com/Azure/azure-quickstart-templates/pull/7644

Can merge at any time. Our docs now point to another I authored.

Thanks.
