### ISSUE TITLE
ARM template for Redis cache does not have minimum TLS version 

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-quickstart-templates#7608]
https://github.com/Azure/azure-quickstart-templates/blob/master/101-redis-cache/azuredeploy.json

### Issue Details
The redis template does not specify the minimum TLS version in the ARM template. This makes Azure portal to display the warning message.

** TLS 1.0 and 1.1 support is being retired soon, which may impact... **

**Comment by bmoore-msft** [comment]
@steved0x

**Comment by bmoore-msft** [comment]
thx @MCKLMT
