### ISSUE TITLE
Redis cache failed to deploy because of invalid storage account

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-quickstart-templates#7609]
https://github.com/Azure/azure-quickstart-templates/blob/master/101-redis-cache/azuredeploy.json

### Issue Details
I tried deploying a Basic Redis instance using the ARM template. After a wait of more than 15 minutes the deployment completed and the portal reported a failure.

```
{
"code":"DeploymentFailed",
"message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
"details":[
{
"code":"BadRequest",
"message":"{\r\n \"error\": {\r\n \"code\": \"LinkedInvalidPropertyId\",\r\n \"message\": \"Property id 'GET-PREREQ-existingDiagnosticsStorageAccountId' at path 'properties.storageAccountId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.\"\r\n }\r\n}"
}
]
}

```
I can understand that the storage account specified in the `parameters.json` "GET-PREREQ-existingDiagnosticsStorageAccountId" is not valid. I should have provided a valid storage account id. 

However, the ARM template explicitly disables diagnostics and hence the deployment should have completely ignored the storage account 

```
    "diagnosticsEnabled": {
      "type": "bool",
      "defaultValue": false,
      "metadata": {
        "description": "A value that indicates whether diagnostics should be saved to the specified storage account."
      }

```

### Question
- Why did the deployment go out looking for a storage account when diagnostics appears to be disabled?
- Why didn't the deployment process perform a very early validation for the storage account ?

### Repro steps (*if necessary, delete otherwise*)

```
$envname="dev"
$resourcegroupname="rg-$envname-redis-demo"
$location="uksouth"
$rediscache="saudemo001-$envname"

New-AzResourceGroup -Name $resourcegroupname -Location $location -Force -Verbose
New-AzResourceGroupDeployment -ResourceGroupName $resourcegroupname -TemplateFile $scriptfolder\arm-redis\template.json -TemplateParameterFile $scriptfolder\arm-redis\parameters.json -redisCacheName $rediscache -redisCacheSKU "Basic"   -Verbose 

```

**Comment by bmoore-msft** [comment]
@sdg002 - can you add the sample you're using to the top of the issue?

**Comment by sdg002** [comment]
@bmoore-msft  Link to ARM template added. Thanks for reminding.

**Comment by bmoore-msft** [comment]
the template as written unconditionally expects a storage account to enable the diagsSetting on the cache... the enabled/disabled settings can be toggled post provisioning.  So the scenario is provisioning redis with diags and the the default turns off logging.

It is a bit odd... but not incorrect.  The param for the storageAccount is required (and needs to be valid).
