### ISSUE TITLE
Accessing Linked templates stored in Azure DevOps GIT

### ISSUE THREAD

**Issue by siva-apim** [Azure/azure-quickstart-templates#7612]
Is it possible to access Linked templates from Private GIT Repo on Azure Devops, if yes - please advise on how to do the Authentication and Authorization with private GIT repo ?

I have tried to provide Personal Access token but seems to be not working from ARM perspective but works from browser because I am already logged in to the Azure Devops Organization.

Please provide inputs on how to achieve this and thanks in advance.

**Comment by bmoore-msft** [comment]
it's not possible to use a private repo, but if you follow the patterns for best practices in the repo you can see a pattern for how to stage files from source code for deployment.
