### ISSUE TITLE
Cannot Deploy a DSC Template in region West US

### ISSUE THREAD

**Issue by LandersJ** [Azure/azure-quickstart-templates#763]
I'm trying to deploy a simple VM with Active Directory in the US West region.  I'm using the template located at https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain.

No matter what I do, I consistently get the following error: 
 
    statusCode:NotFound
    statusMessage:{
        "error":{
            "code":"ArtifactNotFound",
            "message":"Extension with publisher 'Microsoft.Powershell', type 'DSC', and type handler version '1.7' could not be found in the extension repository."
        }
    }

Is something wrong with the extension repository?  Is there some step I have to take in my subscription to enable this?

**Comment by rchaganti** [comment]
Edit the template and update the typeHandlerVersion property to 2.8. DSC Extension versions from 1.0 to 2.3 were removed but these templates were not updated.

**Comment by singhkay** [comment]
I believe #772 will fix this once merged. I'll close this in the meantime but please open if this still an issue.
