### ISSUE TITLE
Error: active-directory-new-domain-ha-2-dc

### ISSUE THREAD

**Issue by prashant-kumar-mishra** [Azure/azure-quickstart-templates#7659]
When I am trying to run this template, I get below error.
An item with the same key has already been added.'. (Code: InvalidTemplate)

Can you please fix this issue?
![image](https://user-images.githubusercontent.com/22879359/83958813-35ad1700-a844-11ea-99fc-6b662bbdeeae.png)

**Comment by bmoore-msft** [comment]
@prashant-kumar-mishra - can you open a support ticket with the Azure portal (or tweet @AzureSupport).  The template is working find in CI/CD so it looks to be a portal issue.

If you need to get unblocked, you can use the scripts in the root of the repo to deploy the template.

**Comment by bmoore-msft** [comment]
We've identified a scenario that was regressed with a rollout that completed late last week.  If you have a deployment that deploys the same resource twice e.g. once to create it, once to update it later with information from something else in the deployment, this template will fail the /validate api.  Most tools (PowerShell, CLI, Portal) that perform template deployments in Azure automatically call the /validate api before deployment.  You can workaround the issue by skipping the /validate call (which isn't always possible) or separating the resource update into a separate deployment step.  We understand either of those may be difficult to implement and are actively working on a solution.

We will update the thread when we have more information on the issue - if you have any questions in the meantime feel free to contact me bmoore at microsoft.com.

**Comment by bmoore-msft** [comment]
This fix has been rolled out to all regions...

**Comment by prashant-kumar-mishra** [comment]
Thanks Brian. It's working now.

**Comment by bmoore-msft** [comment]
thanks for confirming
