### ISSUE TITLE
Template deployment (Create a new AD Domain with 2 DCs using Availability Zones) failing with error 

### ISSUE THREAD

**Issue by Shaikngit** [Azure/azure-quickstart-templates#7664]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name:Create a new AD Domain with 2 DCs using Availability Zones](Template link :https://azure.microsoft.com/en-us/resources/templates/active-directory-new-domain-ha-2-dc-zones/

### Issue Details
Template deployment is failing with the error 
   "message": "Deployment template validation failed: 'An item with the same key has already been added.'.

### Repro steps (*if necessary, delete otherwise*)
1. Just try to import the deployment it fails with the error..

**Comment by bmoore-msft** [comment]
We've identified a scenario that was regressed with a rollout that completed late last week.  If you have a deployment that deploys the same resource twice e.g. once to create it, once to update it later with information from something else in the deployment, this template will fail the /validate api.  Most tools (PowerShell, CLI, Portal) that perform template deployments in Azure automatically call the /validate api before deployment.  You can workaround the issue by skipping the /validate call (which isn't always possible) or separating the resource update into a separate deployment step.  We understand either of those may be difficult to implement and are actively working on a solution.

We will update the thread when we have more information on the issue - if you have any questions in the meantime feel free to contact me bmoore at microsoft.com.

**Comment by Shaikngit** [comment]
@bmoore-msft Thanks for the update , just want to know if we have an ETA for this fix

**Comment by bmoore-msft** [comment]
not yet, but we have a fix in PR - if all goes well we will start a rollout tomorrow (it needs to hit all regions)

**Comment by bmoore-msft** [comment]
This fix has been rolled out to all regions...
