### ISSUE TITLE
Templates with AD domain get InvalidTemplate error

### ISSUE THREAD

**Issue by koenhalfwerk** [Azure/azure-quickstart-templates#7666]
[active-directory-new-domain](https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain/)
[301-create-ad-forest-with-subdomain](https://github.com/Azure/azure-quickstart-templates/tree/master/301-create-ad-forest-with-subdomain)

When trying to deploy these to templates, I get an error, that suggests the template is faulty. 
I can't find an actual error in the two templates though
```
InvalidTemplate; 
Deployment template validation failed: 'An item with the same key has already been added.'.
```

### Repro steps (*if necessary, delete otherwise*)
1. Deploy it with powershell
2. Receive and read error
3. Deploy it with Azure
4. read the error

**Comment by koenhalfwerk** [comment]
this sad oneliner should work (geven that the rg exists)
```powershell
New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupName -TemplateUri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain/azuredeploy.json -adminUsername myadmin -adminPassword ('ReallyS3c7re' |ConvertTo-SecureString -AsPlainText -Force) -domainName 'jusademo.local' -dnsPrefix 'dc'
```

but even the gui doesn't work

**Comment by bmoore-msft** [comment]
We've identified a scenario that was regressed with a rollout that completed late last week.  If you have a deployment that deploys the same resource twice e.g. once to create it, once to update it later with information from something else in the deployment, this template will fail the /validate api.  Most tools (PowerShell, CLI, Portal) that perform template deployments in Azure automatically call the /validate api before deployment.  You can workaround the issue by skipping the /validate call (which isn't always possible) or separating the resource update into a separate deployment step.  We understand either of those may be difficult to implement and are actively working on a solution.

We will update the thread when we have more information on the issue - if you have any questions in the meantime feel free to contact me bmoore at microsoft.com.

**Comment by bmoore-msft** [comment]
This fix has been rolled out to all regions...
