### ISSUE TITLE
This SQL Server cluster template is failing - sqlvm-alwayson-cluster

### ISSUE THREAD

**Issue by djmore123** [Azure/azure-quickstart-templates#7668]
I am trying to deploy this azure-quickstart-templates/sqlvm-alwayson-cluster/ template 

but it keeps failing with this message - 

Deployment template validation failed: 'An item with the same key has already been added.'.
{
"deploymentStatusCode": -1,
"stage": 6,
"expected": true,
"error": {
"message": "Deployment template validation failed: 'An item with the same key has already been added.'."
  },
"subscriptionId": "11389280-b2a2-4183-b757-17cf44d245ee",
"resourceGroupName": "hpiRG",
"resourceGroupLocation": "eastus",
"deploymentName": "Microsoft.Template",
"details": {
"code": "InvalidTemplate",
"message": "Deployment template validation failed: 'An item with the same key has already been added.'."
  }
}

Also there was a different sql always on cluster in Azure marketplace that seems to work very well and has gone missing. Do you know why? 

Thanks
-dhanaji

 

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by bmoore-msft** [comment]
We've identified a scenario that was regressed with a rollout that completed late last week.  If you have a deployment that deploys the same resource twice e.g. once to create it, once to update it later with information from something else in the deployment, this template will fail the /validate api.  Most tools (PowerShell, CLI, Portal) that perform template deployments in Azure automatically call the /validate api before deployment.  You can workaround the issue by skipping the /validate call (which isn't always possible) or separating the resource update into a separate deployment step.  We understand either of those may be difficult to implement and are actively working on a solution.

We will update the thread when we have more information on the issue - if you have any questions in the meantime feel free to contact me bmoore at microsoft.com.

**Comment by bmoore-msft** [comment]
This fix has been rolled out to all regions...
