### ISSUE TITLE
Not able to set the diagnostic logs settings through ARM Template deployment for Cosmos DB

### ISSUE THREAD

**Issue by alakiran** [Azure/azure-quickstart-templates#7701]
### Issue Details:

Not able to set the diagnostic logs settings through ARM Template deployment for Cosmos DB.

We were able to set it earlier couple of months back and its not working any more. Below is the ARM template code and Attached are the error details, Tried multiple ways of handling it with no luck. Any help is appreciated!

    {
      "type": "providers/diagnosticSettings",
      "name": "diagnosticLogs",
      "dependsOn": [
        "[parameters('databaseAccountName')]"
      ],
      "apiVersion": "2017-05-01-preview",
      "properties": {
        "name": "[parameters('LogsettingName')]",
        "workspaceId": "[parameters('workspaceId')]",
        "eventHubAuthorizationRuleId": "[parameters('eventHubAuthorizationRuleId')]",
        "eventHubName": "[parameters('eventHubName')]",
        "logs": [
          {
            "category": "DataPlaneRequests",
            "enabled": true,
            "retentionPolicy": {
              "days": 90,
              "enabled": true
            }
          },
          {
            "category": "MongoRequests",
            "enabled": true,
            "retentionPolicy": {
              "days": 90,
              "enabled": true
            }
          },
          {
            "category": "QueryRuntimeStatistics",
            "enabled": true,
            "retentionPolicy": {
              "days": 90,
              "enabled": true
            }
          },
          {
            "category": "PartitionKeyStatistics",
            "enabled": true,
            "retentionPolicy": {
              "days": 90,
              "enabled": true
            }
          }
        ],
        "metrics": [
          {
            "category": "AllMetrics",
            "enabled": true,
            "retentionPolicy": {
              "enabled": true,
              "days": 90
            }
          }
        ]
      }
    }

![image](https://user-images.githubusercontent.com/31290585/84964692-60b02a00-b0d2-11ea-9287-8189ea2c47d8.png)

**Comment by alakiran** [comment]
The way the template file is organized is not correct, After changing it as a subresource, it started working fine.

**Comment by DimitrovMiro** [comment]
@alakiran what do you mean changing it as a subresource. Could you please be more specific. I am looking to enable the diagnostic settings in an arm template as well

Regards,

Miro

**Comment by SQLPRODDBA** [comment]
> The way the template file is organized is not correct, After changing it as a subresource, it started working fine.

Could you please let me know the exact location where you had to put in these settings in your ARM template? I am trying to do similar thing to add diagnostic settings and storage account in the same ARM template but didn't succeed yet.

**Comment by alakiran** [comment]
Here is the resources section i got it working!

 "resources": [
    {
      "comments": "Cosmos Db Configuration with IpRules to allow cosmosdb access from Azure portal.",
      "type": "Microsoft.DocumentDB/databaseAccounts",
      "apiVersion": "2020-04-01",
      "name": "[Parameters('databaseAccountName')]",
      "tags": "[parameters('tagValues')]",
      "location": "[resourceGroup().location]",
      "kind": "GlobalDocumentDB",
      "properties": {
        "name": "[Parameters('databaseAccountName')]",
        "databaseAccountOfferType": "[variables('offerType')]",
        "consistencyPolicy": {
          "defaultConsistencyLevel": "[parameters('consistencyLevel')]",
          "maxStalenessPrefix": "[parameters('maxStalenessPrefix')]",
          "maxIntervalInSeconds": "[parameters('maxIntervalInSeconds')]"
        },
        "ipRules": [
       
        ]
      },
      "resources": [
        {
          "condition": "[parameters('advancedThreatProtectionEnabled')]",
          "type": "providers/advancedThreatProtectionSettings",
          "name": "Microsoft.Security/current",
          "apiVersion": "2019-01-01",
          "dependsOn": [
            "[resourceId('Microsoft.DocumentDB/databaseAccounts/', Parameters('databaseAccountName'))]"
          ],
          "properties": {
            "isEnabled": true
          }
        },
        {
          "type": "providers/diagnosticSettings",
          "name": "[concat('Microsoft.Insights/', Parameters('databaseAccountName'))]",
          "tags": "[parameters('tagValues')]",
          "dependsOn": [
            "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
          ],
          "apiVersion": "2017-05-01-preview",
          "properties": {
            "name": "[Parameters('databaseAccountName')]",
            "workspaceId": "[variables('logAnalyticsWorkspaceResourceId')]",
            "eventHubAuthorizationRuleId": "[variables('eventHubAuthorizationRuleId')]",
            "eventHubName": "[variables('eventHubName')]",
            "logs": [
              {
                "category": "DataPlaneRequests",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "MongoRequests",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "QueryRuntimeStatistics",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "PartitionKeyStatistics",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "PartitionKeyRUConsumption",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "ControlPlaneRequests",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              },
              {
                "category": "CassandraRequests",
                "enabled": true,
                "retentionPolicy": {
                  "days": 90,
                  "enabled": true
                }
              }
            ],
            "metrics": [
              {
                "category": "AllMetrics",
                "enabled": true,
                "retentionPolicy": {
                  "enabled": true,
                  "days": 90
                }
              }
            ]
          }
        },
        {
          "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases",
          "apiVersion": "2020-04-01",
          "name": "[concat(Parameters('databaseAccountName'), '/', parameters('databaseName'))]",
          "dependsOn": [
            "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
          ],
          "properties": {
            "resource": {
              "id": "[parameters('databaseName')]"
            },
            "options": {
              "throughput": "[parameters('throughput')]"
            }
          }
        },
        {
          "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers",
          "apiVersion": "2020-04-01",
          "name": "[concat(Parameters('databaseAccountName'), '/', parameters('databaseName'), '/', parameters('containerName'))]",
          "dependsOn": [
            "[resourceId('Microsoft.DocumentDB/databaseAccounts/sqlDatabases', Parameters('databaseAccountName'), parameters('databaseName'))]",
            "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
          ],
          "properties": {
            "resource": {
              "id": "[parameters('containerName')]",
              "indexingPolicy": {
                "indexingMode": "consistent",
                "automatic": true,
                "includedPaths": [
                  {
                    "path": "/*"
                  }
                ],
                "excludedPaths": [
                  {
                    "path": "/\"_etag\"/?"
                  }
                ]
              },
              "partitionKey": {
                "paths": [
                  "[parameters('authorizationsPartitionKey')]"
                ],
                "kind": "Hash"
              },
              "defaultTtl": "[parameters('timeToLive')]"
            }
          }
        }
      ]
    }

  ]

**Comment by SQLPRODDBA** [comment]
> Here is the resources section i got it working!
> 
> "resources": [
> {
> "comments": "Cosmos Db Configuration with IpRules to allow cosmosdb access from Azure portal.",
> "type": "Microsoft.DocumentDB/databaseAccounts",
> "apiVersion": "2020-04-01",
> "name": "[Parameters('databaseAccountName')]",
> "tags": "[parameters('tagValues')]",
> "location": "[resourceGroup().location]",
> "kind": "GlobalDocumentDB",
> "properties": {
> "name": "[Parameters('databaseAccountName')]",
> "databaseAccountOfferType": "[variables('offerType')]",
> "consistencyPolicy": {
> "defaultConsistencyLevel": "[parameters('consistencyLevel')]",
> "maxStalenessPrefix": "[parameters('maxStalenessPrefix')]",
> "maxIntervalInSeconds": "[parameters('maxIntervalInSeconds')]"
> },
> "ipRules": [
> 
> ```
>     ]
>   },
>   "resources": [
>     {
>       "condition": "[parameters('advancedThreatProtectionEnabled')]",
>       "type": "providers/advancedThreatProtectionSettings",
>       "name": "Microsoft.Security/current",
>       "apiVersion": "2019-01-01",
>       "dependsOn": [
>         "[resourceId('Microsoft.DocumentDB/databaseAccounts/', Parameters('databaseAccountName'))]"
>       ],
>       "properties": {
>         "isEnabled": true
>       }
>     },
>     {
>       "type": "providers/diagnosticSettings",
>       "name": "[concat('Microsoft.Insights/', Parameters('databaseAccountName'))]",
>       "tags": "[parameters('tagValues')]",
>       "dependsOn": [
>         "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
>       ],
>       "apiVersion": "2017-05-01-preview",
>       "properties": {
>         "name": "[Parameters('databaseAccountName')]",
>         "workspaceId": "[variables('logAnalyticsWorkspaceResourceId')]",
>         "eventHubAuthorizationRuleId": "[variables('eventHubAuthorizationRuleId')]",
>         "eventHubName": "[variables('eventHubName')]",
>         "logs": [
>           {
>             "category": "DataPlaneRequests",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "MongoRequests",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "QueryRuntimeStatistics",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "PartitionKeyStatistics",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "PartitionKeyRUConsumption",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "ControlPlaneRequests",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           },
>           {
>             "category": "CassandraRequests",
>             "enabled": true,
>             "retentionPolicy": {
>               "days": 90,
>               "enabled": true
>             }
>           }
>         ],
>         "metrics": [
>           {
>             "category": "AllMetrics",
>             "enabled": true,
>             "retentionPolicy": {
>               "enabled": true,
>               "days": 90
>             }
>           }
>         ]
>       }
>     },
>     {
>       "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases",
>       "apiVersion": "2020-04-01",
>       "name": "[concat(Parameters('databaseAccountName'), '/', parameters('databaseName'))]",
>       "dependsOn": [
>         "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
>       ],
>       "properties": {
>         "resource": {
>           "id": "[parameters('databaseName')]"
>         },
>         "options": {
>           "throughput": "[parameters('throughput')]"
>         }
>       }
>     },
>     {
>       "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers",
>       "apiVersion": "2020-04-01",
>       "name": "[concat(Parameters('databaseAccountName'), '/', parameters('databaseName'), '/', parameters('containerName'))]",
>       "dependsOn": [
>         "[resourceId('Microsoft.DocumentDB/databaseAccounts/sqlDatabases', Parameters('databaseAccountName'), parameters('databaseName'))]",
>         "[resourceId('Microsoft.DocumentDB/databaseAccounts', Parameters('databaseAccountName'))]"
>       ],
>       "properties": {
>         "resource": {
>           "id": "[parameters('containerName')]",
>           "indexingPolicy": {
>             "indexingMode": "consistent",
>             "automatic": true,
>             "includedPaths": [
>               {
>                 "path": "/*"
>               }
>             ],
>             "excludedPaths": [
>               {
>                 "path": "/\"_etag\"/?"
>               }
>             ]
>           },
>           "partitionKey": {
>             "paths": [
>               "[parameters('authorizationsPartitionKey')]"
>             ],
>             "kind": "Hash"
>           },
>           "defaultTtl": "[parameters('timeToLive')]"
>         }
>       }
>     }
>   ]
> }
> ```
> 
> ]

Thanks a lot! Much appreciated!

**Comment by sagarkul** [comment]
look like it requires Log Analytics Workspace. 
Is it possible to do this without log analytics ?

**Comment by ejsealms** [comment]
> 

It doesn't seem like it. At least, you can't do this with a storage account. There doesn't appear to be any documentation about it, but attempting to set up a diagnostic settings with the logs going from your cosmos db to a storage account just doesn't work if you do a template deployment, and storage accounts don't show up for you to select if you try to do it from the portal.
