### ISSUE TITLE
Bug in the 101-hub-and-spoke templates

### ISSUE THREAD

**Issue by steinrr** [Azure/azure-quickstart-templates#7730]
101-hub-and-spoke-sandbox https://github.com/Azure/azure-quickstart-templates/tree/master/101-hub-and-spoke-sandbox

### Issue Details
The templates fails if gateway is set to YES. The reason is that the peering from spokes are created before the gateway itself, and then the useremotegateway in the peering cannot be set to true:

`        "statusMessage": "{\"error\":{\"code\":\"RemoteVnetHasNoGateways\",\"message\":\"Peering /subscriptions/XXX/resourceGroups/hubandspoke-rg/providers/Microsoft.Network/virtualNetworks/spokeProdVnet/virtualNetworkPeerings/gwPeering_spokeProdVnet_hubVnet cannot have UseRemoteGateway flag set to true because remote virtual network /subscriptions/XXX/resourceGroups/hubandspoke-rg/providers/Microsoft.Network/virtualNetworks/hubVnet referenced by the peering does not have any gateways.\",\"details\":[]}}",`

### Repro steps (*if necessary, delete otherwise*)
1. Run template with usegateway=true
2. Observe that network peering from spokes fails due to no gateway defined in hub yet

**Comment by bmoore-msft** [comment]
fixed in #7865

**Comment by MCKLMT** [comment]
@steinrr Can you close the issue if solved on your side?

**Comment by steinrr** [comment]
Tested and confirmed fixed. Closing.
