### ISSUE TITLE
Update dokku quickstart template

### ISSUE THREAD

**Issue by benaboki** [Azure/azure-quickstart-templates#7768]
[Deploy a Dokku Instance](https://github.com/azure/azure-quickstart-templates/tree/master/dokku-vm)

### Issue Details
The template fails to run. Version number is outdated. Deployment fails with the following messages:

- "code": "VMExtensionProvisioningError",
- "message": "VM has reported a failure when processing extension 'initdokku'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=100
- The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FB2B6AA421CD193F
- Unable to locate package dokku\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot

### Solution
* change Dokku version from 0.10.3 to 0.14.2

**Comment by HamzaBoukraa** [comment]
@benaboki :
Will be fixed in a PR today

**Comment by benaboki** [comment]
Just tested and saw that the dokku version is still 0.10.3. I spent hours trying to troubleshoot this and the error messages I was getting were not helpful.

**Comment by bmoore-msft** [comment]
thx @MCKLMT
