### ISSUE TITLE
Deploy virtual application

### ISSUE THREAD

**Issue by chungvinhkhang** [Azure/azure-quickstart-templates#778]
Hello,
Can I use template to deploy a package to a virtual application (sub site) of a webapp?
Something similar DeployIisAppPath in msbuild. 
I tried both IIS Application Path and Application Path but not work too.

**Comment by singhkay** [comment]
@davidebbo Can you help with this?

**Comment by davidebbo** [comment]
@chungvinhkhang can you please post the question to https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview instead? Please include more details about exactly what you are trying in your template. Thanks!
