### ISSUE TITLE
CI - Add Continuous Template validation

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-quickstart-templates#793]
I noticed that there isn't any automated validation of the templates.

The Azure CLI has a command to do this:

`azure group template validate`

This can catch some preliminary issues with templates. There's also a bit of inconsistencies between template directories. For example, some templates have parameters called `azuredeploy-paramters.json` and `azuredeploy.paramteres.json`.

Automated validation could make the entire repo more uniform as well as keep it that way as changes come in.

I created a [tiny server](https://github.com/sedouard/azure-arm-validator) which has exactly one endpoint `/validate` which calls the azure CLI command to validate the template. It'll return the CLI error if there is a problem.

I quickly implemented this idea, and you can see the [test log here](https://travis-ci.org/sedouard/azure-quickstart-templates/builds/88926761) of my fork.

The failures seem legitimate and most templates do pass.

Is this something that would be interesting to implement in this repository?

**Comment by saschagottfried** [comment]
very good idea.

**Comment by sedouard** [comment]
@saschagottfried I'm actively working on this. Keep an eye out for updates!

**Comment by singhkay** [comment]
Closing, as we've achieved this! For info on how to CI your template see here https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci
