### ISSUE TITLE
Issue with Deploy-AzTemplate.ps1

### ISSUE THREAD

**Issue by MCKLMT** [Azure/azure-quickstart-templates#7965]
Hi,

I have encountered a bug I spend a long time to debug when trying to understand why the build of this template ([101-automation-configuration](https://github.com/Azure/azure-quickstart-templates/tree/master/101-automation-configuration))  was failing.

I observed that the content of the folder _dscConfigurations_ is not uploaded to the artifacts storage account. The PowerShell script is missing and the build fails.

After having a look at the template, I see that it contains this condition:
https://github.com/Azure/azure-quickstart-templates/blob/800d9c3cb9f0c1738c22f68337befe96a472b080/Deploy-AzTemplate.ps1#L148

In my case, the folder _dscConfigurations_ contains a ps1 but not a zip and the content is ignored. Moving the ps1 to the _nested_ folder solved the issue.
Is it expected?

We have the same problem with this template ([201-vmss-automation-dsc](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-automation-dsc)).

**Comment by MCKLMT** [comment]
@bmoore-msft Can you comment please?

**Comment by bmoore-msft** [comment]
DSC files should be in a folder named "DSC" but many samples have not been updated to account for the practice...
