### ISSUE TITLE
object id harded coded in 101-aks-advanced-networking/azuredeploy.json

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-quickstart-templates#7969]
There's an object id is hard coded in the template on line 219 : 

 "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "parameters": {},
                    "variables": {},
                    "resources": [
                        {
                            "type": "Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments",
                            "apiVersion": "2019-04-01-preview",
                            "name": "[concat(parameters('existingVirtualNetworkName'), '/', parameters('existingSubnetName'), '/Microsoft.Authorization/', guid(resourceGroup().id, deployment().name))]",
                            "properties": {
                                "roleDefinitionId": "[subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4d97b98b-1d4f-4787-a291-c67834d212e7')]",
                                "principalId": "[parameters('existingServicePrincipalObjectId')]",
                                "scope": "[variables('vnetSubnetId')]"
                            }
                        }
                    ]
                }
            }

https://github.com/Azure/azure-quickstart-templates/blob/master/101-aks-advanced-networking/azuredeploy.json

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by MCKLMT** [comment]
Feel free to submit a pull request to fix it. 😉
