### ISSUE TITLE
101-automation template throws error on deployment

### ISSUE THREAD

**Issue by michaelwilliams1** [Azure/azure-quickstart-templates#7974]
[101-automation](https://github.com/Azure/azure-quickstart-templates/blob/master/101-automation/azuredeploy.json)

### Issue Details
When I deploy the 101-automation template, I get an error: 
Deployment template validation failed: 'The template resource 'Microsoft.OperationalInsights/workspaces/shoreline-monitor/linkedServices/Automation' cannot reference itself. Please see https://aka.ms/arm-template-expressions/#reference for usage details.'.

### Repro steps (*if necessary, delete otherwise*)
1. Go to [Quickstart: Create an Automation account by using an ARM template](https://docs.microsoft.com/en-us/azure/automation/quickstart-create-automation-account-template)
2. Click the "Deploy to Azure" link in the documentation page
3. Fill out the form in the Azure portal
4. Click the Purchase button
5. Observe the validation error

It seems to not like the last resource (Microsoft.OperationalInsights/workspaces/linkedServices) in the template. Commenting that resource allows the deployment to succeed, but of course the automation account does not get linked to the Log Analytics Workspace.

**Comment by MCKLMT** [comment]
Can you check again? A recent pull request (#7982) has been merged. I don't encounter your issue.
