### ISSUE TITLE
Why does the hdinsight-linux-with-edge-node use 2 separate storage accounts?

### ISSUE THREAD

**Issue by joshwg** [Azure/azure-quickstart-templates#798]
What is the benefit of creating a separate storage account for the edge and cluster?
Also is there a way to allow those storage accounts to optionally be the same so you can have it both ways?

**Comment by singhkay** [comment]
Adding @anthony-murphy who wrote the template

**Comment by anthony-murphy** [comment]
The reason the HDInsight cluster and the edge node are in separate storage accounts is to ensure the edge node and the cluster don't compete for storage resources. Here's a like to the azure documentation that describes the limits of a storage accounts:
https://azure.microsoft.com/en-us/documentation/articles/storage-scalability-targets/#scalability-targets-for-standard-storage-accounts

**Comment by singhkay** [comment]
Closing. please reopen if this is still an issue
