### ISSUE TITLE
Some Active Directory templates do not reboot following configuration, breaking RDP access

### ISSUE THREAD

**Issue by hrboyceiii** [Azure/azure-quickstart-templates#799]
The active-directory-new-domain and active-directory-new-domain-ha-2-dc were not specifying RebootIfNeeded = $true LocalConfigurationManager settings as part of the DSC configuration script for provisioning and configuring the active directory domain.  Other templates, such as sql-alwayson and sharepoint, have this as part of their DSC scripts

**Comment by singhkay** [comment]
Closing since #800 is merged! Thanks for the fix @hrboyceiii !
