### ISSUE TITLE
Are not all the API providers available on the USGov side for quickstarts? I can't find a list of what is and isn't enabled.

### ISSUE THREAD

**Issue by JFolberth** [Azure/azure-quickstart-templates#8006]
Are not all the API providers available on the USGov side? I can't find a list of what is and isn't enabled.

_Originally posted by @JFolberth in https://github.com/Azure/azure-quickstart-templates/pull/8002#issuecomment-677763720_

**Comment by JFolberth** [comment]
Thanks @MCKLMT .  This template is hooking up Application Insights into an App service at deployment time.  As such it also needs the necessary pieces of an App Service Plan and a Log Analytics Workspace.  It looks like the App Service Plan latest API version of 2020-06-01 is not supported by the government cloud instance.  Is that the expected behavior and/or does the Government cloud instance need to be updated?

**Comment by MCKLMT** [comment]
You can use the previous API version. The US GOV is often upgraded later.

**Comment by JFolberth** [comment]
I have updated the apis and it worked.  Also had to roll back the sites service to an earlier endpoint.
