### ISSUE TITLE
Dynamically get correct container ip address

### ISSUE THREAD

**Issue by shortpoet** [Azure/azure-quickstart-templates#8017]
When I create a container it shows the ip address.  I can retrieve that ip address with the below command.

```bash
cmd="az container show \
-n $CONTAINER \
--query ipAddress.ip \
-o tsv \
-g $RG"
```
The problem is, that is not the ip address under which the container actually runs.  When checking container logs in azure portal, I see the error that says the server is trying to connect to my database under a different ip.  I need that ip to be able to configure server firewall.

```bash
  az sql server firewall-rule create \
  -g $DB_RG \
  -s $DB_SERVER \
  -n $FIREWALL_RULE \
  --start-ip-address $IP \
  --end-ip-address $IP

```

How to retrieve the correct ip dynamically so it can be set in create-container script?

**Comment by MCKLMT** [comment]
I think this is not the good place to post this issue. I suggest to post it to [the Azure CLI repository](https://github.com/Azure/azure-cli).

**Comment by shortpoet** [comment]
@MCKLMT Thank you for the feedback, will do!  I searched for azure containers in the repo and wasn't sure which.
