### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by srusru** [Azure/azure-quickstart-templates#8021]
test

**Comment by MCKLMT** [comment]
The template you mention is an example. You should author your own template based on your needs.
If you need more listeners, you can add them after the gateway has been created and execute the template again in incremental mode.

**Comment by srusru** [comment]
Can you please provide me a sample template for having multiple listeners or any link, i searched online could not find any. I am new to this ARM templates @MCKLMT . Any help is appreciated. Thanks.
