### ISSUE TITLE
Wrong comma @ line 62 that blocks deployment

### ISSUE THREAD

**Issue by kanovic** [Azure/azure-quickstart-templates#8029]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by MCKLMT** [comment]
What's the template please?

**Comment by kanovic** [comment]
I'm sorry I thought I was setting up the issue in that repository. 
It's in [101-application-gateway-public-ip](https://github.com/Azure/azure-quickstart-templates/blob/master/101-application-gateway-public-ip/azuredeploy.json).

**Comment by MCKLMT** [comment]
This template has passed with success the CI 14 days ago. Are you sure about you?

**Comment by kanovic** [comment]
Deployment in Azure portal gave error. After downloading the JSON and viewing in VS Code the ARM extension gave Validation error on the comma.

**Comment by MCKLMT** [comment]
Can you post a screenshot of what you see?

**Comment by MCKLMT** [comment]
The pull request has been merged solving this issue. 
@kanovic Can you confirm and close the issue?

**Comment by kanovic** [comment]
Working thank you.
