### ISSUE TITLE
Deployment of Integration Runtime Template Results in Remote Name Could Not Be Resolved Failure

### ISSUE THREAD

**Issue by natefleming** [Azure/azure-quickstart-templates#8069]
[101-vms-with-selfhost-integration-runtime] (https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vms-with-selfhost-integration-runtime/azuredeploy.json)

When attempting to deploy an Integration Runtime using the template either from the command line or from the portal results in an exception. This particular stack trace is from the IR virtual machine trace logs, however, the same exception is produced if we generate the key from data factory and manually enter it into the IR user interface on the VM.

2020-09-02 16:12:01 DMDTTP is failed: Failed to run process: exitCode=-2146233088, errVariable=, errContent=, outContent=Failed to execute the command ' -k IR@1fb5ce1f-cdb8-4b89-ad52-e42fc9ad03c8@deleteme-df@ServiceEndpoint=deleteme-df.eastus2.datafactory.azure.net@SygTiL+9cjYwfg2/eCQxfxYKwJF2OJ0V+AFFEzFNmT0='. Error message: Microsoft.DataTransfer.DIAgentClient.HostServiceException: Failed to get service token from ADF service with key IR@1fb5ce1f-cdb8-4b89-ad52-e42fc9ad03c8@deleteme-df@ServiceEndpoint=deleteme-df.eastus2.datafactory.azure.net@****************** and time cost is: 3.3750692 seconds, the error code is: UnexpectedFault, activityId is: 7399b1f8-3a8b-45a5-8bd4-xxxxxxx and detailed error message is An error occurred while sending the request.
The remote name could not be resolved: 'deleteme-df.eastus2.datafactory.azure.net'
.
 ---> System.AggregateException: One or more errors occurred. ---> Microsoft.DataTransfer.DIAgentClient.HostServiceException: Failed to get service token from ADF service with key IR@1fb5ce1f-cdb8-4b89-ad52-e42fc9ad03c8@deleteme-df@ServiceEndpoint=deleteme-df.eastus2.datafactory.azure.net@****************** and time cost is: 3.3750692 seconds, the error code is: UnexpectedFault, activityId is: 7399b1f8-3a8b-45a5-8bd4-248d067ae28f and detailed error message is An error occurred while sending the request.
The remote name could not be resolved: 'deleteme-df.eastus2.datafactory.azure.net'
.

### Repro steps (*if necessary, delete otherwise*)

All regions are US EAST 2

1. Create a resource group - deleteme-rg
2. Create a virtual network 10.x.0.0/16 - deleteme-vnet
3. Create a subnet 10.x.0.0/24 - deleteme-svnet
4. Create a data factory - deleteme-df
5.a Select Deploy to Azure from the templates home page - Fill out the template and create
OR
5.b Run from the command line
       az deployment group create 
        --resource-group deleteme-rg
        --template-uri "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vms-with-selfhost-integration-runtime/azuredeploy.json"
        --parameters 
            "existingDataFactoryResourceGroup=deleteme-rg"
            "existingDataFactoryName=deleteme-df"
            "existingDataFactoryVersion=V2"
            "IntegrationRuntimeName=deletemeshirt"
            "NodeCount=2"
            "existingVirtualNetworkName=deleteme-vnet"
            "existingVnetLocation=US EAST 2"
            "existingVnetResourceGroupName=deleteme-rg"
            "existingSubnetInYourVnet=deleteme-svnet"
            "adminUserName=myadmin"
            "adminPassword=mypassword"
6. After about 5 or 6 minutes the jobs will fail

**Comment by MCKLMT** [comment]
Did you read the README.md? You should create the DataFactory instance before deploying the IR. Did you deployed it?

```
Before deploying the template you must have the following

Data Factory. The integration runtime is created in the data factory. If you don't have a data factory, see the Create data factory for steps to create one.
```

**Comment by natefleming** [comment]
Thank you for the reply @MCKLMT.  The data factory definitely exists in the resource group. If you look in my step number 4 I do create the data factory. I explained in the summary that I get the same error when I use the key that is generated from DataFactory.

**Comment by natefleming** [comment]
@MCKLMT Thank you for the reply. The Data Factory is definitely created ahead of time. This is step number 4 in my steps to reproduce. In addition I describe in the summary that even when I use the key which is generated from creating the Integration Runtime in DataFactory.

**Comment by natefleming** [comment]
Here is a screen shot with the exception that I get when I manually enter the ID. It appears to be identical to the one that is in the log file when the template tries to register it.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2520297/92129627-c78bd800-edd1-11ea-93cf-795c7e887150.png">

**Comment by MCKLMT** [comment]
Can you share the link under the "Click here" link please?

**Comment by natefleming** [comment]
https://docs.microsoft.com/en-us/azure/data-factory/self-hosted-integration-runtime-troubleshoot-guide#error-message-self-hosted-integration-runtime-is-unable-to-connect-to-cloud-service

Ive read through the troubleshooting. It hints that there is a DNS issue and we should contact our support. Ill add that other than create the resource group, data factory instance, vnet/subnet, deploy integration runtime template we havent made any changes. I can tear this resource group down and reproduce it every time.

**Comment by MCKLMT** [comment]
Can you try another region please? I was able to successfully deploy the template in West Europe.

**Comment by natefleming** [comment]
@MCKLMT 

Thank you for the response. I was able to get it to successfully deploy to West Europe as well. Do you have any idea why EAST US 2 is not resolving? 

The cloud status says everything is ok in the US

https://status.azure.com/en-us/status

but ironically, says that network infrastructure is having issues in West Europe

**Comment by natefleming** [comment]
@MCKLMT 

This was a problem with Azure infrastructure. The template appears to be working as intended.
Thank you.
