### ISSUE TITLE
Validation failed: is not valid according to the validation procedure [free trial]

### ISSUE THREAD

**Issue by mootduo** [Azure/azure-quickstart-templates#8085]
Hello guys. Im getting this error: 

"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 0, Additional Required: 6." 

This template needs 6 Regional Cores to run but it seems that only 4 Cores are available with the azure trial, is there any way of getting the template to run on 4? Removing resources?  

I would love to get this running with the free trial to be 100% before i upgrade. 

Thanks for your time, all the best.

**Comment by MCKLMT** [comment]
Hi,
Can you share the template?
Thanks

**Comment by mootduo** [comment]
Oops! Yeah mate, here’s the template:  https://azure.microsoft.com/en-us/resources/templates/obs-studio-stream-vm-chocolatey/?cdn=disable

Thanks for taking a look.

**Comment by MCKLMT** [comment]
You can edit the template and try a _Standard_NV4as_v4_ VM size which is only 4 cores. Keep in mind this VM series is not available everywhere. You can have a look [at this page](https://azure.microsoft.com/en-us/global-infrastructure/services/?products=virtual-machines&regions=us-east,us-east-2,us-central,us-north-central,us-south-central,us-west-central,us-west,us-west-2,europe-north,europe-west) to check the availability.
