### ISSUE TITLE
Need to update with valid VM Sizes here

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-quickstart-templates#8186]
[VM-DSC-Extension-IIS-Server](https://github.com/Azure/azure-quickstart-templates/tree/master/dsc-extension-iis-server-windows-vm)

### Issue Details

1. Template has hard coded and out-of-date value specified for VM Size, should use a 'List Available Sizes' function
1.  Template has bug and does not autofill value for Module .zip file

**Comment by MCKLMT** [comment]
The template has been updated.

**Comment by stowen-msft** [comment]
Confirmed the changes worked, closing!  Thank you.
