### ISSUE TITLE
Cannot deploy Template - sharepoint-three-vm 

### ISSUE THREAD

**Issue by CristianB79** [Azure/azure-quickstart-templates#821]
The deployment stops the creation of the DC machine with the error message you see in the attached image.
Maybe I'm wrong to define the parameters, can I have an example of parameters to use.
Thanks a lot.

![azureerror](https://cloud.githubusercontent.com/assets/15730976/11036933/700b1e16-86fb-11e5-9166-75212d37901a.png)

**Comment by singhkay** [comment]
@CristianB79 Can you take a look at the instance view of the VM and see if the DSC config error has any more details?

**Comment by singhkay** [comment]
@CristianB79 Tested this working locally and also updated it to use DSC 2.11. Closing, if you find any issues feel free to reopen.
