### ISSUE TITLE
Please parameterize inputs so it's clear what to change

### ISSUE THREAD

**Issue by andybouts** [Azure/azure-quickstart-templates#8223]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[sas-viya_add-a-user](https://github.com/Azure/azure-quickstart-templates/tree/master/sas-viya/#add-a-user)

### Issue Details
Please parameterize inputs so it's clear what to change.
I am adding a new user and it's not quite clear which parameters should be changes vs which ones should remain unchanged.

**Comment by bmoore-msft** [comment]
@sassoftware can you help?

**Comment by patbrown56** [comment]
I'm currently working on rewriting this section to be more clear on where to add the new user information.

**Comment by patbrown56** [comment]
This has been completed. This issue can be closed.

**Comment by andybouts** [comment]
Thanks Pat, trust you ;->
