### ISSUE TITLE
Add User Instructions Not Clear

### ISSUE THREAD

**Issue by andybouts** [Azure/azure-quickstart-templates#8225]
[sas-viya_add-a-user](https://github.com/Azure/azure-quickstart-templates/tree/master/sas-viya/#add-a-user)

### Issue Details
I'll list the issues as follows:
Step 1 ... does this file need to end in `ldif`, please provide an example filename with extension
Step 3 is very unclear ... is the command to run this command included as a part of the text file body?
Step 3 ... does this file need to end in `ldif`, please provide an example filename with extension
Why do we do step 1 and step 3 separately (I believe those can be combined into one step)?
Step 4 ... if a user is already on the services host, they should not have to ssh to it again, right?
Step 4, why not issue a recursive chown instead of multiple steps?

**Comment by bmoore-msft** [comment]
@sassoftware can you help?

**Comment by patbrown56** [comment]
I'm currently working on rewriting this section to be more clear.

**Comment by patbrown56** [comment]
This has been completed. This issue can be closed.

**Comment by andybouts** [comment]
Thanks Pat, trust you ;->
