### ISSUE TITLE
Service Fabric: Managed Service Identity issue with API version 2020-03-01 

### ISSUE THREAD

**Issue by heywoodj** [Azure/azure-quickstart-templates#8226]
{
      "apiVersion": "2020-03-01",
      "type": "Microsoft.ServiceFabric/clusters/applications",
      "name": "[concat(parameters('clusterName'), '/', parameters('applicationName'))]",
      "location": "[variables('clusterLocation')]",
      "identity": {
        "**type": "SystemAssigned"**
      },
      "properties": {
      }
    }

### Issue Details
I currently have Managed Service Identity set up for a Service Fabric application successfully when deployed, via ARM template, for apiVersion : '2019-06-01-preview' but when I switch to non preview version '2020-03-01' I receive the error _'Request is invalid. Reason: Managed identity is not supported for this API version, please use '2019-06-01-preview' or above.'_ during deployment.
The issue is the usage of 'SystemAssigned'. Is this available for API version '2020-03-01' as the docs for the versions are identical around the 'identity' property.

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicefabric/2019-06-01-preview/clusters/applications

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicefabric/2020-03-01/clusters/applications#ManagedIdentity

### Repro steps (*if necessary, delete otherwise*)
1. Set up Managed Service Identity using 'SystemAssigned' identity using version ARM API '2019-06-01-preview' which works fine.  
2. Switch to use version "2020-03-01".

**Comment by bmoore-msft** [comment]
@heywoodj can you tweet @AzureSupport with this?

**Comment by heywoodj** [comment]
@bmoore-msft, I raised a ticket in the end and it was identified as a bug. A fix is scheduled to be released this month so awaiting the outcome of that.

**Comment by bmoore-msft** [comment]
Ok - thanks for the follow up...  I'll close this then since I don't think there's anything to do with the sample for now.
