### ISSUE TITLE
SAS Viya SASWork not properly configured

### ISSUE THREAD

**Issue by andybouts** [Azure/azure-quickstart-templates#8278]
[azure-quickstart-templates/sas-viya/](https://github.com/Azure/azure-quickstart-templates/tree/master/sas-viya)

### Issue Details

There is  an issue with the Azure QuickStart where it’s not properly configuring the /SASWork mount for use.  

### Repro steps (*if necessary, delete otherwise*)
1. Complete the deployment
2. Create data in SAS StudioV in the work library
3. Nothing is created in /mnt/resource/sastmp/saswork, as it should be
4. Add proper configuration to file (see before and after below)
5. Repeat steps 2, voila, data is created as expected into /mnt/resource/sastmp/saswork

_**Before the manual fix post-deployment:**_
```
[root@services sastmp]# cat /etc/sysconfig/sas/sas-viya-compsrv-default
# Config for compute server

#COMPUTESERVER_LOG_PATH="/opt/sas/viya/config/var/log/compsrv/default"

#Uncomment the following line to enable lockdown for the compute server
#export COMPUTESERVER_LOCKDOWN_ENABLE=1

#ARM_SUBSYS=[ ARM_PROC | ARM_DSIO | ARM_ALL | ARM_NONE ]
#export ARM_SUBSYS=ARM_PROC
[root@services sastmp]#
````

**_After:_**
```
[root@services saswork]# cat /etc/sysconfig/sas/sas-viya-compsrv-default
# Config for compute server

#COMPUTESERVER_LOG_PATH="/opt/sas/viya/config/var/log/compsrv/default"

#Uncomment the following line to enable lockdown for the compute server
#export COMPUTESERVER_LOCKDOWN_ENABLE=1

#ARM_SUBSYS=[ ARM_PROC | ARM_DSIO | ARM_ALL | ARM_NONE ]
#export ARM_SUBSYS=ARM_PROC

# Edited 25 Sep 2020 | Andy Bouts | To fix SASWork mapping so that it's correctly mounted
# Session defined export for saswork env variable
#[root@services saswork]# pwd
#/mnt/resource/sastmp/saswork
export COMPUTESERVER_TMP_PATH=/mnt/resource/sastmp/saswork
[root@services saswork]#
```

**Comment by bmoore-msft** [comment]
@sassoftware to have a look...

**Comment by patbrown56** [comment]
Currently investigating how to resolve this.

**Comment by patbrown56** [comment]
This has been completed. The issue can be closed.

**Comment by andybouts** [comment]
Thanks Pat, trust you ;->
