### ISSUE TITLE
Deployment of template gluster-file-system fails

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-quickstart-templates#840]
It appears there is a package dependency issue in the rpm install.  Stack from the deployment error below.

{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'extension'. Error message: \"Script returned an error.\n---stdout---\n1.el6.x86_64\n--> Processing Dependency: glusterfs-libs = 3.6.3-1.el6 for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.4.0)(64bit) for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_PRIVATE_3.4.0)(64bit) for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Running transaction check\n---> Package glusterfs.x86_64 0:3.6.3-1.el6 will be installed\n--> Processing Dependency: glusterfs-libs = 3.6.3-1.el6 for package: glusterfs-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.4.0)(64bit) for package: glusterfs-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.4.2)(64bit) for package: glusterfs-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.5.1)(64bit) for package: glusterfs-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.6.0)(64bit) for package: glusterfs-3.6.3-1.el6.x86_64\n---> Package glusterfs-api.x86_64 0:3.6.0.54-1.el6 will be installed\n--> Processing Dependency: glusterfs = 3.6.0.54-1.el6 for package: glusterfs-api-3.6.0.54-1.el6.x86_64\n---> Package glusterfs-libs.x86_64 0:3.6.0.54-1.el6 will be installed\n---> Package glusterfs-server.x86_64 0:3.6.3-1.el6 will be installed\n--> Processing Dependency: glusterfs-cli = 3.6.3-1.el6 for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Processing Dependency: glusterfs-libs = 3.6.3-1.el6 for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_3.4.0)(64bit) for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Processing Dependency: libgfapi.so.0(GFAPI_PRIVATE_3.4.0)(64bit) for package: glusterfs-server-3.6.3-1.el6.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\ngluster peer probe gfstestvm0 failed\ngluster peer status gfstestvm0 failed\ngluster peer probe gfstestvm1 failed\ngluster peer status gfstestvm1 failed\ngluster peer probe gfstestvm2 failed\ngluster peer status gfstestvm2 failed\n\n---errout---\negfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\nazuregfs.sh: line 253: gluster: command not found\nazuregfs.sh: line 259: gluster: command not found\nazuregfs.sh: line 260: gluster: command not found\n\n\"."}]}}

**Comment by singhkay** [comment]
Adding @liupeirong who wrote the template for guidance

**Comment by singhkay** [comment]
closing as the PR was merged
