### ISSUE TITLE
How to create domain verification records without domain verification id?

### ISSUE THREAD

**Issue by zendu** [Azure/azure-quickstart-templates#8433]
[201-web-app-custom-domain-and-ssl](https://github.com/Azure/azure-quickstart-templates/tree/master/201-web-app-custom-domain-and-ssl)

### Issue Details
Description of the sample template says "Create the required DNS record for adding custom hostname". Apparently creating necessary TXT record to verify domain ownership needs "customDomainVerificationId" - this id will be available only after creating the app service. How to handle this circular dependency?

**Comment by bmoore-msft** [comment]
@zendu - this isn't really a template issue so I'm going to close out...  you might be able to raise this question on the docs that mention this behavior or tweet @AzureSupport

**Comment by zendu** [comment]
This really is issue with sample. It is missing out on vital piece.

**Comment by bmoore-msft** [comment]
I think the template is working as it was intended, it just has the prereqs mentioned in the readme.  

I don't know if it's possible to fulfill the prereqs via a template (it's not to my knowledge) which is why I think @AzureSupport may be a better source.
