### ISSUE TITLE
OS provisioning error with the VM's

### ISSUE THREAD

**Issue by cc-sshaik** [Azure/azure-quickstart-templates#8444]
![image](https://user-images.githubusercontent.com/70511398/96464579-a0844b00-1245-11eb-894c-fb86efc11af4.png)
Hi @bmoore-msft , 

We are seeing the **OS provisioning error** with the VM's when we trigger our deployment through this Pull request. Can you please help us to check and overcome this issue?

_Originally posted by @cc-sshaik in https://github.com/Azure/azure-quickstart-templates/pull/8405#issuecomment-712203710_

**Comment by bmoore-msft** [comment]
if you're still seeing this please open a support case with Azure Support.
