### ISSUE TITLE
Azure Backup Quickstart settings template has issues

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-quickstart-templates#8448]
-------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------
Weekly Backup Policy Setting - https://github.com/Azure/azure-quickstart-templates/tree/master/101-recovery-services-weekly-backup-policy-create 

### Issue Details

Over time, it seems that a few small issues have surfaced with this template.

#### Template Values not Filled in

The Template includes parameter values to be used when you click 'Deploy to Azure', but none of the values are recognized.  This is probably due to the value IDs needing to be updated.

To Reproduce, click 'Deploy to Azure'

Expected:

Values from template.json should be pre-filled or drive the options for a dropdown box.

Actual:

No values are carried over.

#### Template Settings may not be valid

I have been unable to verify that these selections in the template are valid for an azure deployment.  I get errors of 'Invalid setting' when creating a Yearly backup policy using the settings from this template.

**Comment by bmoore-msft** [comment]
The portal doesn't pre-populate param values from the param file, only from the template file's defaultValues....  this template doesn't have any defaultValues...  Though if you wanted to add some defaultValues based on what's in the param file, that would be a helpful PR - this is a pretty challenging template to deploy manually.
