### ISSUE TITLE
Using virtualMachines/extensions with CopyIndex.

### ISSUE THREAD

**Issue by willguibr** [Azure/azure-quickstart-templates#8451]
Hi There, I managed to deploy this script without any problems, but I am trying to provision the VMs with a bash script using the virtualMachines/extensions. Do you have any suggestions on how to use the copyIndex in this section? I tried in several ways but I had no luck and the script fails to deploy with syntax errors.
This is the script I am trying to repurpose: https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-copy-index-loops. Any assistance is appreciated. Thank you.

This is the code I was using, but without the copyIndex. The script needs to pass parameters to each VM.
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "name": "[concat(parameters('MetaPortName'),'/newuserscript')]",
      "apiVersion": "2020-06-01",
      "location": "[parameters('location')]",
      "dependsOn": [
        "[resourceId('Microsoft.Compute/virtualMachines/', parameters('MetaPortName'))]"
      ],
      "properties": {
        "publisher": "Microsoft.Azure.Extensions",
        "type": "CustomScript",
        "typeHandlerVersion": "2.0",
        "autoUpgradeMinorVersion": true,
        "settings": {
          "fileUris": ["https://raw.githubusercontent.com/willguibr/azure/main/MetaPort-Standalone-NATGW-v1.0/install_metaport.sh"]
        },
        "protectedSettings": {
          "commandToExecute": "[concat('sh install_metaport.sh ', parameters('MP1TokenCode'), parameters('MP2TokenCode'))]"
        }
      }
    }

**Comment by bmoore-msft** [comment]
what you have will work fine if you add the copy property to it - the dependsOn will need to change, the simplest change would be to make it dependent on the virtualMachineLoop

**Comment by willguibr** [comment]
@bmoore-msft bmoore-msft I think I got it. I added the copy propery along with the dependsOn: VirtualMachineLoop. Initially I had the cdependson pointing to the myvm  and the script was trying to run before the VM was built. So I reversed and added the myVM in the copy property and the Machine Loop in the depends on as you suggested and it works like a charm. I now did some additional modifications and added a NAT Gateway so the VMs can go out to the Internet. Really cool template. Thank you for the insight. Much appreciated sir.
Here is the modification I had to do:

        "type": "Microsoft.Compute/virtualMachines/extensions",
        "name": "[concat('myvm', copyIndex(), '/newuserscript')]",
        "apiVersion": "2020-06-01",
        "location": "[parameters('location')]",
        "copy": {
            "name": "myvm",
            "count": "[parameters('numberOfInstances')]"
            },
        "dependsOn":[
            "virtualMachineLoop"
        ],
        "properties": {
            "publisher": "Microsoft.Azure.Extensions",
            "type": "CustomScript",
            "typeHandlerVersion": "2.0",
            "autoUpgradeMinorVersion": true,
            "settings": {
            "fileUris": ["https://raw.githubusercontent.com/willguibr/azure/main/MetaPort-Dual-AvailabilitySet-v2.0/install_metaport.sh"]
            },
            "protectedSettings": {
            "commandToExecute": "[concat('sh install_metaport.sh ', parameters('MP1TokenCode'), parameters('MP2TokenCode'))]"
        }
      }
    }

**Comment by bmoore-msft** [comment]
LGTM - thanks for confirming...

**Comment by willguibr** [comment]
@bmoore-msft bmoore-msft  I just ran into another issue that I did not realize before. The script in fact is running only in one machine twice in this case. In my example above the bash script should run the parameters once per VM For example: (MP1TokenCode) should run on VM1 and  (MP2TokenCode) should run on VM2. I also had to add some line breakers because otherwise it template was combining both tokens together and breaking everything. So, I have now the following, but as I mentioned, it is running the script twice in the same VM and not running on the second. Any suggestions?
```
{
        "type": "Microsoft.Compute/virtualMachines/extensions",
        "name": "[concat('metaport', copyIndex(), '/newuserscript')]",
        "apiVersion": "2020-06-01",
        "location": "[parameters('location')]",
        "copy": {
            "name": "metaport",
            "count": "[parameters('numberOfInstances')]"
            },
        "dependsOn":[
            "virtualMachineLoop"
        ],
        "properties": {
            "publisher": "Microsoft.Azure.Extensions",
            "type": "CustomScript",
            "typeHandlerVersion": "2.0",
            "autoUpgradeMinorVersion": true,
            "settings": {
            "fileUris": ["https://raw.githubusercontent.com/willguibr/azure/main/MetaPort-Dual-AvailabilitySet-v2.0/install_metaport.sh"]
            },
            "protectedSettings": {
            "commandToExecute": "[concat('sh install_metaport.sh ', parameters('MP1TokenCode'), ' ', parameters('MP2TokenCode'), ' ')]"
        }
      }
    }
```
