### ISSUE TITLE
Azure ARM Template Copy property - Bash Script Execution

### ISSUE THREAD

**Issue by willguibr** [Azure/azure-quickstart-templates#8456]
I am trying to deploy an Azure ARM Template that creates two VMs in different Availability sets. The deployment is working fine and the VMs are successfully deployed; however, I also need to run a bash script, which must provide two distinct parameters (One for each VM), as those are unique token codes that cannot be ran twice (OTAP).The script in fact is runs successfully in the first VM, but it rans both parameters in the same VM and not in the second VM. For example: (MP1TokenCode) should run on VM1 and (MP2TokenCode) should run on VM2. I also had to add some line breakers because otherwise the template was combining both tokens together and breaking everything. So, I have now the following, but as I mentioned, it is running the script twice in the same VM and not running on the second. In fact, the execution of the script in the second VM fails. I repurposed the following template:
https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-copy-index-loops.

```
{
        "type": "Microsoft.Compute/virtualMachines",
        "name": "[concat('metaport-', copyIndex())]",
        "apiVersion": "2020-06-01",
        "location": "[parameters('location')]",
        "copy": {
            "name": "virtualMachineLoop",
            "count": "[parameters('numberOfInstances')]"
        },
        "dependsOn": [
            "nicLoop"
        ],
        "properties": {
            "availabilitySet": {
                "id": "[resourceId('Microsoft.Compute/availabilitySets', variables('availabilitySetName'))]"
            },
            "hardwareProfile": {
                "vmSize": "[parameters('vmSize')]"
            },
            "osProfile": {
                "computerName": "[concat('vm', copyIndex())]",
                "adminUsername": "[parameters('adminUsername')]",
                "adminPassword": "[parameters('adminPasswordOrKey')]",
                "linuxConfiguration": "[if(equals(parameters('authenticationType'), 'password'), json('null'), variables('linuxConfiguration'))]"
            },
            "storageProfile": {
                "imageReference": "[variables('imageReference')[parameters('OS')]]",
                "osDisk": {
                    "createOption": "FromImage"
                }
            },
            "networkProfile": {
                "networkInterfaces": [
                    {
                        "id": "[resourceId('Microsoft.Network/networkInterfaces',concat('nic', copyindex()))]"
                    }
                ]
            }
        }
    },
{
    "type": "Microsoft.Compute/virtualMachines/extensions",
    "name": "[concat('metaport', copyIndex(), '/newuserscript')]",
    "apiVersion": "2020-06-01",
    "location": "[parameters('location')]",
    "copy": {
        "name": "metaport",
        "count": "[parameters('numberOfInstances')]"
        },
    "dependsOn":[
        "virtualMachineLoop"
    ],
    "properties": {
        "publisher": "Microsoft.Azure.Extensions",
        "type": "CustomScript",
        "typeHandlerVersion": "2.0",
        "autoUpgradeMinorVersion": true,
        "settings": {
        "fileUris": ["https://raw.githubusercontent.com/willguibr/azure/main/MetaPort-Dual-AvailabilitySet-v2.0/install_metaport.sh"]
        },
        "protectedSettings": {
        "commandToExecute": "[concat('sh install_metaport.sh ', parameters('MP1TokenCode'), ' ', parameters('MP2TokenCode'), ' ')]"
    }
  }
}
```

I also tried to break down the script in two parts and create two virtualmachines/extension sections but no luck. The script fails in both executions. Anyone have any suggestions on how I can run execute this script to pass each parameter individually to each VM instance? The current script version I've been working on is posted here: https://github.com/willguibr/azure/tree/main/MetaPort-Dual-AvailabilitySet-v3.0
Any suggestions? Thank you

**Comment by bmoore-msft** [comment]
Can you post this over on stackoverflow - probably more suited for that forum... feel free to post a link to it back here and I can take a look.

**Comment by bmoore-msft** [comment]
I think I saw this on SO - post a link back if you haven't found a resolution
