### ISSUE TITLE
SAS Viya deployment issue - possible ansible version mismatch.

### ISSUE THREAD

**Issue by singhvi** [Azure/azure-quickstart-templates#8460]
Issue is with the [SAS-Viya](azure-quickstart-templates/sas-viya/) quick start deployment.

### Issue Details
Deployment fails for SAS-Viya quick start (on step AnsiblePhase6Part1RunViyaInstall), with the below error. It looks like there is a ansible version mismatch.

`
nTASK [Gathering Facts] *********************************************************\\nok: [localhost]\\n\\nTASK [Verify that a valid Ansible version is installed] ************************\\nok: [localhost]\\n\\nTASK [Verify that a valid Python version is installed] *************************\\nskipping: [localhost]\\n\\nTASK [Halt execution on any third-party assessment check failures] *************\\nfatal: [localhost]: FAILED! => {\\n \\\"changed\\\": false, \\n \\\"failed_when_result\\\": true\\n}\\n\\nMSG:\\n\\nAt least one third-party assessment check failed: The Ansible version check failed. Deployment requires Ansible, version 2.8 or later. SAS recommends version 2.10 or earlier.\\n\\nNO MORE HOSTS LEFT *************************************************************\\n\\nPLAY RECAP *********************************************************************\\ncontroller : ok=2 changed=0 unreachable=0 failed=0 \\nlocalhost : ok=2 changed=0 unreachable=0 failed=1 
`

**_What is the best way to resolve this issue?_**

### Repro steps (*if necessary, delete otherwise*)
1. Run the viya quick start deployment (from the azure portal) providing the required values (like `DeploymentDataLocation`, `SSHPublicKey`, `DeploymentMirror` etc.)
2. The deployment fails on step `AnsiblePhase6Part1RunViyaInstall`... with the above error!

**Comment by bmoore-msft** [comment]
@sasgwb

**Comment by sasgwb** [comment]
The Quickstart has been updated to use Ansible 2.9.14, which meets the requirements of the updated SAS installation tools used by the Quickstart.

**Comment by rupeshgunapati** [comment]
@sasgwb i tried 3 days ago with the latest ansible 2.9.14 version, still an issue with ansible.

**Comment by patbrown56** [comment]
This has been resolved. The issue can be closed.
