### ISSUE TITLE
uppercase letters in storage account name does not return an error

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-quickstart-templates#847]
If there are uppercase letters in the parameter "storage account name", for example "FOO", the storage account will be created successfully with a name "foo". But on the portal, it is still "FOO".

My question is:
1. Does ARM templates or SRP perform the conversion?
2. IMO, the conversion may hide some errors and confuse customers.

Thanks

**Comment by singhkay** [comment]
@bingosummer Are you seeing this in a particular template? ARM or SRP doesn't do the conversion automatically. SRP always errors out.

**Comment by bingosummer** [comment]
Not from a specific template. I saw this issue in simple-linux-vm and bosh-setup.

This is the customer's complaint.

https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/46

Sent from my phone

???: Kay Singh
???: 11?14???? 01:46
??: Re: [azure-quickstart-templates] uppercase letters in storage account name does not return an error (#847)
???: Azure/azure-quickstart-templates
??: Bin Xia

@bingosummer<https://github.com/bingosummer> Are you seeing this in a particular template? ARM or SRP doesn't do the conversion automatically. SRP always errors out.

-

**Comment by bingosummer** [comment]
@singhkay . I think you can repro it easily using simple-linux-vm.

**Comment by singhkay** [comment]
@bingosummer This is interesting, I'll check with the storage team

**Comment by bingosummer** [comment]
@singhkay Any update on this? Could your repro this issue?

**Comment by singhkay** [comment]
@bingosummer Yep, storage team recently introduced bug where they were lowering all names. They'll fix this in an upcoming release.

**Comment by singhkay** [comment]
Closing as this is a storage bug and will be fixed in an upcoming platform release.
