### ISSUE TITLE
Issue with templates using default values for Boolean parameters in portal "Deploy to Azure" view

### ISSUE THREAD

**Issue by Taejas** [Azure/azure-quickstart-templates#8536]
[Backup Azure File Share to Recovery Services Vault](https://github.com/Azure/azure-quickstart-templates/tree/master/101-recovery-services-backup-file-share)
[Azure Backup for SQL Server in Azure Virtual Machines](https://github.com/Azure/azure-quickstart-templates/tree/master/101-recovery-services-vm-workload-backup)
[Create PostgreSQL Datastore in Azure Machine Learning Workspace](https://github.com/Azure/azure-quickstart-templates/tree/master/101-machine-learning-datastore-create-psql)

### Issue Details
I have listed down a few templates above, but the issue appears to be for not just those, but for all templates using default values for Boolean parameters. In the portal deployment view, these parameter inputs are displaying an error as shown in the attached screenshot, and are unable to pick up the corresponding default values (although the value can still be selected manually using the dropdown to successfully deploy the template).

This seems to be a recent portal side regression, as this error didn't show up until a few days ago when deploying a template using default Boolean values on the portal deployment view. The templates are still working fine with the default values when deploying using PowerShell.

### Repro steps
1. Navigate to any of the links for the templates above.
2. Click the "Deploy to Azure" button.
3. You will find the error being displayed under all parameters having a default Boolean value associated with them.

![Screenshot_bool_issue](https://user-images.githubusercontent.com/23445202/99832352-67adfd80-2b86-11eb-80f6-823752a0367f.png)

**Comment by MCKLMT** [comment]
Hello,
I reproduced the issue on my own and opened a support request internally. 
The bug should be fixed in a near future release. 
Thanks for reporting it.

**Comment by MCKLMT** [comment]
The fix should be deployed in the coming weeks to production portal. Thanks again for your contribution!

**Comment by MCKLMT** [comment]
@Taejas Can you check again?

**Comment by Taejas** [comment]
It seems to be resolved now, thanks :)

**Comment by MCKLMT** [comment]
> It seems to be resolved now, thanks :)

Can you close the issue?
