### ISSUE TITLE
using DNS Forwarder Template - Issue installing Extension - Setupdnsfirewall step

### ISSUE THREAD

**Issue by mimanu** [Azure/azure-quickstart-templates#8624]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Sorry to hear you had a bad experience with one of the templates :worried: But, in case you're just asking a question, we're happy to help. You can also check if the question might already have been asked here https://github.com/Azure/azure-quickstart-templates/issues?utf8=%E2%9C%93&q=is%3Aissue

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

[Template Name goes here](Template link goes here)

### Issue Details: Deploying DNS Forwarder in Azure. Use the Template 301-dns-forwarder. the stage of extension it failed.
Error Details:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'setupdnsfirewall'. Error message: \"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: http request failed: Get [REDACTED] dial tcp 151.101.8.133:443: connect: connection refused\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "}]}

![image](https://user-images.githubusercontent.com/41720328/102706438-e6ed3900-42cc-11eb-90e1-133f58e3259e.png)
![image](https://user-images.githubusercontent.com/41720328/102706448-f1a7ce00-42cc-11eb-8903-40d1d575a866.png)

**Comment by mimanu** [comment]
Discovered Network Routes the internet differently

**Comment by tomasevicius** [comment]
Hi, I am getting a different error:
Status Message: VM has reported a failure when processing extension 'setupdnsfirewall'. Error message: "Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: unexpected status code: actual=404 expected=200"

How can I solve this?
