### ISSUE TITLE
Azure DevOps CI Pipeline File

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/azure-quickstart-templates#8667]
Not an issue but more of a question - I'd like to use a similar workflow for my own template repo (run the arm-ttk and add a best practices check badge to the README)

Can anyone advise how I can get hold of the YAML file that's being used here, and how to add the badge to the README?

Thanks

**Comment by MCKLMT** [comment]
You can find the tooling used in this repository there: https://github.com/Azure/azure-quickstart-templates/tree/master/test

**Comment by thepaulmacca** [comment]
Thanks for replying, I've seen that but it's not very clear how to import the pipeline, unless I'm missing something?

**Comment by MCKLMT** [comment]
The documentation explaining how to import a pipeline is there: https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/clone-import-pipeline?view=azure-devops&tabs=yaml

**Comment by thepaulmacca** [comment]
Thanks, I've read that and tried to import the pipeline and I'm getting this error:

![image](https://user-images.githubusercontent.com/41340540/104894442-a4228d80-596c-11eb-8f6b-e5e563b37f31.png)

I think it's probably down to there being quite a lot of changes since that file was created. Are you able to import it?

**Comment by bmoore-msft** [comment]
The readme here will get you started with the pipeline we use:

https://github.com/Azure/azure-quickstart-templates/tree/master/test/pipeline

It's JSON, not YAML - TLDR; for security.  But if you import it, you can see the tasks we have and what each does.

The badges are not your typical pipeline badges - normally you would see one for the repo, we have one for each sample, so they are embedded into the README.md files for each sample.

That help?

**Comment by thepaulmacca** [comment]
Thanks for replying @bmoore-msft, that's good info to know. I'll close this off now
