### ISSUE TITLE
Azure template is not working

### ISSUE THREAD

**Issue by Pascal997** [Azure/azure-quickstart-templates#8674]
Hello,

Just to notice that Azure template is not working, when we click on the "Deploy to Azure" link. Because of a format error in the Json template (azuredeploy.json).

We get this error message:

```
Error parsing template. Please ensure template is valid JSON. Unexpected end of string at character position 24867. (52 other errors)
```

Thanks

**Comment by MCKLMT** [comment]
What's the template?

**Comment by Pascal997** [comment]
301-drupal8-vmss-glusterfs-mysql

https://github.com/Azure/azure-quickstart-templates/blob/master/301-drupal8-vmss-glusterfs-mysql/azuredeploy.json

**Comment by MCKLMT** [comment]
I submitted a pull request fixing the issue. Thanks for the heads-up.

**Comment by Pascal997** [comment]
It's works now, thanks!
