### ISSUE TITLE
How to create azure aad app registration by ARM template

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-quickstart-templates#8681]
### Issue Details
It's a question. How to create azure add app registration by ARM template?

**Comment by MCKLMT** [comment]
You can deploy User Managed Identity but I think you can't deploy app registration with ARM: https://docs.microsoft.com/en-us/azure/templates/microsoft.managedidentity/userassignedidentities

**Comment by bmoore-msft** [comment]
The only way to do this today is via a deploymentScript resource: 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template

https://github.com/Azure/azure-quickstart-templates/tree/master/201-deployment-script-ssh-key-gen
