### ISSUE TITLE
Incorrect schema validation for additionalUnattendContent 

### ISSUE THREAD

**Issue by blumu** [Azure/azure-quickstart-templates#888]
The current Azure template schema incorrectly types `additionalUnattendContent` as a JSON object instead of the array type expected by the ARM compute provider (see screenshot below).
![azurearm_templateschemabug](https://cloud.githubusercontent.com/assets/3913258/11356019/83131ff4-920e-11e5-9f3c-4c90967c0b51.PNG)

**Comment by singhkay** [comment]
@blumu Can you elaborate on this a bit. What are you suggesting it should look like?

**Comment by blumu** [comment]
@singhkay The additionalUnattenContent should not be underlined. The Json object blob specified in the screenshot is valid and accepted by the Azure Compute REST API whereas passing a Json array as suggested by the schema validation would be rejected by the Azure Compute REST API.

**Comment by singhkay** [comment]
@blumu I see, looks like the fixes were submitted for this
