### ISSUE TITLE
deployment script errors

### ISSUE THREAD

**Issue by kbroughton** [Azure/azure-quickstart-templates#8925]
Example, but I didn't find any that deployed with 
https://github.com/Azure/azure-quickstart-templates/tree/master/101-aks-vmss-systemassigned-identity
                                                                                                               /201-front-door-premium-vm-private-link
### Issue Details
In the deployment instructions of each repo it says
"or follow the instructions for command line deployment using the scripts in the root of this repo."

I am able to deploy with the blue Azure deploy button, but am not able to get the CLI to work. This is necessary for making modifications like combining different blueprints.

### Repro steps (*if necessary, delete otherwise*)
1. clone azure-quickstart-templates
2. install bicep and kubectl
3. create a resource group "blueprints-tests" in my example
4. pick any folder. Error messages vary slightly.
./az-group-deploy.sh -l centralus -g blueprints-tests -a ./201-front-door-premium-vm-private-link
Unhandled exception. System.ArgumentException: The specified file already already has the '.json' extension.
   at Bicep.Core.FileSystem.PathHelper.GetDefaultOutputPath(String path)
   at Bicep.Cli.Program.Build(ILogger logger, BuildArguments arguments)
   at Bicep.Cli.Program.Run(String[] args)
   at Bicep.Cli.Program.Main(String[] args)
./az-group-deploy.sh: line 62:  2740 Aborted                 bicep build $templateFile

I also tried running with -b false but it just complains

./az-group-deploy.sh -l centralus -g blueprints-tests -a ./101-aks-azml-targetcompute/ -b false
An error occurred reading file. Could not find file '/work/101-aks-azml-targetcompute/main.bicep

### Expected Results
It seems like the comment to use the script in the repo is az-group-deploy.sh. I just added options until it got passed the "missing argument" errors. If the script is not straight forward there should be a more detailed description of how to use it.

Some folders have a .bicep file and others do not.

**Comment by lanceshelton** [comment]
I encountered the same issue and have submitted a fix:

https://github.com/Azure/azure-quickstart-templates/pull/10104
