### ISSUE TITLE
mesos-swarm-marathon: Unused agent file?

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-quickstart-templates#894]
I'm reviewing and testing [mesos-swarm-marathon/azuredeploy.json](https://github.com/joshgav/azure-quickstart-templates/blob/master/mesos-swarm-marathon/azuredeploy.json). [Line 206](https://github.com/joshgav/azure-quickstart-templates/blob/master/mesos-swarm-marathon/azuredeploy.json#L206) is:
```json
"agentFile": "[variables('agentFiles')[mod(add(parameters('agentCount'),2),add(parameters('agentCount'),1))]]",
```
Since `agentCount` is constant here and `mod(x+1,x)` will always return `1`, this seems like a long way to refer to agentFiles[1], i.e. the second agent file `agent-gt0.json`. Am I missing something here or can I fix this up to be more clear and remove the extra `agent-0.json` file? Thanks!

//cc @anhowe

**Comment by anhowe** [comment]
The series is mod(x+2, x+1).  If you choose 0 agents, the 0 file is chosen, otherwise agents>0 will return 1.

Anthony

-----Original Message-----

**Comment by joshgav** [comment]
Ah, for the case of 0 agents, I see. Thanks!
