### ISSUE TITLE
Use of `storageAccountName` as parameter in AzureDeploy.json results in no account name

### ISSUE THREAD

**Issue by m-gagne** [Azure/azure-quickstart-templates#895]
Using `storageAccountName` as a parameter results in the following error "The StorageAccountName parameter is no longer used and will be removed in a future release. Also, the variable `$storageAccountName` is empty causing deployment errors due to the account names being a concat of `$storageAccountName` & the iterator (basically tries to create a storage account name of `0`, `1` etc.)

Resolution is to rename `storageAccountName` to `storageAccountNamePrefix`

**Comment by singhkay** [comment]
@m-gagne Thank you for the fix! Closing since the PR is merged
