### ISSUE TITLE
[HELP WANTED] Make apiVersion properties a variable across templates

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-quickstart-templates#934]
Currently we have most templates that hardcode an `apiVersion` for the resource. For example 

    "apiVersion": "2015-08-01",

You can help us by finding templates that do this and modifying it to use a variable. Here's how to do this

* Define a `variable apiVersion` in the variables section. Potentially different resources could use different apiVersions. In that case, you'll need to define multiple apiVersion variables.

          "variables": {   
             "apiVersion": "2015-08-01"
          },

* Then use this variable for the `apiVersion` property of the resource

        "apiVersion": "[variables('apiVersion')]",

When submitting the PR, please deploy the template to make sure there are no errors. If you run into errors, please file a Github issue against the template and we can investigate.

**Comment by boutquin** [comment]
Happy to work on this; started with a single template #1087 . Validation still failing though the deployment using the template succeeds. Will also incorporate #944 and #966 when touching a template.

**Comment by bmoore-msft** [comment]
We are going to move to using literal string values for apiVersion so that JSON schema validation can be performed on the templates.
