### ISSUE TITLE
Wrond description of 201-2-vms-internal-load-balancer template

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-quickstart-templates#936]
Either description is wrong, or we have template do not implementing second virtual machine.
We have only one resource with type  "type": "Microsoft.Compute/virtualMachines" inside https://github.com/Azure/azure-quickstart-templates/blob/master/201-2-vms-internal-load-balancer/azuredeploy.json

**Comment by SychevIgor** [comment]
My fault. This template will create more than one instance.

**Comment by singhkay** [comment]
@SychevIgor no worries :)
