### ISSUE TITLE
[HELP WANTED] Sanitize storage account name input in existing templates

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-quickstart-templates#944]
Currently the storage account names have the most strict requirements for the input. These are needed to be globally unique, all lower case and 24 characters or less. Most templates do not currently sanitize the user input which leads to a bunch of failures. We can use your help to improve the existing templates by making sure the storage account inputs follow the rules. Here's how to do this
### New Proposal (based on @bingosummer's suggestion below)
1. Remove any storage account name parameters. Create a variable instead. Only get a storage account name input from user if **absolutely** required.
2. Create a storage account variable and assign it's value like below

```
"storageAccountName": "[concat(uniquestring(resourceGroup().id), '<scenario name or a common suffix>')]",
```

An example template is found here https://github.com/Azure/azure-quickstart-templates/blob/master/101-storage-account-create/azuredeploy.json#L20

**Comment by bingosummer** [comment]
@singhkay 
Does it make sense that I concat a fixed prefix `cf` and `uniqueString(resourceGroup().id)` as the storage name? Then I can remove the storage account parameter.

**Comment by singhkay** [comment]
@bingosummer That makes sense. Actually, after discussions with the team that might be the direction we move in and eliminate the storage account parameter to avoid any chance of failure (unless it really is needed to be entered from the user). Also having a different prefix for different account names ensures they land on different racks which could help with HA scenarios.

Here's the proposed solution

PROPOSED:
``` concat(uniqueString() + <scenario name>)```

**Comment by boutquin** [comment]
@singhkay 
I think I followed the above recipe in pull request #1087 and the template fails validation, seemingly because the variable value defined in
```
"storageAccountNamePrefix": {
   "value": "GEN_UNIQUE_11"
 },
```
conflicts with the string length specified in
```
"storageAccountNamePrefix": {
  "type": "string",
  "maxLength": 11
  "metadata": {
    "description": "Name prefix of the Storage Account"
  }
},
```
Any advice, short of adding .ci_skip?

**Comment by boutquin** [comment]
@singhkay 

Never mind. Found the issue: using"GEN-UNIQUE-11" instead of "GEN_UNIQUE_11" helps. ;)

**Comment by ryanreich** [comment]
This fails for me: `The resource name 'dwjbicumxp2fy' is not allowed.`.  It seems that `uniqueString` produces alpha *numeric* strings, while storage account names must be alphabetic only...
