### ISSUE TITLE
SQL Injection template is missing

### ISSUE THREAD

**Issue by wehackpurple** [Azure/azure-quickstart-templates#9501]
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

azure-quickstart-templates/101-SQL-Injection-Attack-Prevention/

### Issue Details
I cloned this repo to use in a workshop (I've been giving it for years) and have been using my cloned version of the repo without issue. I went to "Deploy to Azure" in my own repo (https://github.com/wehackpurple/azure-quickstart-templates/tree/master/101-SQL-Injection-Attack-Prevention) and it's telling me that the Azuredeploy.json file is not longer publicly accessible. I'm pretty surprised, because I thought the entire point of cloning a repo was so stuff like this couldn't happen.

### Repro steps (*if necessary, delete otherwise*)
1.Go to cloned repo of this repo.
2. Click "Deploy to azure button"
3.Receive this message:
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-SQL-Injection-Attack-Prevention/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 
4. Be sad that your workshop for tomorrow is likely ruined. :-/

**Comment by bmoore-msft** [comment]
The sample is here: https://github.com/Azure/azure-quickstart-templates/tree/master/demos/SQL-Injection-Attack-Prevention

If you fork/clone the repo, you'll be fine (i.e. isolated) unless you git pull from Azure - then you'll get whatever the lastest changes are.  When they first did the move some of the links did not get updated and were later fixed.  If you did a pull in the middle of that, that's probably what you ran into...
