### ISSUE TITLE
Template to deploy Azure VM with a new AD Forest is missing

### ISSUE THREAD

**Issue by MNuijen** [Azure/azure-quickstart-templates#9589]
Create an Azure VM with a new AD Forest
https://github.com/Azure/azure-quickstart-templates/tree/master/active-directory-new-domain

### Issue Details
Template seems to be missing from the repository

### Repro steps (*if necessary, delete otherwise*)
1. go to https://azure.microsoft.com/en-us/resources/templates/active-directory-new-domain/
2. click deploy to Azure
3. log into an Azure subscription with appropriate credentials
4. error message: "There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/active-directory-new-domain/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below."

**Comment by pkrasnousov** [comment]
Same for me

**Comment by pkrasnousov** [comment]
UPD
They moved it into another path
https://github.com/Azure/azure-quickstart-templates/commit/e70cdcc84793515985e03469e79640b6d5ef2a92

**Comment by bmoore-msft** [comment]
yes we had to move them as we hit a limit in the GH api... lmk if you're looking for any others you can't find.
