### ISSUE TITLE
[HELP WANTED] DNS names best guidance

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-quickstart-templates#966]
Currently for DNS names the user must provide a prefix rather than a FQDN. The provided prefix is concatenated with <location>.cloudapp.azure.com by the platform to provide the FQDN for the Public IP. We see users trying to enter a FQDN (abc.com, def.com etc.) which causes failures. The DNS prefix must match the following regex or it will cause an error 

```
`^[a-z][a-z0-9-]{1,61}[a-z0-9]$`
```

We'd like to change current templates to provide this guidance as part of the parameter name and description. Here's how to do this
1. Make sure any template parameter for a DNS label has a `Prefix` at the end. This will give the user a hint of the value that's needed for this parameter. 
2. Add to the `metadata.description` information about the regex the DNS labels are expected to meet.

Here's how a good dns label parameter will look

```
"dnsLabelPrefix": {
   "type": "string",
   "metadata": {
      "description": "DNS Label for the Public IP. Must be lowercase. It should match with the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$ or it will raise an error."
   }
},
```

---

UPDATE 12/17/2015
@humbertcostas is working on this now

**Comment by humbertcostas** [comment]
Hi @singhkay , could you assign me this issue?

**Comment by singhkay** [comment]
@humbertcostas For some reason, Github doesn't let me assign it to you :|
![image](https://cloud.githubusercontent.com/assets/6164178/11877242/dc6fb0ca-a4a2-11e5-9a20-ba47e0a93bf2.png)

**Comment by sedouard** [comment]
@singhkay you can't assign to non-collaborators. You'll just have to note in the comment's that @humbertcostas is working on it. :-)

**Comment by singhkay** [comment]
@sedouard Ah ok! 

@humbertcostas is working on this now

**Comment by humbertcostas** [comment]
Hi @sedouard , I signed the CLA days ago...
https://github.com/Azure/azure-quickstart-templates/pull/942#issuecomment-164702940
