### ISSUE TITLE
rds-deployment failure (cb-vm/rdsdeployment) 

### ISSUE THREAD

**Issue by jorkovic** [Azure/azure-quickstart-templates#999]
Hi there
I tried to deploy an RDS enviroment with the following script
https://azure.microsoft.com/en-us/documentation/templates/rds-deployment/
during the deployment i get the following error

{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'rdsdeployment'. Error message: \"DSC Configuration completed with error(s).\"."}]}}
Resource
cb-vm/rdsdeployment

 any thoughts about whats going wrong?

thanks a lot

DSC error details

    {
        "code": "ComponentStatus/DscConfigurationLog/failed/8",
        "displayStatus": "Provisioning failed",
        "level": "Error",
        "message": "Performing the operation \"Start-DscConfiguration: SendMetaConfigurationApply\" on target \"MSFT_DSCLocalConfigurationManager\".\r\nPerform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.\r\nAn LCM method call arrived from computer BROKER with user sid S-1-5-18.\r\n[BROKER]: LCM:  [ Start  Set      ]\r\n[BROKER]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0660 seconds.\r\n[BROKER]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ End    Set      ]\r\n[BROKER]: LCM:  [ End    Set      ]    in  0.2190 seconds.\r\nOperation 'Invoke CimMethod' complete.\r\nSet-DscLocalConfigurationManager finished in 3.288 seconds.\r\nPerform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.\r\nAn LCM method call arrived from computer BROKER with user sid S-1-5-18.\r\n[BROKER]: LCM:  [ Start  Set      ]\r\n[BROKER]: LCM:  [ End    Set      ]\r\nThe PowerShell DSC resource MSFT_RoleResource from module <PSDesiredStateConfiguration,1.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC resource.\r\nOperation 'Invoke CimMethod' complete.\r\nTime taken for configuration job to complete is 12.421 seconds\r\nPerforming the operation \"Start-DscConfiguration: SendMetaConfigurationApply\" on target \"MSFT_DSCLocalConfigurationManager\".\r\nPerform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.\r\nAn LCM method call arrived from computer BROKER with user sid S-1-5-18.\r\n[BROKER]: LCM:  [ Start  Set      ]\r\n[BROKER]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0000 seconds.\r\n[BROKER]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]\r\n[BROKER]: LCM:  [ End    Set      ]\r\n[BROKER]: LCM:  [ End    Set      ]    in  0.0920 seconds.\r\nOperation 'Invoke CimMethod' complete.\r\nSet-DscLocalConfigurationManager finished in 1.396 seconds.",
        "time": null
    }
]

**Comment by singhkay** [comment]
@narrieta can you take a look at this?

**Comment by singhkay** [comment]
@jorkovic This is now working. Tested passing locally and with our CI. #1013

**Comment by jorkovic** [comment]
i give it a try! thanks for helping me out
